// @generated by OntOS Codesmith Module Contract v1
// @ontos-deployment-app-id catalog
// @ontos-module-id commerce.catalog
import {
  defineOntosModuleManifest,
  ShellNavigationContributionSchema,
  ShellPageContributionSchema,
  ShellPublicComponentContributionSchema,
  ShellReportContributionSchema,
  ShellSearchContributionSchema,
} from '@app/core-runtime';
import type { OntosModuleManifestInput } from '@app/core-runtime';
import { Result, Schema } from 'effect';
// <generated-module-manifest-imports>
import { activatePackageDefinitionAction } from './src/actions/activate-package-definition.action.ts';
import { activatePackageOptionAction } from './src/actions/activate-package-option.action.ts';
import { addProductCategoryAssignmentAction } from './src/actions/add-product-category-assignment.action.ts';
import { assertSizeEquivalenceAction } from './src/actions/assert-size-equivalence.action.ts';
import { assignCatalogMediaAction } from './src/actions/assign-catalog-media.action.ts';
import { assignSkuAction } from './src/actions/assign-sku.action.ts';
import { attributeDefinitionResourceDescriptor } from './shared/resources/attribute-definition.ts';
import { BrandCurrentApi } from './shared/apis/brand-current.ts';
import { BrandHistoryApi } from './shared/apis/brand-history.ts';
import { brandResourceDescriptor } from './shared/resources/brand.ts';
import { CatalogMediaCurrentApi } from './shared/apis/catalog-media-current.ts';
import { catalogRootResourceDescriptor } from './shared/resources/catalog-root.ts';
import { CatalogWidget } from './src/components/catalog-widget.tsx';
import { changeProductManufacturerAction } from './src/actions/change-product-manufacturer.action.ts';
import { changeProductRelationshipAction } from './src/actions/change-product-relationship.action.ts';
import { changeVariantAction } from './src/actions/change-variant.action.ts';
import { ColorCurrentApi } from './shared/apis/color-current.ts';
import { ColorHistoryApi } from './shared/apis/color-history.ts';
import { configurationUnitResourceDescriptor } from './shared/resources/configuration-unit.ts';
import { confirmGtinAction } from './src/actions/confirm-gtin.action.ts';
import { controlledAttributeValueResourceDescriptor } from './shared/resources/controlled-attribute-value.ts';
import { correctGtinAction } from './src/actions/correct-gtin.action.ts';
import { correctProductAction } from './src/actions/correct-product.action.ts';
import { correctSkuAction } from './src/actions/correct-sku.action.ts';
import { createAttributeDefinitionAction } from './src/actions/create-attribute-definition.action.ts';
import { CreateAttributeDefinitionRecoveryApi } from './shared/apis/create-attribute-definition-recovery.ts';
import { createBrandAction } from './src/actions/create-brand.action.ts';
import { CreateBrandRecoveryApi } from './shared/apis/create-brand-recovery.ts';
import { createConfigurationUnitAction } from './src/actions/create-configuration-unit.action.ts';
import { CreateConfigurationUnitRecoveryApi } from './shared/apis/create-configuration-unit-recovery.ts';
import { createControlledAttributeValueAction } from './src/actions/create-controlled-attribute-value.action.ts';
import { CreateControlledAttributeValueRecoveryApi } from './shared/apis/create-controlled-attribute-value-recovery.ts';
import { createPackageDefinitionAction } from './src/actions/create-package-definition.action.ts';
import { CreatePackageDefinitionRecoveryApi } from './shared/apis/create-package-definition-recovery.ts';
import { createProductAction } from './src/actions/create-product.action.ts';
import { createProductCategoryAction } from './src/actions/create-product-category.action.ts';
import { CreateProductCategoryRecoveryApi } from './shared/apis/create-product-category-recovery.ts';
import { CreateProductRecoveryApi } from './shared/apis/create-product-recovery.ts';
import { createProductRelationshipAction } from './src/actions/create-product-relationship.action.ts';
import { CreateProductRelationshipRecoveryApi } from './shared/apis/create-product-relationship-recovery.ts';
import { createProductTypeAction } from './src/actions/create-product-type.action.ts';
import { CreateProductTypeRecoveryApi } from './shared/apis/create-product-type-recovery.ts';
import { createProductUnitAction } from './src/actions/create-product-unit.action.ts';
import { CreateProductUnitRecoveryApi } from './shared/apis/create-product-unit-recovery.ts';
import { createSetCompositionAction } from './src/actions/create-set-composition.action.ts';
import { CreateSetCompositionRecoveryApi } from './shared/apis/create-set-composition-recovery.ts';
import { createVariantAction } from './src/actions/create-variant.action.ts';
import { CreateVariantRecoveryApi } from './shared/apis/create-variant-recovery.ts';
import { decideProductTypeUnnecessaryAction } from './src/actions/decide-product-type-unnecessary.action.ts';
import { EffectiveAttributeValuesCurrentApi } from './shared/apis/effective-attribute-values-current.ts';
import { governProductAttributeApplicabilityAction } from './src/actions/govern-product-attribute-applicability.action.ts';
import { governVariantAxesAction } from './src/actions/govern-variant-axes.action.ts';
import { GtinCurrentApi } from './shared/apis/gtin-current.ts';
import { GtinHistoryApi } from './shared/apis/gtin-history.ts';
import { ManufacturerRelationCurrentApi } from './shared/apis/manufacturer-relation-current.ts';
import { ManufacturerRelationHistoryApi } from './shared/apis/manufacturer-relation-history.ts';
import { markGtinUnresolvedAction } from './src/actions/mark-gtin-unresolved.action.ts';
import { moveProductCategoryAction } from './src/actions/move-product-category.action.ts';
import { PackageDefinitionHistoryApi } from './shared/apis/package-definition-history.ts';
import { packageDefinitionResourceDescriptor } from './shared/resources/package-definition.ts';
import { PackageOptionHistoryApi } from './shared/apis/package-option-history.ts';
import { ProductBrandCurrentApi } from './shared/apis/product-brand-current.ts';
import { ProductBrandHistoryApi } from './shared/apis/product-brand-history.ts';
import { ProductCategoryClassificationApi } from './shared/apis/product-category-classification.ts';
import { ProductCategoryHistoryApi } from './shared/apis/product-category-history.ts';
import { productCategoryResourceDescriptor } from './shared/resources/product-category.ts';
import { ProductDetailApi } from './shared/apis/product-detail.ts';
import { ProductHistoryApi } from './shared/apis/product-history.ts';
import { ProductRelationshipCurrentApi } from './shared/apis/product-relationship-current.ts';
import { ProductRelationshipHistoryApi } from './shared/apis/product-relationship-history.ts';
import { productResourceDescriptor } from './shared/resources/product.ts';
import { ProductSizeCurrentApi } from './shared/apis/product-size-current.ts';
import { productTypeResourceDescriptor } from './shared/resources/product-type.ts';
import { productUnitResourceDescriptor } from './shared/resources/product-unit.ts';
import { promotePackageDefinitionAction } from './src/actions/promote-package-definition.action.ts';
import { publishProductConfigurationAction } from './src/actions/publish-product-configuration.action.ts';
import { QuantityPreparationApi } from './shared/apis/quantity-preparation.ts';
import { reactivateBrandAction } from './src/actions/reactivate-brand.action.ts';
import { reactivateControlledAttributeValueAction } from './src/actions/reactivate-controlled-attribute-value.action.ts';
import { reactivateProductAction } from './src/actions/reactivate-product.action.ts';
import { reactivateVariantAction } from './src/actions/reactivate-variant.action.ts';
import { removeCatalogMediaAction } from './src/actions/remove-catalog-media.action.ts';
import { removeProductAttributeValuesAction } from './src/actions/remove-product-attribute-values.action.ts';
import { removeProductCategoryAssignmentAction } from './src/actions/remove-product-category-assignment.action.ts';
import { removeProductLocalizedFactsAction } from './src/actions/remove-product-localized-facts.action.ts';
import { removeProductManufacturerAction } from './src/actions/remove-product-manufacturer.action.ts';
import { removeProductRelationshipAction } from './src/actions/remove-product-relationship.action.ts';
import { removeVariantAttributeOverrideAction } from './src/actions/remove-variant-attribute-override.action.ts';
import { removeVariantLocalizedFactsAction } from './src/actions/remove-variant-localized-facts.action.ts';
import { renameAttributeDefinitionAction } from './src/actions/rename-attribute-definition.action.ts';
import { renameBrandAction } from './src/actions/rename-brand.action.ts';
import { renameControlledAttributeValueAction } from './src/actions/rename-controlled-attribute-value.action.ts';
import { renameProductCategoryAction } from './src/actions/rename-product-category.action.ts';
import { renameSkuAction } from './src/actions/rename-sku.action.ts';
import { reorderCatalogMediaAction } from './src/actions/reorder-catalog-media.action.ts';
import { replaceProductSizesAction } from './src/actions/replace-product-sizes.action.ts';
import { retireBrandAction } from './src/actions/retire-brand.action.ts';
import { retireConfigurationUnitAction } from './src/actions/retire-configuration-unit.action.ts';
import { retireControlledAttributeValueAction } from './src/actions/retire-controlled-attribute-value.action.ts';
import { retireGtinAction } from './src/actions/retire-gtin.action.ts';
import { retirePackageDefinitionAction } from './src/actions/retire-package-definition.action.ts';
import { retirePackageOptionAction } from './src/actions/retire-package-option.action.ts';
import { retireProductAction } from './src/actions/retire-product.action.ts';
import { retireProductCategoryAction } from './src/actions/retire-product-category.action.ts';
import { retireProductUnitAction } from './src/actions/retire-product-unit.action.ts';
import { retireVariantAction } from './src/actions/retire-variant.action.ts';
import { reviseAttributeDefinitionAction } from './src/actions/revise-attribute-definition.action.ts';
import { reviseConfigurationUnitAction } from './src/actions/revise-configuration-unit.action.ts';
import { revisePackageDefinitionAction } from './src/actions/revise-package-definition.action.ts';
import { reviseProductTypeAction } from './src/actions/revise-product-type.action.ts';
import { reviseProductUnitAction } from './src/actions/revise-product-unit.action.ts';
import { reviseSetCompositionAction } from './src/actions/revise-set-composition.action.ts';
import { SetCompositionCurrentApi } from './shared/apis/set-composition-current.ts';
import { SetCompositionHistoryApi } from './shared/apis/set-composition-history.ts';
import { setProductAttributeValuesAction } from './src/actions/set-product-attribute-values.action.ts';
import { setProductBrandAction } from './src/actions/set-product-brand.action.ts';
import { setProductLocalizedFactsAction } from './src/actions/set-product-localized-facts.action.ts';
import { setProductManufacturerAction } from './src/actions/set-product-manufacturer.action.ts';
import { setProductTypeAction } from './src/actions/set-product-type.action.ts';
import { setProductUnitTargetDivisibilityAction } from './src/actions/set-product-unit-target-divisibility.action.ts';
import { setVariantAttributeOverrideAction } from './src/actions/set-variant-attribute-override.action.ts';
import { setVariantLocalizedFactsAction } from './src/actions/set-variant-localized-facts.action.ts';
import { SkuLookupApi } from './shared/apis/sku-lookup.ts';
import { updateProductAction } from './src/actions/update-product.action.ts';
import { UpdateProductRecoveryApi } from './shared/apis/update-product-recovery.ts';
import { VariantHistoryApi } from './shared/apis/variant-history.ts';
import { variantResourceDescriptor } from './shared/resources/variant.ts';
// </generated-module-manifest-imports>

type NavigationContributionInput = typeof ShellNavigationContributionSchema.Encoded;
type PageContributionInput = typeof ShellPageContributionSchema.Encoded;
type PublicComponentContributionInput = typeof ShellPublicComponentContributionSchema.Encoded;
type ReportContributionInput = typeof ShellReportContributionSchema.Encoded;
type SearchContributionInput = typeof ShellSearchContributionSchema.Encoded;

const _navigationContribution = (value: NavigationContributionInput) =>
  Result.getOrThrow(Schema.decodeResult(ShellNavigationContributionSchema)(value));
const _pageContribution = (value: PageContributionInput) =>
  Result.getOrThrow(Schema.decodeResult(ShellPageContributionSchema)(value));
const publicComponentContribution = (value: PublicComponentContributionInput) =>
  Result.getOrThrow(Schema.decodeResult(ShellPublicComponentContributionSchema)(value));
const _reportContribution = (value: ReportContributionInput) =>
  Result.getOrThrow(Schema.decodeResult(ShellReportContributionSchema)(value));
const _searchContribution = (value: SearchContributionInput) =>
  Result.getOrThrow(Schema.decodeResult(ShellSearchContributionSchema)(value));

export const catalogManifest: OntosModuleManifestInput = defineOntosModuleManifest({
  activation: {
    defaultState: 'inactive',
    preservesHistoryWhenInactive: true,
    scope: 'tenant',
    supportedStates: ['inactive', 'active', 'read_only', 'suspended', 'quarantined', 'deprecated', 'archived'],
  },
  module: {
    description: 'Catalog business capability.',
    displayName: 'Catalog',
    id: 'commerce.catalog',
    implementedAs: 'ultramodern_microvertical',
    kind: 'business_module',
  },
  publicSurface: {
    actions: [
      // <generated-module-manifest-actions>
      activatePackageDefinitionAction,
      activatePackageOptionAction,
      addProductCategoryAssignmentAction,
      assertSizeEquivalenceAction,
      assignCatalogMediaAction,
      assignSkuAction,
      changeProductManufacturerAction,
      changeProductRelationshipAction,
      changeVariantAction,
      confirmGtinAction,
      correctGtinAction,
      correctProductAction,
      correctSkuAction,
      createAttributeDefinitionAction,
      createBrandAction,
      createConfigurationUnitAction,
      createControlledAttributeValueAction,
      createPackageDefinitionAction,
      createProductAction,
      createProductCategoryAction,
      createProductRelationshipAction,
      createProductTypeAction,
      createProductUnitAction,
      createSetCompositionAction,
      createVariantAction,
      decideProductTypeUnnecessaryAction,
      governProductAttributeApplicabilityAction,
      governVariantAxesAction,
      markGtinUnresolvedAction,
      moveProductCategoryAction,
      promotePackageDefinitionAction,
      publishProductConfigurationAction,
      reactivateBrandAction,
      reactivateControlledAttributeValueAction,
      reactivateProductAction,
      reactivateVariantAction,
      removeCatalogMediaAction,
      removeProductAttributeValuesAction,
      removeProductCategoryAssignmentAction,
      removeProductLocalizedFactsAction,
      removeProductManufacturerAction,
      removeProductRelationshipAction,
      removeVariantAttributeOverrideAction,
      removeVariantLocalizedFactsAction,
      renameAttributeDefinitionAction,
      renameBrandAction,
      renameControlledAttributeValueAction,
      renameProductCategoryAction,
      renameSkuAction,
      reorderCatalogMediaAction,
      replaceProductSizesAction,
      retireBrandAction,
      retireConfigurationUnitAction,
      retireControlledAttributeValueAction,
      retireGtinAction,
      retirePackageDefinitionAction,
      retirePackageOptionAction,
      retireProductAction,
      retireProductCategoryAction,
      retireProductUnitAction,
      retireVariantAction,
      reviseAttributeDefinitionAction,
      reviseConfigurationUnitAction,
      revisePackageDefinitionAction,
      reviseProductTypeAction,
      reviseProductUnitAction,
      reviseSetCompositionAction,
      setProductAttributeValuesAction,
      setProductBrandAction,
      setProductLocalizedFactsAction,
      setProductManufacturerAction,
      setProductTypeAction,
      setProductUnitTargetDivisibilityAction,
      setVariantAttributeOverrideAction,
      setVariantLocalizedFactsAction,
      updateProductAction,
      // </generated-module-manifest-actions>
    ],
    api: {
      // <generated-module-manifest-apis>
      'brand-current': BrandCurrentApi,
      'brand-history': BrandHistoryApi,
      'catalog-media-current': CatalogMediaCurrentApi,
      'color-current': ColorCurrentApi,
      'color-history': ColorHistoryApi,
      'create-attribute-definition-recovery': CreateAttributeDefinitionRecoveryApi,
      'create-brand-recovery': CreateBrandRecoveryApi,
      'create-configuration-unit-recovery': CreateConfigurationUnitRecoveryApi,
      'create-controlled-attribute-value-recovery': CreateControlledAttributeValueRecoveryApi,
      'create-package-definition-recovery': CreatePackageDefinitionRecoveryApi,
      'create-product-category-recovery': CreateProductCategoryRecoveryApi,
      'create-product-recovery': CreateProductRecoveryApi,
      'create-product-relationship-recovery': CreateProductRelationshipRecoveryApi,
      'create-product-type-recovery': CreateProductTypeRecoveryApi,
      'create-product-unit-recovery': CreateProductUnitRecoveryApi,
      'create-set-composition-recovery': CreateSetCompositionRecoveryApi,
      'create-variant-recovery': CreateVariantRecoveryApi,
      'effective-attribute-values-current': EffectiveAttributeValuesCurrentApi,
      'gtin-current': GtinCurrentApi,
      'gtin-history': GtinHistoryApi,
      'manufacturer-relation-current': ManufacturerRelationCurrentApi,
      'manufacturer-relation-history': ManufacturerRelationHistoryApi,
      'package-definition-history': PackageDefinitionHistoryApi,
      'package-option-history': PackageOptionHistoryApi,
      'product-brand-current': ProductBrandCurrentApi,
      'product-brand-history': ProductBrandHistoryApi,
      'product-category-classification': ProductCategoryClassificationApi,
      'product-category-history': ProductCategoryHistoryApi,
      'product-detail': ProductDetailApi,
      'product-history': ProductHistoryApi,
      'product-relationship-current': ProductRelationshipCurrentApi,
      'product-relationship-history': ProductRelationshipHistoryApi,
      'product-size-current': ProductSizeCurrentApi,
      'quantity-preparation': QuantityPreparationApi,
      'set-composition-current': SetCompositionCurrentApi,
      'set-composition-history': SetCompositionHistoryApi,
      'sku-lookup': SkuLookupApi,
      'update-product-recovery': UpdateProductRecoveryApi,
      'variant-history': VariantHistoryApi,
      // </generated-module-manifest-apis>
    },
    businessPermissions: [
      // <generated-module-manifest-business-permissions>
      // </generated-module-manifest-business-permissions>
    ],
    components: {
      // <generated-module-manifest-components>
      'catalog-widget': CatalogWidget,
      // </generated-module-manifest-components>
    },
    events: [],
    reports: [
      // <generated-module-manifest-reports>
      // </generated-module-manifest-reports>
    ],
    resourceTypes: [
      // <generated-module-manifest-resources>
      attributeDefinitionResourceDescriptor,
      brandResourceDescriptor,
      catalogRootResourceDescriptor,
      configurationUnitResourceDescriptor,
      controlledAttributeValueResourceDescriptor,
      packageDefinitionResourceDescriptor,
      productCategoryResourceDescriptor,
      productResourceDescriptor,
      productTypeResourceDescriptor,
      productUnitResourceDescriptor,
      variantResourceDescriptor,
      // </generated-module-manifest-resources>
    ],
    search: [
      // <generated-module-manifest-search>
      // </generated-module-manifest-search>
    ],
    shellContributions: {
      mediaAttachments: [],
      navigation: [
        // <generated-module-shell-navigation>
        // </generated-module-shell-navigation>
      ],
      pages: [
        // <generated-module-shell-pages>
        // </generated-module-shell-pages>
      ],
      publicComponents: [
        // <generated-module-shell-components>
        publicComponentContribution({
          componentKey: 'commerce.catalog.catalog-widget',
          contributionKey: 'commerce.catalog.component.catalog-widget',
          entrypoint: {
            access: 'read',
            authorization: { kind: 'authenticated_principal' },
            entrypointKey: 'commerce.catalog.component.catalog-widget',
            moduleKey: 'commerce.catalog',
            role: 'public_component',
            scope: 'tenant',
          },
        }),
        // </generated-module-shell-components>
      ],
      reports: [
        // <generated-module-shell-reports>
        // </generated-module-shell-reports>
      ],
      resourceDetails: [],
      search: [
        // <generated-module-shell-search>
        // </generated-module-shell-search>
      ],
      timelines: [],
    },
  },
});
