// @generated by OntOS Codesmith module-api v1
import type { ReadHandlerContext, ReadHandlerResult } from '@app/core-runtime';
import {
  OperationContextUnavailable,
  ReadHandlerUnavailable,
  ReadPermissionDenied,
  defineRead,
  defineReadResourcePermission,
  defineTenantModuleEntrypoint,
} from '@app/core-runtime';
import {
  MarketAffectedUseSourceEvidenceSchema,
  MarketAffectedUseAssessmentRequestSchema,
  MarketAffectedUseAssessmentResponseSchema,
  MarketBootstrapReferenceSchema,
  MarketCurrentProposalReferenceSchema,
  MarketRetainedHistoryReferenceSchema,
  MarketRetirementInstantSchema,
  MarketRevisionSchema,
} from '../../shared/apis/market-affected-use-assessment.ts';
import type {
  MarketAffectedUseAssessmentRequest,
  MarketAffectedUseAssessmentResponse,
  MarketAffectedUseSourceEvidence,
} from '../../shared/apis/market-affected-use-assessment.ts';
import { createHash } from 'node:crypto';
import { DateTime, Context, Effect, Option, Schema } from 'effect';
import { MarketRefSchema } from '@app/commerce-market-catalog/resources/market';

import { marketAffectedUseAssessmentRepositoryForInvoker } from '../persistence/market-retirement-persistence.ts';
import type { MarketAffectedUseAssessmentRepository } from '../persistence/market-retirement-persistence.ts';

const MARKET_AFFECTED_USE_MODULE_KEY = 'commerce.customer-context';

export interface MarketReferenceOwnerDeploymentStateAuthority {
  /**
   * Returns Application Composition evidence for every Market-reference owner that is not read
   * through this deployment. Disabled/unimplemented and enabled-unreachable are distinct: the
   * latter must fail instead of returning an empty proof.
   */
  readonly proveReferenceOwnerStates: (
    input: MarketAffectedUseAssessmentRequest,
  ) => Effect.Effect<
    Readonly<{ readonly sourceEvidence: readonly MarketAffectedUseSourceEvidence[] }>,
    ReadHandlerUnavailable
  >;
}

export class MarketReferenceOwnerDeploymentStateAuthorityService extends Context.Service<
  MarketReferenceOwnerDeploymentStateAuthorityService,
  MarketReferenceOwnerDeploymentStateAuthority
>()(
  '@app/commerce-customer-context/api/market-affected-use-assessment.read/MarketReferenceOwnerDeploymentStateAuthorityService',
) {}

export interface MarketAffectedUseAssessmentServices {
  readonly assess: (
    input: MarketAffectedUseAssessmentRequest,
  ) => Effect.Effect<MarketAffectedUseAssessmentResponse, ReadHandlerUnavailable>;
}

const CanonicalMarketAffectedUseDigestInputSchema = Schema.Struct({
  evaluatedAt: MarketRetirementInstantSchema,
  liveBlockingReferences: Schema.Struct({
    bootstrapDefaults: Schema.Array(MarketBootstrapReferenceSchema),
    currentProposals: Schema.Array(MarketCurrentProposalReferenceSchema),
  }),
  marketRef: MarketRefSchema,
  marketRevision: MarketRevisionSchema,
  nextApplicabilityBoundary: Schema.optionalKey(MarketRetirementInstantSchema),
  observedAt: MarketRetirementInstantSchema,
  retainedHistoryReferences: Schema.Array(MarketRetainedHistoryReferenceSchema),
  sourceEvidence: Schema.Array(MarketAffectedUseSourceEvidenceSchema),
  tenantId: MarketRefSchema.fields.tenantId,
});
const CanonicalMarketAffectedUseDigestJsonSchema = Schema.fromJsonString(CanonicalMarketAffectedUseDigestInputSchema);

const canonicalDigest = (
  assessment: Extract<MarketAffectedUseAssessmentResponse, { readonly outcome: 'VERIFIED' }>,
) => {
  const digestInput = {
    evaluatedAt: assessment.evaluatedAt,
    liveBlockingReferences: assessment.liveBlockingReferences,
    marketRef: assessment.marketRef,
    marketRevision: assessment.marketRevision,
    observedAt: assessment.observedAt,
    retainedHistoryReferences: assessment.retainedHistoryReferences,
    sourceEvidence: assessment.sourceEvidence.toSorted((left, right) => left.sourceId.localeCompare(right.sourceId)),
    tenantId: assessment.tenantId,
  };
  const completeDigestInput =
    assessment.nextApplicabilityBoundary === undefined
      ? digestInput
      : { ...digestInput, nextApplicabilityBoundary: assessment.nextApplicabilityBoundary };
  return Schema.encodeEffect(CanonicalMarketAffectedUseDigestJsonSchema)(completeDigestInput).pipe(
    Effect.map((encoded) => createHash('sha256').update(encoded).digest('hex')),
    Effect.mapError((cause) => {
      const failure = new ReadHandlerUnavailable({
        code: 'read_handler_unavailable',
        reason: 'Market affected-use evidence could not be canonicalized',
      });
      Object.defineProperty(failure, 'cause', { configurable: true, value: cause });
      return failure;
    }),
  );
};

const staleEvidenceSourceIds = (
  evaluatedAt: string,
  sourceEvidence: readonly MarketAffectedUseSourceEvidence[],
): readonly string[] => {
  const evaluated = DateTime.toEpochMillis(DateTime.makeUnsafe(evaluatedAt));
  const seen = new Set<string>();
  return sourceEvidence.flatMap((evidence) => {
    const observed = DateTime.toEpochMillis(evidence.completenessEvidence.observedAt);
    const nextBoundary = evidence.completenessEvidence.nextApplicabilityBoundary;
    const next = nextBoundary === undefined ? undefined : DateTime.toEpochMillis(nextBoundary);
    const duplicated = seen.has(evidence.sourceId);
    seen.add(evidence.sourceId);
    return duplicated ||
      evidence.ownerRevision !== evidence.completenessEvidence.ownerRevision ||
      observed > evaluated ||
      (next !== undefined && evaluated >= next)
      ? [evidence.sourceId]
      : [];
  });
};

type AssessLocalAffectedUse = MarketAffectedUseAssessmentRepository['assess'];
type ProveReferenceOwnerStates = MarketReferenceOwnerDeploymentStateAuthority['proveReferenceOwnerStates'];

export const makeMarketAffectedUseAssessmentServices = (
  assessLocalAffectedUse: AssessLocalAffectedUse,
  proveReferenceOwnerStates: ProveReferenceOwnerStates,
): MarketAffectedUseAssessmentServices => ({
  assess: Effect.fn('MarketAffectedUseAssessment.assess')(function* assess(input) {
    const local = yield* assessLocalAffectedUse(input);
    if (local.outcome !== 'VERIFIED') {
      return local;
    }
    const ownerStates = yield* proveReferenceOwnerStates(input);
    const sourceEvidence = [...local.sourceEvidence, ...ownerStates.sourceEvidence].toSorted((left, right) =>
      left.sourceId.localeCompare(right.sourceId),
    );
    const staleSourceIds = staleEvidenceSourceIds(input.evaluatedAt, sourceEvidence);
    if (staleSourceIds.length > 0) {
      return {
        ...input,
        code: 'stale-owner-evidence',
        observedAt: local.observedAt,
        outcome: 'STALE' as const,
        reason: 'Market affected-use source evidence is stale, duplicated, or revision-inconsistent',
        staleSourceIds,
      };
    }
    const combined = {
      ...local,
      sourceEvidence,
    };
    return { ...combined, assessmentDigest: yield* canonicalDigest(combined) };
  }),
});

export const handleMarketAffectedUseAssessment: (
  input: MarketAffectedUseAssessmentRequest,
  context: ReadHandlerContext<MarketAffectedUseAssessmentServices>,
) => Effect.Effect<
  ReadHandlerResult<MarketAffectedUseAssessmentResponse>,
  ReadHandlerUnavailable | ReadPermissionDenied
> = (input, context) => {
  if (input.tenantId !== context.scope.tenantId || input.marketRef.tenantId !== context.scope.tenantId) {
    return Effect.fail(
      new ReadPermissionDenied({
        code: 'read_permission_denied',
        reason: 'The assessed Market is outside the trusted Tenant context',
      }),
    );
  }
  return context.services
    .assess(input)
    .pipe(Effect.map((result) => ({ evidence: { resultCount: result.outcome === 'VERIFIED' ? 1 : 0 }, result })));
};

export const marketAffectedUseAssessmentEntrypoint = defineTenantModuleEntrypoint({
  access: 'read',
  authorization: { kind: 'context_permission', permission: 'market.catalog.read' },
  entrypointKey: 'commerce.customer-context.api.market-affected-use-assessment',
  moduleKey: MARKET_AFFECTED_USE_MODULE_KEY,
  role: 'api',
});

export const marketAffectedUseAssessmentRead = defineRead(
  {
    accessKind: 'detail',
    entrypoint: marketAffectedUseAssessmentEntrypoint,
    evidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.customer-context.api.market-affected-use-assessment.evidence.v1',
    },
    inputSchema: MarketAffectedUseAssessmentRequestSchema,
    legalEntityScope: 'required',
    owningModuleKey: MARKET_AFFECTED_USE_MODULE_KEY,
    permissionTarget: 'module',
    policies: [],
    readKey: 'commerce.customer-context.api.market-affected-use-assessment',
    resourcePermission: defineReadResourcePermission<MarketAffectedUseAssessmentRequest>(({ marketRef }) => ({
      permission: 'read',
      resource: marketRef,
    })),
    resultSchema: MarketAffectedUseAssessmentResponseSchema,
    schemaVersion: '1',
  },
  handleMarketAffectedUseAssessment,
  (transaction, scope) => {
    const { legalEntityId } = scope;
    if (legalEntityId === undefined) {
      return Effect.fail(
        new OperationContextUnavailable({
          code: 'operation_context_unavailable',
          reason: 'Market affected-use assessment requires a trusted Legal Entity scope',
        }),
      );
    }
    return Effect.gen(function* makeServices() {
      const deploymentStateService = yield* Effect.serviceOption(MarketReferenceOwnerDeploymentStateAuthorityService);
      const deploymentState = Option.match(deploymentStateService, {
        onNone: (): MarketReferenceOwnerDeploymentStateAuthority => ({
          proveReferenceOwnerStates: () =>
            Effect.fail(
              new ReadHandlerUnavailable({
                code: 'read_handler_unavailable',
                reason: 'Authoritative Market-reference deployment state is not configured',
              }),
            ),
        }),
        onSome: (authority) => authority,
      });
      const repository = marketAffectedUseAssessmentRepositoryForInvoker(transaction);
      return makeMarketAffectedUseAssessmentServices(repository.assess, deploymentState.proveReferenceOwnerStates);
    });
  },
  () => ({ kind: 'module', moduleId: MARKET_AFFECTED_USE_MODULE_KEY }),
);
