// @generated by OntOS Codesmith Resource v1
// @ontos-resource-owner commerce.catalog
// @ontos-resource-slug product-category
import type { OntosResourceType } from '@app/core-runtime';
import { Schema } from 'effect';

const ResourceIdSchema = Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(300));
const TenantIdSchema = Schema.String.check(Schema.isUUID());

export const ProductCategoryRefSchema = Schema.Struct({
  moduleId: Schema.Literal('commerce.catalog'),
  resourceId: ResourceIdSchema,
  resourceType: Schema.Literal('commerce.catalog.product-category'),
  tenantId: TenantIdSchema,
});
export type ProductCategoryRef = typeof ProductCategoryRefSchema.Type;

export const productCategoryResourceDescriptor = {
  capabilities: {
    graphVisible: false,
    linkable: false,
    mediaAttachable: false,
    searchable: false,
    timelineVisible: false,
  },
  description: 'Product Category resource.',
  key: 'commerce.catalog.product-category',
  label: 'Product Category',
  owningModuleId: 'commerce.catalog',
} as const satisfies OntosResourceType;
