// @generated by OntOS Codesmith module-api v1
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted } from 'effect';
import { CreateProductCategoryRecoveryApi } from '../../shared/apis/create-product-category-recovery.ts';
import type { CreateProductCategoryRecoveryRequest } from '../../shared/apis/create-product-category-recovery.ts';
import { operationGateway } from './action-gateway.ts';

export interface CreateProductCategoryRecoveryClientOptions {
  readonly baseUrl?: string | URL;
}

type CreateProductCategoryRecoveryAuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options?: CreateProductCategoryRecoveryClientOptions,
];

type CreateProductCategoryRecoveryOperationInvocation = readonly [
  requestCorrelation: string,
  options?: CreateProductCategoryRecoveryClientOptions,
];

const createProductCategoryRecoveryClient = (
  credential: Redacted.Redacted,
  {
    options,
    requestCorrelation,
  }: { readonly options: CreateProductCategoryRecoveryClientOptions; readonly requestCorrelation: string },
) =>
  makeGovernedEffectBffClient(
    {
      api: CreateProductCategoryRecoveryApi,
      credential,
      defaultApiPrefix: '/catalog-api',
      requestCorrelation,
    },
    options,
  );

export const executeCreateProductCategoryRecoveryWithAuthorization = (
  payload: CreateProductCategoryRecoveryRequest,
  ...[credential, requestCorrelation, options = {}]: CreateProductCategoryRecoveryAuthorizedInvocation
) =>
  createProductCategoryRecoveryClient(Redacted.make(credential), { options, requestCorrelation }).pipe(
    Effect.flatMap((client) =>
      client.createProductCategoryRecovery.execute({ headers: {}, params: {}, payload, query: {} }),
    ),
  );

export const executeCreateProductCategoryRecovery = (
  payload: CreateProductCategoryRecoveryRequest,
  ...[requestCorrelation, options = {}]: CreateProductCategoryRecoveryOperationInvocation
) =>
  operationGateway.invoke((credential) =>
    executeCreateProductCategoryRecoveryWithAuthorization(payload, credential, requestCorrelation, options),
  );
