// @generated by OntOS Codesmith module-api v1
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted } from 'effect';
import { CreateProductUnitRecoveryApi } from '../../shared/apis/create-product-unit-recovery.ts';
import type { CreateProductUnitRecoveryRequest } from '../../shared/apis/create-product-unit-recovery.ts';
import { operationGateway } from './action-gateway.ts';

export interface CreateProductUnitRecoveryClientOptions {
  readonly baseUrl?: string | URL;
}

type CreateProductUnitRecoveryAuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options?: CreateProductUnitRecoveryClientOptions,
];

type CreateProductUnitRecoveryOperationInvocation = readonly [
  requestCorrelation: string,
  options?: CreateProductUnitRecoveryClientOptions,
];

const createProductUnitRecoveryClient = (
  credential: Redacted.Redacted,
  {
    options,
    requestCorrelation,
  }: { readonly options: CreateProductUnitRecoveryClientOptions; readonly requestCorrelation: string },
) =>
  makeGovernedEffectBffClient(
    {
      api: CreateProductUnitRecoveryApi,
      credential,
      defaultApiPrefix: '/catalog-api',
      requestCorrelation,
    },
    options,
  );

export const executeCreateProductUnitRecoveryWithAuthorization = (
  payload: CreateProductUnitRecoveryRequest,
  ...[credential, requestCorrelation, options = {}]: CreateProductUnitRecoveryAuthorizedInvocation
) =>
  createProductUnitRecoveryClient(Redacted.make(credential), { options, requestCorrelation }).pipe(
    Effect.flatMap((client) =>
      client.createProductUnitRecovery.execute({ headers: {}, params: {}, payload, query: {} }),
    ),
  );

export const executeCreateProductUnitRecovery = (
  payload: CreateProductUnitRecoveryRequest,
  ...[requestCorrelation, options = {}]: CreateProductUnitRecoveryOperationInvocation
) =>
  operationGateway.invoke((credential) =>
    executeCreateProductUnitRecoveryWithAuthorization(payload, credential, requestCorrelation, options),
  );
