// @generated by OntOS Codesmith module-api v1
import type { ReadHandlerContext } from '@app/core-runtime';
import { ReadHandlerUnavailable, defineRead, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { Effect } from 'effect';

import {
  ExternalTargetResolutionRequestSchema,
  ExternalTargetResolutionResponseSchema,
} from '../../shared/apis/external-target-resolution.ts';
import type {
  ExternalTargetResolutionRequest,
  ExternalTargetResolutionResponse,
} from '../../shared/apis/external-target-resolution.ts';
import {
  makeExternalCorrelationResolver,
  type ExternalCorrelationRegistryPorts,
  type ExternalCorrelationResolverRules,
} from '../persistence/external-correlation-resolver.ts';

const readKey = 'commerce.catalog.api.external-target-resolution';
const moduleKey = 'commerce.catalog';
type Services = ReturnType<typeof makeExternalCorrelationResolver>;

const externalTargetResolutionEntrypoint = defineTenantModuleEntrypoint({
  access: 'read',
  authorization: { kind: 'context_permission', permission: 'commerce.catalog.read.external-target-resolution' },
  entrypointKey: readKey,
  moduleKey,
  role: 'api',
});

const unavailable = (cause: unknown) => {
  const error = new ReadHandlerUnavailable({
    code: 'read_handler_unavailable',
    reason: 'Connector Registry target evidence is temporarily unavailable',
  });
  Object.defineProperty(error, 'cause', { configurable: true, value: cause });
  return error;
};

export const readExternalTargetResolution = Effect.fn('ExternalTargetResolutionRead.read')(
  function* readExternalTargetResolution(
    input: ExternalTargetResolutionRequest,
    tenantId: string,
    services: Services,
  ): Effect.fn.Return<ExternalTargetResolutionResponse, ReadHandlerUnavailable> {
    if (input.sourceRecord.tenantId !== tenantId) {
      return { reason: 'Source record does not belong to the trusted Tenant', status: 'INVALID' };
    }
    return yield* services.resolve(input).pipe(
      Effect.catchTags({
        ExternalCorrelationAmbiguous: (failure) =>
          Effect.succeed({ candidates: failure.candidates, reason: failure.reason, status: 'AMBIGUOUS' as const }),
        ExternalCorrelationInvalid: (failure) => Effect.succeed({ reason: failure.reason, status: 'INVALID' as const }),
        ExternalCorrelationMissingLink: () =>
          Effect.succeed({
            reason: 'No confirmed owner correlation addresses this source record',
            status: 'MISSING_LINK' as const,
          }),
        ExternalCorrelationTargetTypeMismatch: (failure) =>
          Effect.succeed({ reason: failure.reason, status: 'TARGET_TYPE_MISMATCH' as const }),
        ExternalCorrelationUnverifiable: unavailable,
      }),
    );
  },
);

/** Connector Registry and deterministic-rule evidence are deployment bindings; no binding fails closed. */
export const makeExternalTargetResolutionRead = (
  registry?: ExternalCorrelationRegistryPorts,
  rules?: ExternalCorrelationResolverRules,
) =>
  defineRead(
    {
      accessKind: 'detail',
      entrypoint: externalTargetResolutionEntrypoint,
      evidencePolicy: { captureMode: 'metadata_only', policyKey: `${readKey}.evidence.v1` },
      inputSchema: ExternalTargetResolutionRequestSchema,
      legalEntityScope: 'forbidden',
      owningModuleKey: moduleKey,
      permissionTarget: 'tenant',
      policies: [],
      readKey,
      resultSchema: ExternalTargetResolutionResponseSchema,
      schemaVersion: '1',
    },
    (input, context: ReadHandlerContext<Services>) =>
      readExternalTargetResolution(input, context.scope.tenantId, context.services).pipe(
        Effect.map((result) => ({ evidence: { resultCount: result.status === 'RESOLVED' ? 1 : 0 }, result })),
      ),
    () => Effect.succeed(makeExternalCorrelationResolver(registry, rules)),
    () => ({ kind: 'tenant', permission: 'access' }),
  );

export const externalTargetResolutionRead = makeExternalTargetResolutionRead();
