// @generated by OntOS Codesmith module-api v1
import type { ReadHandlerContext } from '@app/core-runtime';
import {
  ReadHandlerNotFound,
  ReadHandlerUnavailable,
  defineRead,
  defineReadResourcePermission,
  defineTenantModuleEntrypoint,
} from '@app/core-runtime';
import { Effect } from 'effect';
import {
  ProductRelationshipCurrentRequestSchema,
  ProductRelationshipCurrentResponseSchema,
} from '../../shared/apis/product-relationship-current.ts';
import type {
  ProductRelationshipCurrentRequest,
  ProductRelationshipCurrentResponse,
} from '../../shared/apis/product-relationship-current.ts';
import type { ProductRelationshipReads } from '../persistence/product-relationship-reads.ts';
import { productRelationshipReadsForScope } from '../persistence/product-relationship-reads.ts';

export const productRelationshipCurrentEntrypoint = defineTenantModuleEntrypoint({
  access: 'read',
  authorization: { kind: 'context_permission', permission: 'commerce.catalog.read.product-relationship' },
  entrypointKey: 'commerce.catalog.api.product-relationship-current',
  moduleKey: 'commerce.catalog',
  role: 'api',
});

const unavailable = (cause: unknown) => {
  const error = new ReadHandlerUnavailable({
    code: 'read_handler_unavailable',
    reason: 'Catalog relationships are temporarily unavailable',
  });
  Object.defineProperty(error, 'cause', { configurable: true, value: cause });
  return error;
};

export const readProductRelationshipCurrent = Effect.fn('ProductRelationshipCurrentRead.read')(function* (
  input: ProductRelationshipCurrentRequest,
  tenantId: string,
  services: ProductRelationshipReads,
  at = new Date().toISOString(),
): Effect.fn.Return<ProductRelationshipCurrentResponse, ReadHandlerNotFound | ReadHandlerUnavailable> {
  if (input.endpoint.tenantId !== tenantId) {
    return yield* new ReadHandlerNotFound({
      code: 'read_handler_not_found',
      reason: 'The endpoint is outside the trusted Tenant',
    });
  }
  const rows = yield* (
    input.direction === 'forward' ? services.forward(input.endpoint, at) : services.reverse(input.endpoint, at)
  ).pipe(Effect.mapError(unavailable));
  return {
    relationships: rows
      .filter((row) => row.current)
      .map(({ relationship, relationshipId, revision }) => ({ relationship, relationshipId, revision })),
  };
});

export const productRelationshipCurrentRead = defineRead(
  {
    accessKind: 'search',
    entrypoint: productRelationshipCurrentEntrypoint,
    evidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.api.product-relationship-current.evidence.v1',
    },
    inputSchema: ProductRelationshipCurrentRequestSchema,
    legalEntityScope: 'required',
    owningModuleKey: 'commerce.catalog',
    permissionTarget: 'module',
    policies: [],
    readKey: 'commerce.catalog.api.product-relationship-current',
    resourcePermission: defineReadResourcePermission<ProductRelationshipCurrentRequest>(({ endpoint }) => ({
      permission: 'read',
      resource: endpoint,
    })),
    resultSchema: ProductRelationshipCurrentResponseSchema,
    schemaVersion: '1',
  },
  (input, context: ReadHandlerContext<ProductRelationshipReads>) =>
    readProductRelationshipCurrent(input, context.scope.tenantId, context.services).pipe(
      Effect.map((result) => ({ evidence: { resultCount: result.relationships.length }, result })),
    ),
  (transaction, scope) => Effect.succeed(productRelationshipReadsForScope(transaction, scope)),
  () => ({ kind: 'module', moduleId: 'commerce.catalog' }),
  ({ relationships }) => relationships.flatMap(({ relationship }) => [relationship.source, relationship.target]),
);
