// @generated by OntOS Codesmith module-api v1
import type { ReadHandlerContext } from '@app/core-runtime';
import {
  ReadHandlerNotFound,
  ReadHandlerUnavailable,
  defineRead,
  defineTenantModuleEntrypoint,
} from '@app/core-runtime';
import { Effect, Option } from 'effect';

import { ProductDetailRequestSchema, ProductDetailResponseSchema } from '../../shared/apis/product-detail.ts';
import type { ProductDetailRequest, ProductDetailResponse } from '../../shared/apis/product-detail.ts';
import type { CatalogPersistence } from '../persistence/catalog-persistence.ts';
import { catalogPersistenceForScope } from '../persistence/catalog-persistence.ts';

const catalogModuleKey = 'commerce.catalog';

const productDetailEntrypoint = defineTenantModuleEntrypoint({
  access: 'read',
  authorization: { kind: 'context_permission', permission: 'commerce.catalog.read.product-detail' },
  entrypointKey: 'commerce.catalog.api.product-detail',
  moduleKey: catalogModuleKey,
  role: 'api',
});

const notFound = () =>
  new ReadHandlerNotFound({
    code: 'read_handler_not_found',
    reason: 'The requested Product does not exist in the trusted tenant scope',
  });

const unavailable = (cause: unknown) => {
  const error = new ReadHandlerUnavailable({
    code: 'read_handler_unavailable',
    reason: 'Catalog Product detail is temporarily unavailable',
  });
  Object.defineProperty(error, 'cause', { configurable: true, value: cause });
  return error;
};

export const readProductDetail = Effect.fn('ProductDetailRead.read')(function* readProductDetail(
  input: ProductDetailRequest,
  trustedTenantId: string,
  services: CatalogPersistence,
): Effect.fn.Return<ProductDetailResponse, ReadHandlerNotFound | ReadHandlerUnavailable> {
  if (input.productRef.tenantId !== trustedTenantId) {
    return yield* notFound();
  }
  const product = yield* services.getCurrent(input.productRef.resourceId).pipe(Effect.mapError(unavailable));
  if (Option.isNone(product)) {
    return yield* notFound();
  }
  return { product: product.value };
});

export const productDetailRead = defineRead(
  {
    accessKind: 'detail',
    entrypoint: productDetailEntrypoint,
    evidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.api.product-detail.evidence.v1',
    },
    inputSchema: ProductDetailRequestSchema,
    legalEntityScope: 'forbidden',
    owningModuleKey: catalogModuleKey,
    permissionTarget: 'tenant',
    policies: [],
    readKey: 'commerce.catalog.api.product-detail',
    resultSchema: ProductDetailResponseSchema,
    schemaVersion: '1',
  },
  (input, context: ReadHandlerContext<CatalogPersistence>) =>
    readProductDetail(input, context.scope.tenantId, context.services).pipe(
      Effect.map((result) => ({
        evidence: { resultCount: 1 },
        result,
      })),
    ),
  (transaction, scope) => catalogPersistenceForScope(transaction, scope),
  () => ({ kind: 'tenant', permission: 'access' }),
);
