// @generated by OntOS Codesmith module-api v1
import type { ReadHandlerContext } from '@app/core-runtime';
import {
  ReadHandlerNotFound,
  ReadHandlerUnavailable,
  defineRead,
  defineReadResourcePermission,
  defineTenantModuleEntrypoint,
} from '@app/core-runtime';
import { Effect } from 'effect';
import {
  QuantityPreparationRequestSchema,
  QuantityPreparationResponseSchema,
} from '../../shared/apis/quantity-preparation.ts';
import type {
  QuantityPreparationRequest,
  QuantityPreparationResponse,
} from '../../shared/apis/quantity-preparation.ts';
import { catalogQuantityPreparationForScope } from '../persistence/catalog-quantity-preparation.ts';

const readKey = 'commerce.catalog.api.quantity-preparation';
const moduleKey = 'commerce.catalog';

const quantityPreparationEntrypoint = defineTenantModuleEntrypoint({
  access: 'read',
  authorization: { kind: 'context_permission', permission: 'commerce.catalog.read.quantity-preparation' },
  entrypointKey: readKey,
  moduleKey,
  role: 'api',
});

const unavailable = (cause: unknown) => {
  const error = new ReadHandlerUnavailable({
    code: 'read_handler_unavailable',
    reason: 'Catalog Quantity preparation is temporarily unavailable',
  });
  Object.defineProperty(error, 'cause', { configurable: true, value: cause });
  return error;
};

export const readQuantityPreparation = Effect.fn('QuantityPreparationRead.read')(function* readQuantityPreparation(
  input: QuantityPreparationRequest,
  tenantId: string,
  services: ReturnType<typeof catalogQuantityPreparationForScope>,
): Effect.fn.Return<QuantityPreparationResponse, ReadHandlerNotFound | ReadHandlerUnavailable> {
  if (input.selection.productRef.tenantId !== tenantId) {
    return yield* new ReadHandlerNotFound({
      code: 'read_handler_not_found',
      reason: 'The requested Catalog Product does not exist in the trusted Tenant',
    });
  }
  const result = yield* services
    .prepare({ amount: input.amount, phase: 'PREPARE', selection: input.selection })
    .pipe(Effect.mapError(unavailable));
  return result.status === 'PREPARED'
    ? { ...result, sources: { ...result.sources, packageDefinition: result.sources.packageDefinition ?? null } }
    : result;
});

export const quantityPreparationRead = defineRead(
  {
    accessKind: 'detail',
    entrypoint: quantityPreparationEntrypoint,
    evidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: `${readKey}.evidence.v1`,
    },
    inputSchema: QuantityPreparationRequestSchema,
    legalEntityScope: 'required',
    owningModuleKey: moduleKey,
    permissionTarget: 'resource',
    policies: [],
    readKey: 'commerce.catalog.api.quantity-preparation',
    resourcePermission: defineReadResourcePermission<QuantityPreparationRequest>(({ selection }) => ({
      permission: 'read',
      resource: selection.productRef,
    })),
    resultSchema: QuantityPreparationResponseSchema,
    schemaVersion: '1',
  },
  Effect.fn('QuantityPreparationRead.handler')(function* handler(
    input: QuantityPreparationRequest,
    context: ReadHandlerContext<ReturnType<typeof catalogQuantityPreparationForScope>>,
  ) {
    const result = yield* readQuantityPreparation(input, context.scope.tenantId, context.services);
    return { evidence: { resultCount: result.status === 'PREPARED' ? 1 : 0 }, result };
  }),
  (transaction, scope) => Effect.succeed(catalogQuantityPreparationForScope(transaction, scope)),
  () => ({ kind: 'module', moduleId: moduleKey }),
);
