// @generated by @modern-js/ultramodern-create.
// Author route metadata in colocated src/routes/**/route.meta.ts files.
// This compatibility manifest is regenerated from route-owned metadata.

export const ultramodernRouteNamespace = 'workforce' as const;

const routeValue1 = 'workforce.planning';
const routeValue2 = '/';
const routeValue3 = '/workforce';

export const ultramodernRouteMetadata = [
  {
    canonicalPath: routeValue2,
    descriptionKey: 'workforce.seo.description',
    entrypoint: {
      access: 'read',
      authorization: {
        kind: 'context_permission',
        permission: 'module.access',
      },
      entrypointKey: 'workforce.planning.page.workforce-home',
      moduleKey: routeValue1,
      role: 'page',
      scope: 'tenant',
    },
    id: 'workforce-home',
    indexable: false,
    localisedPaths: {
      cs: routeValue2,
      en: routeValue2,
    },
    mfBoundaryId: 'verticalWorkforce',
    moduleId: routeValue1,
    namespace: ultramodernRouteNamespace,
    ownerAppId: ultramodernRouteNamespace,
    public: false,
    publicSurface: 'private-app-screen',
    titleKey: 'workforce.title',
  },
  {
    canonicalPath: routeValue3,
    descriptionKey: 'workforce.pages.workforce.description',
    entrypoint: {
      access: 'read',
      authorization: {
        kind: 'context_permission',
        permission: 'module.access',
      },
      entrypointKey: 'workforce.planning.page.workforce',
      moduleKey: routeValue1,
      role: 'page',
      scope: 'tenant',
    },
    id: 'workforce-workforce',
    indexable: false,
    localisedPaths: {
      cs: routeValue3,
      en: routeValue3,
    },
    mfBoundaryId: 'verticalWorkforce',
    moduleId: routeValue1,
    namespace: ultramodernRouteNamespace,
    ownerAppId: ultramodernRouteNamespace,
    public: false,
    publicSurface: 'private-app-screen',
    titleKey: 'workforce.pages.workforce.title',
  },
] as const;

export const ultramodernLocalisedUrls = {
  '/workforce': {
    cs: routeValue3,
    en: routeValue3,
  },
} as const;
