// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner pricing.price-group-catalog
// @ontos-action-http-slug create-price-group
import { Effect, Redacted, Schema } from 'effect';
import {
  CreatePriceGroupActionApi,
  CreatePriceGroupPayloadSchema,
} from '../../shared/apis/create-price-group-action.ts';
import type { CreatePriceGroupPayload } from '../../shared/actions/create-price-group.ts';
import { makePriceGroupActionEffectBffClient, operationGateway } from './action-gateway.ts';

const traceIdOption = 'traceId' as const;

export interface CreatePriceGroupActionClientOptions {
  readonly baseUrl?: string | URL;
  readonly gateway?: Parameters<typeof operationGateway.invoke>[1];
  readonly idempotencyKey: string;
  readonly [traceIdOption]?: string;
}

type AuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options: CreatePriceGroupActionClientOptions,
];
type OperationInvocation = readonly [requestCorrelation: string, options: CreatePriceGroupActionClientOptions];

interface MakeClientOptions {
  readonly credential: Redacted.Redacted;
  readonly options: CreatePriceGroupActionClientOptions;
  readonly requestCorrelation: string;
}

const makeClient = ({ credential, options, requestCorrelation }: MakeClientOptions) =>
  makePriceGroupActionEffectBffClient(
    {
      api: CreatePriceGroupActionApi,
      credential,
      defaultApiPrefix: '/price-group-catalog-api',
      requestCorrelation,
      requestTrace: options[traceIdOption],
    },
    options,
  );

export const executeCreatePriceGroupWithAuthorization = (
  payload: CreatePriceGroupPayload,
  ...[credential, requestCorrelation, options]: AuthorizedInvocation
) =>
  Schema.encodeUnknownEffect(CreatePriceGroupPayloadSchema)(payload).pipe(
    Effect.flatMap((encoded) =>
      makeClient({ credential: Redacted.make(credential), options, requestCorrelation }).pipe(
        Effect.flatMap((client) =>
          client.createPriceGroupAction.execute({
            headers: { 'idempotency-key': options.idempotencyKey },
            payload: encoded,
          }),
        ),
      ),
    ),
  );

export const executeCreatePriceGroup = (
  payload: CreatePriceGroupPayload,
  ...[requestCorrelation, options]: OperationInvocation
) =>
  operationGateway.invoke(
    (credential) => executeCreatePriceGroupWithAuthorization(payload, credential, requestCorrelation, options),
    options.gateway,
  );
