// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner pricing.price-group-catalog
// @ontos-action-http-slug retire-price-group
import { Effect, Redacted, Schema } from 'effect';
import {
  RetirePriceGroupActionApi,
  RetirePriceGroupPayloadSchema,
} from '../../shared/apis/retire-price-group-action.ts';
import type { RetirePriceGroupPayload } from '../../shared/actions/retire-price-group.ts';
import { makePriceGroupActionEffectBffClient, operationGateway } from './action-gateway.ts';

const traceIdOption = 'traceId' as const;

export interface RetirePriceGroupActionClientOptions {
  readonly baseUrl?: string | URL;
  readonly gateway?: Parameters<typeof operationGateway.invoke>[1];
  readonly idempotencyKey: string;
  readonly [traceIdOption]?: string;
}

type AuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options: RetirePriceGroupActionClientOptions,
];
type OperationInvocation = readonly [requestCorrelation: string, options: RetirePriceGroupActionClientOptions];

interface MakeClientOptions {
  readonly credential: Redacted.Redacted;
  readonly options: RetirePriceGroupActionClientOptions;
  readonly requestCorrelation: string;
}

const makeClient = ({ credential, options, requestCorrelation }: MakeClientOptions) =>
  makePriceGroupActionEffectBffClient(
    {
      api: RetirePriceGroupActionApi,
      credential,
      defaultApiPrefix: '/price-group-catalog-api',
      requestCorrelation,
      requestTrace: options[traceIdOption],
    },
    options,
  );

export const executeRetirePriceGroupWithAuthorization = (
  payload: RetirePriceGroupPayload,
  ...[credential, requestCorrelation, options]: AuthorizedInvocation
) =>
  Schema.encodeUnknownEffect(RetirePriceGroupPayloadSchema)(payload).pipe(
    Effect.flatMap((encoded) =>
      makeClient({ credential: Redacted.make(credential), options, requestCorrelation }).pipe(
        Effect.flatMap((client) =>
          client.retirePriceGroupAction.execute({
            headers: { 'idempotency-key': options.idempotencyKey },
            payload: encoded,
          }),
        ),
      ),
    ),
  );

export const executeRetirePriceGroup = (
  payload: RetirePriceGroupPayload,
  ...[requestCorrelation, options]: OperationInvocation
) =>
  operationGateway.invoke(
    (credential) => executeRetirePriceGroupWithAuthorization(payload, credential, requestCorrelation, options),
    options.gateway,
  );
