// @generated by OntOS Codesmith Action v1
// @ontos-action-owner workforce.planning
// @ontos-action-slug change-worker-status
import { DateTime, Effect, Schema } from 'effect';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import type { ActionHandlerContext } from '@app/core-runtime';
import {
  ChangeWorkerStatusPayloadSchema,
  ChangeWorkerStatusResultSchema,
} from '../../shared/actions/change-worker-status.ts';

import { WorkforceRejected, WorkforceUnavailable } from '../../shared/resources/workforce-failure.ts';
import { workforcePersistenceService } from '../services/workforce-persistence.service.ts';
import type { WorkforcePersistence } from '../services/workforce-persistence.service.ts';

import { recordWorker } from './worker-action-support.ts';

const handleChangeWorkerStatus = Effect.fn('ChangeWorkerStatus.handle')(function* handleChangeWorkerStatus(
  payload: typeof ChangeWorkerStatusPayloadSchema.Type,
  context: ActionHandlerContext<Record<never, never>, WorkforcePersistence>,
) {
  const current = yield* context.services.lock(payload.id);
  yield* recordWorker(context, current);
  if (current.revision !== payload.expectedRevision) {
    return yield* new WorkforceRejected({ code: 'revision_conflict', reason: 'Reload the Worker' });
  }
  const now = yield* DateTime.now;
  return yield* context.services.save(
    { ...current, revision: current.revision + 1, status: payload.status, updatedAt: now },
    payload.expectedRevision,
  );
});
export const changeWorkerStatusAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'workforce.planning.change-worker-status.access.v1',
    },
    actionKey: 'workforce.planning.change-worker-status',
    auditProfile: 'standard',
    domainErrorSchema: Schema.Union([WorkforceRejected, WorkforceUnavailable]),
    domainEvents: {},
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'tenant_membership_default' },
      entrypointKey: 'workforce.planning.change-worker-status',
      moduleKey: 'workforce.planning',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'required',
    owningModuleKey: 'workforce.planning',
    payloadSchema: ChangeWorkerStatusPayloadSchema,
    policies: [],
    resultSchema: ChangeWorkerStatusResultSchema,
    schemaVersion: '1',
  },
  handleChangeWorkerStatus,
  workforcePersistenceService,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>

export {
  ChangeWorkerStatusPayloadSchema,
  ChangeWorkerStatusResultSchema,
} from '../../shared/actions/change-worker-status.ts';
