// @generated by OntOS Codesmith Action v1
// @ontos-action-owner workforce.planning
// @ontos-action-slug remove-absence
import { DateTime, Effect, Schema } from 'effect';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import type { ActionHandlerContext } from '@app/core-runtime';
import { RemoveAbsencePayloadSchema, RemoveAbsenceResultSchema } from '../../shared/actions/remove-absence.ts';

import { WorkforceRejected, WorkforceUnavailable } from '../../shared/resources/workforce-failure.ts';
import { workforcePersistenceService } from '../services/workforce-persistence.service.ts';
import type { WorkforcePersistence } from '../services/workforce-persistence.service.ts';

import { recordWorker } from './worker-action-support.ts';
import { pragueDay } from '../domain/availability.ts';

const handleRemoveAbsence = Effect.fn('RemoveAbsence.handle')(function* handleRemoveAbsence(
  payload: typeof RemoveAbsencePayloadSchema.Type,
  context: ActionHandlerContext<Record<never, never>, WorkforcePersistence>,
) {
  const worker = yield* context.services.lock(payload.workerId);
  yield* recordWorker(context, worker);
  const absences = yield* context.services.absenceList(payload.workerId);
  const absence = absences.find((item) => item.id === payload.id);
  if (absence === undefined) {
    return yield* new WorkforceRejected({ code: 'not_found', reason: 'Absence was not found' });
  }
  if (absence.dateFrom <= pragueDay(DateTime.toEpochMillis(yield* DateTime.now))) {
    return yield* new WorkforceRejected({ code: 'invalid_absence', reason: 'A started absence cannot be removed' });
  }
  yield* context.services.removeAbsence(payload.workerId, payload.id);
  return worker;
});
export const removeAbsenceAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'workforce.planning.remove-absence.access.v1',
    },
    actionKey: 'workforce.planning.remove-absence',
    auditProfile: 'standard',
    domainErrorSchema: Schema.Union([WorkforceRejected, WorkforceUnavailable]),
    domainEvents: {},
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'tenant_membership_default' },
      entrypointKey: 'workforce.planning.remove-absence',
      moduleKey: 'workforce.planning',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'required',
    owningModuleKey: 'workforce.planning',
    payloadSchema: RemoveAbsencePayloadSchema,
    policies: [],
    resultSchema: RemoveAbsenceResultSchema,
    schemaVersion: '1',
  },
  handleRemoveAbsence,
  workforcePersistenceService,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>

export { RemoveAbsencePayloadSchema, RemoveAbsenceResultSchema } from '../../shared/actions/remove-absence.ts';
