// This file is auto-generated by Modern.js. Do not edit manually.

import {
  createMemoryHistory,
  createRootRouteWithContext,
  createRoute,
  createRouter,
  createRouteStaticData,
  type ModernRouterContext,
  modernLoaderToTanstack,
  modernTanstackRouterFastDefaults,
} from '@modern-js/plugin-tanstack/runtime';

import { loader as loader_0 } from "../../routes/[lang]/page.data";
import component_0 from "../../routes/[lang]/page";
import { loader as loader_1 } from "../../routes/[lang]/contacts/page.data";
import component_1 from "../../routes/[lang]/contacts/page";
import { loader as loader_2 } from "../../routes/[lang]/inquiries/page.data";
import component_2 from "../../routes/[lang]/inquiries/page";
import { loader as loader_3 } from "../../routes/[lang]/jobs/page.data";
import { validateSearch as validateSearch_0 } from "../../routes/[lang]/jobs/page.search";
import component_3 from "../../routes/[lang]/jobs/page";
import component_4 from "../../routes/[lang]/login/page";
import { loader as loader_4 } from "../../routes/[lang]/modules/[moduleId]/page.data";
import component_5 from "../../routes/[lang]/modules/[moduleId]/page";
import { loader as loader_5 } from "../../routes/[lang]/resources/[moduleId]/[resourceType]/[resourceId]/page.data";
import component_6 from "../../routes/[lang]/resources/[moduleId]/[resourceType]/[resourceId]/page";
import { loader as loader_6 } from "../../routes/[lang]/search/page.data";
import component_7 from "../../routes/[lang]/search/page";
import component_8 from "../../routes/layout";

export const rootRoute = createRootRouteWithContext<ModernRouterContext>()({
  component: component_8,
  staticData: createRouteStaticData({
    modernRouteId: "layout",
  }),

});

const route__lang__page = createRoute({
  getParentRoute: () => rootRoute,
  path: "$lang",
  component: component_0,
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_0),
  staticData: createRouteStaticData({
    modernRouteId: "(lang)/page",
    modernRouteLoader: loader_0,
  }),
});

const route__lang__contacts_page = createRoute({
  getParentRoute: () => rootRoute,
  path: "$lang/contacts",
  component: component_1,
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_1),
  staticData: createRouteStaticData({
    modernRouteId: "(lang)/contacts/page",
    modernRouteLoader: loader_1,
  }),
});

const route__lang__inquiries_page = createRoute({
  getParentRoute: () => rootRoute,
  path: "$lang/inquiries",
  component: component_2,
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_2),
  staticData: createRouteStaticData({
    modernRouteId: "(lang)/inquiries/page",
    modernRouteLoader: loader_2,
  }),
});

const route__lang__jobs_page = createRoute({
  getParentRoute: () => rootRoute,
  path: "$lang/jobs",
  component: component_3,
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_3),
  validateSearch: validateSearch_0,
  staticData: createRouteStaticData({
    modernRouteId: "(lang)/jobs/page",
    modernRouteLoader: loader_3,
  }),
});

const route__lang__login_page = createRoute({
  getParentRoute: () => rootRoute,
  path: "$lang/login",
  component: component_4,
  staticData: createRouteStaticData({
    modernRouteId: "(lang)/login/page",
  }),
});

const route__lang__modules__moduleId__page = createRoute({
  getParentRoute: () => rootRoute,
  path: "$lang/modules/$moduleId",
  component: component_5,
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_4),
  staticData: createRouteStaticData({
    modernRouteId: "(lang)/modules/(moduleId)/page",
    modernRouteLoader: loader_4,
  }),
});

const route__lang__resources__moduleId___resourceType___resourceId__page = createRoute({
  getParentRoute: () => rootRoute,
  path: "$lang/resources/$moduleId/$resourceType/$resourceId",
  component: component_6,
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_5),
  staticData: createRouteStaticData({
    modernRouteId: "(lang)/resources/(moduleId)/(resourceType)/(resourceId)/page",
    modernRouteLoader: loader_5,
  }),
});

const route__lang__search_page = createRoute({
  getParentRoute: () => rootRoute,
  path: "$lang/search",
  component: component_7,
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_6),
  staticData: createRouteStaticData({
    modernRouteId: "(lang)/search/page",
    modernRouteLoader: loader_6,
  }),
});

export const routeTree = rootRoute.addChildren([route__lang__page, route__lang__contacts_page, route__lang__inquiries_page, route__lang__jobs_page, route__lang__login_page, route__lang__modules__moduleId__page, route__lang__resources__moduleId___resourceType___resourceId__page, route__lang__search_page]);

export const router = createRouter({
  ...modernTanstackRouterFastDefaults,
  routeTree,
  history: createMemoryHistory({
    initialEntries: ['/'],
  }),
  context: {},
});
