// @generated by OntOS Codesmith module-api v1
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { Schema } from 'effect';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';

import { JobIdSchema, ServiceJobSchema } from '../resources/service-job.ts';
import { SalesInquiryRefSchema } from '@app/sales-inquiries/resources/sales-inquiry';

export const JobDetailRequestSchema = Schema.Struct({
  target: Schema.Union([Schema.Struct({ id: JobIdSchema }), Schema.Struct({ sourceRef: SalesInquiryRefSchema })]),
});
export type JobDetailRequest = typeof JobDetailRequestSchema.Type;
export const JobDetailResponseSchema = ServiceJobSchema;

export const JobDetailAuthenticationProblemSchema = makeProblemDetailsSchema('JobDetailAuthenticationProblem', 401);
export const JobDetailInvalidProblemSchema = makeProblemDetailsSchema('JobDetailInvalidProblem', 400);
export const JobDetailUnavailableProblemSchema = makeRetryableProblemDetailsSchema('JobDetailUnavailableProblem', 503);
export const JobDetailForbiddenProblemSchema = makeProblemDetailsSchema('JobDetailForbiddenProblem', 403);
export const JobDetailNotFoundProblemSchema = makeProblemDetailsSchema('JobDetailNotFoundProblem', 404);
export const JobDetailPolicyProblemSchema = makeProblemDetailsSchema('JobDetailPolicyProblem', 422);
export const JobDetailPolicyConflictProblemSchema = makeProblemDetailsSchema('JobDetailPolicyConflictProblem', 409);
export const JobDetailInternalProblemSchema = makeProblemDetailsSchema('JobDetailInternalProblem', 500);

export const JobDetailApi = HttpApi.make('JobDetailApi').add(
  HttpApiGroup.make('jobDetail').add(
    HttpApiEndpoint.post('execute', '/reads/job-detail', {
      error: [
        JobDetailInvalidProblemSchema,
        JobDetailAuthenticationProblemSchema,
        JobDetailForbiddenProblemSchema,
        JobDetailNotFoundProblemSchema,
        JobDetailPolicyConflictProblemSchema,
        JobDetailPolicyProblemSchema,
        JobDetailUnavailableProblemSchema,
        JobDetailInternalProblemSchema,
      ],
      headers: {},
      params: {},
      payload: JobDetailRequestSchema,
      query: {},
      success: JobDetailResponseSchema,
    }),
  ),
);
