// @generated by OntOS Codesmith module-api v1
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { DateTime, Option, Schema, SchemaGetter } from 'effect';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';

import { ServiceJobRefSchema, ServiceJobSchema } from '../resources/service-job.ts';

export const JobListViewSchema = Schema.Literals(['ALL', 'TODAY', 'UPCOMING', 'IN_PROGRESS', 'COMPLETED']);
const isUuid = Schema.is(Schema.String.check(Schema.isUUID()));
export const JobListCursorSchema = Schema.String.check(
  Schema.isMinLength(1),
  Schema.isMaxLength(120),
  Schema.isPattern(/^\d{1,17}~[^~]{36}$/u),
  Schema.makeFilter((value) => isUuid(value.slice(value.indexOf('~') + 1))),
);
const utcInstantSchema = Schema.String.check(
  Schema.isPattern(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/u),
  Schema.makeFilter((value) => {
    const instant = DateTime.make(value);
    if (Option.isNone(instant)) {
      return false;
    }
    const canonical = DateTime.formatIso(instant.value);
    return value === canonical || value === canonical.replace('.000Z', 'Z');
  }),
).pipe(
  Schema.decodeTo(Schema.toType(Schema.DateTimeUtc), {
    decode: SchemaGetter.transform(DateTime.makeUnsafe),
    encode: SchemaGetter.transform(DateTime.formatIso),
  }),
);
/** Complete bounded union for planning: one provider request consumes one assertion. */
export const JobScheduleSelectionSchema = Schema.Struct({
  interval: Schema.optionalKey(
    Schema.Struct({
      from: utcInstantSchema,
      to: utcInstantSchema,
    }).check(
      Schema.makeFilter(({ from, to }) => {
        const duration = DateTime.toEpochMillis(to) - DateTime.toEpochMillis(from);
        return duration > 0 && duration <= 8 * 86_400_000;
      }),
    ),
  ),
  references: Schema.Array(ServiceJobRefSchema).check(Schema.isMaxLength(1000)),
}).check(Schema.makeFilter(({ interval, references }) => interval !== undefined || references.length > 0));
export const JobListRequestSchema = Schema.Struct({
  cursor: Schema.optionalKey(JobListCursorSchema),
  pageSize: Schema.optionalKey(Schema.Int.check(Schema.isGreaterThanOrEqualTo(1), Schema.isLessThanOrEqualTo(100))),
  selection: Schema.optionalKey(JobScheduleSelectionSchema),
  view: Schema.optionalKey(JobListViewSchema),
}).check(
  Schema.makeFilter(
    ({ cursor, pageSize, selection, view }) =>
      selection === undefined || (view === undefined && cursor === undefined && pageSize === undefined),
  ),
);
export type JobListRequest = typeof JobListRequestSchema.Type;
export const JobListResponseSchema = Schema.Struct({
  items: Schema.Array(ServiceJobSchema),
  nextCursor: Schema.toEncoded(Schema.OptionFromNullOr(JobListCursorSchema)),
});
export type JobListResponse = typeof JobListResponseSchema.Type;

export const JobListAuthenticationProblemSchema = makeProblemDetailsSchema('JobListAuthenticationProblem', 401);
export const JobListInvalidProblemSchema = makeProblemDetailsSchema('JobListInvalidProblem', 400);
export const JobListUnavailableProblemSchema = makeRetryableProblemDetailsSchema('JobListUnavailableProblem', 503);
export const JobListForbiddenProblemSchema = makeProblemDetailsSchema('JobListForbiddenProblem', 403);
export const JobListNotFoundProblemSchema = makeProblemDetailsSchema('JobListNotFoundProblem', 404);
export const JobListPolicyProblemSchema = makeProblemDetailsSchema('JobListPolicyProblem', 422);
export const JobListPolicyConflictProblemSchema = makeProblemDetailsSchema('JobListPolicyConflictProblem', 409);
export const JobListInternalProblemSchema = makeProblemDetailsSchema('JobListInternalProblem', 500);

export const JobListApi = HttpApi.make('JobListApi').add(
  HttpApiGroup.make('jobList').add(
    HttpApiEndpoint.post('execute', '/reads/job-list', {
      error: [
        JobListInvalidProblemSchema,
        JobListAuthenticationProblemSchema,
        JobListForbiddenProblemSchema,
        JobListNotFoundProblemSchema,
        JobListPolicyConflictProblemSchema,
        JobListPolicyProblemSchema,
        JobListUnavailableProblemSchema,
        JobListInternalProblemSchema,
      ],
      headers: {},
      params: {},
      payload: JobListRequestSchema,
      query: {},
      success: JobListResponseSchema,
    }),
  ),
);
