// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner service.jobs
// @ontos-action-http-slug update-execution
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { HttpApi, HttpApiEndpoint, HttpApiGroup, Schema } from '@modern-js/bff-effect/effect-client';
import { HttpApiMiddleware } from 'effect/unstable/httpapi';
import { UpdateExecutionPayloadSchema, UpdateExecutionResultSchema } from '../actions/update-execution.ts';

export { UpdateExecutionPayloadSchema } from '../actions/update-execution.ts';

const UpdateExecutionActionHeadersSchema = Schema.Struct({
  'idempotency-key': Schema.optionalKey(Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(200))),
});

export const UpdateExecutionActionInvalidProblemSchema = makeProblemDetailsSchema(
  'UpdateExecutionActionInvalidProblem',
  400,
);
export const UpdateExecutionActionAuthenticationProblemSchema = makeProblemDetailsSchema(
  'UpdateExecutionActionAuthenticationProblem',
  401,
);
export const UpdateExecutionActionForbiddenProblemSchema = makeProblemDetailsSchema(
  'UpdateExecutionActionForbiddenProblem',
  403,
  {
    code: Schema.Literals([
      'action_permission_denied',
      'module_state_denied',
      'operation_context_denied',
      'operation_context_invalid',
    ]),
  },
);
export const UpdateExecutionActionNotFoundProblemSchema = makeProblemDetailsSchema(
  'UpdateExecutionActionNotFoundProblem',
  404,
  { code: Schema.Literals(['action_invocation_not_found', 'not_found']) },
);
export const UpdateExecutionActionConflictProblemSchema = makeProblemDetailsSchema(
  'UpdateExecutionActionConflictProblem',
  409,
  { code: Schema.Literals(['action_request_hash_conflict', 'action_invocation_state_invalid', 'revision_conflict']) },
);
export const UpdateExecutionActionIneligibleProblemSchema = makeProblemDetailsSchema(
  'UpdateExecutionActionIneligibleProblem',
  422,
  { code: Schema.Literals(['action_policy_denied', 'invalid_transition', 'source_invalid']) },
);
export const UpdateExecutionActionPreconditionProblemSchema = makeProblemDetailsSchema(
  'UpdateExecutionActionPreconditionProblem',
  428,
);
export const UpdateExecutionActionUnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  'UpdateExecutionActionUnavailableProblem',
  503,
  {
    code: Schema.Literals([
      'action_invocation_persistence_failed',
      'action_permission_check_failed',
      'action_policy_evaluation_failed',
      'action_transaction_failed',
      'module_state_check_unavailable',
      'operation_context_unavailable',
      'authentication',
      'conflict',
      'forbidden',
      'ineligible',
      'internal',
      'invalid',
      'not_found',
      'job_unavailable',
    ]),
  },
);
export const UpdateExecutionActionAlreadyCommittedProblemSchema = makeProblemDetailsSchema(
  'UpdateExecutionActionAlreadyCommittedProblem',
  409,
  {
    code: Schema.Literal('action_already_committed'),
    invocationId: Schema.String,
    resolution: Schema.Literal('REFRESH_GOVERNED_READS'),
    retryCommand: Schema.Literal(false),
  },
);
export const UpdateExecutionActionCommitIndeterminateProblemSchema = makeProblemDetailsSchema(
  'UpdateExecutionActionCommitIndeterminateProblem',
  503,
  {
    invocationId: Schema.String,
    resolution: Schema.Literal('RESOLVE_COMMIT'),
    retryCommand: Schema.Literal(false),
  },
);
export const UpdateExecutionActionInternalProblemSchema = makeProblemDetailsSchema(
  'UpdateExecutionActionInternalProblem',
  500,
);

export type UpdateExecutionActionProblem =
  | typeof UpdateExecutionActionInvalidProblemSchema.Type
  | typeof UpdateExecutionActionAuthenticationProblemSchema.Type
  | typeof UpdateExecutionActionForbiddenProblemSchema.Type
  | typeof UpdateExecutionActionNotFoundProblemSchema.Type
  | typeof UpdateExecutionActionConflictProblemSchema.Type
  | typeof UpdateExecutionActionIneligibleProblemSchema.Type
  | typeof UpdateExecutionActionPreconditionProblemSchema.Type
  | typeof UpdateExecutionActionUnavailableProblemSchema.Type
  | typeof UpdateExecutionActionAlreadyCommittedProblemSchema.Type
  | typeof UpdateExecutionActionCommitIndeterminateProblemSchema.Type
  | typeof UpdateExecutionActionInternalProblemSchema.Type;

export class UpdateExecutionActionSchemaErrorMiddleware extends HttpApiMiddleware.Service<UpdateExecutionActionSchemaErrorMiddleware>()(
  'service-jobs/UpdateExecutionActionSchemaErrorMiddleware',
  { error: UpdateExecutionActionInvalidProblemSchema },
) {}

const actionErrors = [
  UpdateExecutionActionInvalidProblemSchema,
  UpdateExecutionActionAuthenticationProblemSchema,
  UpdateExecutionActionForbiddenProblemSchema,
  UpdateExecutionActionNotFoundProblemSchema,
  UpdateExecutionActionConflictProblemSchema,
  UpdateExecutionActionIneligibleProblemSchema,
  UpdateExecutionActionPreconditionProblemSchema,
  UpdateExecutionActionUnavailableProblemSchema,
  UpdateExecutionActionAlreadyCommittedProblemSchema,
  UpdateExecutionActionCommitIndeterminateProblemSchema,
  UpdateExecutionActionInternalProblemSchema,
] as const;

/**
 * The endpoint chain stays a `const`. The MicroVertical API boundary checker walks a root API's
 * operands through const bindings only, so a class declaration hides the composed endpoints from
 * it. The exported group is annotated with a named type alias so its type still has a name: the
 * vertical's `shared/api.ts` merges every group type into one `HttpApi` and declaration emit
 * serializes that union verbatim, so an anonymous group type pushes the composed contract past
 * the compiler's serialization limit (TS7056).
 *
 * Exported only so the named contract type can reference it; the merged vertical HttpApi prints
 * this group by name (declaration-emit size).
 *
 * @public
 */
export const updateExecutionActionGroupDefinition = HttpApiGroup.make('updateExecutionAction')
  .add(
    HttpApiEndpoint.post('execute', '/service-jobs/actions/update-execution', {
      error: actionErrors,
      headers: UpdateExecutionActionHeadersSchema,
      payload: Schema.toEncoded(UpdateExecutionPayloadSchema),
      success: UpdateExecutionResultSchema,
    }),
  )
  .middleware(UpdateExecutionActionSchemaErrorMiddleware);

export type UpdateExecutionActionGroupContract = HttpApiGroup.HttpApiGroup<
  'updateExecutionAction',
  HttpApiGroup.Endpoints<typeof updateExecutionActionGroupDefinition>
>;

const UpdateExecutionActionGroup: UpdateExecutionActionGroupContract = updateExecutionActionGroupDefinition;

export const UpdateExecutionActionApi = HttpApi.make('UpdateExecutionActionApi').add(UpdateExecutionActionGroup);
