// @generated by OntOS Codesmith module-api v1
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { Schema } from 'effect';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';

import { ServiceJobRefSchema } from '@app/service-jobs/resources/service-job';
import { WorkerCandidateSchema } from '../workforce-views.ts';

export const AvailableWorkersRequestSchema = Schema.Struct({ jobRef: ServiceJobRefSchema });
export type AvailableWorkersRequest = typeof AvailableWorkersRequestSchema.Type;
export const AvailableWorkersResponseSchema = Schema.Struct({ items: Schema.Array(WorkerCandidateSchema) });

export const AvailableWorkersAuthenticationProblemSchema = makeProblemDetailsSchema(
  'AvailableWorkersAuthenticationProblem',
  401,
);
export const AvailableWorkersInvalidProblemSchema = makeProblemDetailsSchema('AvailableWorkersInvalidProblem', 400);
export const AvailableWorkersUnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  'AvailableWorkersUnavailableProblem',
  503,
);
export const AvailableWorkersForbiddenProblemSchema = makeProblemDetailsSchema('AvailableWorkersForbiddenProblem', 403);
export const AvailableWorkersNotFoundProblemSchema = makeProblemDetailsSchema('AvailableWorkersNotFoundProblem', 404);
export const AvailableWorkersPolicyProblemSchema = makeProblemDetailsSchema('AvailableWorkersPolicyProblem', 422);
export const AvailableWorkersPolicyConflictProblemSchema = makeProblemDetailsSchema(
  'AvailableWorkersPolicyConflictProblem',
  409,
);
export const AvailableWorkersInternalProblemSchema = makeProblemDetailsSchema('AvailableWorkersInternalProblem', 500);

export const AvailableWorkersApi = HttpApi.make('AvailableWorkersApi').add(
  HttpApiGroup.make('availableWorkers').add(
    HttpApiEndpoint.post('execute', '/reads/available-workers', {
      error: [
        AvailableWorkersInvalidProblemSchema,
        AvailableWorkersAuthenticationProblemSchema,
        AvailableWorkersForbiddenProblemSchema,
        AvailableWorkersNotFoundProblemSchema,
        AvailableWorkersPolicyConflictProblemSchema,
        AvailableWorkersPolicyProblemSchema,
        AvailableWorkersUnavailableProblemSchema,
        AvailableWorkersInternalProblemSchema,
      ],
      headers: {},
      params: {},
      payload: AvailableWorkersRequestSchema,
      query: {},
      success: AvailableWorkersResponseSchema,
    }),
  ),
);
