// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner workforce.planning
// @ontos-action-http-slug update-worker
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { HttpApi, HttpApiEndpoint, HttpApiGroup, Schema } from '@modern-js/bff-effect/effect-client';
import { HttpApiMiddleware } from 'effect/unstable/httpapi';
import { UpdateWorkerPayloadSchema, UpdateWorkerResultSchema } from '../actions/update-worker.ts';

export { UpdateWorkerPayloadSchema } from '../actions/update-worker.ts';

const UpdateWorkerActionHeadersSchema = Schema.Struct({
  'idempotency-key': Schema.optionalKey(Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(200))),
});

export const UpdateWorkerActionInvalidProblemSchema = makeProblemDetailsSchema('UpdateWorkerActionInvalidProblem', 400);
export const UpdateWorkerActionAuthenticationProblemSchema = makeProblemDetailsSchema(
  'UpdateWorkerActionAuthenticationProblem',
  401,
);
export const UpdateWorkerActionForbiddenProblemSchema = makeProblemDetailsSchema(
  'UpdateWorkerActionForbiddenProblem',
  403,
  {
    code: Schema.Literals([
      'action_permission_denied',
      'module_state_denied',
      'operation_context_denied',
      'operation_context_invalid',
      'scope_mismatch',
    ]),
  },
);
export const UpdateWorkerActionNotFoundProblemSchema = makeProblemDetailsSchema(
  'UpdateWorkerActionNotFoundProblem',
  404,
  { code: Schema.Literals(['action_invocation_not_found', 'not_found']) },
);
export const UpdateWorkerActionConflictProblemSchema = makeProblemDetailsSchema(
  'UpdateWorkerActionConflictProblem',
  409,
  {
    code: Schema.Literals([
      'action_request_hash_conflict',
      'action_invocation_state_invalid',
      'job_conflict',
      'revision_conflict',
    ]),
  },
);
export const UpdateWorkerActionIneligibleProblemSchema = makeProblemDetailsSchema(
  'UpdateWorkerActionIneligibleProblem',
  422,
  {
    code: Schema.Literals([
      'action_policy_denied',
      'absence_blocked',
      'crew_locked',
      'invalid_absence',
      'invalid_job',
      'invalid_worker',
      'outside_agreement',
      'worker_inactive',
    ]),
  },
);
export const UpdateWorkerActionPreconditionProblemSchema = makeProblemDetailsSchema(
  'UpdateWorkerActionPreconditionProblem',
  428,
);
export const UpdateWorkerActionUnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  'UpdateWorkerActionUnavailableProblem',
  503,
  {
    code: Schema.Literals([
      'action_invocation_persistence_failed',
      'action_permission_check_failed',
      'action_policy_evaluation_failed',
      'action_transaction_failed',
      'module_state_check_unavailable',
      'operation_context_unavailable',
      'workforce_unavailable',
    ]),
  },
);
export const UpdateWorkerActionAlreadyCommittedProblemSchema = makeProblemDetailsSchema(
  'UpdateWorkerActionAlreadyCommittedProblem',
  409,
  {
    code: Schema.Literal('action_already_committed'),
    invocationId: Schema.String,
    resolution: Schema.Literal('REFRESH_GOVERNED_READS'),
    retryCommand: Schema.Literal(false),
  },
);
export const UpdateWorkerActionCommitIndeterminateProblemSchema = makeProblemDetailsSchema(
  'UpdateWorkerActionCommitIndeterminateProblem',
  503,
  {
    invocationId: Schema.String,
    resolution: Schema.Literal('RESOLVE_COMMIT'),
    retryCommand: Schema.Literal(false),
  },
);
export const UpdateWorkerActionInternalProblemSchema = makeProblemDetailsSchema(
  'UpdateWorkerActionInternalProblem',
  500,
);

export type UpdateWorkerActionProblem =
  | typeof UpdateWorkerActionInvalidProblemSchema.Type
  | typeof UpdateWorkerActionAuthenticationProblemSchema.Type
  | typeof UpdateWorkerActionForbiddenProblemSchema.Type
  | typeof UpdateWorkerActionNotFoundProblemSchema.Type
  | typeof UpdateWorkerActionConflictProblemSchema.Type
  | typeof UpdateWorkerActionIneligibleProblemSchema.Type
  | typeof UpdateWorkerActionPreconditionProblemSchema.Type
  | typeof UpdateWorkerActionUnavailableProblemSchema.Type
  | typeof UpdateWorkerActionAlreadyCommittedProblemSchema.Type
  | typeof UpdateWorkerActionCommitIndeterminateProblemSchema.Type
  | typeof UpdateWorkerActionInternalProblemSchema.Type;

export class UpdateWorkerActionSchemaErrorMiddleware extends HttpApiMiddleware.Service<UpdateWorkerActionSchemaErrorMiddleware>()(
  'workforce/UpdateWorkerActionSchemaErrorMiddleware',
  { error: UpdateWorkerActionInvalidProblemSchema },
) {}

const actionErrors = [
  UpdateWorkerActionInvalidProblemSchema,
  UpdateWorkerActionAuthenticationProblemSchema,
  UpdateWorkerActionForbiddenProblemSchema,
  UpdateWorkerActionNotFoundProblemSchema,
  UpdateWorkerActionConflictProblemSchema,
  UpdateWorkerActionIneligibleProblemSchema,
  UpdateWorkerActionPreconditionProblemSchema,
  UpdateWorkerActionUnavailableProblemSchema,
  UpdateWorkerActionAlreadyCommittedProblemSchema,
  UpdateWorkerActionCommitIndeterminateProblemSchema,
  UpdateWorkerActionInternalProblemSchema,
] as const;

/**
 * The endpoint chain stays a `const`. The MicroVertical API boundary checker walks a root API's
 * operands through const bindings only, so a class declaration hides the composed endpoints from
 * it. The exported group is annotated with a named type alias so its type still has a name: the
 * vertical's `shared/api.ts` merges every group type into one `HttpApi` and declaration emit
 * serializes that union verbatim, so an anonymous group type pushes the composed contract past
 * the compiler's serialization limit (TS7056).
 *
 * Exported only so the named contract type can reference it; the merged vertical HttpApi prints
 * this group by name (declaration-emit size).
 *
 * @public
 */
export const updateWorkerActionGroupDefinition = HttpApiGroup.make('updateWorkerAction')
  .add(
    HttpApiEndpoint.post('execute', '/workforce/actions/update-worker', {
      error: actionErrors,
      headers: UpdateWorkerActionHeadersSchema,
      payload: Schema.toEncoded(UpdateWorkerPayloadSchema),
      success: UpdateWorkerResultSchema,
    }),
  )
  .middleware(UpdateWorkerActionSchemaErrorMiddleware);

export type UpdateWorkerActionGroupContract = HttpApiGroup.HttpApiGroup<
  'updateWorkerAction',
  HttpApiGroup.Endpoints<typeof updateWorkerActionGroupDefinition>
>;

const UpdateWorkerActionGroup: UpdateWorkerActionGroupContract = updateWorkerActionGroupDefinition;

export const UpdateWorkerActionApi = HttpApi.make('UpdateWorkerActionApi').add(UpdateWorkerActionGroup);
