// @generated by OntOS Codesmith module-api v1
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { Schema } from 'effect';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';

export const WorkforceCommitStatusRequestSchema = Schema.Struct({
  invocationId: Schema.String.check(Schema.isUUID()).pipe(Schema.brand('ActionInvocationId')),
});
export type WorkforceCommitStatusRequest = typeof WorkforceCommitStatusRequestSchema.Type;
export const WorkforceCommitStatusResponseSchema = Schema.Struct({
  retryCommand: Schema.Boolean,
  state: Schema.Literals(['OPEN', 'COMMITTED', 'INDETERMINATE']),
});

export const WorkforceCommitStatusAuthenticationProblemSchema = makeProblemDetailsSchema(
  'WorkforceCommitStatusAuthenticationProblem',
  401,
);
export const WorkforceCommitStatusInvalidProblemSchema = makeProblemDetailsSchema(
  'WorkforceCommitStatusInvalidProblem',
  400,
);
export const WorkforceCommitStatusUnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  'WorkforceCommitStatusUnavailableProblem',
  503,
);
export const WorkforceCommitStatusForbiddenProblemSchema = makeProblemDetailsSchema(
  'WorkforceCommitStatusForbiddenProblem',
  403,
);
export const WorkforceCommitStatusNotFoundProblemSchema = makeProblemDetailsSchema(
  'WorkforceCommitStatusNotFoundProblem',
  404,
);
export const WorkforceCommitStatusPolicyProblemSchema = makeProblemDetailsSchema(
  'WorkforceCommitStatusPolicyProblem',
  422,
);
export const WorkforceCommitStatusPolicyConflictProblemSchema = makeProblemDetailsSchema(
  'WorkforceCommitStatusPolicyConflictProblem',
  409,
);
export const WorkforceCommitStatusInternalProblemSchema = makeProblemDetailsSchema(
  'WorkforceCommitStatusInternalProblem',
  500,
);

export const WorkforceCommitStatusApi = HttpApi.make('WorkforceCommitStatusApi').add(
  HttpApiGroup.make('workforceCommitStatus').add(
    HttpApiEndpoint.post('execute', '/reads/workforce-commit-status', {
      error: [
        WorkforceCommitStatusInvalidProblemSchema,
        WorkforceCommitStatusAuthenticationProblemSchema,
        WorkforceCommitStatusForbiddenProblemSchema,
        WorkforceCommitStatusNotFoundProblemSchema,
        WorkforceCommitStatusPolicyConflictProblemSchema,
        WorkforceCommitStatusPolicyProblemSchema,
        WorkforceCommitStatusUnavailableProblemSchema,
        WorkforceCommitStatusInternalProblemSchema,
      ],
      headers: {},
      params: {},
      payload: WorkforceCommitStatusRequestSchema,
      query: {},
      success: WorkforceCommitStatusResponseSchema,
    }),
  ),
);
