// @generated by OntOS Codesmith module-api v1
import type { ReadHandlerContext } from '@app/core-runtime';
import { ReadPermissionDenied, defineRead, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { Effect, Option } from 'effect';
import {
  EligibleMarketTuplesRequestSchema,
  EligibleMarketTuplesResponseSchema,
} from '../../shared/apis/eligible-market-tuples.ts';
import type {
  EligibleMarketTuplesRequest,
  EligibleMarketTuplesResponse,
} from '../../shared/apis/eligible-market-tuples.ts';
import { discoverEligibleMarketTuples } from '../domain/market-resolution.ts';
import type { MarketResolutionPersistence } from '../persistence/market-resolution-persistence.ts';
import { marketResolutionPersistenceForScope } from '../persistence/market-resolution-persistence.ts';

const commerceMarketCatalogModuleKey = 'commerce.market-catalog';

const eligibleMarketTuplesEntrypoint = defineTenantModuleEntrypoint({
  access: 'read',
  authorization: { kind: 'context_permission', permission: 'module.access' },
  entrypointKey: 'commerce.market-catalog.api.eligible-market-tuples',
  moduleKey: commerceMarketCatalogModuleKey,
  role: 'api',
});

const unavailable = (): EligibleMarketTuplesResponse => ({
  outcome: 'MARKET_ELIGIBILITY_UNAVAILABLE',
  reason: 'Current Commerce Market eligibility could not be established',
  retryable: true,
});

const validateTrustedScope = (
  input: EligibleMarketTuplesRequest,
  context: ReadHandlerContext<MarketResolutionPersistence>,
) => {
  if (
    input.storefrontRef.tenantId !== context.scope.tenantId ||
    context.scope.trustedStorefrontId === undefined ||
    input.storefrontRef.appId !== context.scope.trustedStorefrontId
  ) {
    return Effect.fail(
      new ReadPermissionDenied({
        code: 'read_permission_denied',
        reason: 'The requested Storefront is outside the trusted operational context',
      }),
    );
  }
  if (
    input.sellingLegalEntityRestriction !== undefined &&
    (input.sellingLegalEntityRestriction.tenantId !== context.scope.tenantId ||
      input.sellingLegalEntityRestriction.resourceId !== context.scope.legalEntityId)
  ) {
    return Effect.fail(
      new ReadPermissionDenied({
        code: 'read_permission_denied',
        reason: 'The seller restriction is not owner-issued by the trusted operational context',
      }),
    );
  }
  if (
    input.channel === 'B2B' &&
    input.subject?.kind === 'COUNTERPARTY' &&
    input.sellingLegalEntityRestriction === undefined
  ) {
    return Effect.fail(
      new ReadPermissionDenied({
        code: 'read_permission_denied',
        reason: 'Counterparty discovery requires an owner-issued seller restriction',
      }),
    );
  }
  return Effect.succeed(true as const);
};

export const handleEligibleMarketTuples = Effect.fn('EligibleMarketTuplesRead.handle')(
  function* handleEligibleMarketTuplesEffect(
    input: EligibleMarketTuplesRequest,
    context: ReadHandlerContext<MarketResolutionPersistence>,
  ) {
    yield* validateTrustedScope(input, context);
    const snapshot = yield* context.services.load(input).pipe(Effect.option);
    const result = Option.isNone(snapshot) ? unavailable() : discoverEligibleMarketTuples(input, snapshot.value);
    return {
      evidence: { resultCount: result.outcome === 'ELIGIBLE_MARKET_TUPLES' ? result.tuples.length : 0 },
      result,
    };
  },
);

export const eligibleMarketTuplesRead = defineRead(
  {
    accessKind: 'detail',
    entrypoint: eligibleMarketTuplesEntrypoint,
    evidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.market-catalog.api.eligible-market-tuples.evidence.v1',
    },
    inputSchema: EligibleMarketTuplesRequestSchema,
    legalEntityScope: 'optional',
    owningModuleKey: commerceMarketCatalogModuleKey,
    permissionTarget: 'module',
    policies: [],
    readKey: 'commerce.market-catalog.api.eligible-market-tuples',
    resultSchema: EligibleMarketTuplesResponseSchema,
    schemaVersion: '1',
  },
  handleEligibleMarketTuples,
  (transaction, scope) => marketResolutionPersistenceForScope(transaction, scope),
  () => ({ kind: 'module', moduleId: commerceMarketCatalogModuleKey }),
);
