// @generated by OntOS Codesmith module-api v1
import { ReadHandlerUnavailable, defineRead, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { Effect } from 'effect';
import { MarketHistoryRequestSchema, MarketHistoryResponseSchema } from '../../shared/apis/market-history.ts';

const commerceMarketCatalogModuleKey = 'commerce.market-catalog';

const marketHistoryEntrypoint = defineTenantModuleEntrypoint({
  access: 'read',
  authorization: { kind: 'context_permission', permission: 'module.access' },
  entrypointKey: 'commerce.market-catalog.api.market-history',
  moduleKey: commerceMarketCatalogModuleKey,
  role: 'api',
});

export const marketHistoryRead = defineRead(
  {
    accessKind: 'detail',
    entrypoint: marketHistoryEntrypoint,
    evidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.market-catalog.api.market-history.evidence.v1',
    },
    inputSchema: MarketHistoryRequestSchema,
    legalEntityScope: 'required',
    owningModuleKey: commerceMarketCatalogModuleKey,
    permissionTarget: 'module',
    policies: [],
    readKey: 'commerce.market-catalog.api.market-history',
    resultSchema: MarketHistoryResponseSchema,
    schemaVersion: '1',
  },
  () =>
    Effect.fail(
      new ReadHandlerUnavailable({
        code: 'read_handler_unavailable',
        reason: 'Market history persistence is not implemented',
      }),
    ),
  () => Effect.succeed({}),
  () => ({ kind: 'module', moduleId: commerceMarketCatalogModuleKey }),
);
