// @generated by OntOS Codesmith MicroVertical Action Boundary v1
// @ontos-action-boundary-owner billing-documents
// @ontos-action-boundary-audience billing-documents
import { issueGatewayContext, makeOperationGateway as makeSharedOperationGateway } from '@app/shared-contracts';
import type {
  GatewayContextClientError,
  OperationGatewayIssuer as SharedOperationGatewayIssuer,
} from '@app/shared-contracts';

export const ACTION_GATEWAY_AUDIENCE = 'billing-documents' as const;

export type OperationGatewayIssuer = SharedOperationGatewayIssuer<
  typeof ACTION_GATEWAY_AUDIENCE,
  GatewayContextClientError
>;

export const makeOperationGateway = (acquire: OperationGatewayIssuer = issueGatewayContext) =>
  makeSharedOperationGateway(ACTION_GATEWAY_AUDIENCE, acquire);

export const operationGateway = makeOperationGateway();
