// @generated by OntOS Codesmith module-api v1
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted } from 'effect';
import { InvoiceableJobsApi } from '../../shared/apis/invoiceable-jobs.ts';
import type { InvoiceableJobsRequest } from '../../shared/apis/invoiceable-jobs.ts';
import { operationGateway } from './action-gateway.ts';

export interface InvoiceableJobsClientOptions {
  readonly baseUrl?: string | URL;
}

type InvoiceableJobsAuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options?: InvoiceableJobsClientOptions,
];

type InvoiceableJobsOperationInvocation = readonly [requestCorrelation: string, options?: InvoiceableJobsClientOptions];

const invoiceableJobsClient = (
  credential: Redacted.Redacted,
  requestCorrelation: string,
  options: InvoiceableJobsClientOptions,
) =>
  makeGovernedEffectBffClient(
    {
      api: InvoiceableJobsApi,
      credential,
      defaultApiPrefix: '/billing-documents-api',
      requestCorrelation,
    },
    options,
  );

export const executeInvoiceableJobsWithAuthorization = (
  payload: InvoiceableJobsRequest,
  ...[credential, requestCorrelation, options = {}]: InvoiceableJobsAuthorizedInvocation
) =>
  invoiceableJobsClient(Redacted.make(credential), requestCorrelation, options).pipe(
    Effect.flatMap((client) => client.invoiceableJobs.execute({ headers: {}, params: {}, payload, query: {} })),
  );

export const executeInvoiceableJobs = (
  payload: InvoiceableJobsRequest,
  ...[requestCorrelation, options = {}]: InvoiceableJobsOperationInvocation
) =>
  operationGateway.invoke((credential) =>
    executeInvoiceableJobsWithAuthorization(payload, credential, requestCorrelation, options),
  );
