// @generated by OntOS Codesmith module-api v1
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted } from 'effect';
import { InvoiceDetailApi } from '../../shared/apis/invoice-detail.ts';
import type { InvoiceDetailRequest } from '../../shared/apis/invoice-detail.ts';
import { operationGateway } from './action-gateway.ts';

export interface InvoiceDetailClientOptions {
  readonly baseUrl?: string | URL;
}

type InvoiceDetailAuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options?: InvoiceDetailClientOptions,
];

type InvoiceDetailOperationInvocation = readonly [requestCorrelation: string, options?: InvoiceDetailClientOptions];

const invoiceDetailClient = (
  credential: Redacted.Redacted,
  requestCorrelation: string,
  options: InvoiceDetailClientOptions,
) =>
  makeGovernedEffectBffClient(
    {
      api: InvoiceDetailApi,
      credential,
      defaultApiPrefix: '/billing-documents-api',
      requestCorrelation,
    },
    options,
  );

export const executeInvoiceDetailWithAuthorization = (
  payload: InvoiceDetailRequest,
  ...[credential, requestCorrelation, options = {}]: InvoiceDetailAuthorizedInvocation
) =>
  invoiceDetailClient(Redacted.make(credential), requestCorrelation, options).pipe(
    Effect.flatMap((client) => client.invoiceDetail.execute({ headers: {}, params: {}, payload, query: {} })),
  );

export const executeInvoiceDetail = (
  payload: InvoiceDetailRequest,
  ...[requestCorrelation, options = {}]: InvoiceDetailOperationInvocation
) =>
  operationGateway.invoke((credential) =>
    executeInvoiceDetailWithAuthorization(payload, credential, requestCorrelation, options),
  );
