// @generated by OntOS Codesmith Action v1
// @ontos-action-owner sales.inquiries
// @ontos-action-slug update-offer-draft
import {
  UpdateOfferDraftPayloadSchema,
  UpdateOfferDraftResultSchema,
} from '../../shared/actions/update-offer-draft.ts';
import { DateTime, Effect, Option } from 'effect';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import type { ActionHandlerContext } from '@app/core-runtime';
import { InquiryErrorSchema, InquiryRejected, calculateServiceOffer } from '../../shared/resources/sales-inquiry.ts';
import { inquiryPersistenceService } from '../services/inquiry-persistence.service.ts';
import type { InquiryPersistence } from '../services/inquiry-persistence.service.ts';

export const handleUpdateOfferDraft = Effect.fn('UpdateOfferDraft.handle')(function* handle(
  payload: typeof UpdateOfferDraftPayloadSchema.Type,
  context: ActionHandlerContext<Record<never, never>, InquiryPersistence>,
) {
  const current = yield* context.services.get(payload.id);
  yield* context.recordDataAccess({
    accessKind: 'read',
    queryHash: `sales-inquiry-invariant:${current.ref.resourceId}:${current.revision}`,
    resultCount: 1,
    servingModuleKey: current.ref.moduleId,
    targetModuleKey: current.ref.moduleId,
    targetResourceId: current.ref.resourceId,
    targetResourceType: current.ref.resourceType,
  });
  if (current.stage !== 'PRICING') {
    return yield* new InquiryRejected({ code: 'commercial_frozen', reason: 'Offer is editable only during pricing' });
  }
  return yield* context.services.save(
    {
      ...current,
      offer: Option.some(calculateServiceOffer(payload.offer)),
      revision: current.revision + 1,
      updatedAt: yield* DateTime.now,
    },
    payload.expectedRevision,
  );
});

export const updateOfferDraftAction = defineAction(
  {
    accessEvidencePolicy: { captureMode: 'metadata_only', policyKey: 'sales.inquiries.update-offer-draft.access.v1' },
    actionKey: 'sales.inquiries.update-offer-draft',
    auditProfile: 'standard',
    domainErrorSchema: InquiryErrorSchema,
    domainEvents: {},
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'tenant_membership_default' },
      entrypointKey: 'sales.inquiries.update-offer-draft',
      moduleKey: 'sales.inquiries',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'required',
    owningModuleKey: 'sales.inquiries',
    payloadSchema: UpdateOfferDraftPayloadSchema,
    policies: [],
    resultSchema: UpdateOfferDraftResultSchema,
    schemaVersion: '1',
  },
  handleUpdateOfferDraft,
  inquiryPersistenceService,
);
// <generated-outbox-message-exports>
// </generated-outbox-message-exports>

export {
  UpdateOfferDraftPayloadSchema,
  UpdateOfferDraftResultSchema,
} from '../../shared/actions/update-offer-draft.ts';
