// @generated by OntOS Codesmith Action v1
// @ontos-action-owner job.expenses
// @ontos-action-slug update-job-expense
import { DateTime, Effect, Schema } from 'effect';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import type { ActionHandlerContext } from '@app/core-runtime';
import {
  UpdateJobExpensePayloadSchema,
  UpdateJobExpenseResultSchema,
} from '../../shared/actions/update-job-expense.ts';
import { JobExpenseRejected, JobExpenseUnavailable } from '../../shared/resources/job-expense-failure.ts';
import { JobExpenseIdSchema } from '../../shared/resources/job-expense.ts';
import { expenseServices } from '../services/expense-services.service.ts';
import type { ExpenseServices } from '../services/expense-services.service.ts';
import { recordExpenseRead, recordJobRead, validateIncurredOn } from './job-expense-action-support.ts';

const UpdateExpenseAuditSchema = Schema.Struct({
  expenseId: JobExpenseIdSchema,
  operation: Schema.Literal('update'),
  previousRevision: Schema.Int,
  reason: Schema.String,
  resultRevision: Schema.Int,
});
const handleUpdateJobExpense = Effect.fn('UpdateJobExpense.handle')(function* handleUpdateJobExpense(
  payload: typeof UpdateJobExpensePayloadSchema.Type,
  context: ActionHandlerContext<Record<never, never>, ExpenseServices>,
) {
  const current = yield* context.services.get(payload.id);
  yield* recordExpenseRead(context, current);
  const job = yield* context.services.jobs.get(current.serviceJobRef);
  yield* recordJobRead(context, job);
  if (current.status !== 'RECORDED') {
    return yield* new JobExpenseRejected({ code: 'invalid_state', reason: 'Voided expense cannot be edited' });
  }
  if (current.revision !== payload.expectedRevision) {
    return yield* new JobExpenseRejected({ code: 'revision_conflict', reason: 'Reload the expense' });
  }
  const now = yield* DateTime.now;
  yield* validateIncurredOn(payload.incurredOn, now);
  const updated = yield* context.services.saveRecorded(
    {
      ...current,
      amountCzk: payload.amountCzk,
      category: payload.category,
      description: payload.description.trim(),
      incurredOn: payload.incurredOn,
      revision: current.revision + 1,
      updatedAt: now,
    },
    payload.expectedRevision,
  );
  yield* context.recordAuditEvidence({
    expenseId: updated.ref.resourceId,
    operation: 'update',
    previousRevision: current.revision,
    reason: payload.changeReason.trim(),
    resultRevision: updated.revision,
  });
  return updated;
});

export const updateJobExpenseAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'job.expenses.update-job-expense.access.v1',
    },
    actionKey: 'job.expenses.update-job-expense',
    auditEvidenceSchema: UpdateExpenseAuditSchema,
    auditProfile: 'standard',
    domainErrorSchema: Schema.Union([JobExpenseRejected, JobExpenseUnavailable]),
    domainEvents: {},
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'tenant_membership_default' },
      entrypointKey: 'job.expenses.update-job-expense',
      moduleKey: 'job.expenses',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'required',
    owningModuleKey: 'job.expenses',
    payloadSchema: UpdateJobExpensePayloadSchema,
    policies: [],
    resultSchema: UpdateJobExpenseResultSchema,
    schemaVersion: '1',
  },
  handleUpdateJobExpense,
  expenseServices,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>

export {
  UpdateJobExpensePayloadSchema,
  UpdateJobExpenseResultSchema,
} from '../../shared/actions/update-job-expense.ts';
