// @generated by OntOS Codesmith module-api v1
import { makeGovernedReadHttpHandler } from '@app/core-runtime/http/governed-read';
import { makeGovernedReadProblems } from '@app/shared-contracts/server/effect-bff-runtime';
import { HttpApiBuilder } from '@modern-js/bff-effect/effect-edge';
import { jobExpensesApi } from '../shared/api.ts';
import {
  JobEconomicsAuthenticationProblemSchema,
  JobEconomicsForbiddenProblemSchema,
  JobEconomicsInternalProblemSchema,
  JobEconomicsInvalidProblemSchema,
  JobEconomicsNotFoundProblemSchema,
  JobEconomicsPolicyConflictProblemSchema,
  JobEconomicsPolicyProblemSchema,
  JobEconomicsUnavailableProblemSchema,
} from '../shared/apis/job-economics.ts';
import { jobEconomicsRead } from '../src/api/job-economics.read.ts';
import { authenticateOperationPrincipal } from './auth/action-principal.ts';

const problems = makeGovernedReadProblems({
  authentication: JobEconomicsAuthenticationProblemSchema,
  forbidden: JobEconomicsForbiddenProblemSchema,
  internal: JobEconomicsInternalProblemSchema,
  invalid: JobEconomicsInvalidProblemSchema,
  notFound: JobEconomicsNotFoundProblemSchema,
  policyConflict: JobEconomicsPolicyConflictProblemSchema,
  policyIneligible: JobEconomicsPolicyProblemSchema,
  unavailable: JobEconomicsUnavailableProblemSchema,
});

export const jobEconomicsReadApiLive = HttpApiBuilder.group(jobExpensesApi, 'jobEconomics', (handlers) =>
  handlers.handle(
    'execute',
    makeGovernedReadHttpHandler({
      authenticatePrincipal: authenticateOperationPrincipal,
      problems,
      registration: jobEconomicsRead,
    }),
  ),
);
