// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner job.expenses
// @ontos-action-http-slug record-job-expense
// oxlint-disable sonarjs/function-name -- Effect Match.tags requires owner-declared tag keys; remove-when: sonarjs accepts discriminant-map properties.
import type { ActionCoreError } from '@app/core-runtime';
import { Effect, HttpApiMiddleware } from '@modern-js/bff-effect/effect-edge';
import { Match, Schema } from 'effect';
import {
  RecordJobExpenseActionAlreadyCommittedProblemSchema,
  RecordJobExpenseActionAuthenticationProblemSchema,
  RecordJobExpenseActionCommitIndeterminateProblemSchema,
  RecordJobExpenseActionConflictProblemSchema,
  RecordJobExpenseActionForbiddenProblemSchema,
  RecordJobExpenseActionIneligibleProblemSchema,
  RecordJobExpenseActionInternalProblemSchema,
  RecordJobExpenseActionInvalidProblemSchema,
  RecordJobExpenseActionNotFoundProblemSchema,
  RecordJobExpenseActionPreconditionProblemSchema,
  RecordJobExpenseActionSchemaErrorMiddleware,
  RecordJobExpenseActionUnavailableProblemSchema,
} from '../shared/apis/record-job-expense-action.ts';
import type { RecordJobExpenseActionProblem } from '../shared/apis/record-job-expense-action.ts';
import { recordJobExpenseAction } from '../src/actions/record-job-expense.action.ts';

type DomainError = typeof recordJobExpenseAction.descriptor.domainErrorSchema.Type;
type ProblemOf<Tag extends RecordJobExpenseActionProblem['_tag']> = Extract<
  RecordJobExpenseActionProblem,
  { readonly _tag: Tag }
>;
type DomainProblemIdentity =
  | { readonly code: 'revision_conflict'; readonly kind: 'conflict' }
  | { readonly code: 'scope_mismatch'; readonly kind: 'forbidden' }
  | { readonly code: 'invalid_expense' | 'invalid_state'; readonly kind: 'ineligible' }
  | { readonly code: 'job_not_found' | 'not_found'; readonly kind: 'notFound' }
  | { readonly code: 'job_expenses_unavailable'; readonly kind: 'unavailable' };

const problemStatus = {
  authentication: 401,
  conflict: 409,
  forbidden: 403,
  ineligible: 422,
  internal: 500,
  invalid: 400,
  notFound: 404,
  precondition: 428,
  rateLimited: 429,
  timeout: 504,
  unavailable: 503,
} as const;

const jobExpenseRejectedProblemByCode = {
  invalid_expense: { code: 'invalid_expense', kind: 'ineligible' },
  invalid_state: { code: 'invalid_state', kind: 'ineligible' },
  job_not_found: { code: 'job_not_found', kind: 'notFound' },
  not_found: { code: 'not_found', kind: 'notFound' },
  revision_conflict: { code: 'revision_conflict', kind: 'conflict' },
  scope_mismatch: { code: 'scope_mismatch', kind: 'forbidden' },
} as const satisfies Record<
  Extract<DomainError, { readonly _tag: 'JobExpenseRejected' }>['code'],
  DomainProblemIdentity
>;

export const recordJobExpenseActionProblem = {
  authentication: (): ProblemOf<'RecordJobExpenseActionAuthenticationProblem'> =>
    RecordJobExpenseActionAuthenticationProblemSchema.make({
      detail: 'A valid audience-scoped Bearer assertion is required.',
      status: problemStatus.authentication,
      title: 'Authentication required',
      type: 'https://ontos.dev/problems/operation-authentication-required',
    }),
  conflict: (
    code: ProblemOf<'RecordJobExpenseActionConflictProblem'>['code'],
  ): ProblemOf<'RecordJobExpenseActionConflictProblem'> =>
    RecordJobExpenseActionConflictProblemSchema.make({
      code,
      detail: 'The Action conflicts with current state.',
      status: problemStatus.conflict,
      title: 'Action conflict',
      type: 'https://ontos.dev/problems/action-conflict',
    }),
  forbidden: (
    code: ProblemOf<'RecordJobExpenseActionForbiddenProblem'>['code'],
  ): ProblemOf<'RecordJobExpenseActionForbiddenProblem'> =>
    RecordJobExpenseActionForbiddenProblemSchema.make({
      code,
      detail: 'The principal is not permitted to perform this Action.',
      status: problemStatus.forbidden,
      title: 'Action forbidden',
      type: 'https://ontos.dev/problems/action-forbidden',
    }),
  ineligible: (
    code: ProblemOf<'RecordJobExpenseActionIneligibleProblem'>['code'],
  ): ProblemOf<'RecordJobExpenseActionIneligibleProblem'> =>
    RecordJobExpenseActionIneligibleProblemSchema.make({
      code,
      detail: 'The request is not eligible for this Action.',
      status: problemStatus.ineligible,
      title: 'Action ineligible',
      type: 'https://ontos.dev/problems/action-ineligible',
    }),
  internal: (): ProblemOf<'RecordJobExpenseActionInternalProblem'> =>
    RecordJobExpenseActionInternalProblemSchema.make({
      detail: 'The Action could not be completed.',
      status: problemStatus.internal,
      title: 'Action failed',
      type: 'https://ontos.dev/problems/action-failed',
    }),
  invalid: (): ProblemOf<'RecordJobExpenseActionInvalidProblem'> =>
    RecordJobExpenseActionInvalidProblemSchema.make({
      detail: 'The record-job-expense Action request is invalid.',
      status: problemStatus.invalid,
      title: 'Invalid Action request',
      type: 'https://ontos.dev/problems/action-invalid',
    }),
  notFound: (
    code: ProblemOf<'RecordJobExpenseActionNotFoundProblem'>['code'],
  ): ProblemOf<'RecordJobExpenseActionNotFoundProblem'> =>
    RecordJobExpenseActionNotFoundProblemSchema.make({
      code,
      detail: 'The requested resource was not found.',
      status: problemStatus.notFound,
      title: 'Resource not found',
      type: 'https://ontos.dev/problems/action-resource-not-found',
    }),
  precondition: (): ProblemOf<'RecordJobExpenseActionPreconditionProblem'> =>
    RecordJobExpenseActionPreconditionProblemSchema.make({
      detail: 'An Idempotency-Key header is required.',
      status: problemStatus.precondition,
      title: 'Idempotency key required',
      type: 'https://ontos.dev/problems/idempotency-key-required',
    }),
  unavailable: (
    code: ProblemOf<'RecordJobExpenseActionUnavailableProblem'>['code'],
  ): ProblemOf<'RecordJobExpenseActionUnavailableProblem'> =>
    RecordJobExpenseActionUnavailableProblemSchema.make({
      code,
      detail: 'The Action capability is temporarily unavailable.',
      retryable: true,
      status: problemStatus.unavailable,
      title: 'Action unavailable',
      type: 'https://ontos.dev/problems/action-unavailable',
    }),
} as const;

const mapDomainIdentity = (identity: DomainProblemIdentity): RecordJobExpenseActionProblem =>
  Match.value(identity).pipe(
    Match.when({ kind: 'conflict' as const }, (matched) => recordJobExpenseActionProblem.conflict(matched.code)),
    Match.when({ kind: 'forbidden' as const }, (matched) => recordJobExpenseActionProblem.forbidden(matched.code)),
    Match.when({ kind: 'ineligible' as const }, (matched) => recordJobExpenseActionProblem.ineligible(matched.code)),
    Match.when({ kind: 'notFound' as const }, (matched) => recordJobExpenseActionProblem.notFound(matched.code)),
    Match.when({ kind: 'unavailable' as const }, (matched) => recordJobExpenseActionProblem.unavailable(matched.code)),
    Match.exhaustive,
  );

const mapDomainProblem = (error: DomainError): RecordJobExpenseActionProblem =>
  Match.value(error).pipe(
    Match.tags({
      JobExpenseRejected: (failure) => mapDomainIdentity(jobExpenseRejectedProblemByCode[failure.code]),
      JobExpenseUnavailable: () => recordJobExpenseActionProblem.unavailable('job_expenses_unavailable'),
    }),
    Match.exhaustive,
  );

const mapCoreProblem = (error: ActionCoreError): RecordJobExpenseActionProblem =>
  Match.value(error).pipe(
    Match.tags({
      ActionAlreadyCommitted: (failure) =>
        RecordJobExpenseActionAlreadyCommittedProblemSchema.make({
          code: failure.code,
          detail: 'This Action is already committed. Refresh governed reads.',
          invocationId: failure.invocationId,
          resolution: 'REFRESH_GOVERNED_READS',
          retryCommand: false,
          status: problemStatus.conflict,
          title: 'Action already committed',
          type: 'https://ontos.dev/problems/action-already-committed',
        }),
      ActionCollectorError: recordJobExpenseActionProblem.internal,
      ActionCommitIndeterminate: (failure) =>
        RecordJobExpenseActionCommitIndeterminateProblemSchema.make({
          detail: 'The Action commit is uncertain. Resolve this invocation before another attempt.',
          invocationId: failure.invocationId,
          resolution: 'RESOLVE_COMMIT',
          retryCommand: false,
          status: problemStatus.unavailable,
          title: 'Action commit uncertain',
          type: 'https://ontos.dev/problems/action-commit-indeterminate',
        }),
      ActionHandlerExecutionError: recordJobExpenseActionProblem.internal,
      ActionIdempotencyKeyRequired: recordJobExpenseActionProblem.precondition,
      ActionInvocationNotFound: (failure) => recordJobExpenseActionProblem.notFound(failure.code),
      ActionInvocationPersistenceError: (failure) => recordJobExpenseActionProblem.unavailable(failure.code),
      ActionInvocationStateError: (failure) => recordJobExpenseActionProblem.conflict(failure.code),
      ActionPayloadValidationError: recordJobExpenseActionProblem.invalid,
      ActionPermissionCheckError: (failure) => recordJobExpenseActionProblem.unavailable(failure.code),
      ActionPermissionDenied: (failure) => recordJobExpenseActionProblem.forbidden(failure.code),
      ActionPolicyDenied: (failure) => recordJobExpenseActionProblem.ineligible(failure.code),
      ActionPolicyEvaluationError: (failure) => recordJobExpenseActionProblem.unavailable(failure.code),
      ActionRequestHashConflict: (failure) => recordJobExpenseActionProblem.conflict(failure.code),
      ActionResultValidationError: recordJobExpenseActionProblem.internal,
      ActionTransactionError: (failure) => recordJobExpenseActionProblem.unavailable(failure.code),
      ActionTrustedContextValidationError: recordJobExpenseActionProblem.authentication,
      ModuleStateCheckUnavailableError: (failure) => recordJobExpenseActionProblem.unavailable(failure.code),
      ModuleStateDeniedError: (failure) => recordJobExpenseActionProblem.forbidden(failure.code),
      OperationAuthenticationRequired: recordJobExpenseActionProblem.authentication,
      OperationContextDenied: (failure) => recordJobExpenseActionProblem.forbidden(failure.code),
      OperationContextInvalid: (failure) => recordJobExpenseActionProblem.forbidden(failure.code),
      OperationContextUnavailable: (failure) => recordJobExpenseActionProblem.unavailable(failure.code),
    }),
    Match.exhaustive,
  );

const isDomainError = Schema.is(recordJobExpenseAction.descriptor.domainErrorSchema);
export const mapRecordJobExpenseActionProblem = (
  error: ActionCoreError | DomainError,
): RecordJobExpenseActionProblem => (isDomainError(error) ? mapDomainProblem(error) : mapCoreProblem(error));

export const recordJobExpenseActionSchemaErrorLive = HttpApiMiddleware.layerSchemaErrorTransform(
  RecordJobExpenseActionSchemaErrorMiddleware,
  () => Effect.fail(recordJobExpenseActionProblem.invalid()),
);
