// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner job.expenses
// @ontos-action-http-slug update-job-expense
// oxlint-disable sonarjs/function-name -- Effect Match.tags requires owner-declared tag keys; remove-when: sonarjs accepts discriminant-map properties.
import type { ActionCoreError } from '@app/core-runtime';
import { Effect, HttpApiMiddleware } from '@modern-js/bff-effect/effect-edge';
import { Match, Schema } from 'effect';
import {
  UpdateJobExpenseActionAlreadyCommittedProblemSchema,
  UpdateJobExpenseActionAuthenticationProblemSchema,
  UpdateJobExpenseActionCommitIndeterminateProblemSchema,
  UpdateJobExpenseActionConflictProblemSchema,
  UpdateJobExpenseActionForbiddenProblemSchema,
  UpdateJobExpenseActionIneligibleProblemSchema,
  UpdateJobExpenseActionInternalProblemSchema,
  UpdateJobExpenseActionInvalidProblemSchema,
  UpdateJobExpenseActionNotFoundProblemSchema,
  UpdateJobExpenseActionPreconditionProblemSchema,
  UpdateJobExpenseActionSchemaErrorMiddleware,
  UpdateJobExpenseActionUnavailableProblemSchema,
} from '../shared/apis/update-job-expense-action.ts';
import type { UpdateJobExpenseActionProblem } from '../shared/apis/update-job-expense-action.ts';
import { updateJobExpenseAction } from '../src/actions/update-job-expense.action.ts';

type DomainError = typeof updateJobExpenseAction.descriptor.domainErrorSchema.Type;
type ProblemOf<Tag extends UpdateJobExpenseActionProblem['_tag']> = Extract<
  UpdateJobExpenseActionProblem,
  { readonly _tag: Tag }
>;
type DomainProblemIdentity =
  | { readonly code: 'revision_conflict'; readonly kind: 'conflict' }
  | { readonly code: 'scope_mismatch'; readonly kind: 'forbidden' }
  | { readonly code: 'invalid_expense' | 'invalid_state'; readonly kind: 'ineligible' }
  | { readonly code: 'job_not_found' | 'not_found'; readonly kind: 'notFound' }
  | { readonly code: 'job_expenses_unavailable'; readonly kind: 'unavailable' };

const problemStatus = {
  authentication: 401,
  conflict: 409,
  forbidden: 403,
  ineligible: 422,
  internal: 500,
  invalid: 400,
  notFound: 404,
  precondition: 428,
  rateLimited: 429,
  timeout: 504,
  unavailable: 503,
} as const;

const jobExpenseRejectedProblemByCode = {
  invalid_expense: { code: 'invalid_expense', kind: 'ineligible' },
  invalid_state: { code: 'invalid_state', kind: 'ineligible' },
  job_not_found: { code: 'job_not_found', kind: 'notFound' },
  not_found: { code: 'not_found', kind: 'notFound' },
  revision_conflict: { code: 'revision_conflict', kind: 'conflict' },
  scope_mismatch: { code: 'scope_mismatch', kind: 'forbidden' },
} as const satisfies Record<
  Extract<DomainError, { readonly _tag: 'JobExpenseRejected' }>['code'],
  DomainProblemIdentity
>;

export const updateJobExpenseActionProblem = {
  authentication: (): ProblemOf<'UpdateJobExpenseActionAuthenticationProblem'> =>
    UpdateJobExpenseActionAuthenticationProblemSchema.make({
      detail: 'A valid audience-scoped Bearer assertion is required.',
      status: problemStatus.authentication,
      title: 'Authentication required',
      type: 'https://ontos.dev/problems/operation-authentication-required',
    }),
  conflict: (
    code: ProblemOf<'UpdateJobExpenseActionConflictProblem'>['code'],
  ): ProblemOf<'UpdateJobExpenseActionConflictProblem'> =>
    UpdateJobExpenseActionConflictProblemSchema.make({
      code,
      detail: 'The Action conflicts with current state.',
      status: problemStatus.conflict,
      title: 'Action conflict',
      type: 'https://ontos.dev/problems/action-conflict',
    }),
  forbidden: (
    code: ProblemOf<'UpdateJobExpenseActionForbiddenProblem'>['code'],
  ): ProblemOf<'UpdateJobExpenseActionForbiddenProblem'> =>
    UpdateJobExpenseActionForbiddenProblemSchema.make({
      code,
      detail: 'The principal is not permitted to perform this Action.',
      status: problemStatus.forbidden,
      title: 'Action forbidden',
      type: 'https://ontos.dev/problems/action-forbidden',
    }),
  ineligible: (
    code: ProblemOf<'UpdateJobExpenseActionIneligibleProblem'>['code'],
  ): ProblemOf<'UpdateJobExpenseActionIneligibleProblem'> =>
    UpdateJobExpenseActionIneligibleProblemSchema.make({
      code,
      detail: 'The request is not eligible for this Action.',
      status: problemStatus.ineligible,
      title: 'Action ineligible',
      type: 'https://ontos.dev/problems/action-ineligible',
    }),
  internal: (): ProblemOf<'UpdateJobExpenseActionInternalProblem'> =>
    UpdateJobExpenseActionInternalProblemSchema.make({
      detail: 'The Action could not be completed.',
      status: problemStatus.internal,
      title: 'Action failed',
      type: 'https://ontos.dev/problems/action-failed',
    }),
  invalid: (): ProblemOf<'UpdateJobExpenseActionInvalidProblem'> =>
    UpdateJobExpenseActionInvalidProblemSchema.make({
      detail: 'The update-job-expense Action request is invalid.',
      status: problemStatus.invalid,
      title: 'Invalid Action request',
      type: 'https://ontos.dev/problems/action-invalid',
    }),
  notFound: (
    code: ProblemOf<'UpdateJobExpenseActionNotFoundProblem'>['code'],
  ): ProblemOf<'UpdateJobExpenseActionNotFoundProblem'> =>
    UpdateJobExpenseActionNotFoundProblemSchema.make({
      code,
      detail: 'The requested resource was not found.',
      status: problemStatus.notFound,
      title: 'Resource not found',
      type: 'https://ontos.dev/problems/action-resource-not-found',
    }),
  precondition: (): ProblemOf<'UpdateJobExpenseActionPreconditionProblem'> =>
    UpdateJobExpenseActionPreconditionProblemSchema.make({
      detail: 'An Idempotency-Key header is required.',
      status: problemStatus.precondition,
      title: 'Idempotency key required',
      type: 'https://ontos.dev/problems/idempotency-key-required',
    }),
  unavailable: (
    code: ProblemOf<'UpdateJobExpenseActionUnavailableProblem'>['code'],
  ): ProblemOf<'UpdateJobExpenseActionUnavailableProblem'> =>
    UpdateJobExpenseActionUnavailableProblemSchema.make({
      code,
      detail: 'The Action capability is temporarily unavailable.',
      retryable: true,
      status: problemStatus.unavailable,
      title: 'Action unavailable',
      type: 'https://ontos.dev/problems/action-unavailable',
    }),
} as const;

const mapDomainIdentity = (identity: DomainProblemIdentity): UpdateJobExpenseActionProblem =>
  Match.value(identity).pipe(
    Match.when({ kind: 'conflict' as const }, (matched) => updateJobExpenseActionProblem.conflict(matched.code)),
    Match.when({ kind: 'forbidden' as const }, (matched) => updateJobExpenseActionProblem.forbidden(matched.code)),
    Match.when({ kind: 'ineligible' as const }, (matched) => updateJobExpenseActionProblem.ineligible(matched.code)),
    Match.when({ kind: 'notFound' as const }, (matched) => updateJobExpenseActionProblem.notFound(matched.code)),
    Match.when({ kind: 'unavailable' as const }, (matched) => updateJobExpenseActionProblem.unavailable(matched.code)),
    Match.exhaustive,
  );

const mapDomainProblem = (error: DomainError): UpdateJobExpenseActionProblem =>
  Match.value(error).pipe(
    Match.tags({
      JobExpenseRejected: (failure) => mapDomainIdentity(jobExpenseRejectedProblemByCode[failure.code]),
      JobExpenseUnavailable: () => updateJobExpenseActionProblem.unavailable('job_expenses_unavailable'),
    }),
    Match.exhaustive,
  );

const mapCoreProblem = (error: ActionCoreError): UpdateJobExpenseActionProblem =>
  Match.value(error).pipe(
    Match.tags({
      ActionAlreadyCommitted: (failure) =>
        UpdateJobExpenseActionAlreadyCommittedProblemSchema.make({
          code: failure.code,
          detail: 'This Action is already committed. Refresh governed reads.',
          invocationId: failure.invocationId,
          resolution: 'REFRESH_GOVERNED_READS',
          retryCommand: false,
          status: problemStatus.conflict,
          title: 'Action already committed',
          type: 'https://ontos.dev/problems/action-already-committed',
        }),
      ActionCollectorError: updateJobExpenseActionProblem.internal,
      ActionCommitIndeterminate: (failure) =>
        UpdateJobExpenseActionCommitIndeterminateProblemSchema.make({
          detail: 'The Action commit is uncertain. Resolve this invocation before another attempt.',
          invocationId: failure.invocationId,
          resolution: 'RESOLVE_COMMIT',
          retryCommand: false,
          status: problemStatus.unavailable,
          title: 'Action commit uncertain',
          type: 'https://ontos.dev/problems/action-commit-indeterminate',
        }),
      ActionHandlerExecutionError: updateJobExpenseActionProblem.internal,
      ActionIdempotencyKeyRequired: updateJobExpenseActionProblem.precondition,
      ActionInvocationNotFound: (failure) => updateJobExpenseActionProblem.notFound(failure.code),
      ActionInvocationPersistenceError: (failure) => updateJobExpenseActionProblem.unavailable(failure.code),
      ActionInvocationStateError: (failure) => updateJobExpenseActionProblem.conflict(failure.code),
      ActionPayloadValidationError: updateJobExpenseActionProblem.invalid,
      ActionPermissionCheckError: (failure) => updateJobExpenseActionProblem.unavailable(failure.code),
      ActionPermissionDenied: (failure) => updateJobExpenseActionProblem.forbidden(failure.code),
      ActionPolicyDenied: (failure) => updateJobExpenseActionProblem.ineligible(failure.code),
      ActionPolicyEvaluationError: (failure) => updateJobExpenseActionProblem.unavailable(failure.code),
      ActionRequestHashConflict: (failure) => updateJobExpenseActionProblem.conflict(failure.code),
      ActionResultValidationError: updateJobExpenseActionProblem.internal,
      ActionTransactionError: (failure) => updateJobExpenseActionProblem.unavailable(failure.code),
      ActionTrustedContextValidationError: updateJobExpenseActionProblem.authentication,
      ModuleStateCheckUnavailableError: (failure) => updateJobExpenseActionProblem.unavailable(failure.code),
      ModuleStateDeniedError: (failure) => updateJobExpenseActionProblem.forbidden(failure.code),
      OperationAuthenticationRequired: updateJobExpenseActionProblem.authentication,
      OperationContextDenied: (failure) => updateJobExpenseActionProblem.forbidden(failure.code),
      OperationContextInvalid: (failure) => updateJobExpenseActionProblem.forbidden(failure.code),
      OperationContextUnavailable: (failure) => updateJobExpenseActionProblem.unavailable(failure.code),
    }),
    Match.exhaustive,
  );

const isDomainError = Schema.is(updateJobExpenseAction.descriptor.domainErrorSchema);
export const mapUpdateJobExpenseActionProblem = (
  error: ActionCoreError | DomainError,
): UpdateJobExpenseActionProblem => (isDomainError(error) ? mapDomainProblem(error) : mapCoreProblem(error));

export const updateJobExpenseActionSchemaErrorLive = HttpApiMiddleware.layerSchemaErrorTransform(
  UpdateJobExpenseActionSchemaErrorMiddleware,
  () => Effect.fail(updateJobExpenseActionProblem.invalid()),
);
