// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner job.expenses
// @ontos-action-http-slug void-job-expense
// oxlint-disable sonarjs/function-name -- Effect Match.tags requires owner-declared tag keys; remove-when: sonarjs accepts discriminant-map properties.
import type { ActionCoreError } from '@app/core-runtime';
import { Effect, HttpApiMiddleware } from '@modern-js/bff-effect/effect-edge';
import { Match, Schema } from 'effect';
import {
  VoidJobExpenseActionAlreadyCommittedProblemSchema,
  VoidJobExpenseActionAuthenticationProblemSchema,
  VoidJobExpenseActionCommitIndeterminateProblemSchema,
  VoidJobExpenseActionConflictProblemSchema,
  VoidJobExpenseActionForbiddenProblemSchema,
  VoidJobExpenseActionIneligibleProblemSchema,
  VoidJobExpenseActionInternalProblemSchema,
  VoidJobExpenseActionInvalidProblemSchema,
  VoidJobExpenseActionNotFoundProblemSchema,
  VoidJobExpenseActionPreconditionProblemSchema,
  VoidJobExpenseActionSchemaErrorMiddleware,
  VoidJobExpenseActionUnavailableProblemSchema,
} from '../shared/apis/void-job-expense-action.ts';
import type { VoidJobExpenseActionProblem } from '../shared/apis/void-job-expense-action.ts';
import { voidJobExpenseAction } from '../src/actions/void-job-expense.action.ts';

type DomainError = typeof voidJobExpenseAction.descriptor.domainErrorSchema.Type;
type ProblemOf<Tag extends VoidJobExpenseActionProblem['_tag']> = Extract<
  VoidJobExpenseActionProblem,
  { readonly _tag: Tag }
>;
type DomainProblemIdentity =
  | { readonly code: 'revision_conflict'; readonly kind: 'conflict' }
  | { readonly code: 'scope_mismatch'; readonly kind: 'forbidden' }
  | { readonly code: 'invalid_expense' | 'invalid_state'; readonly kind: 'ineligible' }
  | { readonly code: 'job_not_found' | 'not_found'; readonly kind: 'notFound' }
  | { readonly code: 'job_expenses_unavailable'; readonly kind: 'unavailable' };

const problemStatus = {
  authentication: 401,
  conflict: 409,
  forbidden: 403,
  ineligible: 422,
  internal: 500,
  invalid: 400,
  notFound: 404,
  precondition: 428,
  rateLimited: 429,
  timeout: 504,
  unavailable: 503,
} as const;

const jobExpenseRejectedProblemByCode = {
  invalid_expense: { code: 'invalid_expense', kind: 'ineligible' },
  invalid_state: { code: 'invalid_state', kind: 'ineligible' },
  job_not_found: { code: 'job_not_found', kind: 'notFound' },
  not_found: { code: 'not_found', kind: 'notFound' },
  revision_conflict: { code: 'revision_conflict', kind: 'conflict' },
  scope_mismatch: { code: 'scope_mismatch', kind: 'forbidden' },
} as const satisfies Record<
  Extract<DomainError, { readonly _tag: 'JobExpenseRejected' }>['code'],
  DomainProblemIdentity
>;

export const voidJobExpenseActionProblem = {
  authentication: (): ProblemOf<'VoidJobExpenseActionAuthenticationProblem'> =>
    VoidJobExpenseActionAuthenticationProblemSchema.make({
      detail: 'A valid audience-scoped Bearer assertion is required.',
      status: problemStatus.authentication,
      title: 'Authentication required',
      type: 'https://ontos.dev/problems/operation-authentication-required',
    }),
  conflict: (
    code: ProblemOf<'VoidJobExpenseActionConflictProblem'>['code'],
  ): ProblemOf<'VoidJobExpenseActionConflictProblem'> =>
    VoidJobExpenseActionConflictProblemSchema.make({
      code,
      detail: 'The Action conflicts with current state.',
      status: problemStatus.conflict,
      title: 'Action conflict',
      type: 'https://ontos.dev/problems/action-conflict',
    }),
  forbidden: (
    code: ProblemOf<'VoidJobExpenseActionForbiddenProblem'>['code'],
  ): ProblemOf<'VoidJobExpenseActionForbiddenProblem'> =>
    VoidJobExpenseActionForbiddenProblemSchema.make({
      code,
      detail: 'The principal is not permitted to perform this Action.',
      status: problemStatus.forbidden,
      title: 'Action forbidden',
      type: 'https://ontos.dev/problems/action-forbidden',
    }),
  ineligible: (
    code: ProblemOf<'VoidJobExpenseActionIneligibleProblem'>['code'],
  ): ProblemOf<'VoidJobExpenseActionIneligibleProblem'> =>
    VoidJobExpenseActionIneligibleProblemSchema.make({
      code,
      detail: 'The request is not eligible for this Action.',
      status: problemStatus.ineligible,
      title: 'Action ineligible',
      type: 'https://ontos.dev/problems/action-ineligible',
    }),
  internal: (): ProblemOf<'VoidJobExpenseActionInternalProblem'> =>
    VoidJobExpenseActionInternalProblemSchema.make({
      detail: 'The Action could not be completed.',
      status: problemStatus.internal,
      title: 'Action failed',
      type: 'https://ontos.dev/problems/action-failed',
    }),
  invalid: (): ProblemOf<'VoidJobExpenseActionInvalidProblem'> =>
    VoidJobExpenseActionInvalidProblemSchema.make({
      detail: 'The void-job-expense Action request is invalid.',
      status: problemStatus.invalid,
      title: 'Invalid Action request',
      type: 'https://ontos.dev/problems/action-invalid',
    }),
  notFound: (
    code: ProblemOf<'VoidJobExpenseActionNotFoundProblem'>['code'],
  ): ProblemOf<'VoidJobExpenseActionNotFoundProblem'> =>
    VoidJobExpenseActionNotFoundProblemSchema.make({
      code,
      detail: 'The requested resource was not found.',
      status: problemStatus.notFound,
      title: 'Resource not found',
      type: 'https://ontos.dev/problems/action-resource-not-found',
    }),
  precondition: (): ProblemOf<'VoidJobExpenseActionPreconditionProblem'> =>
    VoidJobExpenseActionPreconditionProblemSchema.make({
      detail: 'An Idempotency-Key header is required.',
      status: problemStatus.precondition,
      title: 'Idempotency key required',
      type: 'https://ontos.dev/problems/idempotency-key-required',
    }),
  unavailable: (
    code: ProblemOf<'VoidJobExpenseActionUnavailableProblem'>['code'],
  ): ProblemOf<'VoidJobExpenseActionUnavailableProblem'> =>
    VoidJobExpenseActionUnavailableProblemSchema.make({
      code,
      detail: 'The Action capability is temporarily unavailable.',
      retryable: true,
      status: problemStatus.unavailable,
      title: 'Action unavailable',
      type: 'https://ontos.dev/problems/action-unavailable',
    }),
} as const;

const mapDomainIdentity = (identity: DomainProblemIdentity): VoidJobExpenseActionProblem =>
  Match.value(identity).pipe(
    Match.when({ kind: 'conflict' as const }, (matched) => voidJobExpenseActionProblem.conflict(matched.code)),
    Match.when({ kind: 'forbidden' as const }, (matched) => voidJobExpenseActionProblem.forbidden(matched.code)),
    Match.when({ kind: 'ineligible' as const }, (matched) => voidJobExpenseActionProblem.ineligible(matched.code)),
    Match.when({ kind: 'notFound' as const }, (matched) => voidJobExpenseActionProblem.notFound(matched.code)),
    Match.when({ kind: 'unavailable' as const }, (matched) => voidJobExpenseActionProblem.unavailable(matched.code)),
    Match.exhaustive,
  );

const mapDomainProblem = (error: DomainError): VoidJobExpenseActionProblem =>
  Match.value(error).pipe(
    Match.tags({
      JobExpenseRejected: (failure) => mapDomainIdentity(jobExpenseRejectedProblemByCode[failure.code]),
      JobExpenseUnavailable: () => voidJobExpenseActionProblem.unavailable('job_expenses_unavailable'),
    }),
    Match.exhaustive,
  );

const mapCoreProblem = (error: ActionCoreError): VoidJobExpenseActionProblem =>
  Match.value(error).pipe(
    Match.tags({
      ActionAlreadyCommitted: (failure) =>
        VoidJobExpenseActionAlreadyCommittedProblemSchema.make({
          code: failure.code,
          detail: 'This Action is already committed. Refresh governed reads.',
          invocationId: failure.invocationId,
          resolution: 'REFRESH_GOVERNED_READS',
          retryCommand: false,
          status: problemStatus.conflict,
          title: 'Action already committed',
          type: 'https://ontos.dev/problems/action-already-committed',
        }),
      ActionCollectorError: voidJobExpenseActionProblem.internal,
      ActionCommitIndeterminate: (failure) =>
        VoidJobExpenseActionCommitIndeterminateProblemSchema.make({
          detail: 'The Action commit is uncertain. Resolve this invocation before another attempt.',
          invocationId: failure.invocationId,
          resolution: 'RESOLVE_COMMIT',
          retryCommand: false,
          status: problemStatus.unavailable,
          title: 'Action commit uncertain',
          type: 'https://ontos.dev/problems/action-commit-indeterminate',
        }),
      ActionHandlerExecutionError: voidJobExpenseActionProblem.internal,
      ActionIdempotencyKeyRequired: voidJobExpenseActionProblem.precondition,
      ActionInvocationNotFound: (failure) => voidJobExpenseActionProblem.notFound(failure.code),
      ActionInvocationPersistenceError: (failure) => voidJobExpenseActionProblem.unavailable(failure.code),
      ActionInvocationStateError: (failure) => voidJobExpenseActionProblem.conflict(failure.code),
      ActionPayloadValidationError: voidJobExpenseActionProblem.invalid,
      ActionPermissionCheckError: (failure) => voidJobExpenseActionProblem.unavailable(failure.code),
      ActionPermissionDenied: (failure) => voidJobExpenseActionProblem.forbidden(failure.code),
      ActionPolicyDenied: (failure) => voidJobExpenseActionProblem.ineligible(failure.code),
      ActionPolicyEvaluationError: (failure) => voidJobExpenseActionProblem.unavailable(failure.code),
      ActionRequestHashConflict: (failure) => voidJobExpenseActionProblem.conflict(failure.code),
      ActionResultValidationError: voidJobExpenseActionProblem.internal,
      ActionTransactionError: (failure) => voidJobExpenseActionProblem.unavailable(failure.code),
      ActionTrustedContextValidationError: voidJobExpenseActionProblem.authentication,
      ModuleStateCheckUnavailableError: (failure) => voidJobExpenseActionProblem.unavailable(failure.code),
      ModuleStateDeniedError: (failure) => voidJobExpenseActionProblem.forbidden(failure.code),
      OperationAuthenticationRequired: voidJobExpenseActionProblem.authentication,
      OperationContextDenied: (failure) => voidJobExpenseActionProblem.forbidden(failure.code),
      OperationContextInvalid: (failure) => voidJobExpenseActionProblem.forbidden(failure.code),
      OperationContextUnavailable: (failure) => voidJobExpenseActionProblem.unavailable(failure.code),
    }),
    Match.exhaustive,
  );

const isDomainError = Schema.is(voidJobExpenseAction.descriptor.domainErrorSchema);
export const mapVoidJobExpenseActionProblem = (error: ActionCoreError | DomainError): VoidJobExpenseActionProblem =>
  isDomainError(error) ? mapDomainProblem(error) : mapCoreProblem(error);

export const voidJobExpenseActionSchemaErrorLive = HttpApiMiddleware.layerSchemaErrorTransform(
  VoidJobExpenseActionSchemaErrorMiddleware,
  () => Effect.fail(voidJobExpenseActionProblem.invalid()),
);
