// @generated by OntOS Codesmith module-api v1
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { Schema } from 'effect';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';
import { ServiceJobSchema } from '@app/service-jobs/resources/service-job';

export const JobSelectionRequestSchema = Schema.Struct({
  cursor: Schema.optionalKey(Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(120))),
  pageSize: Schema.optionalKey(Schema.Int.check(Schema.isGreaterThanOrEqualTo(1), Schema.isLessThanOrEqualTo(100))),
});
export type JobSelectionRequest = typeof JobSelectionRequestSchema.Type;
export const JobSelectionResponseSchema = Schema.Struct({
  items: Schema.Array(ServiceJobSchema),
  nextCursor: Schema.toEncoded(Schema.OptionFromNullOr(Schema.String)),
});

export const JobSelectionAuthenticationProblemSchema = makeProblemDetailsSchema(
  'JobSelectionAuthenticationProblem',
  401,
);
export const JobSelectionInvalidProblemSchema = makeProblemDetailsSchema('JobSelectionInvalidProblem', 400);
export const JobSelectionUnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  'JobSelectionUnavailableProblem',
  503,
);
export const JobSelectionForbiddenProblemSchema = makeProblemDetailsSchema('JobSelectionForbiddenProblem', 403);
export const JobSelectionNotFoundProblemSchema = makeProblemDetailsSchema('JobSelectionNotFoundProblem', 404);
export const JobSelectionPolicyProblemSchema = makeProblemDetailsSchema('JobSelectionPolicyProblem', 422);
export const JobSelectionPolicyConflictProblemSchema = makeProblemDetailsSchema(
  'JobSelectionPolicyConflictProblem',
  409,
);
export const JobSelectionInternalProblemSchema = makeProblemDetailsSchema('JobSelectionInternalProblem', 500);

export const JobSelectionApi = HttpApi.make('JobSelectionApi').add(
  HttpApiGroup.make('jobSelection').add(
    HttpApiEndpoint.post('execute', '/reads/job-selection', {
      error: [
        JobSelectionInvalidProblemSchema,
        JobSelectionAuthenticationProblemSchema,
        JobSelectionForbiddenProblemSchema,
        JobSelectionNotFoundProblemSchema,
        JobSelectionPolicyConflictProblemSchema,
        JobSelectionPolicyProblemSchema,
        JobSelectionUnavailableProblemSchema,
        JobSelectionInternalProblemSchema,
      ],
      headers: {},
      params: {},
      payload: JobSelectionRequestSchema,
      query: {},
      success: JobSelectionResponseSchema,
    }),
  ),
);
