// @generated by OntOS Codesmith module-api v1
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { Schema } from 'effect';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';

export const CatalogSourceResolutionRequestSchema = Schema.Struct({});
export type CatalogSourceResolutionRequest = typeof CatalogSourceResolutionRequestSchema.Type;
export const CatalogSourceResolutionResponseSchema = Schema.Struct({ ok: Schema.Literal(true) });

export const CatalogSourceResolutionAuthenticationProblemSchema = makeProblemDetailsSchema(
  'CatalogSourceResolutionAuthenticationProblem',
  401,
);
export const CatalogSourceResolutionInvalidProblemSchema = makeProblemDetailsSchema(
  'CatalogSourceResolutionInvalidProblem',
  400,
);
export const CatalogSourceResolutionUnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  'CatalogSourceResolutionUnavailableProblem',
  503,
);
export const CatalogSourceResolutionForbiddenProblemSchema = makeProblemDetailsSchema(
  'CatalogSourceResolutionForbiddenProblem',
  403,
);
export const CatalogSourceResolutionNotFoundProblemSchema = makeProblemDetailsSchema(
  'CatalogSourceResolutionNotFoundProblem',
  404,
);
export const CatalogSourceResolutionPolicyProblemSchema = makeProblemDetailsSchema(
  'CatalogSourceResolutionPolicyProblem',
  422,
);
export const CatalogSourceResolutionPolicyConflictProblemSchema = makeProblemDetailsSchema(
  'CatalogSourceResolutionPolicyConflictProblem',
  409,
);
export const CatalogSourceResolutionInternalProblemSchema = makeProblemDetailsSchema(
  'CatalogSourceResolutionInternalProblem',
  500,
);

export const CatalogSourceResolutionApi = HttpApi.make('CatalogSourceResolutionApi').add(
  HttpApiGroup.make('catalogSourceResolution').add(
    HttpApiEndpoint.post('execute', '/reads/catalog-source-resolution', {
      error: [
        CatalogSourceResolutionInvalidProblemSchema,
        CatalogSourceResolutionAuthenticationProblemSchema,
        CatalogSourceResolutionForbiddenProblemSchema,
        CatalogSourceResolutionNotFoundProblemSchema,
        CatalogSourceResolutionPolicyConflictProblemSchema,
        CatalogSourceResolutionPolicyProblemSchema,
        CatalogSourceResolutionUnavailableProblemSchema,
        CatalogSourceResolutionInternalProblemSchema,
      ],
      headers: {},
      params: {},
      payload: CatalogSourceResolutionRequestSchema,
      query: {},
      success: CatalogSourceResolutionResponseSchema,
    }),
  ),
);
