// @generated by OntOS Codesmith module-api v1
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { Schema } from 'effect';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';
import { ManufacturerRelationRevisionSchema, ManufacturerSubjectSchema } from '../domain/manufacturer-relation.ts';

export const ManufacturerRelationCurrentRequestSchema = Schema.Struct({
  relationId: Schema.String.check(Schema.isUUID(), Schema.isTrimmed()).pipe(
    Schema.brand('CatalogManufacturerRelationId'),
  ),
  subject: ManufacturerSubjectSchema,
});
export type ManufacturerRelationCurrentRequest = typeof ManufacturerRelationCurrentRequestSchema.Type;
export const ManufacturerRelationCurrentResponseSchema = Schema.Struct({
  relation: ManufacturerRelationRevisionSchema,
});
export type ManufacturerRelationCurrentResponse = typeof ManufacturerRelationCurrentResponseSchema.Type;

export const ManufacturerRelationCurrentAuthenticationProblemSchema = makeProblemDetailsSchema(
  'ManufacturerRelationCurrentAuthenticationProblem',
  401,
);
export const ManufacturerRelationCurrentInvalidProblemSchema = makeProblemDetailsSchema(
  'ManufacturerRelationCurrentInvalidProblem',
  400,
);
export const ManufacturerRelationCurrentUnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  'ManufacturerRelationCurrentUnavailableProblem',
  503,
);
export const ManufacturerRelationCurrentForbiddenProblemSchema = makeProblemDetailsSchema(
  'ManufacturerRelationCurrentForbiddenProblem',
  403,
);
export const ManufacturerRelationCurrentNotFoundProblemSchema = makeProblemDetailsSchema(
  'ManufacturerRelationCurrentNotFoundProblem',
  404,
);
export const ManufacturerRelationCurrentPolicyProblemSchema = makeProblemDetailsSchema(
  'ManufacturerRelationCurrentPolicyProblem',
  422,
);
export const ManufacturerRelationCurrentPolicyConflictProblemSchema = makeProblemDetailsSchema(
  'ManufacturerRelationCurrentPolicyConflictProblem',
  409,
);
export const ManufacturerRelationCurrentInternalProblemSchema = makeProblemDetailsSchema(
  'ManufacturerRelationCurrentInternalProblem',
  500,
);

export const ManufacturerRelationCurrentApi = HttpApi.make('ManufacturerRelationCurrentApi').add(
  HttpApiGroup.make('manufacturerRelationCurrent').add(
    HttpApiEndpoint.post('execute', '/reads/manufacturer-relation-current', {
      error: [
        ManufacturerRelationCurrentInvalidProblemSchema,
        ManufacturerRelationCurrentAuthenticationProblemSchema,
        ManufacturerRelationCurrentForbiddenProblemSchema,
        ManufacturerRelationCurrentNotFoundProblemSchema,
        ManufacturerRelationCurrentPolicyConflictProblemSchema,
        ManufacturerRelationCurrentPolicyProblemSchema,
        ManufacturerRelationCurrentUnavailableProblemSchema,
        ManufacturerRelationCurrentInternalProblemSchema,
      ],
      headers: {},
      params: {},
      payload: ManufacturerRelationCurrentRequestSchema,
      query: {},
      success: ManufacturerRelationCurrentResponseSchema,
    }),
  ),
);
