// @generated by OntOS Codesmith module-api v1
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { Schema } from 'effect';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';
import { ProductRefSchema } from '../resources/product.ts';
import { CatalogRevisionResourceIdSchema } from '../domain/catalog-revision-reference.ts';

export const ProductSizeCurrentRequestSchema = Schema.Struct({ productRef: ProductRefSchema });
export type ProductSizeCurrentRequest = typeof ProductSizeCurrentRequestSchema.Type;
export const ProductSizeCurrentResponseSchema = Schema.Struct({
  productRef: ProductRefSchema,
  revision: Schema.Int.check(Schema.isGreaterThanOrEqualTo(0)),
  sizes: Schema.Array(
    Schema.Struct({
      position: Schema.Int.check(Schema.isGreaterThanOrEqualTo(0)),
      sizeId: CatalogRevisionResourceIdSchema,
    }),
  ),
});
export type ProductSizeCurrentResponse = typeof ProductSizeCurrentResponseSchema.Type;

export const ProductSizeCurrentAuthenticationProblemSchema = makeProblemDetailsSchema(
  'ProductSizeCurrentAuthenticationProblem',
  401,
);
export const ProductSizeCurrentInvalidProblemSchema = makeProblemDetailsSchema('ProductSizeCurrentInvalidProblem', 400);
export const ProductSizeCurrentUnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  'ProductSizeCurrentUnavailableProblem',
  503,
);
export const ProductSizeCurrentForbiddenProblemSchema = makeProblemDetailsSchema(
  'ProductSizeCurrentForbiddenProblem',
  403,
);
export const ProductSizeCurrentNotFoundProblemSchema = makeProblemDetailsSchema(
  'ProductSizeCurrentNotFoundProblem',
  404,
);
export const ProductSizeCurrentPolicyProblemSchema = makeProblemDetailsSchema('ProductSizeCurrentPolicyProblem', 422);
export const ProductSizeCurrentPolicyConflictProblemSchema = makeProblemDetailsSchema(
  'ProductSizeCurrentPolicyConflictProblem',
  409,
);
export const ProductSizeCurrentInternalProblemSchema = makeProblemDetailsSchema(
  'ProductSizeCurrentInternalProblem',
  500,
);

export const ProductSizeCurrentApi = HttpApi.make('ProductSizeCurrentApi').add(
  HttpApiGroup.make('productSizeCurrent').add(
    HttpApiEndpoint.post('execute', '/reads/product-size-current', {
      error: [
        ProductSizeCurrentInvalidProblemSchema,
        ProductSizeCurrentAuthenticationProblemSchema,
        ProductSizeCurrentForbiddenProblemSchema,
        ProductSizeCurrentNotFoundProblemSchema,
        ProductSizeCurrentPolicyConflictProblemSchema,
        ProductSizeCurrentPolicyProblemSchema,
        ProductSizeCurrentUnavailableProblemSchema,
        ProductSizeCurrentInternalProblemSchema,
      ],
      headers: {},
      params: {},
      payload: ProductSizeCurrentRequestSchema,
      query: {},
      success: ProductSizeCurrentResponseSchema,
    }),
  ),
);
