// @generated by @modern-js/ultramodern-create.
// Author route metadata in colocated src/routes/**/route.meta.ts files.
// This compatibility manifest is regenerated from route-owned metadata.

export const ultramodernRouteNamespace = 'service-jobs' as const;

const routeValue1 = 'service.jobs';
const routeValue2 = '/';
const routeValue3 = '/jobs';

export const ultramodernRouteMetadata = [
  {
    canonicalPath: routeValue2,
    descriptionKey: 'service-jobs.seo.description',
    entrypoint: {
      access: 'read',
      authorization: {
        kind: 'context_permission',
        permission: 'module.access',
      },
      entrypointKey: 'service.jobs.page.service-jobs-home',
      moduleKey: routeValue1,
      role: 'page',
      scope: 'tenant',
    },
    id: 'service-jobs-home',
    indexable: false,
    localisedPaths: {
      cs: routeValue2,
      en: routeValue2,
    },
    mfBoundaryId: 'verticalServiceJobs',
    moduleId: routeValue1,
    namespace: ultramodernRouteNamespace,
    ownerAppId: ultramodernRouteNamespace,
    public: false,
    publicSurface: 'private-app-screen',
    titleKey: 'service-jobs.title',
  },
  {
    canonicalPath: routeValue3,
    descriptionKey: 'service-jobs.pages.jobs.description',
    entrypoint: {
      access: 'read',
      authorization: {
        kind: 'context_permission',
        permission: 'module.access',
      },
      entrypointKey: 'service.jobs.page.jobs',
      moduleKey: routeValue1,
      role: 'page',
      scope: 'tenant',
    },
    id: 'service-jobs-jobs',
    indexable: false,
    localisedPaths: {
      cs: routeValue3,
      en: routeValue3,
    },
    mfBoundaryId: 'verticalServiceJobs',
    moduleId: routeValue1,
    namespace: ultramodernRouteNamespace,
    ownerAppId: ultramodernRouteNamespace,
    public: false,
    publicSurface: 'private-app-screen',
    titleKey: 'service-jobs.pages.jobs.title',
  },
] as const;

export const ultramodernLocalisedUrls = {
  '/jobs': {
    cs: routeValue3,
    en: routeValue3,
  },
} as const;
