// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner billing.documents
// @ontos-action-http-slug create-invoice-draft
// oxlint-disable sonarjs/function-name -- Effect Match.tags requires owner-declared tag keys; remove-when: sonarjs accepts discriminant-map properties.
import type { ActionCoreError } from '@app/core-runtime';
import { Effect, HttpApiMiddleware } from '@modern-js/bff-effect/effect-edge';
import { Match, Schema } from 'effect';
import {
  CreateInvoiceDraftActionAlreadyCommittedProblemSchema,
  CreateInvoiceDraftActionAuthenticationProblemSchema,
  CreateInvoiceDraftActionCommitIndeterminateProblemSchema,
  CreateInvoiceDraftActionConflictProblemSchema,
  CreateInvoiceDraftActionForbiddenProblemSchema,
  CreateInvoiceDraftActionIneligibleProblemSchema,
  CreateInvoiceDraftActionInternalProblemSchema,
  CreateInvoiceDraftActionInvalidProblemSchema,
  CreateInvoiceDraftActionNotFoundProblemSchema,
  CreateInvoiceDraftActionPreconditionProblemSchema,
  CreateInvoiceDraftActionSchemaErrorMiddleware,
  CreateInvoiceDraftActionUnavailableProblemSchema,
} from '../shared/apis/create-invoice-draft-action.ts';
import type { CreateInvoiceDraftActionProblem } from '../shared/apis/create-invoice-draft-action.ts';
import { createInvoiceDraftAction } from '../src/actions/create-invoice-draft.action.ts';

type DomainError = typeof createInvoiceDraftAction.descriptor.domainErrorSchema.Type;
type ProblemOf<Tag extends CreateInvoiceDraftActionProblem['_tag']> = Extract<
  CreateInvoiceDraftActionProblem,
  { readonly _tag: Tag }
>;
type DomainProblemIdentity =
  | { readonly code: 'invoice_already_exists' | 'revision_conflict'; readonly kind: 'conflict' }
  | { readonly code: 'scope_mismatch'; readonly kind: 'forbidden' }
  | {
      readonly code:
        | 'address_not_current'
        | 'due_date_out_of_range'
        | 'invoice_not_draft'
        | 'job_not_completed'
        | 'payment_term_required'
        | 'payment_term_unusable'
        | 'source_job_changed'
        | 'tax_data_required';
      readonly kind: 'ineligible';
    }
  | { readonly code: 'job_not_found' | 'missing_billing_address' | 'not_found'; readonly kind: 'notFound' }
  | { readonly code: 'billing_documents_unavailable'; readonly kind: 'unavailable' };

const problemStatus = {
  authentication: 401,
  conflict: 409,
  forbidden: 403,
  ineligible: 422,
  internal: 500,
  invalid: 400,
  notFound: 404,
  precondition: 428,
  rateLimited: 429,
  timeout: 504,
  unavailable: 503,
} as const;

const invoiceRejectedProblemByCode = {
  address_not_current: { code: 'address_not_current', kind: 'ineligible' },
  due_date_out_of_range: { code: 'due_date_out_of_range', kind: 'ineligible' },
  invoice_already_exists: { code: 'invoice_already_exists', kind: 'conflict' },
  invoice_not_draft: { code: 'invoice_not_draft', kind: 'ineligible' },
  job_not_completed: { code: 'job_not_completed', kind: 'ineligible' },
  job_not_found: { code: 'job_not_found', kind: 'notFound' },
  missing_billing_address: { code: 'missing_billing_address', kind: 'notFound' },
  not_found: { code: 'not_found', kind: 'notFound' },
  payment_term_required: { code: 'payment_term_required', kind: 'ineligible' },
  payment_term_unusable: { code: 'payment_term_unusable', kind: 'ineligible' },
  revision_conflict: { code: 'revision_conflict', kind: 'conflict' },
  scope_mismatch: { code: 'scope_mismatch', kind: 'forbidden' },
  source_job_changed: { code: 'source_job_changed', kind: 'ineligible' },
  tax_data_required: { code: 'tax_data_required', kind: 'ineligible' },
} as const satisfies Record<Extract<DomainError, { readonly _tag: 'InvoiceRejected' }>['code'], DomainProblemIdentity>;

export const createInvoiceDraftActionProblem = {
  authentication: (): ProblemOf<'CreateInvoiceDraftActionAuthenticationProblem'> =>
    CreateInvoiceDraftActionAuthenticationProblemSchema.make({
      detail: 'A valid audience-scoped Bearer assertion is required.',
      status: problemStatus.authentication,
      title: 'Authentication required',
      type: 'https://ontos.dev/problems/operation-authentication-required',
    }),
  conflict: (
    code: ProblemOf<'CreateInvoiceDraftActionConflictProblem'>['code'],
  ): ProblemOf<'CreateInvoiceDraftActionConflictProblem'> =>
    CreateInvoiceDraftActionConflictProblemSchema.make({
      code,
      detail: 'The Action conflicts with current state.',
      status: problemStatus.conflict,
      title: 'Action conflict',
      type: 'https://ontos.dev/problems/action-conflict',
    }),
  forbidden: (
    code: ProblemOf<'CreateInvoiceDraftActionForbiddenProblem'>['code'],
  ): ProblemOf<'CreateInvoiceDraftActionForbiddenProblem'> =>
    CreateInvoiceDraftActionForbiddenProblemSchema.make({
      code,
      detail: 'The principal is not permitted to perform this Action.',
      status: problemStatus.forbidden,
      title: 'Action forbidden',
      type: 'https://ontos.dev/problems/action-forbidden',
    }),
  ineligible: (
    code: ProblemOf<'CreateInvoiceDraftActionIneligibleProblem'>['code'],
  ): ProblemOf<'CreateInvoiceDraftActionIneligibleProblem'> =>
    CreateInvoiceDraftActionIneligibleProblemSchema.make({
      code,
      detail: 'The request is not eligible for this Action.',
      status: problemStatus.ineligible,
      title: 'Action ineligible',
      type: 'https://ontos.dev/problems/action-ineligible',
    }),
  internal: (): ProblemOf<'CreateInvoiceDraftActionInternalProblem'> =>
    CreateInvoiceDraftActionInternalProblemSchema.make({
      detail: 'The Action could not be completed.',
      status: problemStatus.internal,
      title: 'Action failed',
      type: 'https://ontos.dev/problems/action-failed',
    }),
  invalid: (): ProblemOf<'CreateInvoiceDraftActionInvalidProblem'> =>
    CreateInvoiceDraftActionInvalidProblemSchema.make({
      detail: 'The create-invoice-draft Action request is invalid.',
      status: problemStatus.invalid,
      title: 'Invalid Action request',
      type: 'https://ontos.dev/problems/action-invalid',
    }),
  notFound: (
    code: ProblemOf<'CreateInvoiceDraftActionNotFoundProblem'>['code'],
  ): ProblemOf<'CreateInvoiceDraftActionNotFoundProblem'> =>
    CreateInvoiceDraftActionNotFoundProblemSchema.make({
      code,
      detail: 'The requested resource was not found.',
      status: problemStatus.notFound,
      title: 'Resource not found',
      type: 'https://ontos.dev/problems/action-resource-not-found',
    }),
  precondition: (): ProblemOf<'CreateInvoiceDraftActionPreconditionProblem'> =>
    CreateInvoiceDraftActionPreconditionProblemSchema.make({
      detail: 'An Idempotency-Key header is required.',
      status: problemStatus.precondition,
      title: 'Idempotency key required',
      type: 'https://ontos.dev/problems/idempotency-key-required',
    }),
  unavailable: (
    code: ProblemOf<'CreateInvoiceDraftActionUnavailableProblem'>['code'],
  ): ProblemOf<'CreateInvoiceDraftActionUnavailableProblem'> =>
    CreateInvoiceDraftActionUnavailableProblemSchema.make({
      code,
      detail: 'The Action capability is temporarily unavailable.',
      retryable: true,
      status: problemStatus.unavailable,
      title: 'Action unavailable',
      type: 'https://ontos.dev/problems/action-unavailable',
    }),
} as const;

const mapDomainIdentity = (identity: DomainProblemIdentity): CreateInvoiceDraftActionProblem =>
  Match.value(identity).pipe(
    Match.when({ kind: 'conflict' as const }, (matched) => createInvoiceDraftActionProblem.conflict(matched.code)),
    Match.when({ kind: 'forbidden' as const }, (matched) => createInvoiceDraftActionProblem.forbidden(matched.code)),
    Match.when({ kind: 'ineligible' as const }, (matched) => createInvoiceDraftActionProblem.ineligible(matched.code)),
    Match.when({ kind: 'notFound' as const }, (matched) => createInvoiceDraftActionProblem.notFound(matched.code)),
    Match.when({ kind: 'unavailable' as const }, (matched) =>
      createInvoiceDraftActionProblem.unavailable(matched.code),
    ),
    Match.exhaustive,
  );

const mapDomainProblem = (error: DomainError): CreateInvoiceDraftActionProblem =>
  Match.value(error).pipe(
    Match.tags({
      InvoiceRejected: (failure) => mapDomainIdentity(invoiceRejectedProblemByCode[failure.code]),
      InvoiceUnavailable: () => createInvoiceDraftActionProblem.unavailable('billing_documents_unavailable'),
    }),
    Match.exhaustive,
  );

const mapCoreProblem = (error: ActionCoreError): CreateInvoiceDraftActionProblem =>
  Match.value(error).pipe(
    Match.tags({
      ActionAlreadyCommitted: (failure) =>
        CreateInvoiceDraftActionAlreadyCommittedProblemSchema.make({
          code: failure.code,
          detail: 'This Action is already committed. Refresh governed reads.',
          invocationId: failure.invocationId,
          resolution: 'REFRESH_GOVERNED_READS',
          retryCommand: false,
          status: problemStatus.conflict,
          title: 'Action already committed',
          type: 'https://ontos.dev/problems/action-already-committed',
        }),
      ActionCollectorError: createInvoiceDraftActionProblem.internal,
      ActionCommitIndeterminate: (failure) =>
        CreateInvoiceDraftActionCommitIndeterminateProblemSchema.make({
          detail: 'The Action commit is uncertain. Resolve this invocation before another attempt.',
          invocationId: failure.invocationId,
          resolution: 'RESOLVE_COMMIT',
          retryCommand: false,
          status: problemStatus.unavailable,
          title: 'Action commit uncertain',
          type: 'https://ontos.dev/problems/action-commit-indeterminate',
        }),
      ActionHandlerExecutionError: createInvoiceDraftActionProblem.internal,
      ActionIdempotencyKeyRequired: createInvoiceDraftActionProblem.precondition,
      ActionInvocationNotFound: (failure) => createInvoiceDraftActionProblem.notFound(failure.code),
      ActionInvocationPersistenceError: (failure) => createInvoiceDraftActionProblem.unavailable(failure.code),
      ActionInvocationStateError: (failure) => createInvoiceDraftActionProblem.conflict(failure.code),
      ActionPayloadValidationError: createInvoiceDraftActionProblem.invalid,
      ActionPermissionCheckError: (failure) => createInvoiceDraftActionProblem.unavailable(failure.code),
      ActionPermissionDenied: (failure) => createInvoiceDraftActionProblem.forbidden(failure.code),
      ActionPolicyDenied: (failure) => createInvoiceDraftActionProblem.ineligible(failure.code),
      ActionPolicyEvaluationError: (failure) => createInvoiceDraftActionProblem.unavailable(failure.code),
      ActionRequestHashConflict: (failure) => createInvoiceDraftActionProblem.conflict(failure.code),
      ActionResultValidationError: createInvoiceDraftActionProblem.internal,
      ActionTransactionError: (failure) => createInvoiceDraftActionProblem.unavailable(failure.code),
      ActionTrustedContextValidationError: createInvoiceDraftActionProblem.authentication,
      ModuleStateCheckUnavailableError: (failure) => createInvoiceDraftActionProblem.unavailable(failure.code),
      ModuleStateDeniedError: (failure) => createInvoiceDraftActionProblem.forbidden(failure.code),
      OperationAuthenticationRequired: createInvoiceDraftActionProblem.authentication,
      OperationContextDenied: (failure) => createInvoiceDraftActionProblem.forbidden(failure.code),
      OperationContextInvalid: (failure) => createInvoiceDraftActionProblem.forbidden(failure.code),
      OperationContextUnavailable: (failure) => createInvoiceDraftActionProblem.unavailable(failure.code),
    }),
    Match.exhaustive,
  );

const isDomainError = Schema.is(createInvoiceDraftAction.descriptor.domainErrorSchema);
export const mapCreateInvoiceDraftActionProblem = (
  error: ActionCoreError | DomainError,
): CreateInvoiceDraftActionProblem => (isDomainError(error) ? mapDomainProblem(error) : mapCoreProblem(error));

export const createInvoiceDraftActionSchemaErrorLive = HttpApiMiddleware.layerSchemaErrorTransform(
  CreateInvoiceDraftActionSchemaErrorMiddleware,
  () => Effect.fail(createInvoiceDraftActionProblem.invalid()),
);
