// @generated by OntOS Codesmith module-api v1
// Headless server shim consumed by the deployment runtime when this owner is registered.
export { currentStorefrontApplicationRead as currentStorefrontApplicationReadServer } from '../src/api/current-storefront-application.read.ts';
