// @generated by OntOS Codesmith module-api v1
import { defineRead, defineTenantModuleEntrypoint, ReadHandlerNotFound, ReadPolicyDenied } from '@app/core-runtime';
import type { ReadHandlerContext } from '@app/core-runtime';
import { Effect, Option } from 'effect';
import { inquiryPersistenceService } from '../services/inquiry-persistence.service.ts';
import type { InquiryPersistence } from '../services/inquiry-persistence.service.ts';
import { mapInquiryReadFailure } from './inquiry-read-errors.ts';
import {
  AcceptedOfferHandoffRequestSchema,
  AcceptedOfferHandoffResponseSchema,
} from '../../shared/apis/accepted-offer-handoff.ts';

const acceptedOfferHandoffEntrypoint = defineTenantModuleEntrypoint({
  access: 'read',
  authorization: { kind: 'context_permission', permission: 'module.access' },
  entrypointKey: 'sales.inquiries.api.accepted-offer-handoff',
  moduleKey: 'sales.inquiries',
  role: 'api',
});

export const acceptedOfferHandoffRead = defineRead(
  {
    accessKind: 'detail',
    entrypoint: acceptedOfferHandoffEntrypoint,
    evidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'sales.inquiries.api.accepted-offer-handoff.evidence.v1',
    },
    inputSchema: AcceptedOfferHandoffRequestSchema,
    legalEntityScope: 'required',
    owningModuleKey: 'sales.inquiries',
    permissionTarget: 'module',
    policies: [],
    readKey: 'sales.inquiries.api.accepted-offer-handoff',
    resultSchema: AcceptedOfferHandoffResponseSchema,
    schemaVersion: '1',
  },
  Effect.fn('AcceptedOfferHandoff.read')(function* read(
    input: typeof AcceptedOfferHandoffRequestSchema.Type,
    context: ReadHandlerContext<InquiryPersistence>,
  ) {
    if (input.sourceRef.tenantId !== context.scope.tenantId) {
      return yield* new ReadHandlerNotFound({ code: 'read_handler_not_found', reason: 'Source was not found' });
    }
    const source = yield* context.services.get(input.sourceRef.resourceId).pipe(Effect.mapError(mapInquiryReadFailure));
    if (
      source.stage !== 'ACCEPTED' ||
      Option.isNone(source.acceptedAt) ||
      Option.isNone(source.acceptance) ||
      Option.isNone(source.offer)
    ) {
      return yield* new ReadPolicyDenied({
        code: 'read_policy_denied',
        httpStatus: 422,
        policyReasonCode: 'offer_not_accepted',
        reason: 'The source offer has not been accepted',
      });
    }
    return {
      evidence: { resultCount: 1 },
      result: {
        acceptance: source.acceptance.value,
        acceptedAt: source.acceptedAt.value,
        commercialSummary: {
          currency: source.offer.value.currency,
          priceBasis: source.offer.value.priceBasis,
          total: source.offer.value.total,
        },
        legalEntityId: source.legalEntityId,
        partyRef: source.partyRef,
        serviceLocation: source.location,
        serviceScope: {
          description: source.description,
          elevator: source.elevator,
          estimatedVolumeM3: source.estimatedVolumeM3,
          floor: source.floor,
          objectType: source.objectType,
          specialWaste: source.specialWaste,
        },
        sourceRef: source.ref,
        sourceRevision: source.revision,
      },
    };
  }),
  inquiryPersistenceService,
  () => ({ kind: 'module', moduleId: acceptedOfferHandoffEntrypoint.moduleKey }),
);
