// @generated by OntOS Codesmith module-api v1
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted } from 'effect';
import { InquiryDetailApi } from '../../shared/apis/inquiry-detail.ts';
import type { InquiryDetailRequest } from '../../shared/apis/inquiry-detail.ts';
import { operationGateway } from './action-gateway.ts';

export interface InquiryDetailClientOptions {
  readonly baseUrl?: string | URL;
}

type InquiryDetailAuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options?: InquiryDetailClientOptions,
];

type InquiryDetailOperationInvocation = readonly [requestCorrelation: string, options?: InquiryDetailClientOptions];

const inquiryDetailClient = (
  credential: Redacted.Redacted,
  requestCorrelation: string,
  options: InquiryDetailClientOptions,
) =>
  makeGovernedEffectBffClient(
    {
      api: InquiryDetailApi,
      credential,
      defaultApiPrefix: '/sales-inquiries-api',
      requestCorrelation,
    },
    options,
  );

export const executeInquiryDetailWithAuthorization = (
  payload: InquiryDetailRequest,
  ...[credential, requestCorrelation, options = {}]: InquiryDetailAuthorizedInvocation
) =>
  inquiryDetailClient(Redacted.make(credential), requestCorrelation, options).pipe(
    Effect.flatMap((client) => client.inquiryDetail.execute({ headers: {}, params: {}, payload, query: {} })),
  );

export const executeInquiryDetail = (
  payload: InquiryDetailRequest,
  ...[requestCorrelation, options = {}]: InquiryDetailOperationInvocation
) =>
  operationGateway.invoke((credential) =>
    executeInquiryDetailWithAuthorization(payload, credential, requestCorrelation, options),
  );
