import { mapInquiryReadFailure } from './inquiry-read-errors.ts';
// @generated by OntOS Codesmith module-api v1
import { defineRead, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { Effect } from 'effect';
import type { ReadHandlerContext } from '@app/core-runtime';
import { inquiryPersistenceService } from '../services/inquiry-persistence.service.ts';
import type { InquiryPersistence } from '../services/inquiry-persistence.service.ts';
import { InquiryDetailRequestSchema, InquiryDetailResponseSchema } from '../../shared/apis/inquiry-detail.ts';

const inquiryDetailEntrypoint = defineTenantModuleEntrypoint({
  access: 'read',
  authorization: { kind: 'context_permission', permission: 'module.access' },
  entrypointKey: 'sales.inquiries.api.inquiry-detail',
  moduleKey: 'sales.inquiries',
  role: 'api',
});

export const inquiryDetailRead = defineRead(
  {
    accessKind: 'detail',
    entrypoint: inquiryDetailEntrypoint,
    evidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'sales.inquiries.api.inquiry-detail.evidence.v1',
    },
    inputSchema: InquiryDetailRequestSchema,
    legalEntityScope: 'required',
    owningModuleKey: 'sales.inquiries',
    permissionTarget: 'module',
    policies: [],
    readKey: 'sales.inquiries.api.inquiry-detail',
    resultSchema: InquiryDetailResponseSchema,
    schemaVersion: '1',
  },
  (input: typeof InquiryDetailRequestSchema.Type, context: ReadHandlerContext<InquiryPersistence>) =>
    context.services.get(input.id).pipe(
      Effect.map((value) => ({ evidence: { resultCount: 1 }, result: value })),
      Effect.mapError(mapInquiryReadFailure),
    ),
  inquiryPersistenceService,
  () => ({ kind: 'module', moduleId: inquiryDetailEntrypoint.moduleKey }),
);
