// @generated by OntOS Codesmith module-api v1
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted } from 'effect';
import { PartySelectionApi } from '../../shared/apis/party-selection.ts';
import type { PartySelectionRequest } from '../../shared/apis/party-selection.ts';
import { operationGateway } from './action-gateway.ts';

export interface PartySelectionClientOptions {
  readonly baseUrl?: string | URL;
}

type PartySelectionAuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options?: PartySelectionClientOptions,
];

type PartySelectionOperationInvocation = readonly [requestCorrelation: string, options?: PartySelectionClientOptions];

const partySelectionClient = (
  credential: Redacted.Redacted,
  requestCorrelation: string,
  options: PartySelectionClientOptions,
) =>
  makeGovernedEffectBffClient(
    {
      api: PartySelectionApi,
      credential,
      defaultApiPrefix: '/sales-inquiries-api',
      requestCorrelation,
    },
    options,
  );

export const executePartySelectionWithAuthorization = (
  payload: PartySelectionRequest,
  ...[credential, requestCorrelation, options = {}]: PartySelectionAuthorizedInvocation
) =>
  partySelectionClient(Redacted.make(credential), requestCorrelation, options).pipe(
    Effect.flatMap((client) => client.partySelection.execute({ headers: {}, params: {}, payload, query: {} })),
  );

export const executePartySelection = (
  payload: PartySelectionRequest,
  ...[requestCorrelation, options = {}]: PartySelectionOperationInvocation
) =>
  operationGateway.invoke((credential) =>
    executePartySelectionWithAuthorization(payload, credential, requestCorrelation, options),
  );
