// @generated by OntOS Codesmith module-api v1
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted } from 'effect';
import { PartyDisplayApi } from '../../shared/apis/party-display.ts';
import type { PartyDisplayRequest } from '../../shared/apis/party-display.ts';
import { operationGateway } from './action-gateway.ts';

export interface PartyDisplayClientOptions {
  readonly baseUrl?: string | URL;
}

type PartyDisplayAuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options?: PartyDisplayClientOptions,
];

type PartyDisplayOperationInvocation = readonly [requestCorrelation: string, options?: PartyDisplayClientOptions];

const partyDisplayClient = (
  credential: Redacted.Redacted,
  requestCorrelation: string,
  options: PartyDisplayClientOptions,
) =>
  makeGovernedEffectBffClient(
    {
      api: PartyDisplayApi,
      credential,
      defaultApiPrefix: '/sales-inquiries-api',
      requestCorrelation,
    },
    options,
  );

export const executePartyDisplayWithAuthorization = (
  payload: PartyDisplayRequest,
  ...[credential, requestCorrelation, options = {}]: PartyDisplayAuthorizedInvocation
) =>
  partyDisplayClient(Redacted.make(credential), requestCorrelation, options).pipe(
    Effect.flatMap((client) => client.partyDisplay.execute({ headers: {}, params: {}, payload, query: {} })),
  );

export const executePartyDisplay = (
  payload: PartyDisplayRequest,
  ...[requestCorrelation, options = {}]: PartyDisplayOperationInvocation
) =>
  operationGateway.invoke((credential) =>
    executePartyDisplayWithAuthorization(payload, credential, requestCorrelation, options),
  );
