// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner sales.inquiries
// @ontos-action-http-slug transition-inquiry
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted, Schema } from 'effect';
import {
  TransitionInquiryActionApi,
  TransitionInquiryPayloadSchema,
} from '../../shared/apis/transition-inquiry-action.ts';
import type { TransitionInquiryPayload } from '../../shared/actions/transition-inquiry.ts';
import { operationGateway } from './action-gateway.ts';

const traceIdOption = 'traceId' as const;

export interface TransitionInquiryActionClientOptions {
  readonly baseUrl?: string | URL;
  readonly gateway?: Parameters<typeof operationGateway.invoke>[1];
  readonly idempotencyKey: string;
  readonly [traceIdOption]?: string;
}

type AuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options: TransitionInquiryActionClientOptions,
];
type OperationInvocation = readonly [requestCorrelation: string, options: TransitionInquiryActionClientOptions];

interface MakeClientOptions {
  readonly credential: Redacted.Redacted;
  readonly options: TransitionInquiryActionClientOptions;
  readonly requestCorrelation: string;
}

const makeClient = ({ credential, options, requestCorrelation }: MakeClientOptions) =>
  makeGovernedEffectBffClient(
    { api: TransitionInquiryActionApi, credential, defaultApiPrefix: '/sales-inquiries-api', requestCorrelation },
    options,
  );

export const executeTransitionInquiryWithAuthorization = (
  payload: TransitionInquiryPayload,
  ...[credential, requestCorrelation, options]: AuthorizedInvocation
) =>
  Schema.encodeUnknownEffect(TransitionInquiryPayloadSchema)(payload).pipe(
    Effect.flatMap((encoded) =>
      makeClient({ credential: Redacted.make(credential), options, requestCorrelation }).pipe(
        Effect.flatMap((client) =>
          client.transitionInquiryAction.execute({
            headers: { 'idempotency-key': options.idempotencyKey },
            payload: encoded,
          }),
        ),
      ),
    ),
  );

export const executeTransitionInquiry = (
  payload: TransitionInquiryPayload,
  ...[requestCorrelation, options]: OperationInvocation
) =>
  operationGateway.invoke(
    (credential) => executeTransitionInquiryWithAuthorization(payload, credential, requestCorrelation, options),
    options.gateway,
  );
