// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner service.jobs
// @ontos-action-http-slug complete-service-job
// oxlint-disable sonarjs/function-name -- Effect Match.tags requires owner-declared tag keys; remove-when: sonarjs accepts discriminant-map properties.
import type { ActionCoreError } from '@app/core-runtime';
import { Effect, HttpApiMiddleware } from '@modern-js/bff-effect/effect-edge';
import { Match, Schema } from 'effect';
import {
  CompleteServiceJobActionAlreadyCommittedProblemSchema,
  CompleteServiceJobActionAuthenticationProblemSchema,
  CompleteServiceJobActionCommitIndeterminateProblemSchema,
  CompleteServiceJobActionConflictProblemSchema,
  CompleteServiceJobActionForbiddenProblemSchema,
  CompleteServiceJobActionIneligibleProblemSchema,
  CompleteServiceJobActionInternalProblemSchema,
  CompleteServiceJobActionInvalidProblemSchema,
  CompleteServiceJobActionNotFoundProblemSchema,
  CompleteServiceJobActionPreconditionProblemSchema,
  CompleteServiceJobActionSchemaErrorMiddleware,
  CompleteServiceJobActionUnavailableProblemSchema,
} from '../shared/apis/complete-service-job-action.ts';
import type { CompleteServiceJobActionProblem } from '../shared/apis/complete-service-job-action.ts';
import { completeServiceJobAction } from '../src/actions/complete-service-job.action.ts';

type DomainError = typeof completeServiceJobAction.descriptor.domainErrorSchema.Type;
type ProblemOf<Tag extends CompleteServiceJobActionProblem['_tag']> = Extract<
  CompleteServiceJobActionProblem,
  { readonly _tag: Tag }
>;
type DomainProblemIdentity =
  | { readonly code: 'revision_conflict'; readonly kind: 'conflict' }
  | { readonly code: 'invalid_transition' | 'source_invalid'; readonly kind: 'ineligible' }
  | { readonly code: 'not_found'; readonly kind: 'notFound' }
  | {
      readonly code:
        | 'authentication'
        | 'conflict'
        | 'forbidden'
        | 'ineligible'
        | 'internal'
        | 'invalid'
        | 'not_found'
        | 'job_unavailable';
      readonly kind: 'unavailable';
    };

const problemStatus = {
  authentication: 401,
  conflict: 409,
  forbidden: 403,
  ineligible: 422,
  internal: 500,
  invalid: 400,
  notFound: 404,
  precondition: 428,
  rateLimited: 429,
  timeout: 504,
  unavailable: 503,
} as const;

const jobRejectedProblemByCode = {
  invalid_transition: { code: 'invalid_transition', kind: 'ineligible' },
  not_found: { code: 'not_found', kind: 'notFound' },
  revision_conflict: { code: 'revision_conflict', kind: 'conflict' },
  source_invalid: { code: 'source_invalid', kind: 'ineligible' },
} as const satisfies Record<Extract<DomainError, { readonly _tag: 'JobRejected' }>['code'], DomainProblemIdentity>;

export const completeServiceJobActionProblem = {
  authentication: (): ProblemOf<'CompleteServiceJobActionAuthenticationProblem'> =>
    CompleteServiceJobActionAuthenticationProblemSchema.make({
      detail: 'A valid audience-scoped Bearer assertion is required.',
      status: problemStatus.authentication,
      title: 'Authentication required',
      type: 'https://ontos.dev/problems/operation-authentication-required',
    }),
  conflict: (
    code: ProblemOf<'CompleteServiceJobActionConflictProblem'>['code'],
  ): ProblemOf<'CompleteServiceJobActionConflictProblem'> =>
    CompleteServiceJobActionConflictProblemSchema.make({
      code,
      detail: 'The Action conflicts with current state.',
      status: problemStatus.conflict,
      title: 'Action conflict',
      type: 'https://ontos.dev/problems/action-conflict',
    }),
  forbidden: (
    code: ProblemOf<'CompleteServiceJobActionForbiddenProblem'>['code'],
  ): ProblemOf<'CompleteServiceJobActionForbiddenProblem'> =>
    CompleteServiceJobActionForbiddenProblemSchema.make({
      code,
      detail: 'The principal is not permitted to perform this Action.',
      status: problemStatus.forbidden,
      title: 'Action forbidden',
      type: 'https://ontos.dev/problems/action-forbidden',
    }),
  ineligible: (
    code: ProblemOf<'CompleteServiceJobActionIneligibleProblem'>['code'],
  ): ProblemOf<'CompleteServiceJobActionIneligibleProblem'> =>
    CompleteServiceJobActionIneligibleProblemSchema.make({
      code,
      detail: 'The request is not eligible for this Action.',
      status: problemStatus.ineligible,
      title: 'Action ineligible',
      type: 'https://ontos.dev/problems/action-ineligible',
    }),
  internal: (): ProblemOf<'CompleteServiceJobActionInternalProblem'> =>
    CompleteServiceJobActionInternalProblemSchema.make({
      detail: 'The Action could not be completed.',
      status: problemStatus.internal,
      title: 'Action failed',
      type: 'https://ontos.dev/problems/action-failed',
    }),
  invalid: (): ProblemOf<'CompleteServiceJobActionInvalidProblem'> =>
    CompleteServiceJobActionInvalidProblemSchema.make({
      detail: 'The complete-service-job Action request is invalid.',
      status: problemStatus.invalid,
      title: 'Invalid Action request',
      type: 'https://ontos.dev/problems/action-invalid',
    }),
  notFound: (
    code: ProblemOf<'CompleteServiceJobActionNotFoundProblem'>['code'],
  ): ProblemOf<'CompleteServiceJobActionNotFoundProblem'> =>
    CompleteServiceJobActionNotFoundProblemSchema.make({
      code,
      detail: 'The requested resource was not found.',
      status: problemStatus.notFound,
      title: 'Resource not found',
      type: 'https://ontos.dev/problems/action-resource-not-found',
    }),
  precondition: (): ProblemOf<'CompleteServiceJobActionPreconditionProblem'> =>
    CompleteServiceJobActionPreconditionProblemSchema.make({
      detail: 'An Idempotency-Key header is required.',
      status: problemStatus.precondition,
      title: 'Idempotency key required',
      type: 'https://ontos.dev/problems/idempotency-key-required',
    }),
  unavailable: (
    code: ProblemOf<'CompleteServiceJobActionUnavailableProblem'>['code'],
  ): ProblemOf<'CompleteServiceJobActionUnavailableProblem'> =>
    CompleteServiceJobActionUnavailableProblemSchema.make({
      code,
      detail: 'The Action capability is temporarily unavailable.',
      retryable: true,
      status: problemStatus.unavailable,
      title: 'Action unavailable',
      type: 'https://ontos.dev/problems/action-unavailable',
    }),
} as const;

const mapDomainIdentity = (identity: DomainProblemIdentity): CompleteServiceJobActionProblem =>
  Match.value(identity).pipe(
    Match.when({ kind: 'conflict' as const }, (matched) => completeServiceJobActionProblem.conflict(matched.code)),
    Match.when({ kind: 'ineligible' as const }, (matched) => completeServiceJobActionProblem.ineligible(matched.code)),
    Match.when({ kind: 'notFound' as const }, (matched) => completeServiceJobActionProblem.notFound(matched.code)),
    Match.when({ kind: 'unavailable' as const }, (matched) =>
      completeServiceJobActionProblem.unavailable(matched.code),
    ),
    Match.exhaustive,
  );

const mapDomainProblem = (error: DomainError): CompleteServiceJobActionProblem =>
  Match.value(error).pipe(
    Match.tags({
      JobDependencyFailure: (failure) =>
        Match.value(failure.code).pipe(
          Match.when('authentication', completeServiceJobActionProblem.authentication),
          Match.when('forbidden', () => completeServiceJobActionProblem.forbidden('operation_context_denied')),
          Match.when('not_found', () => completeServiceJobActionProblem.notFound('not_found')),
          Match.when('invalid', completeServiceJobActionProblem.invalid),
          Match.when('conflict', () => completeServiceJobActionProblem.conflict('revision_conflict')),
          Match.when('ineligible', () => completeServiceJobActionProblem.ineligible('source_invalid')),
          Match.when('internal', completeServiceJobActionProblem.internal),
          Match.exhaustive,
        ),
      JobRejected: (failure) => mapDomainIdentity(jobRejectedProblemByCode[failure.code]),
      JobUnavailable: () => completeServiceJobActionProblem.unavailable('job_unavailable'),
    }),
    Match.exhaustive,
  );

const mapCoreProblem = (error: ActionCoreError): CompleteServiceJobActionProblem =>
  Match.value(error).pipe(
    Match.tags({
      ActionAlreadyCommitted: (failure) =>
        CompleteServiceJobActionAlreadyCommittedProblemSchema.make({
          code: failure.code,
          detail: 'This Action is already committed. Refresh governed reads.',
          invocationId: failure.invocationId,
          resolution: 'REFRESH_GOVERNED_READS',
          retryCommand: false,
          status: problemStatus.conflict,
          title: 'Action already committed',
          type: 'https://ontos.dev/problems/action-already-committed',
        }),
      ActionCollectorError: completeServiceJobActionProblem.internal,
      ActionCommitIndeterminate: (failure) =>
        CompleteServiceJobActionCommitIndeterminateProblemSchema.make({
          detail: 'The Action commit is uncertain. Resolve this invocation before another attempt.',
          invocationId: failure.invocationId,
          resolution: 'RESOLVE_COMMIT',
          retryCommand: false,
          status: problemStatus.unavailable,
          title: 'Action commit uncertain',
          type: 'https://ontos.dev/problems/action-commit-indeterminate',
        }),
      ActionHandlerExecutionError: completeServiceJobActionProblem.internal,
      ActionIdempotencyKeyRequired: completeServiceJobActionProblem.precondition,
      ActionInvocationNotFound: (failure) => completeServiceJobActionProblem.notFound(failure.code),
      ActionInvocationPersistenceError: (failure) => completeServiceJobActionProblem.unavailable(failure.code),
      ActionInvocationStateError: (failure) => completeServiceJobActionProblem.conflict(failure.code),
      ActionPayloadValidationError: completeServiceJobActionProblem.invalid,
      ActionPermissionCheckError: (failure) => completeServiceJobActionProblem.unavailable(failure.code),
      ActionPermissionDenied: (failure) => completeServiceJobActionProblem.forbidden(failure.code),
      ActionPolicyDenied: (failure) => completeServiceJobActionProblem.ineligible(failure.code),
      ActionPolicyEvaluationError: (failure) => completeServiceJobActionProblem.unavailable(failure.code),
      ActionRequestHashConflict: (failure) => completeServiceJobActionProblem.conflict(failure.code),
      ActionResultValidationError: completeServiceJobActionProblem.internal,
      ActionTransactionError: (failure) => completeServiceJobActionProblem.unavailable(failure.code),
      ActionTrustedContextValidationError: completeServiceJobActionProblem.authentication,
      ModuleStateCheckUnavailableError: (failure) => completeServiceJobActionProblem.unavailable(failure.code),
      ModuleStateDeniedError: (failure) => completeServiceJobActionProblem.forbidden(failure.code),
      OperationAuthenticationRequired: completeServiceJobActionProblem.authentication,
      OperationContextDenied: (failure) => completeServiceJobActionProblem.forbidden(failure.code),
      OperationContextInvalid: (failure) => completeServiceJobActionProblem.forbidden(failure.code),
      OperationContextUnavailable: (failure) => completeServiceJobActionProblem.unavailable(failure.code),
    }),
    Match.exhaustive,
  );

const isDomainError = Schema.is(completeServiceJobAction.descriptor.domainErrorSchema);
export const mapCompleteServiceJobActionProblem = (
  error: ActionCoreError | DomainError,
): CompleteServiceJobActionProblem => (isDomainError(error) ? mapDomainProblem(error) : mapCoreProblem(error));

export const completeServiceJobActionSchemaErrorLive = HttpApiMiddleware.layerSchemaErrorTransform(
  CompleteServiceJobActionSchemaErrorMiddleware,
  () => Effect.fail(completeServiceJobActionProblem.invalid()),
);
