// @generated by OntOS Codesmith module-api v1
import { makeGovernedReadHttpHandler } from '@app/core-runtime/http/governed-read';
import { makeGovernedReadProblems } from '@app/shared-contracts/server/effect-bff-runtime';
import { HttpApiBuilder } from '@modern-js/bff-effect/effect-edge';
import { serviceJobsApi } from '../shared/api.ts';
import {
  JobListAuthenticationProblemSchema,
  JobListForbiddenProblemSchema,
  JobListInternalProblemSchema,
  JobListInvalidProblemSchema,
  JobListNotFoundProblemSchema,
  JobListPolicyConflictProblemSchema,
  JobListPolicyProblemSchema,
  JobListUnavailableProblemSchema,
} from '../shared/apis/job-list.ts';
import { jobListRead } from '../src/api/job-list.read.ts';
import { authenticateOperationPrincipal } from './auth/action-principal.ts';

const problems = makeGovernedReadProblems({
  authentication: JobListAuthenticationProblemSchema,
  forbidden: JobListForbiddenProblemSchema,
  internal: JobListInternalProblemSchema,
  invalid: JobListInvalidProblemSchema,
  notFound: JobListNotFoundProblemSchema,
  policyConflict: JobListPolicyConflictProblemSchema,
  policyIneligible: JobListPolicyProblemSchema,
  unavailable: JobListUnavailableProblemSchema,
});

export const jobListReadApiLive = HttpApiBuilder.group(serviceJobsApi, 'jobList', (handlers) =>
  handlers.handle(
    'execute',
    makeGovernedReadHttpHandler({
      authenticatePrincipal: authenticateOperationPrincipal,
      problems,
      registration: jobListRead,
    }),
  ),
);
