// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug activate-local-override
import type { ActionHandlerContext } from '@app/core-runtime';
import { ActionTransactionError, defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { DateTime, Effect, Schema } from 'effect';

import {
  ActivateLocalOverridePayloadSchema,
  CatalogLocalOverrideResultSchema as ActivateLocalOverrideResultSchema,
} from '../../shared/actions/catalog-source-resolution.ts';
import type { ActivateLocalOverridePayload } from '../../shared/actions/catalog-source-resolution.ts';
import type { CatalogLocalOverrideResult } from '../../shared/actions/catalog-source-resolution.ts';
import { OutboxPayloadSchema as SelectionSourceChangedEventSchema } from '../../shared/outbox/commerce-catalog-selection-source-changed-v1.ts';
import { makeCatalogLocalOverrideService } from '../persistence/catalog-local-override-service.ts';
import { captureCatalogActionResult } from '../persistence/catalog-action-result-snapshot.ts';
import { createActivateLocalOverrideCommerceCatalogSelectionSourceChangedV1OutboxMessage } from './activate-local-override-commerce-catalog-selection-source-changed-v1.outbox-message.ts';
import {
  CatalogSourceActionErrorSchema,
  CatalogSourceAuditEvidenceSchema,
  CatalogSourceRequestInvalid,
  catalogResolvedCurrentEventPorts,
  catalogSourceValuesEqual,
  makeCatalogSourceActionServices,
} from './catalog-source-action-support.ts';

export { ActivateLocalOverridePayloadSchema } from '../../shared/actions/catalog-source-resolution.ts';
export { CatalogLocalOverrideResultSchema as ActivateLocalOverrideResultSchema } from '../../shared/actions/catalog-source-resolution.ts';
export type { ActivateLocalOverridePayload } from '../../shared/actions/catalog-source-resolution.ts';

const domainEvents = { 'commerce.catalog.selection-source-changed.v1': SelectionSourceChangedEventSchema } as const;
const ACTION_KEY = 'commerce.catalog.activate-local-override' as const;
type Services = ReturnType<typeof makeCatalogSourceActionServices> & {
  readonly captureResult: (
    actionInvocationId: string,
    result: CatalogLocalOverrideResult,
  ) => Effect.Effect<void, ActionTransactionError>;
};

const handleActivateLocalOverride = Effect.fn('ActivateLocalOverrideAction.handle')(
  function* handleActivateLocalOverride(
    payload: ActivateLocalOverridePayload,
    context: ActionHandlerContext<typeof domainEvents, Services>,
  ) {
    if (payload.scope.tenantId !== context.scope.tenantId) {
      return yield* new CatalogSourceRequestInvalid({
        code: 'catalog_source_request_invalid',
        reason: 'The Local Override scope must belong to the trusted Tenant',
      });
    }
    const at = yield* DateTime.nowAsDate;
    const result = yield* makeCatalogLocalOverrideService<Schema.Json>({
      admission: context.services.admission,
      events: catalogResolvedCurrentEventPorts(
        context,
        createActivateLocalOverrideCommerceCatalogSelectionSourceChangedV1OutboxMessage,
      ),
      store: context.services.storeAt({
        actionInvocationId: context.actionInvocationId,
        at,
        principalId: context.scope.principalId,
      }),
      valuesEqual: catalogSourceValuesEqual,
    }).activate({ ...payload, at, principalId: context.scope.principalId });
    yield* context.recordAuditEvidence({ evidenceRefs: [payload.evidenceRef], reason: payload.reason });
    return result.status === 'APPLIED'
      ? {
          ...(result.classification === undefined ? {} : { classification: result.classification }),
          lifecycle: result.override.lifecycle,
          resolved:
            result.resolved.status === 'CURRENT'
              ? { source: result.resolved.source, status: result.resolved.status }
              : result.resolved,
          resolvedCurrentChanged: result.resolvedCurrentChanged,
          revision: result.override.revision,
          status: result.status,
        }
      : result;
  },
);

export const activateLocalOverrideAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.activate-local-override.access.v1',
    },
    actionKey: ACTION_KEY,
    auditEvidenceSchema: CatalogSourceAuditEvidenceSchema,
    auditProfile: 'standard',
    domainErrorSchema: CatalogSourceActionErrorSchema,
    domainEvents,
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: ACTION_KEY,
      moduleKey: 'commerce.catalog',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: 'commerce.catalog',
    payloadSchema: ActivateLocalOverridePayloadSchema,
    policies: [],
    resultSchema: ActivateLocalOverrideResultSchema,
    schemaVersion: '1',
  },
  handleActivateLocalOverride,
  (transaction, scope) =>
    Effect.succeed({
      ...makeCatalogSourceActionServices(transaction, scope, 'ACTIVATE'),
      captureResult: (actionInvocationId: string, result: CatalogLocalOverrideResult) =>
        captureCatalogActionResult(
          transaction,
          scope,
          { actionInvocationId, actionKey: ACTION_KEY, schemaVersion: 1 },
          {
            decode: Schema.decodeUnknownEffect(ActivateLocalOverrideResultSchema),
            encode: Schema.encodeEffect(ActivateLocalOverrideResultSchema),
          },
          result,
        ).pipe(
          Effect.mapError((cause) =>
            Object.assign(
              new ActionTransactionError({
                code: 'action_transaction_failed',
                reason: 'Catalog result capture failed',
              }),
              { cause },
            ),
          ),
        ),
    }),
  ({ actionInvocationId, result, services }) => services.captureResult(actionInvocationId, result),
);

// <generated-outbox-message-exports>
export { ActivateLocalOverrideCommerceCatalogSelectionSourceChangedV1OutboxPayloadSchema } from './activate-local-override-commerce-catalog-selection-source-changed-v1.outbox-message.ts';
export { ActivateLocalOverrideCommerceCatalogSelectionSourceChangedV1OutboxProducerModuleKey } from './activate-local-override-commerce-catalog-selection-source-changed-v1.outbox-message.ts';
export { ActivateLocalOverrideCommerceCatalogSelectionSourceChangedV1OutboxTopic } from './activate-local-override-commerce-catalog-selection-source-changed-v1.outbox-message.ts';
export { createActivateLocalOverrideCommerceCatalogSelectionSourceChangedV1OutboxMessage } from './activate-local-override-commerce-catalog-selection-source-changed-v1.outbox-message.ts';
export type { ActivateLocalOverrideCommerceCatalogSelectionSourceChangedV1OutboxPayload } from './activate-local-override-commerce-catalog-selection-source-changed-v1.outbox-message.ts';
// </generated-outbox-message-exports>
