// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug add-product-category-assignment
import { Effect, Schema } from 'effect';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';

export const AddProductCategoryAssignmentPayloadSchema = Schema.Struct({});
export type AddProductCategoryAssignmentPayload = Schema.Schema.Type<typeof AddProductCategoryAssignmentPayloadSchema>;

export const AddProductCategoryAssignmentResultSchema = Schema.Struct({});
export type AddProductCategoryAssignmentResult = Schema.Schema.Type<typeof AddProductCategoryAssignmentResultSchema>;

export class AddProductCategoryAssignmentNotImplemented extends Schema.TaggedError<AddProductCategoryAssignmentNotImplemented>()(
  'AddProductCategoryAssignmentNotImplemented',
  {
    code: Schema.Literal('action_not_implemented'),
    reason: Schema.String,
  },
) {}

const handleAddProductCategoryAssignment = () =>
  Effect.fail(
    new AddProductCategoryAssignmentNotImplemented({
      code: 'action_not_implemented',
      reason: 'The Add Product Category Assignment Action is not implemented',
    }),
  );

export const addProductCategoryAssignmentAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.add-product-category-assignment.access.v1',
    },
    actionKey: 'commerce.catalog.add-product-category-assignment',
    auditProfile: 'standard',
    domainErrorSchema: AddProductCategoryAssignmentNotImplemented,
    domainEvents: {},
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'commerce.catalog.add-product-category-assignment',
      moduleKey: 'commerce.catalog',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: 'commerce.catalog',
    payloadSchema: AddProductCategoryAssignmentPayloadSchema,
    policies: [],
    resultSchema: AddProductCategoryAssignmentResultSchema,
    schemaVersion: '1',
  },
  handleAddProductCategoryAssignment,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
