// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug assert-size-equivalence
import type { ActionHandlerContext } from '@app/core-runtime';
import { Effect, Schema } from 'effect';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { SizeEquivalenceAssertionSchema } from '../../shared/domain/attribute-vocabulary.ts';
import { ProductAuditEvidenceSchema, ProductReasonSchema } from '../../shared/domain/product.ts';
import { CatalogPersistenceUnavailable } from '../persistence/errors.ts';
import { SizePersistenceConflict, sizeUsagePersistenceForScope } from '../persistence/size-usage-persistence.ts';
import type { SizeUsagePersistence } from '../persistence/size-usage-persistence.ts';

export const AssertSizeEquivalencePayloadSchema = Schema.Struct({
  assertion: SizeEquivalenceAssertionSchema,
  reason: ProductReasonSchema,
});
export type AssertSizeEquivalencePayload = Schema.Schema.Type<typeof AssertSizeEquivalencePayloadSchema>;

export const AssertSizeEquivalenceResultSchema = Schema.Struct({ assertionId: Schema.String.check(Schema.isUUID()) });
export type AssertSizeEquivalenceResult = Schema.Schema.Type<typeof AssertSizeEquivalenceResultSchema>;

export const handleAssertSizeEquivalence = Effect.fn('AssertSizeEquivalenceAction.handle')(
  function* handleAssertSizeEquivalence(
    payload: AssertSizeEquivalencePayload,
    context: ActionHandlerContext<Readonly<Record<string, never>>, SizeUsagePersistence>,
  ) {
    const { leftSizeRef, rightSizeRef } = payload.assertion;
    if (leftSizeRef.tenantId !== context.scope.tenantId || rightSizeRef.tenantId !== context.scope.tenantId) {
      return yield* new SizePersistenceConflict({
        code: 'size_persistence_conflict',
        conflict: 'INVALID_INPUT',
        reason: 'Size evidence must belong to the trusted Tenant',
      });
    }
    const assertionId = yield* context.services.assertEquivalence({
      actionInvocationId: context.actionInvocationId,
      assertion: payload.assertion,
      principalId: context.scope.principalId,
    });
    yield* context.recordDataAccess({
      accessKind: 'read',
      queryHash: `catalog-size-equivalence:${leftSizeRef.resourceId}:${rightSizeRef.resourceId}`,
      resultCount: 2,
      servingModuleKey: 'commerce.catalog',
      targetModuleKey: 'commerce.catalog',
      targetResourceId: leftSizeRef.resourceId,
      targetResourceType: 'commerce.catalog.controlled-attribute-value',
    });
    yield* context.recordAuditEvidence({ evidenceRefs: [payload.assertion.evidence], reason: payload.reason });
    return { assertionId };
  },
);

export const assertSizeEquivalenceAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.assert-size-equivalence.access.v1',
    },
    actionKey: 'commerce.catalog.assert-size-equivalence',
    auditEvidenceSchema: ProductAuditEvidenceSchema,
    auditProfile: 'standard',
    domainErrorSchema: Schema.Union([SizePersistenceConflict, CatalogPersistenceUnavailable]),
    domainEvents: {},
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'commerce.catalog.assert-size-equivalence',
      moduleKey: 'commerce.catalog',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: 'commerce.catalog',
    payloadSchema: AssertSizeEquivalencePayloadSchema,
    policies: [],
    resultSchema: AssertSizeEquivalenceResultSchema,
    schemaVersion: '1',
  },
  handleAssertSizeEquivalence,
  (transaction, scope) => Effect.succeed(sizeUsagePersistenceForScope(transaction, scope)),
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
