// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug change-product-manufacturer
import { Effect } from 'effect';
import type { Schema } from 'effect';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import {
  ChangeProductManufacturerPayloadSchema,
  ManufacturerActionErrorSchema,
  ManufacturerActionError,
  ProductManufacturerMutationResultSchema,
} from '../../shared/actions/manufacturer-mutations.ts';

export { ChangeProductManufacturerPayloadSchema } from '../../shared/actions/manufacturer-mutations.ts';
export type { ChangeProductManufacturerPayload } from '../../shared/actions/manufacturer-mutations.ts';

export const ChangeProductManufacturerResultSchema = ProductManufacturerMutationResultSchema;
export type ChangeProductManufacturerResult = Schema.Schema.Type<typeof ChangeProductManufacturerResultSchema>;

const handleChangeProductManufacturer = () =>
  Effect.fail(
    new ManufacturerActionError({
      code: 'manufacturer_reference_unavailable',
      reason: 'Authoritative manufacturer reference verification is unavailable',
    }),
  );

export const changeProductManufacturerAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.change-product-manufacturer.access.v1',
    },
    actionKey: 'commerce.catalog.change-product-manufacturer',
    auditProfile: 'standard',
    domainErrorSchema: ManufacturerActionErrorSchema,
    domainEvents: {},
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'commerce.catalog.change-product-manufacturer',
      moduleKey: 'commerce.catalog',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: 'commerce.catalog',
    payloadSchema: ChangeProductManufacturerPayloadSchema,
    policies: [],
    resultSchema: ChangeProductManufacturerResultSchema,
    schemaVersion: '1',
  },
  handleChangeProductManufacturer,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
