// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug change-product-relationship
import type { ActionHandlerContext } from '@app/core-runtime';
import { Effect, Match } from 'effect';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import {
  ChangeProductRelationshipPayloadSchema,
  ProductRelationshipMutationResultSchema,
} from '../../shared/actions/product-relationship-mutations.ts';
import type { ChangeProductRelationshipPayload } from '../../shared/actions/product-relationship-mutations.ts';
import type { ProductRelationshipPersistence } from '../persistence/product-relationship-persistence.ts';
import {
  checkRelationshipTenant,
  ProductAuditEvidenceSchema,
  ProductRelationshipActionErrorSchema,
  recordRelationshipAccess,
  relationshipConflict,
  relationshipNotFound,
  relationshipPersistenceServiceFactory,
} from './product-relationship-action-support.ts';

export { ChangeProductRelationshipPayloadSchema } from '../../shared/actions/product-relationship-mutations.ts';
export type { ChangeProductRelationshipPayload } from '../../shared/actions/product-relationship-mutations.ts';
export const ChangeProductRelationshipResultSchema = ProductRelationshipMutationResultSchema;
export type ChangeProductRelationshipResult = typeof ChangeProductRelationshipResultSchema.Type;

export const handleChangeProductRelationship = Effect.fn('ChangeProductRelationshipAction.handle')(
  function* handleChangeProductRelationship(
    payload: ChangeProductRelationshipPayload,
    context: ActionHandlerContext<Readonly<Record<string, never>>, ProductRelationshipPersistence>,
  ) {
    yield* checkRelationshipTenant(context.scope.tenantId, payload.relationship.source);
    yield* checkRelationshipTenant(context.scope.tenantId, payload.relationship.target);
    if (payload.classification === 'MATERIAL_CHANGE') {
      return yield* relationshipConflict('INVALID_CHANGE');
    }
    const outcome = yield* context.services.change({
      actionInvocationId: context.actionInvocationId,
      classification: payload.classification,
      expectedRevision: payload.expectedRevision,
      principalId: context.scope.principalId,
      relationship: payload.relationship,
      relationshipId: payload.relationshipId,
    });
    const result = yield* Match.value(outcome).pipe(
      Match.tag('changed', ({ relationship, relationshipId, revision }) =>
        Effect.succeed({ relationship, relationshipId, revision }),
      ),
      Match.tag('not_found', () => Effect.fail(relationshipNotFound())),
      Match.tag('revision_conflict', () => Effect.fail(relationshipConflict('REVISION'))),
      Match.tag('duplicate', () => Effect.fail(relationshipConflict('DUPLICATE'))),
      Match.tag('identity_conflict', () => Effect.fail(relationshipConflict('IDENTITY'))),
      Match.tag('lifecycle_conflict', () => Effect.fail(relationshipConflict('LIFECYCLE'))),
      Match.tag('invalid_change', () => Effect.fail(relationshipConflict('INVALID_CHANGE'))),
      Match.exhaustive,
    );
    yield* context.recordAuditEvidence({
      evidenceRefs: payload.relationship.evidenceRefs,
      reason: payload.relationship.reason,
    });
    yield* recordRelationshipAccess(context, result.relationship.source);
    yield* recordRelationshipAccess(context, result.relationship.target);
    return result;
  },
);

export const changeProductRelationshipAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.change-product-relationship.access.v1',
    },
    actionKey: 'commerce.catalog.change-product-relationship',
    auditEvidenceSchema: ProductAuditEvidenceSchema,
    auditProfile: 'standard',
    domainErrorSchema: ProductRelationshipActionErrorSchema,
    domainEvents: {},
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'commerce.catalog.change-product-relationship',
      moduleKey: 'commerce.catalog',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: 'commerce.catalog',
    payloadSchema: ChangeProductRelationshipPayloadSchema,
    policies: [],
    resultSchema: ChangeProductRelationshipResultSchema,
    schemaVersion: '1',
  },
  handleChangeProductRelationship,
  relationshipPersistenceServiceFactory,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
