// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug create-set-composition
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';

import {
  CreateSetCompositionPayloadSchema,
  CreateSetCompositionResultSchema,
} from '../../shared/actions/create-set-composition.ts';
import { SetCompositionActionError } from '../../shared/actions/set-composition-contract.ts';
import {
  handleSetCompositionMutation,
  setCompositionPersistenceServiceFactory,
} from './set-composition-action-support.ts';

export { CreateSetCompositionPayloadSchema } from '../../shared/actions/create-set-composition.ts';
export type { CreateSetCompositionPayload } from '../../shared/actions/create-set-composition.ts';

export const createSetCompositionAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.create-set-composition.access.v1',
    },
    actionKey: 'commerce.catalog.create-set-composition',
    auditProfile: 'standard',
    domainErrorSchema: SetCompositionActionError,
    domainEvents: {},
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'commerce.catalog.create-set-composition',
      moduleKey: 'commerce.catalog',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: 'commerce.catalog',
    payloadSchema: CreateSetCompositionPayloadSchema,
    policies: [],
    resultSchema: CreateSetCompositionResultSchema,
    schemaVersion: '1',
  },
  (payload, context) => handleSetCompositionMutation('CREATE', payload, context),
  setCompositionPersistenceServiceFactory,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
