// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug create-product
import type { ActionHandlerContext } from '@app/core-runtime';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { Effect, Match } from 'effect';

import { CreateProductPayloadSchema, CreateProductResultSchema } from '../../shared/actions/create-product.ts';
import type { CreateProductPayload } from '../../shared/actions/create-product.ts';
import { ProductAuditEvidenceSchema } from '../../shared/domain/product.ts';
import { ProductPersistenceConflict } from '../../shared/domain/product-errors.ts';
import {
  ProductActionErrorSchema,
  catalogPersistenceServiceFactory,
  recordProductAccess,
  recordProductEvent,
} from './product-action-support.ts';
import type { CatalogPersistence } from '../persistence/catalog-persistence.ts';

export { CreateProductPayloadSchema } from '../../shared/actions/create-product.ts';
export type { CreateProductPayload } from '../../shared/actions/create-product.ts';

const MODULE_KEY = 'commerce.catalog' as const;
const domainEvents = {
  'commerce.catalog.product-created.v1': CreateProductResultSchema,
} as const;

export const handleCreateProduct = Effect.fn('CreateProductAction.handle')(function* handleCreateProduct(
  payload: CreateProductPayload,
  context: ActionHandlerContext<typeof domainEvents, CatalogPersistence>,
) {
  const outcome = yield* context.services.create({
    actionInvocationId: context.actionInvocationId,
    description: payload.description,
    name: payload.name,
    principalId: context.scope.principalId,
    reason: payload.reason,
    tenantId: context.scope.tenantId,
    variantId: payload.variantId,
  });
  const result = yield* Match.value(outcome).pipe(
    Match.tag('conflict', () =>
      Effect.fail(
        new ProductPersistenceConflict({
          code: 'product_persistence_conflict',
          conflict: 'PRODUCT_ID',
          reason: 'The Product identity conflicts with an existing Catalog resource',
        }),
      ),
    ),
    Match.tag('created', ({ product, variantId }) => Effect.succeed({ product, variantId })),
    Match.exhaustive,
  );
  yield* context.recordAuditEvidence({ reason: payload.reason });
  yield* recordProductAccess(context, result.product.productRef.resourceId);
  yield* recordProductEvent(
    context,
    'commerce.catalog.product-created.v1',
    result.product.productRef.resourceId,
    result,
  );
  return result;
});

export const createProductAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.create-product.access.v1',
    },
    actionKey: 'commerce.catalog.create-product',
    auditEvidenceSchema: ProductAuditEvidenceSchema,
    auditProfile: 'standard',
    domainErrorSchema: ProductActionErrorSchema,
    domainEvents,
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'commerce.catalog.create-product',
      moduleKey: MODULE_KEY,
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: MODULE_KEY,
    payloadSchema: CreateProductPayloadSchema,
    policies: [],
    resultSchema: CreateProductResultSchema,
    schemaVersion: '1',
  },
  handleCreateProduct,
  catalogPersistenceServiceFactory,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
