// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug create-package-definition
import { Effect } from 'effect';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import {
  CreatePackageDefinitionPayloadSchema,
  CreatePackageDefinitionResultSchema,
} from '../../shared/actions/create-package-definition.ts';
import type { CreatePackageDefinitionPayload } from '../../shared/actions/create-package-definition.ts';
import {
  PackageDefinitionActionErrorSchema,
  PackageDefinitionActionError,
} from '../../shared/actions/package-definition-contract.ts';

export { CreatePackageDefinitionPayloadSchema } from '../../shared/actions/create-package-definition.ts';
export type { CreatePackageDefinitionPayload } from '../../shared/actions/create-package-definition.ts';

export const handleCreatePackageDefinition = (
  payload: CreatePackageDefinitionPayload,
  context: { readonly scope: { readonly tenantId: string } },
) => {
  const { tenantId } = context.scope;
  if (
    [
      payload.definitionRef,
      payload.content.form.productRef,
      payload.content.form.variantRef,
      payload.content.unitRef,
      payload.content.lower?.revision.resourceRef,
      payload.content.setComposition?.resourceRef,
    ].some((ref) => ref !== undefined && ref.tenantId !== tenantId)
  ) {
    return Effect.fail(
      new PackageDefinitionActionError({
        code: 'package_definition_invalid',
        reason: 'Package Definition references must belong to the trusted Tenant',
      }),
    );
  }
  return Effect.fail(
    new PackageDefinitionActionError({
      code: 'package_definition_unavailable',
      reason: 'Authoritative Package Definition persistence and Current revision verification are unavailable',
    }),
  );
};

export const createPackageDefinitionAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.create-package-definition.access.v1',
    },
    actionKey: 'commerce.catalog.create-package-definition',
    auditProfile: 'standard',
    domainErrorSchema: PackageDefinitionActionErrorSchema,
    domainEvents: {},
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'tenant_membership_default' },
      entrypointKey: 'commerce.catalog.create-package-definition',
      moduleKey: 'commerce.catalog',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: 'commerce.catalog',
    payloadSchema: CreatePackageDefinitionPayloadSchema,
    policies: [],
    resultSchema: CreatePackageDefinitionResultSchema,
    schemaVersion: '1',
  },
  handleCreatePackageDefinition,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
