// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug govern-variant-axes
import type { ActionHandlerContext } from '@app/core-runtime';
import { ActionTransactionError, defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { Effect, Schema } from 'effect';

import {
  GovernVariantAxesPayloadSchema,
  GovernVariantAxesResultSchema,
} from '../../shared/actions/govern-variant-axes.ts';
import type { GovernVariantAxesPayload } from '../../shared/actions/govern-variant-axes.ts';
import { ProductAuditEvidenceSchema } from '../../shared/domain/product.ts';
import { OutboxPayloadSchema } from '../../shared/outbox/commerce-catalog-variant-axes-changed-v1.ts';
import { captureCatalogActionResult } from '../persistence/catalog-action-result-snapshot.ts';
import { CatalogPersistenceUnavailable } from '../persistence/errors.ts';
import { VariantAxisWriteConflict, variantAxisPersistenceForScope } from '../persistence/variant-axis-persistence.ts';
import type { VariantAxisPersistence } from '../persistence/variant-axis-persistence.ts';
import { createGovernVariantAxesCommerceCatalogVariantAxesChangedV1OutboxMessage } from './govern-variant-axes-commerce-catalog-variant-axes-changed-v1.outbox-message.ts';

export type { GovernVariantAxesPayload } from '../../shared/actions/govern-variant-axes.ts';

const moduleKey = 'commerce.catalog' as const;
const actionKey = 'commerce.catalog.govern-variant-axes' as const;
const domainEvents = { 'commerce.catalog.variant-axes-changed.v1': OutboxPayloadSchema } as const;

export const handleGovernVariantAxes = Effect.fn('GovernVariantAxesAction.handle')(function* handleGovernVariantAxes(
  payload: GovernVariantAxesPayload,
  context: ActionHandlerContext<typeof domainEvents, VariantAxisPersistence>,
) {
  if (payload.axes.some((axis) => axis.attributeDefinitionRef.tenantId !== context.scope.tenantId)) {
    return yield* new VariantAxisWriteConflict({
      code: 'variant_axis_write_conflict',
      conflict: 'INVALID_INPUT',
      reason: 'Axis definition is outside the trusted Tenant',
    });
  }
  const result = yield* context.services.govern({
    actionInvocationId: context.actionInvocationId,
    axes: payload.axes.map((axis) => ({
      attributeDefinitionId: axis.attributeDefinitionRef.resourceId,
      definitionRevision: axis.definitionRevision,
    })),
    expectedAxisRevision: payload.expectedAxisRevision,
    principalId: context.scope.principalId,
    productRef: payload.productRef,
    reason: payload.reason,
  });
  yield* context.recordDataAccess({
    accessKind: 'read',
    queryHash: `catalog-variant-axes:${payload.productRef.resourceId}`,
    resultCount: 1,
    servingModuleKey: moduleKey,
    targetModuleKey: moduleKey,
    targetResourceId: payload.productRef.resourceId,
    targetResourceType: 'commerce.catalog.product',
  });
  yield* context.recordAuditEvidence({ reason: payload.reason });
  const decoded = yield* Schema.decodeEffect(GovernVariantAxesResultSchema)({
    ...result,
    productRef: payload.productRef,
  }).pipe(
    Effect.mapError((cause) => {
      const failure = new CatalogPersistenceUnavailable({
        code: 'catalog_persistence_unavailable',
        reason: 'Catalog returned an invalid Action result',
      });
      Object.defineProperty(failure, 'cause', { configurable: true, value: cause });
      return failure;
    }),
  );
  if (decoded.changed) {
    const eventPayload = {
      axisRevision: decoded.axisRevision,
      productRef: decoded.productRef,
      tenantId: context.scope.tenantId,
    };
    const event = yield* context.addDomainEvent({
      eventType: 'commerce.catalog.variant-axes-changed.v1',
      payloadJson: eventPayload,
      producerModuleKey: moduleKey,
      subjectModuleKey: moduleKey,
      subjectResourceId: decoded.productRef.resourceId,
      subjectResourceType: 'commerce.catalog.product',
    });
    yield* context.addOutboxMessage(
      event,
      createGovernVariantAxesCommerceCatalogVariantAxesChangedV1OutboxMessage(eventPayload),
    );
  }
  return decoded;
});

export const governVariantAxesAction = defineAction(
  {
    accessEvidencePolicy: { captureMode: 'metadata_only', policyKey: 'commerce.catalog.govern-variant-axes.access.v1' },
    actionKey,
    auditEvidenceSchema: ProductAuditEvidenceSchema,
    auditProfile: 'standard',
    domainErrorSchema: Schema.Union([VariantAxisWriteConflict, CatalogPersistenceUnavailable]),
    domainEvents,
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'commerce.catalog.govern-variant-axes',
      moduleKey: 'commerce.catalog',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: moduleKey,
    payloadSchema: GovernVariantAxesPayloadSchema,
    policies: [],
    resultSchema: GovernVariantAxesResultSchema,
    schemaVersion: '1',
  },
  handleGovernVariantAxes,
  (transaction, scope) =>
    Effect.succeed({
      ...variantAxisPersistenceForScope(transaction, scope),
      captureResult: (actionInvocationId: string, result: typeof GovernVariantAxesResultSchema.Type) =>
        captureCatalogActionResult(
          transaction,
          scope,
          { actionInvocationId, actionKey, schemaVersion: 1 },
          {
            decode: Schema.decodeUnknownEffect(GovernVariantAxesResultSchema),
            encode: Schema.encodeEffect(GovernVariantAxesResultSchema),
          },
          result,
        ).pipe(
          Effect.mapError((cause) => {
            const failure = new ActionTransactionError({
              code: 'action_transaction_failed',
              reason: 'Catalog result capture failed',
            });
            Object.defineProperty(failure, 'cause', { configurable: true, value: cause });
            return failure;
          }),
        ),
    }),
  ({ actionInvocationId, result, services }) => services.captureResult(actionInvocationId, result),
);

// <generated-outbox-message-exports>
export { createGovernVariantAxesCommerceCatalogVariantAxesChangedV1OutboxMessage } from './govern-variant-axes-commerce-catalog-variant-axes-changed-v1.outbox-message.ts';
export { GovernVariantAxesCommerceCatalogVariantAxesChangedV1OutboxPayloadSchema } from './govern-variant-axes-commerce-catalog-variant-axes-changed-v1.outbox-message.ts';
export { GovernVariantAxesCommerceCatalogVariantAxesChangedV1OutboxProducerModuleKey } from './govern-variant-axes-commerce-catalog-variant-axes-changed-v1.outbox-message.ts';
export { GovernVariantAxesCommerceCatalogVariantAxesChangedV1OutboxTopic } from './govern-variant-axes-commerce-catalog-variant-axes-changed-v1.outbox-message.ts';
export type { GovernVariantAxesCommerceCatalogVariantAxesChangedV1OutboxPayload } from './govern-variant-axes-commerce-catalog-variant-axes-changed-v1.outbox-message.ts';
// </generated-outbox-message-exports>
