// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug move-product-category
import { Effect, Schema } from 'effect';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';

export const MoveProductCategoryPayloadSchema = Schema.Struct({});
export type MoveProductCategoryPayload = Schema.Schema.Type<typeof MoveProductCategoryPayloadSchema>;

export const MoveProductCategoryResultSchema = Schema.Struct({});
export type MoveProductCategoryResult = Schema.Schema.Type<typeof MoveProductCategoryResultSchema>;

export class MoveProductCategoryNotImplemented extends Schema.TaggedError<MoveProductCategoryNotImplemented>()(
  'MoveProductCategoryNotImplemented',
  {
    code: Schema.Literal('action_not_implemented'),
    reason: Schema.String,
  },
) {}

const handleMoveProductCategory = () =>
  Effect.fail(
    new MoveProductCategoryNotImplemented({
      code: 'action_not_implemented',
      reason: 'The Move Product Category Action is not implemented',
    }),
  );

export const moveProductCategoryAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.move-product-category.access.v1',
    },
    actionKey: 'commerce.catalog.move-product-category',
    auditProfile: 'standard',
    domainErrorSchema: MoveProductCategoryNotImplemented,
    domainEvents: {},
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'commerce.catalog.move-product-category',
      moduleKey: 'commerce.catalog',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: 'commerce.catalog',
    payloadSchema: MoveProductCategoryPayloadSchema,
    policies: [],
    resultSchema: MoveProductCategoryResultSchema,
    schemaVersion: '1',
  },
  handleMoveProductCategory,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
