// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug publish-product-configuration
import { Effect, Match, Schema } from 'effect';
import { ActionTransactionError, defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import {
  PublishProductConfigurationPayloadSchema,
  PublishProductConfigurationResultSchema,
  PublishProductConfigurationError,
} from '../../shared/actions/publish-product-configuration.ts';
import {
  productConfigurationPersistenceForScope,
  ProductConfigurationPersistenceUnavailable,
} from '../persistence/product-configuration-persistence.ts';
import type {
  ConfigurationSelectionImpact,
  ProductConfigurationPersistence,
} from '../persistence/product-configuration-persistence.ts';
import type { ActionHandlerContext } from '@app/core-runtime';
import { captureCatalogActionResult } from '../persistence/catalog-action-result-snapshot.ts';

export { PublishProductConfigurationPayloadSchema } from '../../shared/actions/publish-product-configuration.ts';
export type { PublishProductConfigurationPayload } from '../../shared/actions/publish-product-configuration.ts';
const ACTION_KEY = 'commerce.catalog.publish-product-configuration' as const;

const unavailable = () =>
  new ProductConfigurationPersistenceUnavailable({
    code: 'product_configuration_persistence_unavailable',
    reason: 'Selection-impact proof is unavailable',
  });
const selectionImpact: ConfigurationSelectionImpact = { verify: () => Effect.fail(unavailable()) };
export const publishProductConfigurationPersistenceServiceFactory = (
  transaction: Parameters<typeof productConfigurationPersistenceForScope>[0],
  scope: Parameters<typeof productConfigurationPersistenceForScope>[1],
) => Effect.succeed(productConfigurationPersistenceForScope(transaction, scope, selectionImpact));

const error = (
  code:
    | 'product_configuration_invalid'
    | 'product_configuration_not_found'
    | 'product_configuration_stale'
    | 'product_configuration_unavailable',
  reason: string,
) => new PublishProductConfigurationError({ code, reason });
export const handlePublishProductConfiguration = Effect.fn('PublishProductConfigurationAction.handle')(
  function* publishProductConfiguration(
    payload: typeof PublishProductConfigurationPayloadSchema.Type,
    context: ActionHandlerContext<Readonly<Record<string, never>>, ProductConfigurationPersistence>,
  ) {
    const outcome = yield* context.services
      .publish({
        ...payload,
        actionInvocationId: context.actionInvocationId,
        principalId: context.scope.principalId,
      })
      .pipe(
        Effect.mapError((cause) => {
          const failure = error(
            'product_configuration_unavailable',
            'Authoritative Configuration publication is unavailable',
          );
          Object.defineProperty(failure, 'cause', { configurable: true, value: cause });
          return failure;
        }),
      );
    return yield* Match.value(outcome).pipe(
      Match.tag('published', ({ revision }) => Effect.succeed({ definitionId: payload.definitionId, revision })),
      Match.tag('invalid', ({ reason }) => Effect.fail(error('product_configuration_invalid', reason))),
      Match.tag('incompatible', ({ reason }) => Effect.fail(error('product_configuration_invalid', reason))),
      Match.tag('not_found', () => Effect.fail(error('product_configuration_not_found', 'Definition was not found'))),
      Match.tag('stale', () => Effect.fail(error('product_configuration_stale', 'Definition revision changed'))),
      Match.exhaustive,
    );
  },
);

export const publishProductConfigurationAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.publish-product-configuration.access.v1',
    },
    actionKey: ACTION_KEY,
    auditProfile: 'standard',
    domainErrorSchema: PublishProductConfigurationError,
    domainEvents: {},
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: ACTION_KEY,
      moduleKey: 'commerce.catalog',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: 'commerce.catalog',
    payloadSchema: PublishProductConfigurationPayloadSchema,
    policies: [],
    resultSchema: PublishProductConfigurationResultSchema,
    schemaVersion: '1',
  },
  handlePublishProductConfiguration,
  (transaction, scope) =>
    publishProductConfigurationPersistenceServiceFactory(transaction, scope).pipe(
      Effect.map((services) => ({
        ...services,
        captureResult: (actionInvocationId: string, result: typeof PublishProductConfigurationResultSchema.Type) =>
          captureCatalogActionResult(
            transaction,
            scope,
            { actionInvocationId, actionKey: ACTION_KEY, schemaVersion: 1 },
            {
              decode: Schema.decodeUnknownEffect(PublishProductConfigurationResultSchema),
              encode: Schema.encodeEffect(PublishProductConfigurationResultSchema),
            },
            result,
          ).pipe(
            Effect.mapError((cause) =>
              Object.assign(
                new ActionTransactionError({
                  code: 'action_transaction_failed',
                  reason: 'Catalog result capture failed',
                }),
                { cause },
              ),
            ),
          ),
      })),
    ),
  ({ actionInvocationId, result, services }) => services.captureResult(actionInvocationId, result),
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
