// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug reactivate-product
import type { ActionHandlerContext } from '@app/core-runtime';
import { defineAction, defineActionResourcePermission, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { Effect, Match } from 'effect';

import {
  ReactivateProductPayloadSchema,
  ReactivateProductResultSchema,
} from '../../shared/actions/reactivate-product.ts';
import type { ReactivateProductPayload } from '../../shared/actions/reactivate-product.ts';
import { ProductAuditEvidenceSchema } from '../../shared/domain/product.ts';
import {
  ProductActionErrorSchema,
  catalogPersistenceServiceFactory,
  invalidCrossTenantProduct,
  productActionResourcePermission,
  productLifecycleConflict,
  productNotCatalogReady,
  productNotFound,
  productRevisionConflict,
  recordProductAccess,
  recordProductEvent,
} from './product-action-support.ts';
import type { CatalogPersistence } from '../persistence/catalog-persistence.ts';

export { ReactivateProductPayloadSchema } from '../../shared/actions/reactivate-product.ts';
export type { ReactivateProductPayload } from '../../shared/actions/reactivate-product.ts';

const MODULE_KEY = 'commerce.catalog' as const;
const domainEvents = {
  'commerce.catalog.product-reactivated.v1': ReactivateProductResultSchema,
} as const;

const execute = Effect.fn('ReactivateProductAction.execute')(function* execute(
  payload: ReactivateProductPayload,
  context: ActionHandlerContext<typeof domainEvents, CatalogPersistence>,
) {
  if (payload.productRef.tenantId !== context.scope.tenantId) {
    return yield* invalidCrossTenantProduct(payload.productRef);
  }
  const outcome = yield* context.services.reactivate({
    actionInvocationId: context.actionInvocationId,
    expectedRevision: payload.expectedRevision,
    principalId: context.scope.principalId,
    productId: payload.productRef.resourceId,
    reason: payload.reason,
    tenantId: context.scope.tenantId,
  });
  const result = yield* Match.value(outcome).pipe(
    Match.tag('lifecycle_conflict', ({ product }) =>
      Effect.fail(productLifecycleConflict(product.productRef, 'Only a retired Product can be reactivated')),
    ),
    Match.tag('not_catalog_ready', ({ product, reasons }) =>
      Effect.fail(productNotCatalogReady(product.productRef, reasons)),
    ),
    Match.tag('not_found', () => Effect.fail(productNotFound(payload.productRef))),
    Match.tag('reactivated', ({ product }) => Effect.succeed({ product })),
    Match.tag('revision_conflict', ({ actualRevision }) =>
      Effect.fail(productRevisionConflict(payload.productRef, payload.expectedRevision, actualRevision)),
    ),
    Match.exhaustive,
  );
  yield* context.recordAuditEvidence({ reason: payload.reason });
  yield* recordProductAccess(context, result.product.productRef.resourceId);
  yield* recordProductEvent(
    context,
    'commerce.catalog.product-reactivated.v1',
    result.product.productRef.resourceId,
    result,
  );
  return result;
});

export const reactivateProductAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.reactivate-product.access.v1',
    },
    actionKey: 'commerce.catalog.reactivate-product',
    auditEvidenceSchema: ProductAuditEvidenceSchema,
    auditProfile: 'standard',
    domainErrorSchema: ProductActionErrorSchema,
    domainEvents,
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'commerce.catalog.reactivate-product',
      moduleKey: MODULE_KEY,
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: MODULE_KEY,
    payloadSchema: ReactivateProductPayloadSchema,
    policies: [],
    resourcePermission: defineActionResourcePermission<ReactivateProductPayload>(productActionResourcePermission),
    resultSchema: ReactivateProductResultSchema,
    schemaVersion: '1',
  },
  execute,
  catalogPersistenceServiceFactory,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
