// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug release-local-override
import { Effect, Schema } from 'effect';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';

const ReleaseLocalOverridePayloadSchema = Schema.Struct({});

const ReleaseLocalOverrideResultSchema = Schema.Struct({});

class ReleaseLocalOverrideNotImplemented extends Schema.TaggedError<ReleaseLocalOverrideNotImplemented>()(
  'ReleaseLocalOverrideNotImplemented',
  {
    code: Schema.Literal('action_not_implemented'),
    reason: Schema.String,
  },
) {}

const handleReleaseLocalOverride = () =>
  Effect.fail(
    new ReleaseLocalOverrideNotImplemented({
      code: 'action_not_implemented',
      reason: 'The Release Local Override Action is not implemented',
    }),
  );

export const releaseLocalOverrideAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.release-local-override.access.v1',
    },
    actionKey: 'commerce.catalog.release-local-override',
    auditProfile: 'standard',
    domainErrorSchema: ReleaseLocalOverrideNotImplemented,
    domainEvents: {},
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'commerce.catalog.release-local-override',
      moduleKey: 'commerce.catalog',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: 'commerce.catalog',
    payloadSchema: ReleaseLocalOverridePayloadSchema,
    policies: [],
    resultSchema: ReleaseLocalOverrideResultSchema,
    schemaVersion: '1',
  },
  handleReleaseLocalOverride,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
