// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug remove-variant-attribute-override
import type { ActionHandlerContext } from '@app/core-runtime';
import { captureCatalogActionResult } from '../persistence/catalog-action-result-snapshot.ts';
import { ActionTransactionError, defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { Effect, Schema } from 'effect';

import {
  RemoveVariantAttributeOverridePayloadSchema,
  RemoveVariantAttributeOverrideResultSchema,
  VariantAttributeChangeConflict,
  requireVariantAttributeChange,
} from '../../shared/actions/attribute-value-mutations.ts';
import type { RemoveVariantAttributeOverridePayload } from '../../shared/actions/attribute-value-mutations.ts';
import { ProductAuditEvidenceSchema } from '../../shared/domain/product.ts';
import {
  AttributeValuesConflict,
  attributeValuesPersistenceForScope,
} from '../persistence/attribute-values-persistence.ts';
import type { AttributeValuesPersistence } from '../persistence/attribute-values-persistence.ts';
import { CatalogPersistenceUnavailable } from '../persistence/errors.ts';
import {
  CatalogOpenSelectionImpactUnavailable,
  catalogOpenSelectionImpactForScope,
} from '../persistence/catalog-open-selection-impact.ts';

export type { RemoveVariantAttributeOverridePayload } from '../../shared/actions/attribute-value-mutations.ts';

const CATALOG_MODULE_KEY = 'commerce.catalog' as const;
const domainEvents = {} as const;
type VariantAttributeServices = AttributeValuesPersistence & {
  readonly assessOpenSelectionImpact: (
    productRef: RemoveVariantAttributeOverridePayload['productRef'],
  ) => Effect.Effect<void, CatalogOpenSelectionImpactUnavailable>;
};
export const handleRemoveVariantAttributeOverride = Effect.fn('RemoveVariantAttributeOverrideAction.handle')(
  function* handleRemoveVariantAttributeOverride(
    payload: RemoveVariantAttributeOverridePayload,
    context: ActionHandlerContext<typeof domainEvents, VariantAttributeServices>,
  ) {
    const impact = yield* requireVariantAttributeChange(payload.classification);
    if (impact === 'REVALIDATION_REQUIRED') {
      yield* context.services.assessOpenSelectionImpact(payload.productRef);
    }
    const result = yield* context.services.removeVariantOverride({
      ...payload,
      actionInvocationId: context.actionInvocationId,
      principalId: context.scope.principalId,
    });
    yield* context.recordDataAccess({
      accessKind: 'read',
      queryHash: `catalog-attribute-value:${payload.productRef.resourceId}:${payload.attributeDefinitionRef.resourceId}:${payload.variantRef.resourceId}`,
      resultCount: 1,
      servingModuleKey: CATALOG_MODULE_KEY,
      targetModuleKey: CATALOG_MODULE_KEY,
      targetResourceId: payload.variantRef.resourceId,
      targetResourceType: 'commerce.catalog.variant',
    });
    yield* context.recordAuditEvidence({ evidenceRefs: payload.classification.evidenceRefs, reason: payload.reason });
    return yield* Schema.decodeEffect(RemoveVariantAttributeOverrideResultSchema)(result).pipe(
      Effect.mapError((cause) => {
        const failure = new CatalogPersistenceUnavailable({
          code: 'catalog_persistence_unavailable',
          reason: 'Catalog returned an invalid Action result',
        });
        Object.defineProperty(failure, 'cause', { configurable: true, value: cause });
        return failure;
      }),
    );
  },
);

const ACTION_KEY = 'commerce.catalog.remove-variant-attribute-override' as const;
const toSnapshotFailure = (cause: unknown): ActionTransactionError => {
  const failure = new ActionTransactionError({
    code: 'action_transaction_failed',
    reason: 'Catalog result capture failed',
  });
  Object.defineProperty(failure, 'cause', { configurable: true, value: cause });
  return failure;
};
export const removeVariantAttributeOverrideAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.remove-variant-attribute-override.access.v1',
    },
    actionKey: ACTION_KEY,
    auditEvidenceSchema: ProductAuditEvidenceSchema,
    auditProfile: 'standard',
    domainErrorSchema: Schema.Union([
      AttributeValuesConflict,
      CatalogPersistenceUnavailable,
      VariantAttributeChangeConflict,
      CatalogOpenSelectionImpactUnavailable,
    ]),
    domainEvents,
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: ACTION_KEY,
      moduleKey: CATALOG_MODULE_KEY,
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: CATALOG_MODULE_KEY,
    payloadSchema: RemoveVariantAttributeOverridePayloadSchema,
    policies: [],
    resultSchema: RemoveVariantAttributeOverrideResultSchema,
    schemaVersion: '1',
  },
  handleRemoveVariantAttributeOverride,
  (transaction, scope) =>
    attributeValuesPersistenceForScope(transaction, scope).pipe(
      Effect.map(
        (
          services,
        ): VariantAttributeServices & {
          captureResult: (
            actionInvocationId: string,
            result: typeof RemoveVariantAttributeOverrideResultSchema.Type,
          ) => Effect.Effect<void, ActionTransactionError>;
        } => ({
          ...services,
          assessOpenSelectionImpact: catalogOpenSelectionImpactForScope(transaction, scope).assess,
          captureResult: (actionInvocationId: string, result: typeof RemoveVariantAttributeOverrideResultSchema.Type) =>
            captureCatalogActionResult(
              transaction,
              scope,
              { actionInvocationId, actionKey: ACTION_KEY, schemaVersion: 1 },
              {
                decode: Schema.decodeUnknownEffect(RemoveVariantAttributeOverrideResultSchema),
                encode: Schema.encodeEffect(RemoveVariantAttributeOverrideResultSchema),
              },
              result,
            ).pipe(Effect.mapError(toSnapshotFailure)),
        }),
      ),
    ),
  ({ actionInvocationId, result, services }) => services.captureResult(actionInvocationId, result),
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
