// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug remove-product-category-assignment
import type { ActionHandlerContext } from '@app/core-runtime';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { Effect, Schema } from 'effect';

import { ProductCategoryRefSchema } from '../../shared/resources/product-category.ts';
import { ProductRefSchema } from '../../shared/resources/product.ts';
import type { CategoryPersistence } from '../persistence/category-persistence.ts';
import {
  CategoryActionErrorSchema,
  CategoryAssignmentResultSchema,
  CategoryAuditEvidenceSchema,
  CategoryReasonSchema,
  assignmentFailure,
  categoryEventPayload,
  categoryPersistenceServiceFactory,
  crossTenantFailure,
  recordCategoryAccess,
  recordCategoryEvent,
} from './product-category-action-support.ts';

export const RemoveProductCategoryAssignmentPayloadSchema = Schema.Struct({
  categoryRef: ProductCategoryRefSchema,
  productRef: ProductRefSchema,
  reason: CategoryReasonSchema,
});
export type RemoveProductCategoryAssignmentPayload = typeof RemoveProductCategoryAssignmentPayloadSchema.Type;

export const RemoveProductCategoryAssignmentResultSchema = CategoryAssignmentResultSchema;
export type RemoveProductCategoryAssignmentResult = typeof RemoveProductCategoryAssignmentResultSchema.Type;

const domainEvents = {
  'commerce.catalog.product-category-assignment-removed.v1': RemoveProductCategoryAssignmentResultSchema,
} as const;

export const handleRemoveProductCategoryAssignment = Effect.fn('RemoveProductCategoryAssignmentAction.handle')(
  function* handleRemoveProductCategoryAssignment(
    payload: RemoveProductCategoryAssignmentPayload,
    context: ActionHandlerContext<typeof domainEvents, CategoryPersistence>,
  ) {
    if (
      payload.categoryRef.tenantId !== context.scope.tenantId ||
      payload.productRef.tenantId !== context.scope.tenantId
    )
      return yield* crossTenantFailure();
    const outcome = yield* context.services.removeAssignment({
      actionInvocationId: context.actionInvocationId,
      categoryId: payload.categoryRef.resourceId,
      principalId: context.scope.principalId,
      productId: payload.productRef.resourceId,
      reason: payload.reason,
      tenantId: context.scope.tenantId,
    });
    if (!('categoryRef' in outcome)) return yield* assignmentFailure(outcome);
    const result = {
      assignmentRevision: outcome.assignmentRevision,
      categoryRef: outcome.categoryRef,
      changed: outcome._tag === 'removed',
      productRef: outcome.productRef,
    };
    yield* context.recordAuditEvidence({ reason: payload.reason });
    yield* recordCategoryAccess(context, outcome.categoryRef.resourceId);
    yield* recordCategoryAccess(context, outcome.productRef.resourceId, 'commerce.catalog.product');
    if (result.changed)
      yield* recordCategoryEvent(
        context,
        'commerce.catalog.product-category-assignment-removed.v1',
        outcome.categoryRef.resourceId,
        categoryEventPayload(result),
      );
    return result;
  },
);

export const removeProductCategoryAssignmentAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.remove-product-category-assignment.access.v1',
    },
    actionKey: 'commerce.catalog.remove-product-category-assignment',
    auditEvidenceSchema: CategoryAuditEvidenceSchema,
    auditProfile: 'standard',
    domainErrorSchema: CategoryActionErrorSchema,
    domainEvents,
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'commerce.catalog.remove-product-category-assignment',
      moduleKey: 'commerce.catalog',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: 'commerce.catalog',
    payloadSchema: RemoveProductCategoryAssignmentPayloadSchema,
    policies: [],
    resultSchema: RemoveProductCategoryAssignmentResultSchema,
    schemaVersion: '1',
  },
  handleRemoveProductCategoryAssignment,
  categoryPersistenceServiceFactory,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
