// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug rename-controlled-attribute-value
import type { ActionHandlerContext } from '@app/core-runtime';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { DateTime, Effect, Schema } from 'effect';

import {
  RenameControlledAttributeValuePayloadSchema,
  RenameControlledAttributeValueResultSchema,
} from '../../shared/actions/attribute-governance.ts';
import type { RenameControlledAttributeValuePayload } from '../../shared/actions/attribute-governance.ts';
import { ProductAuditEvidenceSchema } from '../../shared/domain/product.ts';
import {
  AttributePersistenceConflict,
  AttributePersistenceNotFound,
  attributePersistenceForScope,
} from '../persistence/attribute-persistence.ts';
import type { AttributePersistence } from '../persistence/attribute-persistence.ts';
import { CatalogPersistenceUnavailable } from '../persistence/errors.ts';

export {
  RenameControlledAttributeValuePayloadSchema,
  RenameControlledAttributeValueResultSchema,
} from '../../shared/actions/attribute-governance.ts';
export type {
  RenameControlledAttributeValuePayload,
  RenameControlledAttributeValueResult,
} from '../../shared/actions/attribute-governance.ts';

const domainEvents = {} as const;
export const handleRenameControlledAttributeValue = Effect.fn('RenameControlledAttributeValueAction.handle')(
  function* handleRenameControlledAttributeValue(
    payload: RenameControlledAttributeValuePayload,
    context: ActionHandlerContext<typeof domainEvents, AttributePersistence>,
  ) {
    if (payload.controlledValueRef.tenantId !== context.scope.tenantId) {
      return yield* new AttributePersistenceNotFound({
        code: 'attribute_persistence_not_found',
        reason: 'Resource not found in trusted Tenant',
        resource: 'CONTROLLED_VALUE',
      });
    }
    const result = yield* context.services.renameControlledValue({
      actionInvocationId: context.actionInvocationId,
      controlledValueRef: payload.controlledValueRef,
      effectiveAt: yield* DateTime.nowAsDate,
      evidence: payload.evidence,
      evidenceRefs: [payload.evidence],
      expectedRevision: payload.expectedRevision,
      name: payload.label,
      principalId: context.scope.principalId,
      reason: payload.reason,
      sameMeaning: payload.sameMeaning,
    });
    yield* context.recordAuditEvidence({ reason: payload.reason });
    return yield* Schema.decodeEffect(RenameControlledAttributeValueResultSchema)(result).pipe(
      Effect.mapError((error) => {
        const failure = new CatalogPersistenceUnavailable({
          code: 'catalog_persistence_unavailable',
          reason: 'Catalog returned an invalid Action result',
        });
        Object.defineProperty(failure, 'cause', { configurable: true, value: error });
        return failure;
      }),
    );
  },
);

export const renameControlledAttributeValueAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.rename-controlled-attribute-value.access.v1',
    },
    actionKey: 'commerce.catalog.rename-controlled-attribute-value',
    auditEvidenceSchema: ProductAuditEvidenceSchema,
    auditProfile: 'standard',
    domainErrorSchema: Schema.Union([
      AttributePersistenceConflict,
      AttributePersistenceNotFound,
      CatalogPersistenceUnavailable,
    ]),
    domainEvents,
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'commerce.catalog.rename-controlled-attribute-value',
      moduleKey: 'commerce.catalog',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: 'commerce.catalog',
    payloadSchema: RenameControlledAttributeValuePayloadSchema,
    policies: [],
    resultSchema: RenameControlledAttributeValueResultSchema,
    schemaVersion: '1',
  },
  handleRenameControlledAttributeValue,
  attributePersistenceForScope,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
