// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug rename-attribute-definition
import type { ActionHandlerContext } from '@app/core-runtime';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { DateTime, Effect, Schema } from 'effect';

import {
  RenameAttributeDefinitionPayloadSchema,
  RenameAttributeDefinitionResultSchema,
} from '../../shared/actions/attribute-governance.ts';
import type { RenameAttributeDefinitionPayload } from '../../shared/actions/attribute-governance.ts';
import { ProductAuditEvidenceSchema } from '../../shared/domain/product.ts';
import {
  AttributePersistenceConflict,
  AttributePersistenceNotFound,
  attributePersistenceForScope,
} from '../persistence/attribute-persistence.ts';
import type { AttributePersistence } from '../persistence/attribute-persistence.ts';
import { CatalogPersistenceUnavailable } from '../persistence/errors.ts';

export {
  RenameAttributeDefinitionPayloadSchema,
  RenameAttributeDefinitionResultSchema,
} from '../../shared/actions/attribute-governance.ts';
export type {
  RenameAttributeDefinitionPayload,
  RenameAttributeDefinitionResult,
} from '../../shared/actions/attribute-governance.ts';

const domainEvents = {} as const;
const CATALOG_MODULE_KEY = 'commerce.catalog' as const;
const handleRenameAttributeDefinition = Effect.fn('RenameAttributeDefinitionAction.handle')(
  function* handleRenameAttributeDefinition(
    payload: RenameAttributeDefinitionPayload,
    context: ActionHandlerContext<typeof domainEvents, AttributePersistence>,
  ) {
    if (payload.attributeDefinitionRef.tenantId !== context.scope.tenantId) {
      return yield* new AttributePersistenceNotFound({
        code: 'attribute_persistence_not_found',
        reason: 'Resource not found in trusted Tenant',
        resource: 'DEFINITION',
      });
    }
    const result = yield* context.services.renameDefinition({
      actionInvocationId: context.actionInvocationId,
      attributeDefinitionRef: payload.attributeDefinitionRef,
      effectiveAt: yield* DateTime.nowAsDate,
      evidence: payload.evidence,
      evidenceRefs: [payload.evidence],
      expectedRevision: payload.expectedRevision,
      name: payload.label,
      principalId: context.scope.principalId,
      reason: payload.reason,
      sameMeaning: payload.sameMeaning,
    });
    yield* context.recordDataAccess({
      accessKind: 'read',
      queryHash: `catalog-attribute-definition:${payload.attributeDefinitionRef.resourceId}`,
      resultCount: 1,
      servingModuleKey: CATALOG_MODULE_KEY,
      targetModuleKey: CATALOG_MODULE_KEY,
      targetResourceId: payload.attributeDefinitionRef.resourceId,
      targetResourceType: 'commerce.catalog.attribute-definition',
    });
    yield* context.recordAuditEvidence({ reason: payload.reason });
    return yield* Schema.decodeEffect(RenameAttributeDefinitionResultSchema)(result).pipe(
      Effect.mapError((error) => {
        const failure = new CatalogPersistenceUnavailable({
          code: 'catalog_persistence_unavailable',
          reason: 'Catalog returned an invalid Action result',
        });
        Object.defineProperty(failure, 'cause', { configurable: true, value: error });
        return failure;
      }),
    );
  },
);

export const renameAttributeDefinitionAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.rename-attribute-definition.access.v1',
    },
    actionKey: 'commerce.catalog.rename-attribute-definition',
    auditEvidenceSchema: ProductAuditEvidenceSchema,
    auditProfile: 'standard',
    domainErrorSchema: Schema.Union([
      AttributePersistenceConflict,
      AttributePersistenceNotFound,
      CatalogPersistenceUnavailable,
    ]),
    domainEvents,
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'commerce.catalog.rename-attribute-definition',
      moduleKey: CATALOG_MODULE_KEY,
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: CATALOG_MODULE_KEY,
    payloadSchema: RenameAttributeDefinitionPayloadSchema,
    policies: [],
    resultSchema: RenameAttributeDefinitionResultSchema,
    schemaVersion: '1',
  },
  handleRenameAttributeDefinition,
  attributePersistenceForScope,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
