// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug replace-product-sizes
import type { ActionHandlerContext } from '@app/core-runtime';
import { Effect, Schema } from 'effect';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { SizeUsageListSchema } from '../../shared/domain/attribute-vocabulary.ts';
import { ProductAuditEvidenceSchema, ProductReasonSchema } from '../../shared/domain/product.ts';
import { CatalogPersistenceUnavailable } from '../persistence/errors.ts';
import { SizePersistenceConflict, sizeUsagePersistenceForScope } from '../persistence/size-usage-persistence.ts';
import type { SizeUsagePersistence } from '../persistence/size-usage-persistence.ts';

export const ReplaceProductSizesPayloadSchema = Schema.Struct({
  evidenceRefs: Schema.Array(Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(1000), Schema.isTrimmed())),
  expectedRevision: Schema.Finite.check(Schema.isInt(), Schema.isBetween({ minimum: 0, maximum: 2_147_483_646 })),
  list: SizeUsageListSchema,
  reason: ProductReasonSchema,
});
export type ReplaceProductSizesPayload = Schema.Schema.Type<typeof ReplaceProductSizesPayloadSchema>;

export const ReplaceProductSizesResultSchema = Schema.Struct({ revision: Schema.Number.check(Schema.isInt()) });
export type ReplaceProductSizesResult = Schema.Schema.Type<typeof ReplaceProductSizesResultSchema>;

export const handleReplaceProductSizes = Effect.fn('ReplaceProductSizesAction.handle')(
  function* handleReplaceProductSizes(
    payload: ReplaceProductSizesPayload,
    context: ActionHandlerContext<Readonly<Record<string, never>>, SizeUsagePersistence>,
  ) {
    const { productRef, orderedSizeRefs } = payload.list;
    if (
      productRef.tenantId !== context.scope.tenantId ||
      orderedSizeRefs.some((ref) => ref.tenantId !== context.scope.tenantId)
    ) {
      return yield* new SizePersistenceConflict({
        code: 'size_persistence_conflict',
        conflict: 'INVALID_INPUT',
        reason: 'Size usage must belong to the trusted Tenant',
      });
    }
    const revision = yield* context.services.replace({
      actionInvocationId: context.actionInvocationId,
      evidenceRefs: payload.evidenceRefs,
      expectedRevision: payload.expectedRevision,
      list: payload.list,
      principalId: context.scope.principalId,
      reason: payload.reason,
    });
    yield* context.recordDataAccess({
      accessKind: 'read',
      queryHash: `catalog-product-size-usage:${productRef.resourceId}`,
      resultCount: orderedSizeRefs.length,
      servingModuleKey: 'commerce.catalog',
      targetModuleKey: 'commerce.catalog',
      targetResourceId: productRef.resourceId,
      targetResourceType: 'commerce.catalog.product',
    });
    yield* context.recordAuditEvidence({ evidenceRefs: payload.evidenceRefs, reason: payload.reason });
    return { revision };
  },
);

export const replaceProductSizesAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.replace-product-sizes.access.v1',
    },
    actionKey: 'commerce.catalog.replace-product-sizes',
    auditEvidenceSchema: ProductAuditEvidenceSchema,
    auditProfile: 'standard',
    domainErrorSchema: Schema.Union([SizePersistenceConflict, CatalogPersistenceUnavailable]),
    domainEvents: {},
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'commerce.catalog.replace-product-sizes',
      moduleKey: 'commerce.catalog',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: 'commerce.catalog',
    payloadSchema: ReplaceProductSizesPayloadSchema,
    policies: [],
    resultSchema: ReplaceProductSizesResultSchema,
    schemaVersion: '1',
  },
  handleReplaceProductSizes,
  (transaction, scope) => Effect.succeed(sizeUsagePersistenceForScope(transaction, scope)),
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
