// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug retire-product-category
import type { ActionHandlerContext } from '@app/core-runtime';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { Effect, Schema } from 'effect';

import { ProductCategoryRefSchema } from '../../shared/resources/product-category.ts';
import type { CategoryPersistence } from '../persistence/category-persistence.ts';
import {
  CategoryActionErrorSchema,
  CategoryAuditEvidenceSchema,
  CategoryMutationResultSchema,
  CategoryNameSchema,
  CategoryReasonSchema,
  CategoryRevisionSchema,
  categoryEventPayload,
  categoryPersistenceServiceFactory,
  crossTenantFailure,
  mutationFailure,
  recordCategoryAccess,
  recordCategoryEvent,
} from './product-category-action-support.ts';

export const RetireProductCategoryPayloadSchema = Schema.Struct({
  categoryRef: ProductCategoryRefSchema,
  expectedRevision: CategoryRevisionSchema,
  reason: CategoryReasonSchema,
});
export type RetireProductCategoryPayload = typeof RetireProductCategoryPayloadSchema.Type;

export const RetireProductCategoryResultSchema = CategoryMutationResultSchema;
export type RetireProductCategoryResult = typeof RetireProductCategoryResultSchema.Type;

const domainEvents = { 'commerce.catalog.product-category-retired.v1': RetireProductCategoryResultSchema } as const;

export const handleRetireProductCategory = Effect.fn('RetireProductCategoryAction.handle')(
  function* handleRetireProductCategory(
    payload: RetireProductCategoryPayload,
    context: ActionHandlerContext<typeof domainEvents, CategoryPersistence>,
  ) {
    if (payload.categoryRef.tenantId !== context.scope.tenantId) return yield* crossTenantFailure();
    const outcome = yield* context.services.retireCategory({
      actionInvocationId: context.actionInvocationId,
      categoryId: payload.categoryRef.resourceId,
      principalId: context.scope.principalId,
      reason: payload.reason,
      tenantId: context.scope.tenantId,
      expectedRevision: payload.expectedRevision,
    });
    if (!('category' in outcome)) return yield* mutationFailure(outcome);
    const result = {
      category: outcome.category,
      changed: outcome.changed,
      hierarchyRevision: outcome.hierarchyRevision,
    };
    yield* context.recordAuditEvidence({ reason: payload.reason });
    yield* recordCategoryAccess(context, outcome.category.categoryRef.resourceId);
    if (outcome.changed)
      yield* recordCategoryEvent(
        context,
        'commerce.catalog.product-category-retired.v1',
        outcome.category.categoryRef.resourceId,
        categoryEventPayload(result),
      );
    return result;
  },
);

export const retireProductCategoryAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.retire-product-category.access.v1',
    },
    actionKey: 'commerce.catalog.retire-product-category',
    auditEvidenceSchema: CategoryAuditEvidenceSchema,
    auditProfile: 'standard',
    domainErrorSchema: CategoryActionErrorSchema,
    domainEvents,
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'commerce.catalog.retire-product-category',
      moduleKey: 'commerce.catalog',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: 'commerce.catalog',
    payloadSchema: RetireProductCategoryPayloadSchema,
    policies: [],
    resultSchema: RetireProductCategoryResultSchema,
    schemaVersion: '1',
  },
  handleRetireProductCategory,
  categoryPersistenceServiceFactory,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
