// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug retire-product
import type { ActionHandlerContext } from '@app/core-runtime';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { DateTime, Effect, Match, Schema } from 'effect';

import { RetireProductPayloadSchema, RetireProductResultSchema } from '../../shared/actions/retire-product.ts';
import type { RetireProductPayload, RetireProductResult } from '../../shared/actions/retire-product.ts';
import { ProductAuditEvidenceSchema } from '../../shared/domain/product.ts';
import {
  ProductActionErrorSchema,
  catalogPersistenceServiceFactory,
  invalidCrossTenantProduct,
  productLifecycleConflict,
  productNotFound,
  productRevisionConflict,
  recordProductAccess,
  recordProductEvent,
} from './product-action-support.ts';
import type { CatalogPersistence } from '../persistence/catalog-persistence.ts';
import { captureCatalogActionResult } from '../persistence/catalog-action-result-snapshot.ts';

type RetireProductServices = CatalogPersistence & {
  readonly captureResult: (
    actionInvocationId: string,
    result: RetireProductResult,
  ) => ReturnType<typeof captureCatalogActionResult<RetireProductResult>>;
};

export { RetireProductPayloadSchema } from '../../shared/actions/retire-product.ts';
export type { RetireProductPayload } from '../../shared/actions/retire-product.ts';

const MODULE_KEY = 'commerce.catalog' as const;
const ACTION_KEY = 'commerce.catalog.retire-product' as const;
const domainEvents = {
  'commerce.catalog.product-retired.v1': RetireProductResultSchema,
} as const;

const execute = Effect.fn('RetireProductAction.execute')(function* execute(
  payload: RetireProductPayload,
  context: ActionHandlerContext<typeof domainEvents, CatalogPersistence>,
) {
  if (payload.productRef.tenantId !== context.scope.tenantId) {
    return yield* invalidCrossTenantProduct(payload.productRef);
  }
  const effectiveAt =
    payload.effectiveAt === undefined
      ? DateTime.toDateUtc(yield* DateTime.now)
      : DateTime.toDateUtc(DateTime.makeUnsafe(payload.effectiveAt));
  const outcome = yield* context.services.retire({
    actionInvocationId: context.actionInvocationId,
    effectiveAt,
    expectedRevision: payload.expectedRevision,
    principalId: context.scope.principalId,
    productId: payload.productRef.resourceId,
    reason: payload.reason,
    tenantId: context.scope.tenantId,
  });
  const result = yield* Match.value(outcome).pipe(
    Match.tag('already_retired', ({ product }) =>
      Effect.fail(productLifecycleConflict(product.productRef, 'The Product is already retired')),
    ),
    Match.tag('not_found', () => Effect.fail(productNotFound(payload.productRef))),
    Match.tag('revision_conflict', ({ actualRevision }) =>
      Effect.fail(productRevisionConflict(payload.productRef, payload.expectedRevision, actualRevision)),
    ),
    Match.tag('retired', ({ product }) => Effect.succeed({ product })),
    Match.exhaustive,
  );
  yield* context.recordAuditEvidence({ reason: payload.reason });
  yield* recordProductAccess(context, result.product.productRef.resourceId);
  yield* recordProductEvent(
    context,
    'commerce.catalog.product-retired.v1',
    result.product.productRef.resourceId,
    result,
  );
  return result;
});

export const retireProductAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.retire-product.access.v1',
    },
    actionKey: ACTION_KEY,
    auditEvidenceSchema: ProductAuditEvidenceSchema,
    auditProfile: 'standard',
    domainErrorSchema: ProductActionErrorSchema,
    domainEvents,
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: ACTION_KEY,
      moduleKey: MODULE_KEY,
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: MODULE_KEY,
    payloadSchema: RetireProductPayloadSchema,
    policies: [],
    resultSchema: RetireProductResultSchema,
    schemaVersion: '1',
  },
  execute,
  (transaction, scope) =>
    catalogPersistenceServiceFactory(transaction, scope).pipe(
      Effect.map((services): RetireProductServices => ({
        ...services,
        captureResult: (actionInvocationId: string, result: RetireProductResult) =>
          captureCatalogActionResult(
            transaction,
            scope,
            { actionInvocationId, actionKey: ACTION_KEY, schemaVersion: 1 },
            {
              decode: Schema.decodeUnknownEffect(RetireProductResultSchema),
              encode: Schema.encodeEffect(RetireProductResultSchema),
            },
            result,
          ),
      })),
    ),
  ({ actionInvocationId, result, services }) => services.captureResult(actionInvocationId, result),
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
