// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug retire-package-definition
import { Effect } from 'effect';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import {
  RetirePackageDefinitionPayloadSchema,
  RetirePackageDefinitionResultSchema,
} from '../../shared/actions/retire-package-definition.ts';
import type { RetirePackageDefinitionPayload } from '../../shared/actions/retire-package-definition.ts';
import {
  PackageDefinitionActionErrorSchema,
  PackageDefinitionActionError,
} from '../../shared/actions/package-definition-contract.ts';

export { RetirePackageDefinitionPayloadSchema } from '../../shared/actions/retire-package-definition.ts';
export type { RetirePackageDefinitionPayload } from '../../shared/actions/retire-package-definition.ts';

export const handleRetirePackageDefinition = (
  payload: RetirePackageDefinitionPayload,
  context: { readonly scope: { readonly tenantId: string } },
) =>
  payload.expectedCurrent.resourceRef.tenantId === context.scope.tenantId
    ? Effect.fail(
        new PackageDefinitionActionError({
          code: 'package_definition_unavailable',
          reason: 'Current Package Definition revision cannot be locked and verified',
        }),
      )
    : Effect.fail(
        new PackageDefinitionActionError({
          code: 'package_definition_invalid',
          reason: 'Package Definition must belong to the trusted Tenant',
        }),
      );

export const retirePackageDefinitionAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.retire-package-definition.access.v1',
    },
    actionKey: 'commerce.catalog.retire-package-definition',
    auditProfile: 'standard',
    domainErrorSchema: PackageDefinitionActionErrorSchema,
    domainEvents: {},
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'tenant_membership_default' },
      entrypointKey: 'commerce.catalog.retire-package-definition',
      moduleKey: 'commerce.catalog',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: 'commerce.catalog',
    payloadSchema: RetirePackageDefinitionPayloadSchema,
    policies: [],
    resultSchema: RetirePackageDefinitionResultSchema,
    schemaVersion: '1',
  },
  handleRetirePackageDefinition,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
