// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug retire-brand
import type { ActionHandlerContext } from '@app/core-runtime';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { Effect } from 'effect';

import {
  BrandActionError,
  BrandActionErrorSchema,
  BrandAuditEvidenceSchema,
  RetireBrandPayloadSchema,
  BrandMutationResultSchema,
} from '../../shared/actions/brand-mutations.ts';
import type { RetireBrandPayload } from '../../shared/actions/brand-mutations.ts';
import type { BrandPersistence } from '../persistence/brand-persistence.ts';
import {
  brandPersistenceServiceFactory,
  mapBrandPersistenceError,
  resolveBrandMutation,
} from './brand-action-support.ts';

export type { RetireBrandPayload } from '../../shared/actions/brand-mutations.ts';

export const handleRetireBrand = Effect.fn('RetireBrandAction.handle')(function* handleRetireBrand(
  payload: RetireBrandPayload,
  context: ActionHandlerContext<Readonly<Record<string, never>>, BrandPersistence>,
) {
  if (payload.brandRef.tenantId !== context.scope.tenantId) {
    return yield* new BrandActionError({
      code: 'brand_invalid',
      reason: 'Brand and Product references must belong to the trusted Tenant',
    });
  }
  const outcome = yield* context.services
    .retire({ actionInvocationId: context.actionInvocationId, payload, principalId: context.scope.principalId })
    .pipe(Effect.mapError(mapBrandPersistenceError));
  const result = yield* resolveBrandMutation(outcome);
  yield* context.recordAuditEvidence({ evidenceRefs: payload.evidenceRefs, reason: payload.reason });
  return result;
});

export const retireBrandAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.retire-brand.access.v1',
    },
    actionKey: 'commerce.catalog.retire-brand',
    auditEvidenceSchema: BrandAuditEvidenceSchema,
    auditProfile: 'standard',
    domainErrorSchema: BrandActionErrorSchema,
    domainEvents: {},
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'commerce.catalog.retire-brand',
      moduleKey: 'commerce.catalog',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: 'commerce.catalog',
    payloadSchema: RetireBrandPayloadSchema,
    policies: [],
    resultSchema: BrandMutationResultSchema,
    schemaVersion: '1',
  },
  handleRetireBrand,
  brandPersistenceServiceFactory,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
