// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug retire-product-category
import { Effect, Schema } from 'effect';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';

export const RetireProductCategoryPayloadSchema = Schema.Struct({});
export type RetireProductCategoryPayload = Schema.Schema.Type<typeof RetireProductCategoryPayloadSchema>;

export const RetireProductCategoryResultSchema = Schema.Struct({});
export type RetireProductCategoryResult = Schema.Schema.Type<typeof RetireProductCategoryResultSchema>;

export class RetireProductCategoryNotImplemented extends Schema.TaggedError<RetireProductCategoryNotImplemented>()(
  'RetireProductCategoryNotImplemented',
  {
    code: Schema.Literal('action_not_implemented'),
    reason: Schema.String,
  },
) {}

const handleRetireProductCategory = () =>
  Effect.fail(
    new RetireProductCategoryNotImplemented({
      code: 'action_not_implemented',
      reason: 'The Retire Product Category Action is not implemented',
    }),
  );

export const retireProductCategoryAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.retire-product-category.access.v1',
    },
    actionKey: 'commerce.catalog.retire-product-category',
    auditProfile: 'standard',
    domainErrorSchema: RetireProductCategoryNotImplemented,
    domainEvents: {},
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'commerce.catalog.retire-product-category',
      moduleKey: 'commerce.catalog',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: 'commerce.catalog',
    payloadSchema: RetireProductCategoryPayloadSchema,
    policies: [],
    resultSchema: RetireProductCategoryResultSchema,
    schemaVersion: '1',
  },
  handleRetireProductCategory,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
