// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug retire-package-definition
import type { ActionHandlerContext } from '@app/core-runtime';
import { Effect } from 'effect';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import {
  RetirePackageDefinitionPayloadSchema,
  RetirePackageDefinitionResultSchema,
} from '../../shared/actions/retire-package-definition.ts';
import type { RetirePackageDefinitionPayload } from '../../shared/actions/retire-package-definition.ts';
import {
  PackageDefinitionActionErrorSchema,
  PackageDefinitionActionError,
  PackageDefinitionAuditEvidenceSchema,
} from '../../shared/actions/package-definition-contract.ts';
import type { PackagePersistence } from '../persistence/package-persistence.ts';
import {
  mapPackagePersistenceError,
  packageDefinitionPersistenceServiceFactory,
  recordPackageDefinitionAccess,
  resolvePackageMutation,
} from './package-definition-action-support.ts';

export { RetirePackageDefinitionPayloadSchema } from '../../shared/actions/retire-package-definition.ts';
export type { RetirePackageDefinitionPayload } from '../../shared/actions/retire-package-definition.ts';

export const handleRetirePackageDefinition = Effect.fn('RetirePackageDefinitionAction.handle')(
  function* handleRetirePackageDefinition(
    payload: RetirePackageDefinitionPayload,
    context: ActionHandlerContext<Readonly<Record<string, never>>, PackagePersistence>,
  ) {
    if (payload.expectedCurrent.resourceRef.tenantId !== context.scope.tenantId) {
      return yield* new PackageDefinitionActionError({
        code: 'package_definition_invalid',
        reason: 'Package Definition must belong to the trusted Tenant',
      });
    }
    const outcome = yield* context.services
      .retire({ actionInvocationId: context.actionInvocationId, payload, principalId: context.scope.principalId })
      .pipe(Effect.mapError(mapPackagePersistenceError));
    const result = yield* resolvePackageMutation(outcome);
    yield* context.recordAuditEvidence({ evidenceRefs: payload.evidenceRefs, reason: payload.reason });
    yield* recordPackageDefinitionAccess(context, result.definitionRef.resourceId);
    return result;
  },
);

export const retirePackageDefinitionAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.retire-package-definition.access.v1',
    },
    actionKey: 'commerce.catalog.retire-package-definition',
    auditEvidenceSchema: PackageDefinitionAuditEvidenceSchema,
    auditProfile: 'standard',
    domainErrorSchema: PackageDefinitionActionErrorSchema,
    domainEvents: {},
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'tenant_membership_default' },
      entrypointKey: 'commerce.catalog.retire-package-definition',
      moduleKey: 'commerce.catalog',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: 'commerce.catalog',
    payloadSchema: RetirePackageDefinitionPayloadSchema,
    policies: [],
    resultSchema: RetirePackageDefinitionResultSchema,
    schemaVersion: '1',
  },
  handleRetirePackageDefinition,
  packageDefinitionPersistenceServiceFactory,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
