// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug revise-product-type
import { Effect, Schema } from 'effect';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import {
  ReviseProductTypePayloadSchema,
  ReviseProductTypeResultSchema,
} from '../../shared/actions/revise-product-type.ts';

export {
  ReviseProductTypePayloadSchema,
  ReviseProductTypeResultSchema,
} from '../../shared/actions/revise-product-type.ts';
export type { ReviseProductTypePayload, ReviseProductTypeResult } from '../../shared/actions/revise-product-type.ts';

/** Concurrent rule, population, or value change invalidates a prior impact review. */
export const ReviseProductTypeStaleBasisSchema = Schema.TaggedStruct('ReviseProductTypeStaleBasis', {
  code: Schema.Literal('product_type_stale_basis'),
  reason: Schema.String,
});
export type ReviseProductTypeStaleBasis = typeof ReviseProductTypeStaleBasisSchema.Type;

export class ReviseProductTypeNotImplemented extends Schema.TaggedError<ReviseProductTypeNotImplemented>()(
  'ReviseProductTypeNotImplemented',
  {
    code: Schema.Literal('action_not_implemented'),
    reason: Schema.String,
  },
) {}

const handleReviseProductType = () =>
  Effect.fail(
    new ReviseProductTypeNotImplemented({
      code: 'action_not_implemented',
      reason: 'The Revise Product Type Action is not implemented',
    }),
  );

export const reviseProductTypeAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.revise-product-type.access.v1',
    },
    actionKey: 'commerce.catalog.revise-product-type',
    auditProfile: 'standard',
    domainErrorSchema: Schema.Union([ReviseProductTypeNotImplemented, ReviseProductTypeStaleBasisSchema]),
    domainEvents: {},
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'commerce.catalog.revise-product-type',
      moduleKey: 'commerce.catalog',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: 'commerce.catalog',
    payloadSchema: ReviseProductTypePayloadSchema,
    policies: [],
    resultSchema: ReviseProductTypeResultSchema,
    schemaVersion: '1',
  },
  handleReviseProductType,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
