// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug revise-product-type
import type { ActionHandlerContext } from '@app/core-runtime';
import { Effect, Match, Schema } from 'effect';
import { ActionTransactionError, defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';

import {
  ReviseProductTypePayloadSchema,
  ReviseProductTypeResultSchema,
} from '../../shared/actions/revise-product-type.ts';
import type { ReviseProductTypePayload } from '../../shared/actions/revise-product-type.ts';
import type { CartOpenSelectionPopulationPort } from '../../shared/domain/catalog-open-selection-population.ts';
import { cartOpenSelectionPopulationFromEnvironment } from '../../shared/domain/catalog-open-selection-population.ts';
import { captureCatalogActionResult } from '../persistence/catalog-action-result-snapshot.ts';
import type { CatalogPersistenceConflict } from '../persistence/errors.ts';
import { CatalogPersistenceUnavailable } from '../persistence/errors.ts';
import {
  ProductTypeImpactBasisUnavailable,
  productTypeRevisePersistenceForScope,
} from '../persistence/product-type-revise-persistence.ts';
import type {
  ProductTypeRevisePersistence,
  ReviseProductTypePersistenceOutcome,
} from '../persistence/product-type-revise-persistence.ts';

export { ReviseProductTypePayloadSchema } from '../../shared/actions/revise-product-type.ts';

const ACTION_KEY = 'commerce.catalog.revise-product-type' as const;
const MODULE_KEY = 'commerce.catalog' as const;
const domainEvents = {} as const;

const mapCaptureError = (error: CatalogPersistenceConflict | CatalogPersistenceUnavailable): ActionTransactionError =>
  Object.assign(
    new ActionTransactionError({ code: 'action_transaction_failed', reason: 'Catalog result capture failed' }),
    { cause: error },
  );

/** Concurrent rule, population, value, or Cart owner evidence changes invalidate a prior review. */
export const ReviseProductTypeStaleBasisSchema = Schema.TaggedStruct('ReviseProductTypeStaleBasis', {
  code: Schema.Literal('product_type_stale_basis'),
  reason: Schema.String,
});

const staleBasis = (reason: string): typeof ReviseProductTypeStaleBasisSchema.Type =>
  ReviseProductTypeStaleBasisSchema.make({ code: 'product_type_stale_basis', reason });

export const reviseProductTypePersistenceServiceFactory = Effect.fn(
  'ReviseProductTypeAction.reviseProductTypePersistenceServiceFactory',
)(function* reviseProductTypePersistenceServiceFactory(
  transaction: Parameters<typeof productTypeRevisePersistenceForScope>[0],
  scope: Parameters<typeof productTypeRevisePersistenceForScope>[1],
  population?: CartOpenSelectionPopulationPort,
) {
  const configuredPopulation = population ?? (yield* cartOpenSelectionPopulationFromEnvironment);
  return yield* productTypeRevisePersistenceForScope(
    transaction,
    scope,
    configuredPopulation === undefined ? {} : { openSelections: configuredPopulation },
  );
});

export const handleReviseProductType = Effect.fn('ReviseProductTypeAction.handle')(function* handleReviseProductType(
  payload: ReviseProductTypePayload,
  context: ActionHandlerContext<typeof domainEvents, ProductTypeRevisePersistence>,
) {
  if (payload.productTypeRef.tenantId !== context.scope.tenantId) {
    return yield* Effect.fail(staleBasis('Product Type is outside the trusted Tenant'));
  }
  const outcome = yield* context.services.revise({
    actionInvocationId: context.actionInvocationId,
    effectiveFrom: payload.effectiveFrom,
    expectedCurrentRevision: payload.expectedCurrentRevision,
    impactBasisToken: payload.impactBasisToken,
    principalId: context.scope.principalId,
    productTypeRef: payload.productTypeRef,
    proposedRules: payload.proposedRules,
    unresolvedProductRefs: payload.unresolvedProductRefs,
  });
  const resolved = Match.value(outcome).pipe(
    Match.tag('not_found', () => Effect.fail(staleBasis('Product Type is absent from the trusted Tenant'))),
    Match.tag(
      'stale_basis',
      ({ reason }: Extract<ReviseProductTypePersistenceOutcome, { readonly _tag: 'stale_basis' }>) =>
        Effect.fail(staleBasis(reason)),
    ),
    Match.tag('revised', ({ result }: Extract<ReviseProductTypePersistenceOutcome, { readonly _tag: 'revised' }>) =>
      context
        .recordDataAccess({
          accessKind: 'read',
          queryHash: `catalog-product-type-revision:${payload.productTypeRef.resourceId}:${payload.expectedCurrentRevision}`,
          resultCount: 1,
          servingModuleKey: MODULE_KEY,
          targetModuleKey: MODULE_KEY,
          targetResourceId: payload.productTypeRef.resourceId,
          targetResourceType: 'commerce.catalog.product-type',
        })
        .pipe(Effect.as(result)),
    ),
    Match.exhaustive,
  );
  return yield* resolved;
});

export const reviseProductTypeAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.revise-product-type.access.v1',
    },
    actionKey: ACTION_KEY,
    auditProfile: 'standard',
    domainErrorSchema: Schema.Union([
      ReviseProductTypeStaleBasisSchema,
      ProductTypeImpactBasisUnavailable,
      CatalogPersistenceUnavailable,
    ]),
    domainEvents,
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: ACTION_KEY,
      moduleKey: MODULE_KEY,
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: MODULE_KEY,
    payloadSchema: ReviseProductTypePayloadSchema,
    policies: [],
    resultSchema: ReviseProductTypeResultSchema,
    schemaVersion: '1',
  },
  handleReviseProductType,
  (transaction, scope) =>
    reviseProductTypePersistenceServiceFactory(transaction, scope).pipe(
      Effect.map(
        (
          services,
        ): ProductTypeRevisePersistence & {
          captureResult: (
            actionInvocationId: string,
            result: typeof ReviseProductTypeResultSchema.Type,
          ) => Effect.Effect<void, ActionTransactionError>;
        } => ({
          ...services,
          captureResult: (actionInvocationId: string, result: typeof ReviseProductTypeResultSchema.Type) =>
            captureCatalogActionResult(
              transaction,
              scope,
              { actionInvocationId, actionKey: ACTION_KEY, schemaVersion: 1 },
              {
                decode: Schema.decodeUnknownEffect(ReviseProductTypeResultSchema),
                encode: Schema.encodeEffect(ReviseProductTypeResultSchema),
              },
              result,
            ).pipe(Effect.mapError(mapCaptureError)),
        }),
      ),
    ),
  ({ actionInvocationId, result, services }) => services.captureResult(actionInvocationId, result),
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
