// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug set-product-type
import type { ActionHandlerContext } from '@app/core-runtime';
import { Effect, Schema } from 'effect';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { SetProductTypePayloadSchema, SetProductTypeResultSchema } from '../../shared/actions/set-product-type.ts';
import type { SetProductTypePayload } from '../../shared/actions/set-product-type.ts';
import { ProductAuditEvidenceSchema } from '../../shared/domain/product.ts';
import { CatalogPersistenceUnavailable } from '../persistence/errors.ts';
import {
  ProductTypeAssignmentRejected,
  productTypeAssignmentPersistenceForScope,
} from '../persistence/product-type-assignment-persistence.ts';
import type { ProductTypeAssignmentPersistence } from '../persistence/product-type-assignment-persistence.ts';

export { SetProductTypePayloadSchema, SetProductTypeResultSchema } from '../../shared/actions/set-product-type.ts';
export type { SetProductTypePayload, SetProductTypeResult } from '../../shared/actions/set-product-type.ts';

const domainEvents = {} as const;
const moduleKey = 'commerce.catalog' as const;

export const handleSetProductType = Effect.fn('SetProductTypeAction.handle')(function* handleSetProductType(
  payload: SetProductTypePayload,
  context: ActionHandlerContext<typeof domainEvents, ProductTypeAssignmentPersistence>,
) {
  if (payload.productRef.tenantId !== context.scope.tenantId) {
    return yield* new ProductTypeAssignmentRejected({
      code: 'product_type_stale_impact_basis',
      reason: 'Product is outside the trusted Tenant',
    });
  }
  const input = {
    actionInvocationId: context.actionInvocationId,
    expectedProductRevision: payload.expectedProductRevision,
    impactBasis: payload.impactBasis,
    principalId: context.scope.principalId,
    productId: payload.productRef.resourceId,
    reason: payload.reason,
  };
  const result = yield* context.services.set(
    payload.nextProductTypeRef === undefined ? input : { ...input, nextProductTypeRef: payload.nextProductTypeRef },
  );
  yield* context.recordDataAccess({
    accessKind: 'read',
    queryHash: `catalog-product-type-assignment:${payload.productRef.resourceId}`,
    resultCount: 1,
    servingModuleKey: moduleKey,
    targetModuleKey: moduleKey,
    targetResourceId: payload.productRef.resourceId,
    targetResourceType: 'commerce.catalog.product',
  });
  if (payload.nextProductTypeRef !== undefined) {
    yield* context.recordDataAccess({
      accessKind: 'read',
      queryHash: `catalog-product-type:${payload.nextProductTypeRef.resourceId}`,
      resultCount: 1,
      servingModuleKey: moduleKey,
      targetModuleKey: moduleKey,
      targetResourceId: payload.nextProductTypeRef.resourceId,
      targetResourceType: 'commerce.catalog.product-type',
    });
  }
  yield* context.recordAuditEvidence({ reason: payload.reason });
  return result;
});

export const setProductTypeAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.set-product-type.access.v1',
    },
    actionKey: 'commerce.catalog.set-product-type',
    auditEvidenceSchema: ProductAuditEvidenceSchema,
    auditProfile: 'standard',
    domainErrorSchema: Schema.Union([ProductTypeAssignmentRejected, CatalogPersistenceUnavailable]),
    domainEvents,
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'commerce.catalog.set-product-type',
      moduleKey,
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: moduleKey,
    payloadSchema: SetProductTypePayloadSchema,
    policies: [],
    resultSchema: SetProductTypeResultSchema,
    schemaVersion: '1',
  },
  handleSetProductType,
  productTypeAssignmentPersistenceForScope,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
