// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug set-product-localized-facts
import type { ActionHandlerContext } from '@app/core-runtime';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { Effect } from 'effect';
import type { localizedProductFactsPersistenceForScope } from '../persistence/localized-product-facts-persistence.ts';

import {
  SetProductLocalizedFactsPayloadSchema,
  LocalizedFactsChangeResultSchema,
} from '../../shared/actions/localized-facts.ts';
import type { SetProductLocalizedFactsPayload } from '../../shared/actions/localized-facts.ts';
import {
  checkLocalizedRefs,
  LocalizedFactsActionErrorSchema,
  localizedFactsActionServiceFactory,
  localizedOutcome,
  ProductAuditEvidenceSchema,
  recordLocalizedAccess,
} from './localized-facts-action-support.ts';

export { SetProductLocalizedFactsPayloadSchema } from '../../shared/actions/localized-facts.ts';
export type { SetProductLocalizedFactsPayload } from '../../shared/actions/localized-facts.ts';

const handleSetProductLocalizedFacts = Effect.fn('SetProductLocalizedFactsAction.handle')(
  function* handleSetProductLocalizedFacts(
    payload: SetProductLocalizedFactsPayload,
    context: ActionHandlerContext<
      Readonly<Record<string, never>>,
      ReturnType<typeof localizedProductFactsPersistenceForScope>
    >,
  ) {
    yield* checkLocalizedRefs(context.scope.tenantId, payload.productRef);
    const outcome = yield* context.services.changeProduct({
      actionInvocationId: context.actionInvocationId,
      evidenceRefs: payload.evidenceRefs,
      expectedRevision: payload.expectedRevision,
      locale: payload.locale,
      principalId: context.scope.principalId,
      productRef: payload.productRef,
      reason: payload.reason,

      value: { facts: payload.facts, kind: 'SET' },
    });
    const result = yield* localizedOutcome(outcome);
    yield* context.recordAuditEvidence({ evidenceRefs: payload.evidenceRefs, reason: payload.reason });
    yield* recordLocalizedAccess(context, payload.productRef.resourceId, 'commerce.catalog.product');
    return result;
  },
);

export const setProductLocalizedFactsAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.set-product-localized-facts.access.v1',
    },
    actionKey: 'commerce.catalog.set-product-localized-facts',
    auditEvidenceSchema: ProductAuditEvidenceSchema,
    auditProfile: 'standard',
    domainErrorSchema: LocalizedFactsActionErrorSchema,
    domainEvents: {},
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'commerce.catalog.set-product-localized-facts',
      moduleKey: 'commerce.catalog',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: 'commerce.catalog',
    payloadSchema: SetProductLocalizedFactsPayloadSchema,
    policies: [],
    resultSchema: LocalizedFactsChangeResultSchema,
    schemaVersion: '1',
  },
  handleSetProductLocalizedFacts,
  localizedFactsActionServiceFactory,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
