// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug set-product-attribute-values
import type { ActionHandlerContext } from '@app/core-runtime';
import { captureCatalogActionResult } from '../persistence/catalog-action-result-snapshot.ts';
import { ActionTransactionError, defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { Effect, Schema } from 'effect';

import {
  SetProductAttributeValuesPayloadSchema,
  SetProductAttributeValuesResultSchema,
} from '../../shared/actions/attribute-value-mutations.ts';
import type { SetProductAttributeValuesPayload } from '../../shared/actions/attribute-value-mutations.ts';
import { ProductAuditEvidenceSchema } from '../../shared/domain/product.ts';
import {
  AttributeValuesConflict,
  attributeValuesPersistenceForScope,
} from '../persistence/attribute-values-persistence.ts';
import type { AttributeValuesPersistence } from '../persistence/attribute-values-persistence.ts';
import { CatalogPersistenceUnavailable } from '../persistence/errors.ts';

export {
  SetProductAttributeValuesPayloadSchema,
  SetProductAttributeValuesResultSchema,
} from '../../shared/actions/attribute-value-mutations.ts';
export type { SetProductAttributeValuesPayload } from '../../shared/actions/attribute-value-mutations.ts';

const CATALOG_MODULE_KEY = 'commerce.catalog' as const;
const domainEvents = {} as const;
export const handleSetProductAttributeValues = Effect.fn('SetProductAttributeValuesAction.handle')(
  function* handleSetProductAttributeValues(
    payload: SetProductAttributeValuesPayload,
    context: ActionHandlerContext<typeof domainEvents, AttributeValuesPersistence>,
  ) {
    const result = yield* context.services.setProductValues({
      ...payload,
      actionInvocationId: context.actionInvocationId,
      principalId: context.scope.principalId,
    });
    yield* context.recordDataAccess({
      accessKind: 'read',
      queryHash: `catalog-attribute-value:${payload.productRef.resourceId}:${payload.attributeDefinitionRef.resourceId}`,
      resultCount: 1,
      servingModuleKey: CATALOG_MODULE_KEY,
      targetModuleKey: CATALOG_MODULE_KEY,
      targetResourceId: payload.productRef.resourceId,
      targetResourceType: 'commerce.catalog.product',
    });
    yield* context.recordAuditEvidence({ reason: payload.reason });
    return yield* Schema.decodeEffect(SetProductAttributeValuesResultSchema)(result).pipe(
      Effect.mapError((cause) => {
        const failure = new CatalogPersistenceUnavailable({
          code: 'catalog_persistence_unavailable',
          reason: 'Catalog returned an invalid Action result',
        });
        Object.defineProperty(failure, 'cause', { configurable: true, value: cause });
        return failure;
      }),
    );
  },
);

const ACTION_KEY = 'commerce.catalog.set-product-attribute-values' as const;
const toSnapshotFailure = (cause: unknown): ActionTransactionError => {
  const failure = new ActionTransactionError({
    code: 'action_transaction_failed',
    reason: 'Catalog result capture failed',
  });
  Object.defineProperty(failure, 'cause', { configurable: true, value: cause });
  return failure;
};
export const setProductAttributeValuesAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.set-product-attribute-values.access.v1',
    },
    actionKey: ACTION_KEY,
    auditEvidenceSchema: ProductAuditEvidenceSchema,
    auditProfile: 'standard',
    domainErrorSchema: Schema.Union([AttributeValuesConflict, CatalogPersistenceUnavailable]),
    domainEvents,
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: ACTION_KEY,
      moduleKey: CATALOG_MODULE_KEY,
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: CATALOG_MODULE_KEY,
    payloadSchema: SetProductAttributeValuesPayloadSchema,
    policies: [],
    resultSchema: SetProductAttributeValuesResultSchema,
    schemaVersion: '1',
  },
  handleSetProductAttributeValues,
  (transaction, scope) =>
    attributeValuesPersistenceForScope(transaction, scope).pipe(
      Effect.map(
        (
          services,
        ): AttributeValuesPersistence & {
          captureResult: (
            actionInvocationId: string,
            result: typeof SetProductAttributeValuesResultSchema.Type,
          ) => Effect.Effect<void, ActionTransactionError>;
        } => ({
          ...services,
          captureResult: (actionInvocationId: string, result: typeof SetProductAttributeValuesResultSchema.Type) =>
            captureCatalogActionResult(
              transaction,
              scope,
              { actionInvocationId, actionKey: ACTION_KEY, schemaVersion: 1 },
              {
                decode: Schema.decodeUnknownEffect(SetProductAttributeValuesResultSchema),
                encode: Schema.encodeEffect(SetProductAttributeValuesResultSchema),
              },
              result,
            ).pipe(Effect.mapError(toSnapshotFailure)),
        }),
      ),
    ),
  ({ actionInvocationId, result, services }) => services.captureResult(actionInvocationId, result),
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
