// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug set-product-unit-target-divisibility
import type { ActionHandlerContext } from '@app/core-runtime';
import { Effect } from 'effect';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';

import {
  SetProductUnitTargetDivisibilityPayloadSchema,
  SetProductUnitTargetDivisibilityResultSchema,
} from '../../shared/actions/set-product-unit-target-divisibility.ts';
import type { SetProductUnitTargetDivisibilityPayload } from '../../shared/actions/set-product-unit-target-divisibility.ts';
import {
  ProductUnitActionError,
  ProductUnitActionErrorSchema,
  ProductUnitAuditEvidenceSchema,
} from '../../shared/actions/product-unit-contract.ts';
import type { ProductUnitPersistence } from '../persistence/product-unit-persistence.ts';
import {
  mapProductUnitPersistenceError,
  productUnitPersistenceServiceFactory,
  resolveProductUnitMutation,
} from './product-unit-action-support.ts';

export { SetProductUnitTargetDivisibilityPayloadSchema } from '../../shared/actions/set-product-unit-target-divisibility.ts';
export type { SetProductUnitTargetDivisibilityPayload } from '../../shared/actions/set-product-unit-target-divisibility.ts';

export const handleSetProductUnitTargetDivisibility = Effect.fn('SetProductUnitTargetDivisibilityAction.handle')(
  function* (
    payload: SetProductUnitTargetDivisibilityPayload,
    context: ActionHandlerContext<Readonly<Record<string, never>>, ProductUnitPersistence>,
  ) {
    if (payload.target.tenantId !== context.scope.tenantId || payload.target.unit.tenantId !== context.scope.tenantId) {
      return yield* new ProductUnitActionError({
        code: 'product_unit_invalid',
        reason: 'Target and Unit must belong to the trusted Tenant',
      });
    }
    const outcome = yield* context.services
      .setTargetDivisibility({
        actionInvocationId: context.actionInvocationId,
        payload,
        principalId: context.scope.principalId,
      })
      .pipe(Effect.mapError(mapProductUnitPersistenceError));
    const result = yield* resolveProductUnitMutation(outcome);
    yield* context.recordAuditEvidence({ evidenceRefs: payload.evidenceRefs, reason: payload.reason });
    return result;
  },
);

export const setProductUnitTargetDivisibilityAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.set-product-unit-target-divisibility.access.v1',
    },
    actionKey: 'commerce.catalog.set-product-unit-target-divisibility',
    auditEvidenceSchema: ProductUnitAuditEvidenceSchema,
    auditProfile: 'standard',
    domainErrorSchema: ProductUnitActionErrorSchema,
    domainEvents: {},
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'commerce.catalog.set-product-unit-target-divisibility',
      moduleKey: 'commerce.catalog',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: 'commerce.catalog',
    payloadSchema: SetProductUnitTargetDivisibilityPayloadSchema,
    policies: [],
    resultSchema: SetProductUnitTargetDivisibilityResultSchema,
    schemaVersion: '1',
  },
  handleSetProductUnitTargetDivisibility,
  productUnitPersistenceServiceFactory,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
