// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug set-product-type
import { Effect, Schema } from 'effect';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { ProductRefSchema } from '../../shared/resources/product.ts';
import { ProductTypeRefSchema } from '../../shared/resources/product-type.ts';
import { ProductRevisionSchema, ProductReasonSchema } from '../../shared/domain/product.ts';

/** The preview token binds the exact inspected population and Current values. */
export const SetProductTypePayloadSchema = Schema.Struct({
  expectedProductRevision: ProductRevisionSchema,
  impactBasis: Schema.Trim.check(Schema.isMinLength(1), Schema.isMaxLength(300)),
  nextProductTypeRef: Schema.optionalKey(ProductTypeRefSchema),
  productRef: ProductRefSchema,
  reason: ProductReasonSchema,
}).check(
  Schema.makeFilter(({ nextProductTypeRef, productRef }) =>
    nextProductTypeRef === undefined || nextProductTypeRef.tenantId === productRef.tenantId
      ? undefined
      : 'Product and next Product Type must belong to the same Tenant',
  ),
);
export type SetProductTypePayload = Schema.Schema.Type<typeof SetProductTypePayloadSchema>;

export const SetProductTypeResultSchema = Schema.Struct({
  currentProductTypeRef: Schema.optionalKey(ProductTypeRefSchema),
  productRef: ProductRefSchema,
  revision: ProductRevisionSchema,
  unresolvedProductRefs: Schema.Array(ProductRefSchema),
});
export type SetProductTypeResult = Schema.Schema.Type<typeof SetProductTypeResultSchema>;

export class SetProductTypeFailure extends Schema.TaggedError<SetProductTypeFailure>()('SetProductTypeFailure', {
  code: Schema.Literals(['action_not_implemented', 'product_type_stale_impact_basis']),
  reason: Schema.String,
}) {}

const handleSetProductType = () =>
  Effect.fail(
    new SetProductTypeFailure({
      code: 'action_not_implemented',
      reason: 'The Set Product Type Action is not implemented',
    }),
  );

export const setProductTypeAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.set-product-type.access.v1',
    },
    actionKey: 'commerce.catalog.set-product-type',
    auditProfile: 'standard',
    domainErrorSchema: SetProductTypeFailure,
    domainEvents: {},
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'commerce.catalog.set-product-type',
      moduleKey: 'commerce.catalog',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: 'commerce.catalog',
    payloadSchema: SetProductTypePayloadSchema,
    policies: [],
    resultSchema: SetProductTypeResultSchema,
    schemaVersion: '1',
  },
  handleSetProductType,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
