// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug set-product-manufacturer
import { Effect, Match, Schema } from 'effect';
import type { ActionHandlerContext } from '@app/core-runtime';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { ProductAuditEvidenceSchema } from '../../shared/domain/product.ts';
import {
  SetProductManufacturerPayloadSchema,
  ManufacturerActionError,
  ProductManufacturerMutationResultSchema,
} from '../../shared/actions/manufacturer-mutations.ts';
import type { SetProductManufacturerPayload } from '../../shared/actions/manufacturer-mutations.ts';
import {
  ManufacturerPersistenceUnavailable,
  manufacturerPersistenceForScope,
} from '../persistence/manufacturer-persistence.ts';
import type { ManufacturerPersistence } from '../persistence/manufacturer-persistence.ts';
import { ManufacturerTargetForbidden } from '../persistence/manufacturer-target-forbidden.ts';

export { SetProductManufacturerPayloadSchema } from '../../shared/actions/manufacturer-mutations.ts';
export type { SetProductManufacturerPayload } from '../../shared/actions/manufacturer-mutations.ts';

export const SetProductManufacturerResultSchema = ProductManufacturerMutationResultSchema;
export type SetProductManufacturerResult = Schema.Schema.Type<typeof SetProductManufacturerResultSchema>;
const CATALOG_MODULE_KEY = 'commerce.catalog';

export const handleSetProductManufacturer = Effect.fn('SetProductManufacturerAction.handle')(
  function* handleSetProductManufacturer(
    payload: SetProductManufacturerPayload,
    context: ActionHandlerContext<Readonly<Record<string, never>>, ManufacturerPersistence>,
  ) {
    if (payload.subject.tenantId !== context.scope.tenantId) {
      return yield* new ManufacturerActionError({
        code: 'manufacturer_invalid',
        reason: 'Manufacturer relation subject must belong to the trusted Tenant',
      });
    }
    const outcome = yield* context.services.set({
      actionInvocationId: context.actionInvocationId,
      payload,
      principalId: context.scope.principalId,
    });
    const applied = yield* Match.value(outcome).pipe(
      Match.tag('applied', (value) => Effect.succeed(value)),
      Match.tag('not_found', () =>
        Effect.fail(new ManufacturerActionError({ code: 'manufacturer_not_found', reason: 'not_found' })),
      ),
      Match.tag('invalid_change', () =>
        Effect.fail(new ManufacturerActionError({ code: 'manufacturer_invalid', reason: 'invalid_change' })),
      ),
      Match.tag('revision_conflict', () =>
        Effect.fail(new ManufacturerActionError({ code: 'manufacturer_conflict', reason: 'revision_conflict' })),
      ),
      Match.tag('identity_conflict', () =>
        Effect.fail(new ManufacturerActionError({ code: 'manufacturer_conflict', reason: 'identity_conflict' })),
      ),
      Match.exhaustive,
    );
    yield* context.recordAuditEvidence({ evidenceRefs: payload.evidenceRefs, reason: payload.reason });
    yield* context.recordDataAccess({
      accessKind: 'read',
      queryHash: `catalog-manufacturer-subject:${payload.subject.resourceType}:${payload.subject.resourceId}`,
      resultCount: 1,
      servingModuleKey: CATALOG_MODULE_KEY,
      targetModuleKey: CATALOG_MODULE_KEY,
      targetResourceId: payload.subject.resourceId,
      targetResourceType: payload.subject.resourceType,
    });
    return { relationId: applied.relationId, revision: applied.revision, subject: payload.subject };
  },
);

export const setProductManufacturerAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.set-product-manufacturer.access.v1',
    },
    actionKey: 'commerce.catalog.set-product-manufacturer',
    auditEvidenceSchema: ProductAuditEvidenceSchema,
    auditProfile: 'standard',
    domainErrorSchema: Schema.Union([
      ManufacturerActionError,
      ManufacturerPersistenceUnavailable,
      ManufacturerTargetForbidden,
    ]),
    domainEvents: {},
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'commerce.catalog.set-product-manufacturer',
      moduleKey: CATALOG_MODULE_KEY,
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: CATALOG_MODULE_KEY,
    payloadSchema: SetProductManufacturerPayloadSchema,
    policies: [],
    resultSchema: SetProductManufacturerResultSchema,
    schemaVersion: '1',
  },
  handleSetProductManufacturer,
  (...args: Parameters<typeof manufacturerPersistenceForScope>) =>
    Effect.succeed(manufacturerPersistenceForScope(...args)),
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
