// @generated by OntOS Codesmith Resource v1
// @ontos-resource-owner job.expenses
// @ontos-resource-slug job-expense
import type { OntosResourceType } from '@app/core-runtime';
import { ServiceJobRefSchema } from '@app/service-jobs/resources/service-job';
import { DateTime, Option, Schema, SchemaGetter } from 'effect';

const ResourceIdSchema = Schema.String.check(Schema.isUUID()).pipe(Schema.brand('JobExpenseResourceId'));
const TenantIdSchema = Schema.String.check(Schema.isUUID()).pipe(Schema.brand('TenantId'));

export const JobExpenseRefSchema = Schema.Struct({
  moduleId: Schema.Literal('job.expenses'),
  resourceId: ResourceIdSchema,
  resourceType: Schema.Literal('job.expenses.job-expense'),
  tenantId: TenantIdSchema,
});
export type JobExpenseRef = typeof JobExpenseRefSchema.Type;

export const jobExpenseResourceDescriptor = {
  capabilities: {
    graphVisible: false,
    linkable: false,
    mediaAttachable: false,
    searchable: false,
    timelineVisible: false,
  },
  description: 'A manually recorded operating cost for one Service Job.',
  key: 'job.expenses.job-expense',
  label: 'Job expense',
  owningModuleId: 'job.expenses',
} as const satisfies OntosResourceType;

export const JobExpenseIdSchema = ResourceIdSchema;
export const JobExpenseCategorySchema = Schema.Literals(['WORK', 'TRANSPORT', 'DISPOSAL', 'MATERIAL', 'OTHER']);
export const JobExpenseStatusSchema = Schema.Literals(['RECORDED', 'VOIDED']);
export const JobExpenseDescriptionSchema = Schema.String.check(
  Schema.isMaxLength(500),
  Schema.makeFilter((value) => value.trim().length > 0),
);
export const JobExpenseReasonSchema = Schema.String.check(
  Schema.isMaxLength(500),
  Schema.makeFilter((value) => value.trim().length > 0),
);
const CalendarDateCodec = Schema.String.pipe(
  Schema.check(
    Schema.isPattern(/^\d{4}-\d{2}-\d{2}$/u),
    Schema.makeFilter((value) => {
      const date = DateTime.make(`${value}T00:00:00.000Z`);
      return Option.isSome(date) && DateTime.formatIsoDateUtc(date.value) === value;
    }),
  ),
  Schema.decodeTo(Schema.toType(Schema.DateTimeUtc), {
    decode: SchemaGetter.transform((value) => DateTime.makeUnsafe(`${value}T00:00:00.000Z`)),
    encode: SchemaGetter.transform(DateTime.formatIsoDateUtc),
  }),
);
export const CalendarDateSchema = Schema.toEncoded(CalendarDateCodec);
export const JobExpenseAmountCzkSchema = Schema.String.check(
  Schema.isPattern(/^(?:0\.0[1-9]|0\.[1-9]\d|[1-9]\d{0,11}\.\d{2})$/u),
);
/** Aggregate values may exceed one row's 12 integer digits and may be signed. */
export const MoneyTotalCzkSchema = Schema.String.check(Schema.isPattern(/^-?(?:0|[1-9]\d*)\.\d{2}$/u));
export const MarginPercentSchema = Schema.String.check(Schema.isPattern(/^-?(?:0|[1-9]\d*)\.\d{2}$/u));

export const JobExpenseInputSchema = Schema.Struct({
  amountCzk: JobExpenseAmountCzkSchema,
  category: JobExpenseCategorySchema,
  description: JobExpenseDescriptionSchema,
  incurredOn: CalendarDateSchema,
});

export const JobExpenseSchema = Schema.Struct({
  ...JobExpenseInputSchema.fields,
  costBasis: Schema.Literal('EXCLUDING_VAT'),
  createdAt: Schema.DateTimeUtcFromString,
  currency: Schema.Literal('CZK'),
  legalEntityId: Schema.String.check(Schema.isUUID()).pipe(Schema.brand('LegalEntityId')),
  ref: JobExpenseRefSchema,
  revision: Schema.Int.check(Schema.isGreaterThanOrEqualTo(1)),
  serviceJobRef: ServiceJobRefSchema,
  status: JobExpenseStatusSchema,
  updatedAt: Schema.DateTimeUtcFromString,
  voidedAt: Schema.OptionFromNullOr(Schema.DateTimeUtcFromString),
  voidReason: Schema.OptionFromNullOr(JobExpenseReasonSchema),
}).check(
  Schema.makeFilter(
    (value) =>
      (value.status === 'RECORDED' && Option.isNone(value.voidedAt) && Option.isNone(value.voidReason)) ||
      (value.status === 'VOIDED' && Option.isSome(value.voidedAt) && Option.isSome(value.voidReason)),
  ),
);
export type JobExpense = typeof JobExpenseSchema.Type;

export { JobExpenseRejected, JobExpenseUnavailable } from './job-expense-failure.ts';
