// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner workforce.planning
// @ontos-action-http-slug assign-worker
// oxlint-disable sonarjs/function-name -- Effect Match.tags requires owner-declared tag keys; remove-when: sonarjs accepts discriminant-map properties.
import type { ActionCoreError } from '@app/core-runtime';
import { Effect, HttpApiMiddleware } from '@modern-js/bff-effect/effect-edge';
import { Match, Schema } from 'effect';
import {
  AssignWorkerActionAlreadyCommittedProblemSchema,
  AssignWorkerActionAuthenticationProblemSchema,
  AssignWorkerActionCommitIndeterminateProblemSchema,
  AssignWorkerActionConflictProblemSchema,
  AssignWorkerActionForbiddenProblemSchema,
  AssignWorkerActionIneligibleProblemSchema,
  AssignWorkerActionInternalProblemSchema,
  AssignWorkerActionInvalidProblemSchema,
  AssignWorkerActionNotFoundProblemSchema,
  AssignWorkerActionPreconditionProblemSchema,
  AssignWorkerActionSchemaErrorMiddleware,
  AssignWorkerActionUnavailableProblemSchema,
} from '../shared/apis/assign-worker-action.ts';
import type { AssignWorkerActionProblem } from '../shared/apis/assign-worker-action.ts';
import { assignWorkerAction } from '../src/actions/assign-worker.action.ts';

type DomainError = typeof assignWorkerAction.descriptor.domainErrorSchema.Type;
type ProblemOf<Tag extends AssignWorkerActionProblem['_tag']> = Extract<
  AssignWorkerActionProblem,
  { readonly _tag: Tag }
>;
type DomainProblemIdentity =
  | { readonly code: 'job_conflict' | 'revision_conflict'; readonly kind: 'conflict' }
  | { readonly code: 'scope_mismatch'; readonly kind: 'forbidden' }
  | {
      readonly code:
        | 'absence_blocked'
        | 'crew_locked'
        | 'invalid_absence'
        | 'invalid_job'
        | 'invalid_worker'
        | 'outside_agreement'
        | 'worker_inactive';
      readonly kind: 'ineligible';
    }
  | { readonly code: 'not_found'; readonly kind: 'notFound' }
  | { readonly code: 'workforce_unavailable'; readonly kind: 'unavailable' };

const problemStatus = {
  authentication: 401,
  conflict: 409,
  forbidden: 403,
  ineligible: 422,
  internal: 500,
  invalid: 400,
  notFound: 404,
  precondition: 428,
  rateLimited: 429,
  timeout: 504,
  unavailable: 503,
} as const;

const workforceRejectedProblemByCode = {
  absence_blocked: { code: 'absence_blocked', kind: 'ineligible' },
  crew_locked: { code: 'crew_locked', kind: 'ineligible' },
  invalid_absence: { code: 'invalid_absence', kind: 'ineligible' },
  invalid_job: { code: 'invalid_job', kind: 'ineligible' },
  invalid_worker: { code: 'invalid_worker', kind: 'ineligible' },
  job_conflict: { code: 'job_conflict', kind: 'conflict' },
  not_found: { code: 'not_found', kind: 'notFound' },
  outside_agreement: { code: 'outside_agreement', kind: 'ineligible' },
  revision_conflict: { code: 'revision_conflict', kind: 'conflict' },
  scope_mismatch: { code: 'scope_mismatch', kind: 'forbidden' },
  worker_inactive: { code: 'worker_inactive', kind: 'ineligible' },
} as const satisfies Record<
  Extract<DomainError, { readonly _tag: 'WorkforceRejected' }>['code'],
  DomainProblemIdentity
>;

export const assignWorkerActionProblem = {
  authentication: (): ProblemOf<'AssignWorkerActionAuthenticationProblem'> =>
    AssignWorkerActionAuthenticationProblemSchema.make({
      detail: 'A valid audience-scoped Bearer assertion is required.',
      status: problemStatus.authentication,
      title: 'Authentication required',
      type: 'https://ontos.dev/problems/operation-authentication-required',
    }),
  conflict: (
    code: ProblemOf<'AssignWorkerActionConflictProblem'>['code'],
  ): ProblemOf<'AssignWorkerActionConflictProblem'> =>
    AssignWorkerActionConflictProblemSchema.make({
      code,
      detail: 'The Action conflicts with current state.',
      status: problemStatus.conflict,
      title: 'Action conflict',
      type: 'https://ontos.dev/problems/action-conflict',
    }),
  forbidden: (
    code: ProblemOf<'AssignWorkerActionForbiddenProblem'>['code'],
  ): ProblemOf<'AssignWorkerActionForbiddenProblem'> =>
    AssignWorkerActionForbiddenProblemSchema.make({
      code,
      detail: 'The principal is not permitted to perform this Action.',
      status: problemStatus.forbidden,
      title: 'Action forbidden',
      type: 'https://ontos.dev/problems/action-forbidden',
    }),
  ineligible: (
    code: ProblemOf<'AssignWorkerActionIneligibleProblem'>['code'],
  ): ProblemOf<'AssignWorkerActionIneligibleProblem'> =>
    AssignWorkerActionIneligibleProblemSchema.make({
      code,
      detail: 'The request is not eligible for this Action.',
      status: problemStatus.ineligible,
      title: 'Action ineligible',
      type: 'https://ontos.dev/problems/action-ineligible',
    }),
  internal: (): ProblemOf<'AssignWorkerActionInternalProblem'> =>
    AssignWorkerActionInternalProblemSchema.make({
      detail: 'The Action could not be completed.',
      status: problemStatus.internal,
      title: 'Action failed',
      type: 'https://ontos.dev/problems/action-failed',
    }),
  invalid: (): ProblemOf<'AssignWorkerActionInvalidProblem'> =>
    AssignWorkerActionInvalidProblemSchema.make({
      detail: 'The assign-worker Action request is invalid.',
      status: problemStatus.invalid,
      title: 'Invalid Action request',
      type: 'https://ontos.dev/problems/action-invalid',
    }),
  notFound: (
    code: ProblemOf<'AssignWorkerActionNotFoundProblem'>['code'],
  ): ProblemOf<'AssignWorkerActionNotFoundProblem'> =>
    AssignWorkerActionNotFoundProblemSchema.make({
      code,
      detail: 'The requested resource was not found.',
      status: problemStatus.notFound,
      title: 'Resource not found',
      type: 'https://ontos.dev/problems/action-resource-not-found',
    }),
  precondition: (): ProblemOf<'AssignWorkerActionPreconditionProblem'> =>
    AssignWorkerActionPreconditionProblemSchema.make({
      detail: 'An Idempotency-Key header is required.',
      status: problemStatus.precondition,
      title: 'Idempotency key required',
      type: 'https://ontos.dev/problems/idempotency-key-required',
    }),
  unavailable: (
    code: ProblemOf<'AssignWorkerActionUnavailableProblem'>['code'],
  ): ProblemOf<'AssignWorkerActionUnavailableProblem'> =>
    AssignWorkerActionUnavailableProblemSchema.make({
      code,
      detail: 'The Action capability is temporarily unavailable.',
      retryable: true,
      status: problemStatus.unavailable,
      title: 'Action unavailable',
      type: 'https://ontos.dev/problems/action-unavailable',
    }),
} as const;

const mapDomainIdentity = (identity: DomainProblemIdentity): AssignWorkerActionProblem =>
  Match.value(identity).pipe(
    Match.when({ kind: 'conflict' as const }, (matched) => assignWorkerActionProblem.conflict(matched.code)),
    Match.when({ kind: 'forbidden' as const }, (matched) => assignWorkerActionProblem.forbidden(matched.code)),
    Match.when({ kind: 'ineligible' as const }, (matched) => assignWorkerActionProblem.ineligible(matched.code)),
    Match.when({ kind: 'notFound' as const }, (matched) => assignWorkerActionProblem.notFound(matched.code)),
    Match.when({ kind: 'unavailable' as const }, (matched) => assignWorkerActionProblem.unavailable(matched.code)),
    Match.exhaustive,
  );

const mapDomainProblem = (error: DomainError): AssignWorkerActionProblem =>
  Match.value(error).pipe(
    Match.tags({
      WorkforceRejected: (failure) => mapDomainIdentity(workforceRejectedProblemByCode[failure.code]),
      WorkforceUnavailable: () => assignWorkerActionProblem.unavailable('workforce_unavailable'),
    }),
    Match.exhaustive,
  );

const mapCoreProblem = (error: ActionCoreError): AssignWorkerActionProblem =>
  Match.value(error).pipe(
    Match.tags({
      ActionAlreadyCommitted: (failure) =>
        AssignWorkerActionAlreadyCommittedProblemSchema.make({
          code: failure.code,
          detail: 'This Action is already committed. Refresh governed reads.',
          invocationId: failure.invocationId,
          resolution: 'REFRESH_GOVERNED_READS',
          retryCommand: false,
          status: problemStatus.conflict,
          title: 'Action already committed',
          type: 'https://ontos.dev/problems/action-already-committed',
        }),
      ActionCollectorError: assignWorkerActionProblem.internal,
      ActionCommitIndeterminate: (failure) =>
        AssignWorkerActionCommitIndeterminateProblemSchema.make({
          detail: 'The Action commit is uncertain. Resolve this invocation before another attempt.',
          invocationId: failure.invocationId,
          resolution: 'RESOLVE_COMMIT',
          retryCommand: false,
          status: problemStatus.unavailable,
          title: 'Action commit uncertain',
          type: 'https://ontos.dev/problems/action-commit-indeterminate',
        }),
      ActionHandlerExecutionError: assignWorkerActionProblem.internal,
      ActionIdempotencyKeyRequired: assignWorkerActionProblem.precondition,
      ActionInvocationNotFound: (failure) => assignWorkerActionProblem.notFound(failure.code),
      ActionInvocationPersistenceError: (failure) => assignWorkerActionProblem.unavailable(failure.code),
      ActionInvocationStateError: (failure) => assignWorkerActionProblem.conflict(failure.code),
      ActionPayloadValidationError: assignWorkerActionProblem.invalid,
      ActionPermissionCheckError: (failure) => assignWorkerActionProblem.unavailable(failure.code),
      ActionPermissionDenied: (failure) => assignWorkerActionProblem.forbidden(failure.code),
      ActionPolicyDenied: (failure) => assignWorkerActionProblem.ineligible(failure.code),
      ActionPolicyEvaluationError: (failure) => assignWorkerActionProblem.unavailable(failure.code),
      ActionRequestHashConflict: (failure) => assignWorkerActionProblem.conflict(failure.code),
      ActionResultValidationError: assignWorkerActionProblem.internal,
      ActionTransactionError: (failure) => assignWorkerActionProblem.unavailable(failure.code),
      ActionTrustedContextValidationError: assignWorkerActionProblem.authentication,
      ModuleStateCheckUnavailableError: (failure) => assignWorkerActionProblem.unavailable(failure.code),
      ModuleStateDeniedError: (failure) => assignWorkerActionProblem.forbidden(failure.code),
      OperationAuthenticationRequired: assignWorkerActionProblem.authentication,
      OperationContextDenied: (failure) => assignWorkerActionProblem.forbidden(failure.code),
      OperationContextInvalid: (failure) => assignWorkerActionProblem.forbidden(failure.code),
      OperationContextUnavailable: (failure) => assignWorkerActionProblem.unavailable(failure.code),
    }),
    Match.exhaustive,
  );

const isDomainError = Schema.is(assignWorkerAction.descriptor.domainErrorSchema);
export const mapAssignWorkerActionProblem = (error: ActionCoreError | DomainError): AssignWorkerActionProblem =>
  isDomainError(error) ? mapDomainProblem(error) : mapCoreProblem(error);

export const assignWorkerActionSchemaErrorLive = HttpApiMiddleware.layerSchemaErrorTransform(
  AssignWorkerActionSchemaErrorMiddleware,
  () => Effect.fail(assignWorkerActionProblem.invalid()),
);
