// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner workforce.planning
// @ontos-action-http-slug change-worker-status
// oxlint-disable sonarjs/function-name -- Effect Match.tags requires owner-declared tag keys; remove-when: sonarjs accepts discriminant-map properties.
import type { ActionCoreError } from '@app/core-runtime';
import { Effect, HttpApiMiddleware } from '@modern-js/bff-effect/effect-edge';
import { Match, Schema } from 'effect';
import {
  ChangeWorkerStatusActionAlreadyCommittedProblemSchema,
  ChangeWorkerStatusActionAuthenticationProblemSchema,
  ChangeWorkerStatusActionCommitIndeterminateProblemSchema,
  ChangeWorkerStatusActionConflictProblemSchema,
  ChangeWorkerStatusActionForbiddenProblemSchema,
  ChangeWorkerStatusActionIneligibleProblemSchema,
  ChangeWorkerStatusActionInternalProblemSchema,
  ChangeWorkerStatusActionInvalidProblemSchema,
  ChangeWorkerStatusActionNotFoundProblemSchema,
  ChangeWorkerStatusActionPreconditionProblemSchema,
  ChangeWorkerStatusActionSchemaErrorMiddleware,
  ChangeWorkerStatusActionUnavailableProblemSchema,
} from '../shared/apis/change-worker-status-action.ts';
import type { ChangeWorkerStatusActionProblem } from '../shared/apis/change-worker-status-action.ts';
import { changeWorkerStatusAction } from '../src/actions/change-worker-status.action.ts';

type DomainError = typeof changeWorkerStatusAction.descriptor.domainErrorSchema.Type;
type ProblemOf<Tag extends ChangeWorkerStatusActionProblem['_tag']> = Extract<
  ChangeWorkerStatusActionProblem,
  { readonly _tag: Tag }
>;
type DomainProblemIdentity =
  | { readonly code: 'job_conflict' | 'revision_conflict'; readonly kind: 'conflict' }
  | { readonly code: 'scope_mismatch'; readonly kind: 'forbidden' }
  | {
      readonly code:
        | 'absence_blocked'
        | 'crew_locked'
        | 'invalid_absence'
        | 'invalid_job'
        | 'invalid_worker'
        | 'outside_agreement'
        | 'worker_inactive';
      readonly kind: 'ineligible';
    }
  | { readonly code: 'not_found'; readonly kind: 'notFound' }
  | { readonly code: 'workforce_unavailable'; readonly kind: 'unavailable' };

const problemStatus = {
  authentication: 401,
  conflict: 409,
  forbidden: 403,
  ineligible: 422,
  internal: 500,
  invalid: 400,
  notFound: 404,
  precondition: 428,
  rateLimited: 429,
  timeout: 504,
  unavailable: 503,
} as const;

const workforceRejectedProblemByCode = {
  absence_blocked: { code: 'absence_blocked', kind: 'ineligible' },
  crew_locked: { code: 'crew_locked', kind: 'ineligible' },
  invalid_absence: { code: 'invalid_absence', kind: 'ineligible' },
  invalid_job: { code: 'invalid_job', kind: 'ineligible' },
  invalid_worker: { code: 'invalid_worker', kind: 'ineligible' },
  job_conflict: { code: 'job_conflict', kind: 'conflict' },
  not_found: { code: 'not_found', kind: 'notFound' },
  outside_agreement: { code: 'outside_agreement', kind: 'ineligible' },
  revision_conflict: { code: 'revision_conflict', kind: 'conflict' },
  scope_mismatch: { code: 'scope_mismatch', kind: 'forbidden' },
  worker_inactive: { code: 'worker_inactive', kind: 'ineligible' },
} as const satisfies Record<
  Extract<DomainError, { readonly _tag: 'WorkforceRejected' }>['code'],
  DomainProblemIdentity
>;

export const changeWorkerStatusActionProblem = {
  authentication: (): ProblemOf<'ChangeWorkerStatusActionAuthenticationProblem'> =>
    ChangeWorkerStatusActionAuthenticationProblemSchema.make({
      detail: 'A valid audience-scoped Bearer assertion is required.',
      status: problemStatus.authentication,
      title: 'Authentication required',
      type: 'https://ontos.dev/problems/operation-authentication-required',
    }),
  conflict: (
    code: ProblemOf<'ChangeWorkerStatusActionConflictProblem'>['code'],
  ): ProblemOf<'ChangeWorkerStatusActionConflictProblem'> =>
    ChangeWorkerStatusActionConflictProblemSchema.make({
      code,
      detail: 'The Action conflicts with current state.',
      status: problemStatus.conflict,
      title: 'Action conflict',
      type: 'https://ontos.dev/problems/action-conflict',
    }),
  forbidden: (
    code: ProblemOf<'ChangeWorkerStatusActionForbiddenProblem'>['code'],
  ): ProblemOf<'ChangeWorkerStatusActionForbiddenProblem'> =>
    ChangeWorkerStatusActionForbiddenProblemSchema.make({
      code,
      detail: 'The principal is not permitted to perform this Action.',
      status: problemStatus.forbidden,
      title: 'Action forbidden',
      type: 'https://ontos.dev/problems/action-forbidden',
    }),
  ineligible: (
    code: ProblemOf<'ChangeWorkerStatusActionIneligibleProblem'>['code'],
  ): ProblemOf<'ChangeWorkerStatusActionIneligibleProblem'> =>
    ChangeWorkerStatusActionIneligibleProblemSchema.make({
      code,
      detail: 'The request is not eligible for this Action.',
      status: problemStatus.ineligible,
      title: 'Action ineligible',
      type: 'https://ontos.dev/problems/action-ineligible',
    }),
  internal: (): ProblemOf<'ChangeWorkerStatusActionInternalProblem'> =>
    ChangeWorkerStatusActionInternalProblemSchema.make({
      detail: 'The Action could not be completed.',
      status: problemStatus.internal,
      title: 'Action failed',
      type: 'https://ontos.dev/problems/action-failed',
    }),
  invalid: (): ProblemOf<'ChangeWorkerStatusActionInvalidProblem'> =>
    ChangeWorkerStatusActionInvalidProblemSchema.make({
      detail: 'The change-worker-status Action request is invalid.',
      status: problemStatus.invalid,
      title: 'Invalid Action request',
      type: 'https://ontos.dev/problems/action-invalid',
    }),
  notFound: (
    code: ProblemOf<'ChangeWorkerStatusActionNotFoundProblem'>['code'],
  ): ProblemOf<'ChangeWorkerStatusActionNotFoundProblem'> =>
    ChangeWorkerStatusActionNotFoundProblemSchema.make({
      code,
      detail: 'The requested resource was not found.',
      status: problemStatus.notFound,
      title: 'Resource not found',
      type: 'https://ontos.dev/problems/action-resource-not-found',
    }),
  precondition: (): ProblemOf<'ChangeWorkerStatusActionPreconditionProblem'> =>
    ChangeWorkerStatusActionPreconditionProblemSchema.make({
      detail: 'An Idempotency-Key header is required.',
      status: problemStatus.precondition,
      title: 'Idempotency key required',
      type: 'https://ontos.dev/problems/idempotency-key-required',
    }),
  unavailable: (
    code: ProblemOf<'ChangeWorkerStatusActionUnavailableProblem'>['code'],
  ): ProblemOf<'ChangeWorkerStatusActionUnavailableProblem'> =>
    ChangeWorkerStatusActionUnavailableProblemSchema.make({
      code,
      detail: 'The Action capability is temporarily unavailable.',
      retryable: true,
      status: problemStatus.unavailable,
      title: 'Action unavailable',
      type: 'https://ontos.dev/problems/action-unavailable',
    }),
} as const;

const mapDomainIdentity = (identity: DomainProblemIdentity): ChangeWorkerStatusActionProblem =>
  Match.value(identity).pipe(
    Match.when({ kind: 'conflict' as const }, (matched) => changeWorkerStatusActionProblem.conflict(matched.code)),
    Match.when({ kind: 'forbidden' as const }, (matched) => changeWorkerStatusActionProblem.forbidden(matched.code)),
    Match.when({ kind: 'ineligible' as const }, (matched) => changeWorkerStatusActionProblem.ineligible(matched.code)),
    Match.when({ kind: 'notFound' as const }, (matched) => changeWorkerStatusActionProblem.notFound(matched.code)),
    Match.when({ kind: 'unavailable' as const }, (matched) =>
      changeWorkerStatusActionProblem.unavailable(matched.code),
    ),
    Match.exhaustive,
  );

const mapDomainProblem = (error: DomainError): ChangeWorkerStatusActionProblem =>
  Match.value(error).pipe(
    Match.tags({
      WorkforceRejected: (failure) => mapDomainIdentity(workforceRejectedProblemByCode[failure.code]),
      WorkforceUnavailable: () => changeWorkerStatusActionProblem.unavailable('workforce_unavailable'),
    }),
    Match.exhaustive,
  );

const mapCoreProblem = (error: ActionCoreError): ChangeWorkerStatusActionProblem =>
  Match.value(error).pipe(
    Match.tags({
      ActionAlreadyCommitted: (failure) =>
        ChangeWorkerStatusActionAlreadyCommittedProblemSchema.make({
          code: failure.code,
          detail: 'This Action is already committed. Refresh governed reads.',
          invocationId: failure.invocationId,
          resolution: 'REFRESH_GOVERNED_READS',
          retryCommand: false,
          status: problemStatus.conflict,
          title: 'Action already committed',
          type: 'https://ontos.dev/problems/action-already-committed',
        }),
      ActionCollectorError: changeWorkerStatusActionProblem.internal,
      ActionCommitIndeterminate: (failure) =>
        ChangeWorkerStatusActionCommitIndeterminateProblemSchema.make({
          detail: 'The Action commit is uncertain. Resolve this invocation before another attempt.',
          invocationId: failure.invocationId,
          resolution: 'RESOLVE_COMMIT',
          retryCommand: false,
          status: problemStatus.unavailable,
          title: 'Action commit uncertain',
          type: 'https://ontos.dev/problems/action-commit-indeterminate',
        }),
      ActionHandlerExecutionError: changeWorkerStatusActionProblem.internal,
      ActionIdempotencyKeyRequired: changeWorkerStatusActionProblem.precondition,
      ActionInvocationNotFound: (failure) => changeWorkerStatusActionProblem.notFound(failure.code),
      ActionInvocationPersistenceError: (failure) => changeWorkerStatusActionProblem.unavailable(failure.code),
      ActionInvocationStateError: (failure) => changeWorkerStatusActionProblem.conflict(failure.code),
      ActionPayloadValidationError: changeWorkerStatusActionProblem.invalid,
      ActionPermissionCheckError: (failure) => changeWorkerStatusActionProblem.unavailable(failure.code),
      ActionPermissionDenied: (failure) => changeWorkerStatusActionProblem.forbidden(failure.code),
      ActionPolicyDenied: (failure) => changeWorkerStatusActionProblem.ineligible(failure.code),
      ActionPolicyEvaluationError: (failure) => changeWorkerStatusActionProblem.unavailable(failure.code),
      ActionRequestHashConflict: (failure) => changeWorkerStatusActionProblem.conflict(failure.code),
      ActionResultValidationError: changeWorkerStatusActionProblem.internal,
      ActionTransactionError: (failure) => changeWorkerStatusActionProblem.unavailable(failure.code),
      ActionTrustedContextValidationError: changeWorkerStatusActionProblem.authentication,
      ModuleStateCheckUnavailableError: (failure) => changeWorkerStatusActionProblem.unavailable(failure.code),
      ModuleStateDeniedError: (failure) => changeWorkerStatusActionProblem.forbidden(failure.code),
      OperationAuthenticationRequired: changeWorkerStatusActionProblem.authentication,
      OperationContextDenied: (failure) => changeWorkerStatusActionProblem.forbidden(failure.code),
      OperationContextInvalid: (failure) => changeWorkerStatusActionProblem.forbidden(failure.code),
      OperationContextUnavailable: (failure) => changeWorkerStatusActionProblem.unavailable(failure.code),
    }),
    Match.exhaustive,
  );

const isDomainError = Schema.is(changeWorkerStatusAction.descriptor.domainErrorSchema);
export const mapChangeWorkerStatusActionProblem = (
  error: ActionCoreError | DomainError,
): ChangeWorkerStatusActionProblem => (isDomainError(error) ? mapDomainProblem(error) : mapCoreProblem(error));

export const changeWorkerStatusActionSchemaErrorLive = HttpApiMiddleware.layerSchemaErrorTransform(
  ChangeWorkerStatusActionSchemaErrorMiddleware,
  () => Effect.fail(changeWorkerStatusActionProblem.invalid()),
);
