// @generated by OntOS Codesmith module-api v1
import { makeGovernedReadHttpHandler } from '@app/core-runtime/http/governed-read';
import { makeGovernedReadProblems } from '@app/shared-contracts/server/effect-bff-runtime';
import { HttpApiBuilder } from '@modern-js/bff-effect/effect-edge';
import { workforceApi } from '../shared/api.ts';
import {
  WeeklyScheduleAuthenticationProblemSchema,
  WeeklyScheduleForbiddenProblemSchema,
  WeeklyScheduleInternalProblemSchema,
  WeeklyScheduleInvalidProblemSchema,
  WeeklyScheduleNotFoundProblemSchema,
  WeeklySchedulePolicyConflictProblemSchema,
  WeeklySchedulePolicyProblemSchema,
  WeeklyScheduleUnavailableProblemSchema,
} from '../shared/apis/weekly-schedule.ts';
import { weeklyScheduleRead } from '../src/api/weekly-schedule.read.ts';
import { authenticateOperationPrincipal } from './auth/action-principal.ts';

const problems = makeGovernedReadProblems({
  authentication: WeeklyScheduleAuthenticationProblemSchema,
  forbidden: WeeklyScheduleForbiddenProblemSchema,
  internal: WeeklyScheduleInternalProblemSchema,
  invalid: WeeklyScheduleInvalidProblemSchema,
  notFound: WeeklyScheduleNotFoundProblemSchema,
  policyConflict: WeeklySchedulePolicyConflictProblemSchema,
  policyIneligible: WeeklySchedulePolicyProblemSchema,
  unavailable: WeeklyScheduleUnavailableProblemSchema,
});

export const weeklyScheduleReadApiLive = HttpApiBuilder.group(workforceApi, 'weeklySchedule', (handlers) =>
  handlers.handle(
    'execute',
    makeGovernedReadHttpHandler({
      authenticatePrincipal: authenticateOperationPrincipal,
      problems,
      registration: weeklyScheduleRead,
    }),
  ),
);
