// @generated by OntOS Codesmith module-api v1
import { makeGovernedReadHttpHandler } from '@app/core-runtime/http/governed-read';
import { makeGovernedReadProblems } from '@app/shared-contracts/server/effect-bff-runtime';
import { HttpApiBuilder } from '@modern-js/bff-effect/effect-edge';
import { workforceApi } from '../shared/api.ts';
import {
  WorkerDetailAuthenticationProblemSchema,
  WorkerDetailForbiddenProblemSchema,
  WorkerDetailInternalProblemSchema,
  WorkerDetailInvalidProblemSchema,
  WorkerDetailNotFoundProblemSchema,
  WorkerDetailPolicyConflictProblemSchema,
  WorkerDetailPolicyProblemSchema,
  WorkerDetailUnavailableProblemSchema,
} from '../shared/apis/worker-detail.ts';
import { workerDetailRead } from '../src/api/worker-detail.read.ts';
import { authenticateOperationPrincipal } from './auth/action-principal.ts';

const problems = makeGovernedReadProblems({
  authentication: WorkerDetailAuthenticationProblemSchema,
  forbidden: WorkerDetailForbiddenProblemSchema,
  internal: WorkerDetailInternalProblemSchema,
  invalid: WorkerDetailInvalidProblemSchema,
  notFound: WorkerDetailNotFoundProblemSchema,
  policyConflict: WorkerDetailPolicyConflictProblemSchema,
  policyIneligible: WorkerDetailPolicyProblemSchema,
  unavailable: WorkerDetailUnavailableProblemSchema,
});

export const workerDetailReadApiLive = HttpApiBuilder.group(workforceApi, 'workerDetail', (handlers) =>
  handlers.handle(
    'execute',
    makeGovernedReadHttpHandler({
      authenticatePrincipal: authenticateOperationPrincipal,
      problems,
      registration: workerDetailRead,
    }),
  ),
);
