// @generated by OntOS Codesmith public-component v1
import { FederatedI18nBoundary, useModernI18n } from '@modern-js/plugin-i18n/runtime/consumer';

import csResource from '../../locales/cs/billing-documents.json';
import enResource from '../../locales/en/billing-documents.json';

const federatedI18nLanguages = ['en', 'cs'];
const federatedI18nResources = {
  cs: { 'billing-documents': csResource },
  en: { 'billing-documents': enResource },
};

const BillingDocumentsWidgetContent = () => {
  const { t } = useModernI18n();

  return (
    <section
      className="billingdocuments:rounded-2xl billingdocuments:bg-white/90 billingdocuments:p-5 billingdocuments:shadow-xl billingdocuments:shadow-stone-900/10"
      data-modern-boundary-id="verticalBillingDocuments"
      data-modern-mf-expose="./BillingDocumentsWidget"
    >
      <h2 className="billingdocuments:text-2xl billingdocuments:font-black">{t('billing-documents.title')}</h2>
      <p className="billingdocuments:mt-2 billingdocuments:text-stone-600">{t('billing-documents.widgetBody')}</p>
    </section>
  );
};

export const BillingDocumentsWidget = (_props: Record<string, never>) => {
  void _props;
  return (
    <FederatedI18nBoundary
      defaultNamespace="billing-documents"
      fallbackLanguage="en"
      resources={federatedI18nResources}
      supportedLanguages={federatedI18nLanguages}
    >
      <BillingDocumentsWidgetContent />
    </FederatedI18nBoundary>
  );
};

export default BillingDocumentsWidget;
