// @generated by OntOS Codesmith Module Contract v1
// @ontos-deployment-app-id job-expenses
// @ontos-module-id job.expenses
import { defineVerticalRuntimeRegistration } from '@app/core-runtime';
import { jobExpensesManifest } from './vertical.manifest.ts';
// <generated-module-registration-imports>
import { recordJobExpenseAction } from './src/actions/record-job-expense.action.ts';
import { updateJobExpenseAction } from './src/actions/update-job-expense.action.ts';
import { voidJobExpenseAction } from './src/actions/void-job-expense.action.ts';
// </generated-module-registration-imports>

export const jobExpensesRegistration = defineVerticalRuntimeRegistration({
  actions: [
    // <generated-module-registration-actions>
    recordJobExpenseAction,
    updateJobExpenseAction,
    voidJobExpenseAction,
    // </generated-module-registration-actions>
  ],
  entrypoints: {
    api: {
      // <generated-module-registration-apis>
      'job-economics': () => import('./src/api/job-economics-client.ts'),
      'job-expense-list': () => import('./src/api/job-expense-list-client.ts'),
      'job-expenses-commit-status': () => import('./src/api/job-expenses-commit-status-client.ts'),
      'job-selection': () => import('./src/api/job-selection-client.ts'),
      // </generated-module-registration-apis>
    },
    components: {
      // <generated-module-registration-components>
      // </generated-module-registration-components>
    },
    pages: {
      // <generated-module-registration-pages>
      'page-expenses': () => import('./src/routes/[lang]/expenses/page.tsx'),
      // </generated-module-registration-pages>
    },
    reports: {
      // <generated-module-registration-reports>
      // </generated-module-registration-reports>
    },
    search: {
      // <generated-module-registration-search>
      // </generated-module-registration-search>
    },
  },
  manifest: jobExpensesManifest,
  outboxWorkers: [
    // <generated-module-registration-workers>
    // </generated-module-registration-workers>
  ],
});

// <generated-public-component-registrations>
// </generated-public-component-registrations>
// <generated-search-registrations>
// </generated-search-registrations>
// <generated-report-registrations>
// </generated-report-registrations>
