// @generated by OntOS Codesmith module-api v1
import { defineRead, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { Effect } from 'effect';
import type { ReadHandlerContext } from '@app/core-runtime';

import { workforceServices } from '../services/workforce-services.service.ts';
import type { WorkforceServices } from '../services/workforce-services.service.ts';
import { readAvailableWorkers } from '../services/workforce-read-model.ts';
import { mapWorkforceReadFailure } from './workforce-read-errors.ts';
import { AvailableWorkersRequestSchema, AvailableWorkersResponseSchema } from '../../shared/apis/available-workers.ts';

const workforceModuleId = 'workforce.planning' as const;

const availableWorkersEntrypoint = defineTenantModuleEntrypoint({
  access: 'read',
  authorization: { kind: 'context_permission', permission: 'module.access' },
  entrypointKey: 'workforce.planning.api.available-workers',
  moduleKey: workforceModuleId,
  role: 'api',
});

export const availableWorkersRead = defineRead(
  {
    accessKind: 'detail',
    entrypoint: availableWorkersEntrypoint,
    evidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'workforce.planning.api.available-workers.evidence.v1',
    },
    inputSchema: AvailableWorkersRequestSchema,
    legalEntityScope: 'required',
    owningModuleKey: workforceModuleId,
    permissionTarget: 'module',
    policies: [],
    readKey: 'workforce.planning.api.available-workers',
    resultSchema: AvailableWorkersResponseSchema,
    schemaVersion: '1',
  },
  (input: typeof AvailableWorkersRequestSchema.Type, context: ReadHandlerContext<WorkforceServices>) =>
    readAvailableWorkers(context.services, input.jobRef).pipe(
      Effect.map((result) => ({ evidence: { resultCount: result.items.length }, result })),
      Effect.mapError(mapWorkforceReadFailure),
    ),
  workforceServices,
  () => ({ kind: 'module', moduleId: workforceModuleId }),
);
