// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner workforce.planning
// @ontos-action-http-slug change-worker-status
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted, Schema } from 'effect';
import {
  ChangeWorkerStatusActionApi,
  ChangeWorkerStatusPayloadSchema,
} from '../../shared/apis/change-worker-status-action.ts';
import type { ChangeWorkerStatusPayload } from '../../shared/actions/change-worker-status.ts';
import { operationGateway } from './action-gateway.ts';

const traceIdOption = 'traceId' as const;

export interface ChangeWorkerStatusActionClientOptions {
  readonly baseUrl?: string | URL;
  readonly gateway?: Parameters<typeof operationGateway.invoke>[1];
  readonly idempotencyKey: string;
  readonly [traceIdOption]?: string;
}

type AuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options: ChangeWorkerStatusActionClientOptions,
];
type OperationInvocation = readonly [requestCorrelation: string, options: ChangeWorkerStatusActionClientOptions];

interface MakeClientOptions {
  readonly credential: Redacted.Redacted;
  readonly options: ChangeWorkerStatusActionClientOptions;
  readonly requestCorrelation: string;
}

const makeClient = ({ credential, options, requestCorrelation }: MakeClientOptions) =>
  makeGovernedEffectBffClient(
    { api: ChangeWorkerStatusActionApi, credential, defaultApiPrefix: '/workforce-api', requestCorrelation },
    options,
  );

export const executeChangeWorkerStatusWithAuthorization = (
  payload: ChangeWorkerStatusPayload,
  ...[credential, requestCorrelation, options]: AuthorizedInvocation
) =>
  Schema.encodeUnknownEffect(ChangeWorkerStatusPayloadSchema)(payload).pipe(
    Effect.flatMap((encoded) =>
      makeClient({ credential: Redacted.make(credential), options, requestCorrelation }).pipe(
        Effect.flatMap((client) =>
          client.changeWorkerStatusAction.execute({
            headers: { 'idempotency-key': options.idempotencyKey },
            payload: encoded,
          }),
        ),
      ),
    ),
  );

export const executeChangeWorkerStatus = (
  payload: ChangeWorkerStatusPayload,
  ...[requestCorrelation, options]: OperationInvocation
) =>
  operationGateway.invoke(
    (credential) => executeChangeWorkerStatusWithAuthorization(payload, credential, requestCorrelation, options),
    options.gateway,
  );
