// @generated by OntOS Codesmith module-api v1
import { defineRead, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { Effect } from 'effect';
import type { ReadHandlerContext } from '@app/core-runtime';
import { workforcePersistenceService } from '../services/workforce-persistence.service.ts';
import type { WorkforcePersistence } from '../services/workforce-persistence.service.ts';

import { mapWorkforceReadFailure } from './workforce-read-errors.ts';
import { WorkerListRequestSchema, WorkerListResponseSchema } from '../../shared/apis/worker-list.ts';

const workforceModuleId = 'workforce.planning' as const;

const workerListEntrypoint = defineTenantModuleEntrypoint({
  access: 'read',
  authorization: { kind: 'context_permission', permission: 'module.access' },
  entrypointKey: 'workforce.planning.api.worker-list',
  moduleKey: workforceModuleId,
  role: 'api',
});

export const workerListRead = defineRead(
  {
    accessKind: 'detail',
    entrypoint: workerListEntrypoint,
    evidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'workforce.planning.api.worker-list.evidence.v1',
    },
    inputSchema: WorkerListRequestSchema,
    legalEntityScope: 'required',
    owningModuleKey: workforceModuleId,
    permissionTarget: 'module',
    policies: [],
    readKey: 'workforce.planning.api.worker-list',
    resultSchema: WorkerListResponseSchema,
    schemaVersion: '1',
  },
  (_input: typeof WorkerListRequestSchema.Type, context: ReadHandlerContext<WorkforcePersistence>) =>
    context.services.list().pipe(
      Effect.map((items) => ({ items })),
      Effect.map((result) => ({ evidence: { resultCount: result.items.length }, result })),
      Effect.mapError(mapWorkforceReadFailure),
    ),
  workforcePersistenceService,
  () => ({ kind: 'module', moduleId: workforceModuleId }),
);
