// @generated by OntOS Codesmith module-api v1
import {
  ActionRuntime,
  ReadHandlerNotFound,
  ReadHandlerUnavailable,
  defineRead,
  defineTenantModuleEntrypoint,
} from '@app/core-runtime';
import { Effect } from 'effect';
import type { ReadHandlerContext } from '@app/core-runtime';
import {
  WorkforceCommitStatusRequestSchema,
  WorkforceCommitStatusResponseSchema,
} from '../../shared/apis/workforce-commit-status.ts';

interface CommitStatusServices {
  readonly resolve: (
    invocationId: string,
  ) => Effect.Effect<'OPEN' | 'COMMITTED' | 'INDETERMINATE', ReadHandlerNotFound | ReadHandlerUnavailable>;
}

const committed = () => Effect.succeed('COMMITTED' as const);
const indeterminate = () => Effect.succeed('INDETERMINATE' as const);
const invocationNotFound = () =>
  Effect.fail(new ReadHandlerNotFound({ code: 'read_handler_not_found', reason: 'Invocation was not found' }));
const invocationUnavailable = () =>
  Effect.fail(
    new ReadHandlerUnavailable({ code: 'read_handler_unavailable', reason: 'Invocation cannot be resolved' }),
  );

const workforceCommitStatusEntrypoint = defineTenantModuleEntrypoint({
  access: 'read',
  authorization: { kind: 'context_permission', permission: 'module.access' },
  entrypointKey: 'workforce.planning.api.workforce-commit-status',
  moduleKey: 'workforce.planning',
  role: 'api',
});

export const workforceCommitStatusRead = defineRead(
  {
    accessKind: 'detail',
    entrypoint: workforceCommitStatusEntrypoint,
    evidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'workforce.planning.api.workforce-commit-status.evidence.v1',
    },
    inputSchema: WorkforceCommitStatusRequestSchema,
    legalEntityScope: 'required',
    owningModuleKey: 'workforce.planning',
    permissionTarget: 'module',
    policies: [],
    readKey: 'workforce.planning.api.workforce-commit-status',
    resultSchema: WorkforceCommitStatusResponseSchema,
    schemaVersion: '1',
  },
  (input, context: ReadHandlerContext<CommitStatusServices>) =>
    context.services
      .resolve(input.invocationId)
      .pipe(
        Effect.map((state) => ({ evidence: { resultCount: 1 }, result: { retryCommand: state === 'OPEN', state } })),
      ),
  (_transaction, scope) =>
    ActionRuntime.pipe(
      Effect.map((runtime) => ({
        resolve: (invocationId: string) =>
          runtime.resolveActionCommit({ invocationId, principal: scope }).pipe(
            Effect.as('OPEN' as const),
            Effect.catchTags({
              ActionAlreadyCommitted: committed,
              ActionCommitIndeterminate: indeterminate,
              ActionInvocationNotFound: invocationNotFound,
              ActionInvocationStateError: invocationUnavailable,
              ActionPayloadValidationError: invocationNotFound,
              ActionTrustedContextValidationError: invocationUnavailable,
            }),
          ),
      })),
    ),
  () => ({ kind: 'module', moduleId: workforceCommitStatusEntrypoint.moduleKey }),
);
