// @generated by OntOS Codesmith module-api v1
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted } from 'effect';
import { WorkforceCommitStatusApi } from '../../shared/apis/workforce-commit-status.ts';
import type { WorkforceCommitStatusRequest } from '../../shared/apis/workforce-commit-status.ts';
import { operationGateway } from './action-gateway.ts';

export interface WorkforceCommitStatusClientOptions {
  readonly baseUrl?: string | URL;
}

type WorkforceCommitStatusAuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options?: WorkforceCommitStatusClientOptions,
];

type WorkforceCommitStatusOperationInvocation = readonly [
  requestCorrelation: string,
  options?: WorkforceCommitStatusClientOptions,
];

const workforceCommitStatusClient = (
  credential: Redacted.Redacted,
  requestCorrelation: string,
  options: WorkforceCommitStatusClientOptions,
) =>
  makeGovernedEffectBffClient(
    {
      api: WorkforceCommitStatusApi,
      credential,
      defaultApiPrefix: '/workforce-api',
      requestCorrelation,
    },
    options,
  );

export const executeWorkforceCommitStatusWithAuthorization = (
  payload: WorkforceCommitStatusRequest,
  ...[credential, requestCorrelation, options = {}]: WorkforceCommitStatusAuthorizedInvocation
) =>
  workforceCommitStatusClient(Redacted.make(credential), requestCorrelation, options).pipe(
    Effect.flatMap((client) => client.workforceCommitStatus.execute({ headers: {}, params: {}, payload, query: {} })),
  );

export const executeWorkforceCommitStatus = (
  payload: WorkforceCommitStatusRequest,
  ...[requestCorrelation, options = {}]: WorkforceCommitStatusOperationInvocation
) =>
  operationGateway.invoke((credential) =>
    executeWorkforceCommitStatusWithAuthorization(payload, credential, requestCorrelation, options),
  );
