// @generated by OntOS Codesmith module-api v1
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted, Schema } from 'effect';

import {
  CurrentSupportedCurrenciesApi,
  CurrentSupportedCurrenciesRequestSchema,
} from '../apis/current-supported-currencies.ts';
import type { CurrentSupportedCurrenciesRequest } from '../apis/current-supported-currencies.ts';
import { operationGateway } from './action-gateway.ts';

export interface CurrentSupportedCurrenciesClientOptions {
  readonly baseUrl?: string | URL;
}

type AuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options?: CurrentSupportedCurrenciesClientOptions,
];
type OperationInvocation = readonly [requestCorrelation: string, options?: CurrentSupportedCurrenciesClientOptions];

export const executeCurrentSupportedCurrenciesWithAuthorization = (
  payload: CurrentSupportedCurrenciesRequest,
  ...[credential, requestCorrelation, options = {}]: AuthorizedInvocation
) =>
  Schema.encodeUnknownEffect(CurrentSupportedCurrenciesRequestSchema)(payload).pipe(
    Effect.flatMap((encoded) =>
      makeGovernedEffectBffClient(
        {
          api: CurrentSupportedCurrenciesApi,
          credential: Redacted.make(credential),
          defaultApiPrefix: '/pricing-api',
          requestCorrelation,
        },
        options,
      ).pipe(
        Effect.flatMap((client) =>
          client.currentSupportedCurrencies.execute({ headers: {}, params: {}, payload: encoded, query: {} }),
        ),
      ),
    ),
  );

export const executeCurrentSupportedCurrencies = (
  payload: CurrentSupportedCurrenciesRequest,
  ...[requestCorrelation, options = {}]: OperationInvocation
) =>
  operationGateway.invoke((credential) =>
    executeCurrentSupportedCurrenciesWithAuthorization(payload, credential, requestCorrelation, options),
  );
