// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner sales.inquiries
// @ontos-action-http-slug create-inquiry
import { Effect, HttpApiBuilder, Layer } from '@modern-js/bff-effect/effect-edge';
import type { HttpServerRequest } from 'effect/unstable/http';
import { Redacted, Schema } from 'effect';
import { salesInquiriesApi } from '../shared/api.ts';
import { createInquiryAction } from '../src/actions/create-inquiry.action.ts';
import { bindActionHttpRunner } from './action-http-runner.ts';
import {
  createInquiryActionProblem,
  createInquiryActionSchemaErrorLive,
  mapCreateInquiryActionProblem,
} from './create-inquiry-action-problems.ts';

const runActionHttp = bindActionHttpRunner({
  authentication: createInquiryActionProblem.authentication,
  unavailable: () => createInquiryActionProblem.unavailable('operation_context_unavailable'),
});

const execute = Effect.fn('CreateInquiryActionServer.execute')(function* executeCreateInquiry(
  payload: typeof createInquiryAction.descriptor.payloadSchema.Encoded,
  idempotencyKey: string | undefined,
  request: HttpServerRequest.HttpServerRequest,
) {
  const correlationId = request.headers['x-correlation-id'];
  if (correlationId !== undefined && correlationId.length > 200) {
    return yield* Effect.fail(createInquiryActionProblem.invalid());
  }
  const decoded = yield* Schema.decodeEffect(createInquiryAction.descriptor.payloadSchema)(payload).pipe(
    Effect.mapError(createInquiryActionProblem.invalid),
  );
  return yield* runActionHttp({
    endpointHeaders: { idempotencyKey, traceId: request.headers['x-trace-id'] },
    internalProblem: createInquiryActionProblem.internal,
    invalidCorrelationProblem: createInquiryActionProblem.invalid,
    mapError: mapCreateInquiryActionProblem,
    payload: decoded,
    registration: createInquiryAction,
    requestHeaders: {
      authorization: Redacted.make(request.headers['authorization']),
      'x-correlation-id': correlationId,
    },
  });
});

export const createInquiryActionApiLive = HttpApiBuilder.group(salesInquiriesApi, 'createInquiryAction', (handlers) =>
  handlers.handle('execute', ({ headers, payload, request }) => execute(payload, headers['idempotency-key'], request)),
).pipe(Layer.provide(createInquiryActionSchemaErrorLive));
