// @generated by OntOS Codesmith module-api v1
import { makeGovernedReadHttpHandler } from '@app/core-runtime/http/governed-read';
import { makeGovernedReadProblems } from '@app/shared-contracts/server/effect-bff-runtime';
import { HttpApiBuilder } from '@modern-js/bff-effect/effect-edge';
import { salesInquiriesApi } from '../shared/api.ts';
import {
  InquiryListAuthenticationProblemSchema,
  InquiryListForbiddenProblemSchema,
  InquiryListInternalProblemSchema,
  InquiryListInvalidProblemSchema,
  InquiryListNotFoundProblemSchema,
  InquiryListPolicyConflictProblemSchema,
  InquiryListPolicyProblemSchema,
  InquiryListUnavailableProblemSchema,
} from '../shared/apis/inquiry-list.ts';
import { inquiryListRead } from '../src/api/inquiry-list.read.ts';
import { authenticateOperationPrincipal } from './auth/action-principal.ts';

const problems = makeGovernedReadProblems({
  authentication: InquiryListAuthenticationProblemSchema,
  forbidden: InquiryListForbiddenProblemSchema,
  internal: InquiryListInternalProblemSchema,
  invalid: InquiryListInvalidProblemSchema,
  notFound: InquiryListNotFoundProblemSchema,
  policyConflict: InquiryListPolicyConflictProblemSchema,
  policyIneligible: InquiryListPolicyProblemSchema,
  unavailable: InquiryListUnavailableProblemSchema,
});

export const inquiryListReadApiLive = HttpApiBuilder.group(salesInquiriesApi, 'inquiryList', (handlers) =>
  handlers.handle(
    'execute',
    makeGovernedReadHttpHandler({
      authenticatePrincipal: authenticateOperationPrincipal,
      problems,
      registration: inquiryListRead,
    }),
  ),
);
