// @generated by OntOS Codesmith module-api v1
import { makeGovernedReadHttpHandler } from '@app/core-runtime/http/governed-read';
import { makeGovernedReadProblems } from '@app/shared-contracts/server/effect-bff-runtime';
import { HttpApiBuilder } from '@modern-js/bff-effect/effect-edge';
import { salesInquiriesApi } from '../shared/api.ts';
import {
  InquiryDetailAuthenticationProblemSchema,
  InquiryDetailForbiddenProblemSchema,
  InquiryDetailInternalProblemSchema,
  InquiryDetailInvalidProblemSchema,
  InquiryDetailNotFoundProblemSchema,
  InquiryDetailPolicyConflictProblemSchema,
  InquiryDetailPolicyProblemSchema,
  InquiryDetailUnavailableProblemSchema,
} from '../shared/apis/inquiry-detail.ts';
import { inquiryDetailRead } from '../src/api/inquiry-detail.read.ts';
import { authenticateOperationPrincipal } from './auth/action-principal.ts';

const problems = makeGovernedReadProblems({
  authentication: InquiryDetailAuthenticationProblemSchema,
  forbidden: InquiryDetailForbiddenProblemSchema,
  internal: InquiryDetailInternalProblemSchema,
  invalid: InquiryDetailInvalidProblemSchema,
  notFound: InquiryDetailNotFoundProblemSchema,
  policyConflict: InquiryDetailPolicyConflictProblemSchema,
  policyIneligible: InquiryDetailPolicyProblemSchema,
  unavailable: InquiryDetailUnavailableProblemSchema,
});

export const inquiryDetailReadApiLive = HttpApiBuilder.group(salesInquiriesApi, 'inquiryDetail', (handlers) =>
  handlers.handle(
    'execute',
    makeGovernedReadHttpHandler({
      authenticatePrincipal: authenticateOperationPrincipal,
      problems,
      registration: inquiryDetailRead,
    }),
  ),
);
