// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner sales.inquiries
// @ontos-action-http-slug transition-inquiry
import { Effect, HttpApiBuilder, Layer } from '@modern-js/bff-effect/effect-edge';
import type { HttpServerRequest } from 'effect/unstable/http';
import { Redacted, Schema } from 'effect';
import { salesInquiriesApi } from '../shared/api.ts';
import { transitionInquiryAction } from '../src/actions/transition-inquiry.action.ts';
import { bindActionHttpRunner } from './action-http-runner.ts';
import {
  transitionInquiryActionProblem,
  transitionInquiryActionSchemaErrorLive,
  mapTransitionInquiryActionProblem,
} from './transition-inquiry-action-problems.ts';

const runActionHttp = bindActionHttpRunner({
  authentication: transitionInquiryActionProblem.authentication,
  unavailable: () => transitionInquiryActionProblem.unavailable('operation_context_unavailable'),
});

const execute = Effect.fn('TransitionInquiryActionServer.execute')(function* executeTransitionInquiry(
  payload: typeof transitionInquiryAction.descriptor.payloadSchema.Encoded,
  idempotencyKey: string | undefined,
  request: HttpServerRequest.HttpServerRequest,
) {
  const correlationId = request.headers['x-correlation-id'];
  if (correlationId !== undefined && correlationId.length > 200) {
    return yield* Effect.fail(transitionInquiryActionProblem.invalid());
  }
  const decoded = yield* Schema.decodeEffect(transitionInquiryAction.descriptor.payloadSchema)(payload).pipe(
    Effect.mapError(transitionInquiryActionProblem.invalid),
  );
  return yield* runActionHttp({
    endpointHeaders: { idempotencyKey, traceId: request.headers['x-trace-id'] },
    internalProblem: transitionInquiryActionProblem.internal,
    invalidCorrelationProblem: transitionInquiryActionProblem.invalid,
    mapError: mapTransitionInquiryActionProblem,
    payload: decoded,
    registration: transitionInquiryAction,
    requestHeaders: {
      authorization: Redacted.make(request.headers['authorization']),
      'x-correlation-id': correlationId,
    },
  });
});

export const transitionInquiryActionApiLive = HttpApiBuilder.group(
  salesInquiriesApi,
  'transitionInquiryAction',
  (handlers) =>
    handlers.handle('execute', ({ headers, payload, request }) =>
      execute(payload, headers['idempotency-key'], request),
    ),
).pipe(Layer.provide(transitionInquiryActionSchemaErrorLive));
