// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner sales.inquiries
// @ontos-action-http-slug update-inquiry-details
import { Effect, HttpApiBuilder, Layer } from '@modern-js/bff-effect/effect-edge';
import type { HttpServerRequest } from 'effect/unstable/http';
import { Redacted, Schema } from 'effect';
import { salesInquiriesApi } from '../shared/api.ts';
import { updateInquiryDetailsAction } from '../src/actions/update-inquiry-details.action.ts';
import { bindActionHttpRunner } from './action-http-runner.ts';
import {
  updateInquiryDetailsActionProblem,
  updateInquiryDetailsActionSchemaErrorLive,
  mapUpdateInquiryDetailsActionProblem,
} from './update-inquiry-details-action-problems.ts';

const runActionHttp = bindActionHttpRunner({
  authentication: updateInquiryDetailsActionProblem.authentication,
  unavailable: () => updateInquiryDetailsActionProblem.unavailable('operation_context_unavailable'),
});

const execute = Effect.fn('UpdateInquiryDetailsActionServer.execute')(function* executeUpdateInquiryDetails(
  payload: typeof updateInquiryDetailsAction.descriptor.payloadSchema.Encoded,
  idempotencyKey: string | undefined,
  request: HttpServerRequest.HttpServerRequest,
) {
  const correlationId = request.headers['x-correlation-id'];
  if (correlationId !== undefined && correlationId.length > 200) {
    return yield* Effect.fail(updateInquiryDetailsActionProblem.invalid());
  }
  const decoded = yield* Schema.decodeEffect(updateInquiryDetailsAction.descriptor.payloadSchema)(payload).pipe(
    Effect.mapError(updateInquiryDetailsActionProblem.invalid),
  );
  return yield* runActionHttp({
    endpointHeaders: { idempotencyKey, traceId: request.headers['x-trace-id'] },
    internalProblem: updateInquiryDetailsActionProblem.internal,
    invalidCorrelationProblem: updateInquiryDetailsActionProblem.invalid,
    mapError: mapUpdateInquiryDetailsActionProblem,
    payload: decoded,
    registration: updateInquiryDetailsAction,
    requestHeaders: {
      authorization: Redacted.make(request.headers['authorization']),
      'x-correlation-id': correlationId,
    },
  });
});

export const updateInquiryDetailsActionApiLive = HttpApiBuilder.group(
  salesInquiriesApi,
  'updateInquiryDetailsAction',
  (handlers) =>
    handlers.handle('execute', ({ headers, payload, request }) =>
      execute(payload, headers['idempotency-key'], request),
    ),
).pipe(Layer.provide(updateInquiryDetailsActionSchemaErrorLive));
