// @generated by OntOS Codesmith Module Contract v1
// @ontos-deployment-app-id operations-dashboard
// @ontos-module-id operations.dashboard
import {
  defineOntosModuleManifest,
  ShellNavigationContributionSchema,
  ShellPageContributionSchema,
} from '@app/core-runtime';
import { Result, Schema } from 'effect';
// <generated-module-manifest-imports>
import { DashboardOverviewApi } from './shared/apis/dashboard-overview.ts';
import { DashboardPage } from './src/routes/[lang]/dashboard/page.tsx';
// </generated-module-manifest-imports>

const operationsDashboardModuleId = 'operations.dashboard' as const;
const dashboardPageKey = 'operations.dashboard.page.dashboard' as const;

type NavigationContributionInput = typeof ShellNavigationContributionSchema.Encoded;
type PageContributionInput = typeof ShellPageContributionSchema.Encoded;
const navigationContribution = (value: NavigationContributionInput) =>
  Result.getOrThrow(Schema.decodeResult(ShellNavigationContributionSchema)(value));
const pageContribution = (value: PageContributionInput) =>
  Result.getOrThrow(Schema.decodeResult(ShellPageContributionSchema)(value));

export const operationsDashboardManifest = defineOntosModuleManifest({
  activation: {
    defaultState: 'inactive',
    preservesHistoryWhenInactive: true,
    scope: 'tenant',
    supportedStates: ['inactive', 'active', 'read_only', 'suspended', 'quarantined', 'deprecated', 'archived'],
  },
  module: {
    description: 'Operations Dashboard business capability.',
    displayName: 'Operations Dashboard',
    id: operationsDashboardModuleId,
    implementedAs: 'ultramodern_microvertical',
    kind: 'business_module',
  },
  publicSurface: {
    actions: [
      // <generated-module-manifest-actions>
      // </generated-module-manifest-actions>
    ],
    api: {
      // <generated-module-manifest-apis>
      'dashboard-overview': DashboardOverviewApi,
      // </generated-module-manifest-apis>
    },
    businessPermissions: [
      // <generated-module-manifest-business-permissions>
      // </generated-module-manifest-business-permissions>
    ],
    components: {
      // <generated-module-manifest-components>
      'page-dashboard': DashboardPage,
      // </generated-module-manifest-components>
    },
    events: [],
    reports: [
      // <generated-module-manifest-reports>
      // </generated-module-manifest-reports>
    ],
    resourceTypes: [
      // <generated-module-manifest-resources>
      // </generated-module-manifest-resources>
    ],
    search: [
      // <generated-module-manifest-search>
      // </generated-module-manifest-search>
    ],
    shellContributions: {
      mediaAttachments: [],
      navigation: [
        // <generated-module-shell-navigation>
        navigationContribution({
          contributionKey: 'operations.dashboard.navigation.dashboard',
          entrypoint: {
            access: 'read',
            authorization: { kind: 'context_permission', permission: 'module.access' },
            entrypointKey: dashboardPageKey,
            moduleKey: operationsDashboardModuleId,
            role: 'page',
            scope: 'tenant',
          },
          groupKey: 'shell.navigation.modules',
          order: 100,
          pageKey: dashboardPageKey,
        }),
        // </generated-module-shell-navigation>
      ],
      pages: [
        // <generated-module-shell-pages>
        pageContribution({
          componentKey: 'operations.dashboard.page-dashboard',
          contributionKey: dashboardPageKey,
          entrypoint: {
            access: 'read',
            authorization: { kind: 'context_permission', permission: 'module.access' },
            entrypointKey: dashboardPageKey,
            moduleKey: operationsDashboardModuleId,
            role: 'page',
            scope: 'tenant',
          },
          routePath: '/dashboard',
        }),
        // </generated-module-shell-pages>
      ],
      publicComponents: [
        // <generated-module-shell-components>
        // </generated-module-shell-components>
      ],
      reports: [
        // <generated-module-shell-reports>
        // </generated-module-shell-reports>
      ],
      resourceDetails: [],
      search: [
        // <generated-module-shell-search>
        // </generated-module-shell-search>
      ],
      timelines: [],
    },
  },
});
