// @generated by OntOS Codesmith Module Contract v1
// @ontos-deployment-app-id operations-dashboard
// @ontos-module-id operations.dashboard
import { defineVerticalRuntimeRegistration } from '@app/core-runtime';
import { operationsDashboardManifest } from './vertical.manifest.ts';
// <generated-module-registration-imports>
// </generated-module-registration-imports>

export const operationsDashboardRegistration = defineVerticalRuntimeRegistration({
  actions: [
    // <generated-module-registration-actions>
    // </generated-module-registration-actions>
  ],
  entrypoints: {
    api: {
      // <generated-module-registration-apis>
      'dashboard-overview': () => import('./src/api/dashboard-overview-client.ts'),
      // </generated-module-registration-apis>
    },
    components: {
      // <generated-module-registration-components>
      // </generated-module-registration-components>
    },
    pages: {
      // <generated-module-registration-pages>
      'page-dashboard': () => import('./src/routes/[lang]/dashboard/page.tsx'),
      // </generated-module-registration-pages>
    },
    reports: {
      // <generated-module-registration-reports>
      // </generated-module-registration-reports>
    },
    search: {
      // <generated-module-registration-search>
      // </generated-module-registration-search>
    },
  },
  manifest: operationsDashboardManifest,
  outboxWorkers: [
    // <generated-module-registration-workers>
    // </generated-module-registration-workers>
  ],
});

// <generated-public-component-registrations>
// </generated-public-component-registrations>
// <generated-search-registrations>
// </generated-search-registrations>
// <generated-report-registrations>
// </generated-report-registrations>
