// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner sales.inquiries
// @ontos-action-http-slug create-inquiry
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { HttpApi, HttpApiEndpoint, HttpApiGroup, Schema } from '@modern-js/bff-effect/effect-client';
import { HttpApiMiddleware } from 'effect/unstable/httpapi';
import { CreateInquiryPayloadSchema, CreateInquiryResultSchema } from '../actions/create-inquiry.ts';

export { CreateInquiryPayloadSchema } from '../actions/create-inquiry.ts';

const CreateInquiryActionHeadersSchema = Schema.Struct({
  'idempotency-key': Schema.optionalKey(Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(200))),
});

export const CreateInquiryActionInvalidProblemSchema = makeProblemDetailsSchema(
  'CreateInquiryActionInvalidProblem',
  400,
);
export const CreateInquiryActionAuthenticationProblemSchema = makeProblemDetailsSchema(
  'CreateInquiryActionAuthenticationProblem',
  401,
);
export const CreateInquiryActionForbiddenProblemSchema = makeProblemDetailsSchema(
  'CreateInquiryActionForbiddenProblem',
  403,
  {
    code: Schema.Literals([
      'action_permission_denied',
      'module_state_denied',
      'operation_context_denied',
      'operation_context_invalid',
    ]),
  },
);
export const CreateInquiryActionNotFoundProblemSchema = makeProblemDetailsSchema(
  'CreateInquiryActionNotFoundProblem',
  404,
  { code: Schema.Literals(['action_invocation_not_found', 'not_found']) },
);
export const CreateInquiryActionConflictProblemSchema = makeProblemDetailsSchema(
  'CreateInquiryActionConflictProblem',
  409,
  {
    code: Schema.Literals([
      'action_request_hash_conflict',
      'action_invocation_state_invalid',
      'revision_conflict',
      'party_conflict',
    ]),
  },
);
export const CreateInquiryActionIneligibleProblemSchema = makeProblemDetailsSchema(
  'CreateInquiryActionIneligibleProblem',
  422,
  {
    code: Schema.Literals([
      'action_policy_denied',
      'commercial_frozen',
      'invalid_transition',
      'offer_required',
      'party_invalid',
      'party_ineligible',
    ]),
  },
);
export const CreateInquiryActionPreconditionProblemSchema = makeProblemDetailsSchema(
  'CreateInquiryActionPreconditionProblem',
  428,
);
export const CreateInquiryActionUnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  'CreateInquiryActionUnavailableProblem',
  503,
  {
    code: Schema.Literals([
      'action_invocation_persistence_failed',
      'action_permission_check_failed',
      'action_policy_evaluation_failed',
      'action_transaction_failed',
      'module_state_check_unavailable',
      'operation_context_unavailable',
      'inquiry_unavailable',
    ]),
  },
);
export const CreateInquiryActionAlreadyCommittedProblemSchema = makeProblemDetailsSchema(
  'CreateInquiryActionAlreadyCommittedProblem',
  409,
  {
    code: Schema.Literal('action_already_committed'),
    invocationId: Schema.String,
    resolution: Schema.Literal('REFRESH_GOVERNED_READS'),
    retryCommand: Schema.Literal(false),
  },
);
export const CreateInquiryActionCommitIndeterminateProblemSchema = makeProblemDetailsSchema(
  'CreateInquiryActionCommitIndeterminateProblem',
  503,
  {
    invocationId: Schema.String,
    resolution: Schema.Literal('RESOLVE_COMMIT'),
    retryCommand: Schema.Literal(false),
  },
);
export const CreateInquiryActionInternalProblemSchema = makeProblemDetailsSchema(
  'CreateInquiryActionInternalProblem',
  500,
);

export type CreateInquiryActionProblem =
  | typeof CreateInquiryActionInvalidProblemSchema.Type
  | typeof CreateInquiryActionAuthenticationProblemSchema.Type
  | typeof CreateInquiryActionForbiddenProblemSchema.Type
  | typeof CreateInquiryActionNotFoundProblemSchema.Type
  | typeof CreateInquiryActionConflictProblemSchema.Type
  | typeof CreateInquiryActionIneligibleProblemSchema.Type
  | typeof CreateInquiryActionPreconditionProblemSchema.Type
  | typeof CreateInquiryActionUnavailableProblemSchema.Type
  | typeof CreateInquiryActionAlreadyCommittedProblemSchema.Type
  | typeof CreateInquiryActionCommitIndeterminateProblemSchema.Type
  | typeof CreateInquiryActionInternalProblemSchema.Type;

export class CreateInquiryActionSchemaErrorMiddleware extends HttpApiMiddleware.Service<CreateInquiryActionSchemaErrorMiddleware>()(
  'sales-inquiries/CreateInquiryActionSchemaErrorMiddleware',
  { error: CreateInquiryActionInvalidProblemSchema },
) {}

const actionErrors = [
  CreateInquiryActionInvalidProblemSchema,
  CreateInquiryActionAuthenticationProblemSchema,
  CreateInquiryActionForbiddenProblemSchema,
  CreateInquiryActionNotFoundProblemSchema,
  CreateInquiryActionConflictProblemSchema,
  CreateInquiryActionIneligibleProblemSchema,
  CreateInquiryActionPreconditionProblemSchema,
  CreateInquiryActionUnavailableProblemSchema,
  CreateInquiryActionAlreadyCommittedProblemSchema,
  CreateInquiryActionCommitIndeterminateProblemSchema,
  CreateInquiryActionInternalProblemSchema,
] as const;

/**
 * The endpoint chain stays a `const`. The MicroVertical API boundary checker walks a root API's
 * operands through const bindings only, so a class declaration hides the composed endpoints from
 * it. The exported group is annotated with a named type alias so its type still has a name: the
 * vertical's `shared/api.ts` merges every group type into one `HttpApi` and declaration emit
 * serializes that union verbatim, so an anonymous group type pushes the composed contract past
 * the compiler's serialization limit (TS7056).
 *
 * Exported only so the named contract type can reference it; the merged vertical HttpApi prints
 * this group by name (declaration-emit size).
 *
 * @public
 */
export const createInquiryActionGroupDefinition = HttpApiGroup.make('createInquiryAction')
  .add(
    HttpApiEndpoint.post('execute', '/sales-inquiries/actions/create-inquiry', {
      error: actionErrors,
      headers: CreateInquiryActionHeadersSchema,
      payload: Schema.toEncoded(CreateInquiryPayloadSchema),
      success: CreateInquiryResultSchema,
    }),
  )
  .middleware(CreateInquiryActionSchemaErrorMiddleware);

export type CreateInquiryActionGroupContract = HttpApiGroup.HttpApiGroup<
  'createInquiryAction',
  HttpApiGroup.Endpoints<typeof createInquiryActionGroupDefinition>
>;

const CreateInquiryActionGroup: CreateInquiryActionGroupContract = createInquiryActionGroupDefinition;

export const CreateInquiryActionApi = HttpApi.make('CreateInquiryActionApi').add(CreateInquiryActionGroup);
