// @generated by OntOS Codesmith module-api v1
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { Schema } from 'effect';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';

export const InquiryCommitStatusRequestSchema = Schema.Struct({
  invocationId: Schema.String.check(Schema.isUUID()).pipe(Schema.brand('ActionInvocationId')),
});
export type InquiryCommitStatusRequest = typeof InquiryCommitStatusRequestSchema.Type;
export const InquiryCommitStatusResponseSchema = Schema.Struct({
  retryCommand: Schema.Boolean,
  state: Schema.Literals(['OPEN', 'COMMITTED', 'INDETERMINATE']),
});

export const InquiryCommitStatusAuthenticationProblemSchema = makeProblemDetailsSchema(
  'InquiryCommitStatusAuthenticationProblem',
  401,
);
export const InquiryCommitStatusInvalidProblemSchema = makeProblemDetailsSchema(
  'InquiryCommitStatusInvalidProblem',
  400,
);
export const InquiryCommitStatusUnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  'InquiryCommitStatusUnavailableProblem',
  503,
);
export const InquiryCommitStatusForbiddenProblemSchema = makeProblemDetailsSchema(
  'InquiryCommitStatusForbiddenProblem',
  403,
);
export const InquiryCommitStatusNotFoundProblemSchema = makeProblemDetailsSchema(
  'InquiryCommitStatusNotFoundProblem',
  404,
);
export const InquiryCommitStatusPolicyProblemSchema = makeProblemDetailsSchema('InquiryCommitStatusPolicyProblem', 422);
export const InquiryCommitStatusPolicyConflictProblemSchema = makeProblemDetailsSchema(
  'InquiryCommitStatusPolicyConflictProblem',
  409,
);
export const InquiryCommitStatusInternalProblemSchema = makeProblemDetailsSchema(
  'InquiryCommitStatusInternalProblem',
  500,
);

export const InquiryCommitStatusApi = HttpApi.make('InquiryCommitStatusApi').add(
  HttpApiGroup.make('inquiryCommitStatus').add(
    HttpApiEndpoint.post('execute', '/reads/inquiry-commit-status', {
      error: [
        InquiryCommitStatusInvalidProblemSchema,
        InquiryCommitStatusAuthenticationProblemSchema,
        InquiryCommitStatusForbiddenProblemSchema,
        InquiryCommitStatusNotFoundProblemSchema,
        InquiryCommitStatusPolicyConflictProblemSchema,
        InquiryCommitStatusPolicyProblemSchema,
        InquiryCommitStatusUnavailableProblemSchema,
        InquiryCommitStatusInternalProblemSchema,
      ],
      headers: {},
      params: {},
      payload: InquiryCommitStatusRequestSchema,
      query: {},
      success: InquiryCommitStatusResponseSchema,
    }),
  ),
);
