// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner service.jobs
// @ontos-action-http-slug create-service-job
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted, Schema } from 'effect';
import {
  CreateServiceJobActionApi,
  CreateServiceJobPayloadSchema,
} from '../../shared/apis/create-service-job-action.ts';
import type { CreateServiceJobPayload } from '../../shared/actions/create-service-job.ts';
import { operationGateway } from './action-gateway.ts';

const traceIdOption = 'traceId' as const;

export interface CreateServiceJobActionClientOptions {
  readonly baseUrl?: string | URL;
  readonly gateway?: Parameters<typeof operationGateway.invoke>[1];
  readonly idempotencyKey: string;
  readonly [traceIdOption]?: string;
}

type AuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options: CreateServiceJobActionClientOptions,
];
type OperationInvocation = readonly [requestCorrelation: string, options: CreateServiceJobActionClientOptions];

interface MakeClientOptions {
  readonly credential: Redacted.Redacted;
  readonly options: CreateServiceJobActionClientOptions;
  readonly requestCorrelation: string;
}

const makeClient = ({ credential, options, requestCorrelation }: MakeClientOptions) =>
  makeGovernedEffectBffClient(
    { api: CreateServiceJobActionApi, credential, defaultApiPrefix: '/service-jobs-api', requestCorrelation },
    options,
  );

export const executeCreateServiceJobWithAuthorization = (
  payload: CreateServiceJobPayload,
  ...[credential, requestCorrelation, options]: AuthorizedInvocation
) =>
  Schema.encodeUnknownEffect(CreateServiceJobPayloadSchema)(payload).pipe(
    Effect.flatMap((encoded) =>
      makeClient({ credential: Redacted.make(credential), options, requestCorrelation }).pipe(
        Effect.flatMap((client) =>
          client.createServiceJobAction.execute({
            headers: { 'idempotency-key': options.idempotencyKey },
            payload: encoded,
          }),
        ),
      ),
    ),
  );

export const executeCreateServiceJob = (
  payload: CreateServiceJobPayload,
  ...[requestCorrelation, options]: OperationInvocation
) =>
  operationGateway.invoke(
    (credential) => executeCreateServiceJobWithAuthorization(payload, credential, requestCorrelation, options),
    options.gateway,
  );
