// @generated by OntOS Codesmith module-api v1
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted } from 'effect';
import { JobDetailApi } from '../../shared/apis/job-detail.ts';
import type { JobDetailRequest } from '../../shared/apis/job-detail.ts';
import { operationGateway } from './action-gateway.ts';

export interface JobDetailClientOptions {
  readonly baseUrl?: string | URL;
}

type JobDetailAuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options?: JobDetailClientOptions,
];

type JobDetailOperationInvocation = readonly [requestCorrelation: string, options?: JobDetailClientOptions];

const jobDetailClient = (credential: Redacted.Redacted, requestCorrelation: string, options: JobDetailClientOptions) =>
  makeGovernedEffectBffClient(
    {
      api: JobDetailApi,
      credential,
      defaultApiPrefix: '/service-jobs-api',
      requestCorrelation,
    },
    options,
  );

export const executeJobDetailWithAuthorization = (
  payload: JobDetailRequest,
  ...[credential, requestCorrelation, options = {}]: JobDetailAuthorizedInvocation
) =>
  jobDetailClient(Redacted.make(credential), requestCorrelation, options).pipe(
    Effect.flatMap((client) => client.jobDetail.execute({ headers: {}, params: {}, payload, query: {} })),
  );

export const executeJobDetail = (
  payload: JobDetailRequest,
  ...[requestCorrelation, options = {}]: JobDetailOperationInvocation
) =>
  operationGateway.invoke((credential) =>
    executeJobDetailWithAuthorization(payload, credential, requestCorrelation, options),
  );
