import type { ReadHandlerContext } from '@app/core-runtime';
import { partyReadService } from '../services/party-read.service.ts';
import type { JobPartyReader } from '../services/party-read.service.ts';
import { mapJobReadFailure } from './job-read-errors.ts';
// @generated by OntOS Codesmith module-api v1
import { defineRead, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { Effect } from 'effect';
import { PartyDisplayRequestSchema, PartyDisplayResponseSchema } from '../../shared/apis/party-display.ts';

const partyDisplayEntrypoint = defineTenantModuleEntrypoint({
  access: 'read',
  authorization: { kind: 'context_permission', permission: 'module.access' },
  entrypointKey: 'service.jobs.api.party-display',
  moduleKey: 'service.jobs',
  role: 'api',
});

export const partyDisplayRead = defineRead(
  {
    accessKind: 'detail',
    entrypoint: partyDisplayEntrypoint,
    evidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'service.jobs.api.party-display.evidence.v1',
    },
    inputSchema: PartyDisplayRequestSchema,
    legalEntityScope: 'required',
    owningModuleKey: 'service.jobs',
    permissionTarget: 'module',
    policies: [],
    readKey: 'service.jobs.api.party-display',
    resultSchema: PartyDisplayResponseSchema,
    schemaVersion: '1',
  },
  (input: typeof PartyDisplayRequestSchema.Type, context: ReadHandlerContext<JobPartyReader>) =>
    context.services.read(input.partyRef).pipe(
      Effect.map((value) => ({ evidence: { resultCount: 1 }, result: value })),
      Effect.mapError(mapJobReadFailure),
    ),
  (_transaction, scope) => partyReadService(scope),
  () => ({ kind: 'module', moduleId: partyDisplayEntrypoint.moduleKey }),
);
