// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner service.jobs
// @ontos-action-http-slug schedule-service-job
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted, Schema } from 'effect';
import {
  ScheduleServiceJobActionApi,
  ScheduleServiceJobPayloadSchema,
} from '../../shared/apis/schedule-service-job-action.ts';
import type { ScheduleServiceJobPayload } from '../../shared/actions/schedule-service-job.ts';
import { operationGateway } from './action-gateway.ts';

const traceIdOption = 'traceId' as const;

export interface ScheduleServiceJobActionClientOptions {
  readonly baseUrl?: string | URL;
  readonly gateway?: Parameters<typeof operationGateway.invoke>[1];
  readonly idempotencyKey: string;
  readonly [traceIdOption]?: string;
}

type AuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options: ScheduleServiceJobActionClientOptions,
];
type OperationInvocation = readonly [requestCorrelation: string, options: ScheduleServiceJobActionClientOptions];

interface MakeClientOptions {
  readonly credential: Redacted.Redacted;
  readonly options: ScheduleServiceJobActionClientOptions;
  readonly requestCorrelation: string;
}

const makeClient = ({ credential, options, requestCorrelation }: MakeClientOptions) =>
  makeGovernedEffectBffClient(
    { api: ScheduleServiceJobActionApi, credential, defaultApiPrefix: '/service-jobs-api', requestCorrelation },
    options,
  );

export const executeScheduleServiceJobWithAuthorization = (
  payload: ScheduleServiceJobPayload,
  ...[credential, requestCorrelation, options]: AuthorizedInvocation
) =>
  Schema.encodeUnknownEffect(ScheduleServiceJobPayloadSchema)(payload).pipe(
    Effect.flatMap((encoded) =>
      makeClient({ credential: Redacted.make(credential), options, requestCorrelation }).pipe(
        Effect.flatMap((client) =>
          client.scheduleServiceJobAction.execute({
            headers: { 'idempotency-key': options.idempotencyKey },
            payload: encoded,
          }),
        ),
      ),
    ),
  );

export const executeScheduleServiceJob = (
  payload: ScheduleServiceJobPayload,
  ...[requestCorrelation, options]: OperationInvocation
) =>
  operationGateway.invoke(
    (credential) => executeScheduleServiceJobWithAuthorization(payload, credential, requestCorrelation, options),
    options.gateway,
  );
