// @generated by OntOS Codesmith module-api v1
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { Schema } from 'effect';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';

export const BillingDocumentsCommitStatusRequestSchema = Schema.Struct({
  invocationId: Schema.String.check(Schema.isUUID()).pipe(Schema.brand('ActionInvocationId')),
});
export type BillingDocumentsCommitStatusRequest = typeof BillingDocumentsCommitStatusRequestSchema.Type;
export const BillingDocumentsCommitStatusResponseSchema = Schema.Struct({
  retryCommand: Schema.Boolean,
  state: Schema.Literals(['OPEN', 'COMMITTED', 'INDETERMINATE']),
});

export const BillingDocumentsCommitStatusAuthenticationProblemSchema = makeProblemDetailsSchema(
  'BillingDocumentsCommitStatusAuthenticationProblem',
  401,
);
export const BillingDocumentsCommitStatusInvalidProblemSchema = makeProblemDetailsSchema(
  'BillingDocumentsCommitStatusInvalidProblem',
  400,
);
export const BillingDocumentsCommitStatusUnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  'BillingDocumentsCommitStatusUnavailableProblem',
  503,
);
export const BillingDocumentsCommitStatusForbiddenProblemSchema = makeProblemDetailsSchema(
  'BillingDocumentsCommitStatusForbiddenProblem',
  403,
);
export const BillingDocumentsCommitStatusNotFoundProblemSchema = makeProblemDetailsSchema(
  'BillingDocumentsCommitStatusNotFoundProblem',
  404,
);
export const BillingDocumentsCommitStatusPolicyProblemSchema = makeProblemDetailsSchema(
  'BillingDocumentsCommitStatusPolicyProblem',
  422,
);
export const BillingDocumentsCommitStatusPolicyConflictProblemSchema = makeProblemDetailsSchema(
  'BillingDocumentsCommitStatusPolicyConflictProblem',
  409,
);
export const BillingDocumentsCommitStatusInternalProblemSchema = makeProblemDetailsSchema(
  'BillingDocumentsCommitStatusInternalProblem',
  500,
);

export const BillingDocumentsCommitStatusApi = HttpApi.make('BillingDocumentsCommitStatusApi').add(
  HttpApiGroup.make('billingDocumentsCommitStatus').add(
    HttpApiEndpoint.post('execute', '/reads/billing-documents-commit-status', {
      error: [
        BillingDocumentsCommitStatusInvalidProblemSchema,
        BillingDocumentsCommitStatusAuthenticationProblemSchema,
        BillingDocumentsCommitStatusForbiddenProblemSchema,
        BillingDocumentsCommitStatusNotFoundProblemSchema,
        BillingDocumentsCommitStatusPolicyConflictProblemSchema,
        BillingDocumentsCommitStatusPolicyProblemSchema,
        BillingDocumentsCommitStatusUnavailableProblemSchema,
        BillingDocumentsCommitStatusInternalProblemSchema,
      ],
      headers: {},
      params: {},
      payload: BillingDocumentsCommitStatusRequestSchema,
      query: {},
      success: BillingDocumentsCommitStatusResponseSchema,
    }),
  ),
);
