// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner billing.documents
// @ontos-action-http-slug create-invoice-draft
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { HttpApi, HttpApiEndpoint, HttpApiGroup, Schema } from '@modern-js/bff-effect/effect-client';
import { HttpApiMiddleware } from 'effect/unstable/httpapi';
import { CreateInvoiceDraftPayloadSchema, CreateInvoiceDraftResultSchema } from '../actions/create-invoice-draft.ts';

export { CreateInvoiceDraftPayloadSchema } from '../actions/create-invoice-draft.ts';

const CreateInvoiceDraftActionHeadersSchema = Schema.Struct({
  'idempotency-key': Schema.optionalKey(Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(200))),
});

export const CreateInvoiceDraftActionInvalidProblemSchema = makeProblemDetailsSchema(
  'CreateInvoiceDraftActionInvalidProblem',
  400,
);
export const CreateInvoiceDraftActionAuthenticationProblemSchema = makeProblemDetailsSchema(
  'CreateInvoiceDraftActionAuthenticationProblem',
  401,
);
export const CreateInvoiceDraftActionForbiddenProblemSchema = makeProblemDetailsSchema(
  'CreateInvoiceDraftActionForbiddenProblem',
  403,
  {
    code: Schema.Literals([
      'action_permission_denied',
      'module_state_denied',
      'operation_context_denied',
      'operation_context_invalid',
      'scope_mismatch',
    ]),
  },
);
export const CreateInvoiceDraftActionNotFoundProblemSchema = makeProblemDetailsSchema(
  'CreateInvoiceDraftActionNotFoundProblem',
  404,
  { code: Schema.Literals(['action_invocation_not_found', 'job_not_found', 'missing_billing_address', 'not_found']) },
);
export const CreateInvoiceDraftActionConflictProblemSchema = makeProblemDetailsSchema(
  'CreateInvoiceDraftActionConflictProblem',
  409,
  {
    code: Schema.Literals([
      'action_request_hash_conflict',
      'action_invocation_state_invalid',
      'invoice_already_exists',
      'revision_conflict',
    ]),
  },
);
export const CreateInvoiceDraftActionIneligibleProblemSchema = makeProblemDetailsSchema(
  'CreateInvoiceDraftActionIneligibleProblem',
  422,
  {
    code: Schema.Literals([
      'action_policy_denied',
      'address_not_current',
      'due_date_out_of_range',
      'invoice_not_draft',
      'job_not_completed',
      'payment_term_required',
      'payment_term_unusable',
      'source_job_changed',
      'tax_data_required',
    ]),
  },
);
export const CreateInvoiceDraftActionPreconditionProblemSchema = makeProblemDetailsSchema(
  'CreateInvoiceDraftActionPreconditionProblem',
  428,
);
export const CreateInvoiceDraftActionUnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  'CreateInvoiceDraftActionUnavailableProblem',
  503,
  {
    code: Schema.Literals([
      'action_invocation_persistence_failed',
      'action_permission_check_failed',
      'action_policy_evaluation_failed',
      'action_transaction_failed',
      'module_state_check_unavailable',
      'operation_context_unavailable',
      'billing_documents_unavailable',
    ]),
  },
);
export const CreateInvoiceDraftActionAlreadyCommittedProblemSchema = makeProblemDetailsSchema(
  'CreateInvoiceDraftActionAlreadyCommittedProblem',
  409,
  {
    code: Schema.Literal('action_already_committed'),
    invocationId: Schema.String,
    resolution: Schema.Literal('REFRESH_GOVERNED_READS'),
    retryCommand: Schema.Literal(false),
  },
);
export const CreateInvoiceDraftActionCommitIndeterminateProblemSchema = makeProblemDetailsSchema(
  'CreateInvoiceDraftActionCommitIndeterminateProblem',
  503,
  {
    invocationId: Schema.String,
    resolution: Schema.Literal('RESOLVE_COMMIT'),
    retryCommand: Schema.Literal(false),
  },
);
export const CreateInvoiceDraftActionInternalProblemSchema = makeProblemDetailsSchema(
  'CreateInvoiceDraftActionInternalProblem',
  500,
);

export type CreateInvoiceDraftActionProblem =
  | typeof CreateInvoiceDraftActionInvalidProblemSchema.Type
  | typeof CreateInvoiceDraftActionAuthenticationProblemSchema.Type
  | typeof CreateInvoiceDraftActionForbiddenProblemSchema.Type
  | typeof CreateInvoiceDraftActionNotFoundProblemSchema.Type
  | typeof CreateInvoiceDraftActionConflictProblemSchema.Type
  | typeof CreateInvoiceDraftActionIneligibleProblemSchema.Type
  | typeof CreateInvoiceDraftActionPreconditionProblemSchema.Type
  | typeof CreateInvoiceDraftActionUnavailableProblemSchema.Type
  | typeof CreateInvoiceDraftActionAlreadyCommittedProblemSchema.Type
  | typeof CreateInvoiceDraftActionCommitIndeterminateProblemSchema.Type
  | typeof CreateInvoiceDraftActionInternalProblemSchema.Type;

export class CreateInvoiceDraftActionSchemaErrorMiddleware extends HttpApiMiddleware.Service<CreateInvoiceDraftActionSchemaErrorMiddleware>()(
  'billing-documents/CreateInvoiceDraftActionSchemaErrorMiddleware',
  { error: CreateInvoiceDraftActionInvalidProblemSchema },
) {}

const actionErrors = [
  CreateInvoiceDraftActionInvalidProblemSchema,
  CreateInvoiceDraftActionAuthenticationProblemSchema,
  CreateInvoiceDraftActionForbiddenProblemSchema,
  CreateInvoiceDraftActionNotFoundProblemSchema,
  CreateInvoiceDraftActionConflictProblemSchema,
  CreateInvoiceDraftActionIneligibleProblemSchema,
  CreateInvoiceDraftActionPreconditionProblemSchema,
  CreateInvoiceDraftActionUnavailableProblemSchema,
  CreateInvoiceDraftActionAlreadyCommittedProblemSchema,
  CreateInvoiceDraftActionCommitIndeterminateProblemSchema,
  CreateInvoiceDraftActionInternalProblemSchema,
] as const;

/**
 * The endpoint chain stays a `const`. The MicroVertical API boundary checker walks a root API's
 * operands through const bindings only, so a class declaration hides the composed endpoints from
 * it. The exported group is annotated with a named type alias so its type still has a name: the
 * vertical's `shared/api.ts` merges every group type into one `HttpApi` and declaration emit
 * serializes that union verbatim, so an anonymous group type pushes the composed contract past
 * the compiler's serialization limit (TS7056).
 *
 * Exported only so the named contract type can reference it; the merged vertical HttpApi prints
 * this group by name (declaration-emit size).
 *
 * @public
 */
export const createInvoiceDraftActionGroupDefinition = HttpApiGroup.make('createInvoiceDraftAction')
  .add(
    HttpApiEndpoint.post('execute', '/billing-documents/actions/create-invoice-draft', {
      error: actionErrors,
      headers: CreateInvoiceDraftActionHeadersSchema,
      payload: Schema.toEncoded(CreateInvoiceDraftPayloadSchema),
      success: CreateInvoiceDraftResultSchema,
    }),
  )
  .middleware(CreateInvoiceDraftActionSchemaErrorMiddleware);

export type CreateInvoiceDraftActionGroupContract = HttpApiGroup.HttpApiGroup<
  'createInvoiceDraftAction',
  HttpApiGroup.Endpoints<typeof createInvoiceDraftActionGroupDefinition>
>;

const CreateInvoiceDraftActionGroup: CreateInvoiceDraftActionGroupContract = createInvoiceDraftActionGroupDefinition;

export const CreateInvoiceDraftActionApi =
  HttpApi.make('CreateInvoiceDraftActionApi').add(CreateInvoiceDraftActionGroup);
