// @generated by OntOS Codesmith module-api v1
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { Schema } from 'effect';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';
import { InvoiceSchema, InvoiceStatusSchema } from '../resources/invoice.ts';

export const InvoiceListCursorSchema = Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(100));
export const InvoiceListRequestSchema = Schema.Struct({
  cursor: Schema.optionalKey(InvoiceListCursorSchema),
  pageSize: Schema.optionalKey(Schema.Int.check(Schema.isBetween({ maximum: 100, minimum: 1 }))),
  status: Schema.optionalKey(InvoiceStatusSchema),
});
export type InvoiceListRequest = typeof InvoiceListRequestSchema.Type;
export const InvoiceListItemSchema = Schema.Struct({
  customerDisplayName: Schema.String,
  invoice: InvoiceSchema,
  sourceJobDisplayName: Schema.String,
});
export type InvoiceListItem = typeof InvoiceListItemSchema.Type;
export const InvoiceListResponseSchema = Schema.Struct({
  items: Schema.Array(InvoiceListItemSchema),
  // null is the stable pagination sentinel used by generated read clients; expires: 2027-09-30.
  // oxlint-disable-next-line effect-native/no-nullable-schema-field
  nextCursor: Schema.NullOr(InvoiceListCursorSchema),
});
export type InvoiceListResponse = typeof InvoiceListResponseSchema.Type;

export const InvoiceListAuthenticationProblemSchema = makeProblemDetailsSchema('InvoiceListAuthenticationProblem', 401);
export const InvoiceListInvalidProblemSchema = makeProblemDetailsSchema('InvoiceListInvalidProblem', 400);
export const InvoiceListUnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  'InvoiceListUnavailableProblem',
  503,
);
export const InvoiceListForbiddenProblemSchema = makeProblemDetailsSchema('InvoiceListForbiddenProblem', 403);
export const InvoiceListNotFoundProblemSchema = makeProblemDetailsSchema('InvoiceListNotFoundProblem', 404);
export const InvoiceListPolicyProblemSchema = makeProblemDetailsSchema('InvoiceListPolicyProblem', 422);
export const InvoiceListPolicyConflictProblemSchema = makeProblemDetailsSchema('InvoiceListPolicyConflictProblem', 409);
export const InvoiceListInternalProblemSchema = makeProblemDetailsSchema('InvoiceListInternalProblem', 500);

export const InvoiceListApi = HttpApi.make('InvoiceListApi').add(
  HttpApiGroup.make('invoiceList').add(
    HttpApiEndpoint.post('execute', '/reads/invoice-list', {
      error: [
        InvoiceListInvalidProblemSchema,
        InvoiceListAuthenticationProblemSchema,
        InvoiceListForbiddenProblemSchema,
        InvoiceListNotFoundProblemSchema,
        InvoiceListPolicyConflictProblemSchema,
        InvoiceListPolicyProblemSchema,
        InvoiceListUnavailableProblemSchema,
        InvoiceListInternalProblemSchema,
      ],
      headers: {},
      params: {},
      payload: InvoiceListRequestSchema,
      query: {},
      success: InvoiceListResponseSchema,
    }),
  ),
);
