// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner billing.documents
// @ontos-action-http-slug issue-invoice
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { HttpApi, HttpApiEndpoint, HttpApiGroup, Schema } from '@modern-js/bff-effect/effect-client';
import { HttpApiMiddleware } from 'effect/unstable/httpapi';
import { IssueInvoicePayloadSchema, IssueInvoiceResultSchema } from '../actions/issue-invoice.ts';

export { IssueInvoicePayloadSchema } from '../actions/issue-invoice.ts';

const IssueInvoiceActionHeadersSchema = Schema.Struct({
  'idempotency-key': Schema.optionalKey(Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(200))),
});

export const IssueInvoiceActionInvalidProblemSchema = makeProblemDetailsSchema('IssueInvoiceActionInvalidProblem', 400);
export const IssueInvoiceActionAuthenticationProblemSchema = makeProblemDetailsSchema(
  'IssueInvoiceActionAuthenticationProblem',
  401,
);
export const IssueInvoiceActionForbiddenProblemSchema = makeProblemDetailsSchema(
  'IssueInvoiceActionForbiddenProblem',
  403,
  {
    code: Schema.Literals([
      'action_permission_denied',
      'module_state_denied',
      'operation_context_denied',
      'operation_context_invalid',
      'scope_mismatch',
    ]),
  },
);
export const IssueInvoiceActionNotFoundProblemSchema = makeProblemDetailsSchema(
  'IssueInvoiceActionNotFoundProblem',
  404,
  { code: Schema.Literals(['action_invocation_not_found', 'job_not_found', 'missing_billing_address', 'not_found']) },
);
export const IssueInvoiceActionConflictProblemSchema = makeProblemDetailsSchema(
  'IssueInvoiceActionConflictProblem',
  409,
  {
    code: Schema.Literals([
      'action_request_hash_conflict',
      'action_invocation_state_invalid',
      'invoice_already_exists',
      'revision_conflict',
    ]),
  },
);
export const IssueInvoiceActionIneligibleProblemSchema = makeProblemDetailsSchema(
  'IssueInvoiceActionIneligibleProblem',
  422,
  {
    code: Schema.Literals([
      'action_policy_denied',
      'address_not_current',
      'due_date_out_of_range',
      'invoice_not_draft',
      'job_not_completed',
      'payment_term_required',
      'payment_term_unusable',
      'source_job_changed',
      'tax_data_required',
    ]),
  },
);
export const IssueInvoiceActionPreconditionProblemSchema = makeProblemDetailsSchema(
  'IssueInvoiceActionPreconditionProblem',
  428,
);
export const IssueInvoiceActionUnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  'IssueInvoiceActionUnavailableProblem',
  503,
  {
    code: Schema.Literals([
      'action_invocation_persistence_failed',
      'action_permission_check_failed',
      'action_policy_evaluation_failed',
      'action_transaction_failed',
      'module_state_check_unavailable',
      'operation_context_unavailable',
      'billing_documents_unavailable',
    ]),
  },
);
export const IssueInvoiceActionAlreadyCommittedProblemSchema = makeProblemDetailsSchema(
  'IssueInvoiceActionAlreadyCommittedProblem',
  409,
  {
    code: Schema.Literal('action_already_committed'),
    invocationId: Schema.String,
    resolution: Schema.Literal('REFRESH_GOVERNED_READS'),
    retryCommand: Schema.Literal(false),
  },
);
export const IssueInvoiceActionCommitIndeterminateProblemSchema = makeProblemDetailsSchema(
  'IssueInvoiceActionCommitIndeterminateProblem',
  503,
  {
    invocationId: Schema.String,
    resolution: Schema.Literal('RESOLVE_COMMIT'),
    retryCommand: Schema.Literal(false),
  },
);
export const IssueInvoiceActionInternalProblemSchema = makeProblemDetailsSchema(
  'IssueInvoiceActionInternalProblem',
  500,
);

export type IssueInvoiceActionProblem =
  | typeof IssueInvoiceActionInvalidProblemSchema.Type
  | typeof IssueInvoiceActionAuthenticationProblemSchema.Type
  | typeof IssueInvoiceActionForbiddenProblemSchema.Type
  | typeof IssueInvoiceActionNotFoundProblemSchema.Type
  | typeof IssueInvoiceActionConflictProblemSchema.Type
  | typeof IssueInvoiceActionIneligibleProblemSchema.Type
  | typeof IssueInvoiceActionPreconditionProblemSchema.Type
  | typeof IssueInvoiceActionUnavailableProblemSchema.Type
  | typeof IssueInvoiceActionAlreadyCommittedProblemSchema.Type
  | typeof IssueInvoiceActionCommitIndeterminateProblemSchema.Type
  | typeof IssueInvoiceActionInternalProblemSchema.Type;

export class IssueInvoiceActionSchemaErrorMiddleware extends HttpApiMiddleware.Service<IssueInvoiceActionSchemaErrorMiddleware>()(
  'billing-documents/IssueInvoiceActionSchemaErrorMiddleware',
  { error: IssueInvoiceActionInvalidProblemSchema },
) {}

const actionErrors = [
  IssueInvoiceActionInvalidProblemSchema,
  IssueInvoiceActionAuthenticationProblemSchema,
  IssueInvoiceActionForbiddenProblemSchema,
  IssueInvoiceActionNotFoundProblemSchema,
  IssueInvoiceActionConflictProblemSchema,
  IssueInvoiceActionIneligibleProblemSchema,
  IssueInvoiceActionPreconditionProblemSchema,
  IssueInvoiceActionUnavailableProblemSchema,
  IssueInvoiceActionAlreadyCommittedProblemSchema,
  IssueInvoiceActionCommitIndeterminateProblemSchema,
  IssueInvoiceActionInternalProblemSchema,
] as const;

/**
 * The endpoint chain stays a `const`. The MicroVertical API boundary checker walks a root API's
 * operands through const bindings only, so a class declaration hides the composed endpoints from
 * it. The exported group is annotated with a named type alias so its type still has a name: the
 * vertical's `shared/api.ts` merges every group type into one `HttpApi` and declaration emit
 * serializes that union verbatim, so an anonymous group type pushes the composed contract past
 * the compiler's serialization limit (TS7056).
 *
 * Exported only so the named contract type can reference it; the merged vertical HttpApi prints
 * this group by name (declaration-emit size).
 *
 * @public
 */
export const issueInvoiceActionGroupDefinition = HttpApiGroup.make('issueInvoiceAction')
  .add(
    HttpApiEndpoint.post('execute', '/billing-documents/actions/issue-invoice', {
      error: actionErrors,
      headers: IssueInvoiceActionHeadersSchema,
      payload: Schema.toEncoded(IssueInvoicePayloadSchema),
      success: IssueInvoiceResultSchema,
    }),
  )
  .middleware(IssueInvoiceActionSchemaErrorMiddleware);

export type IssueInvoiceActionGroupContract = HttpApiGroup.HttpApiGroup<
  'issueInvoiceAction',
  HttpApiGroup.Endpoints<typeof issueInvoiceActionGroupDefinition>
>;

const IssueInvoiceActionGroup: IssueInvoiceActionGroupContract = issueInvoiceActionGroupDefinition;

export const IssueInvoiceActionApi = HttpApi.make('IssueInvoiceActionApi').add(IssueInvoiceActionGroup);
