// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner job.expenses
// @ontos-action-http-slug update-job-expense
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted, Schema } from 'effect';
import {
  UpdateJobExpenseActionApi,
  UpdateJobExpensePayloadSchema,
} from '../../shared/apis/update-job-expense-action.ts';
import type { UpdateJobExpensePayload } from '../../shared/actions/update-job-expense.ts';
import { operationGateway } from './action-gateway.ts';

const traceIdOption = 'traceId' as const;

export interface UpdateJobExpenseActionClientOptions {
  readonly baseUrl?: string | URL;
  readonly gateway?: Parameters<typeof operationGateway.invoke>[1];
  readonly idempotencyKey: string;
  readonly [traceIdOption]?: string;
}

type AuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options: UpdateJobExpenseActionClientOptions,
];
type OperationInvocation = readonly [requestCorrelation: string, options: UpdateJobExpenseActionClientOptions];

interface MakeClientOptions {
  readonly credential: Redacted.Redacted;
  readonly options: UpdateJobExpenseActionClientOptions;
  readonly requestCorrelation: string;
}

const makeClient = ({ credential, options, requestCorrelation }: MakeClientOptions) =>
  makeGovernedEffectBffClient(
    { api: UpdateJobExpenseActionApi, credential, defaultApiPrefix: '/job-expenses-api', requestCorrelation },
    options,
  );

export const executeUpdateJobExpenseWithAuthorization = (
  payload: UpdateJobExpensePayload,
  ...[credential, requestCorrelation, options]: AuthorizedInvocation
) =>
  Schema.encodeUnknownEffect(UpdateJobExpensePayloadSchema)(payload).pipe(
    Effect.flatMap((encoded) =>
      makeClient({ credential: Redacted.make(credential), options, requestCorrelation }).pipe(
        Effect.flatMap((client) =>
          client.updateJobExpenseAction.execute({
            headers: { 'idempotency-key': options.idempotencyKey },
            payload: encoded,
          }),
        ),
      ),
    ),
  );

export const executeUpdateJobExpense = (
  payload: UpdateJobExpensePayload,
  ...[requestCorrelation, options]: OperationInvocation
) =>
  operationGateway.invoke(
    (credential) => executeUpdateJobExpenseWithAuthorization(payload, credential, requestCorrelation, options),
    options.gateway,
  );
